backend/Dockerfile
backend/Dockerfile.background

Dockerfiles were still using old dir structure

Fix Dockerfiles

---

backend/danswer/background/update.py
backend/danswer/connectors/slack/pull.py

Actually index documents pulled from slack + only fetch documents in the specified time range

Background update improvements

---

backend/danswer/configs/app_configs.py
backend/danswer/datastores/__init__.py
backend/danswer/datastores/interfaces.py
backend/danswer/datastores/qdrant/indexing.py
backend/danswer/datastores/qdrant/store.py
backend/danswer/direct_qa/semantic_search.py
backend/danswer/server/search_backend.py
backend/scripts/simulate_frontend.py

Also added in an __init__.py for mypy to work

DAN-2 Backend Support for Filters

---

README.md
backend/danswer/configs/model_configs.py
backend/danswer/direct_qa/__init__.py
backend/danswer/direct_qa/qa_prompts.py
backend/danswer/direct_qa/question_answer.py
backend/requirements/default.txt

Doesn't actually turn on GPT 4 which isn't yet available apparently

DAN-26 Enable GPT 4 through chat completion endpoint

---

backend/danswer/server/models.py
backend/danswer/server/search_backend.py

Added endpoint to be called from frontend

DAN-52 Check user role endpoint

---

backend/danswer/direct_qa/qa_prompts.py
backend/danswer/main.py
backend/danswer/semantic_search/semantic_search.py
backend/danswer/utils/text_processing.py

DAN-51 Model warm up on start

---

backend/danswer/db/engine.py
backend/requirements/default.txt

Didn't add psycopg2 into `requirements/default.txt` + change db connection string to use the right driver

Fix sync DB engine

---

web/src/components/search/SearchSection.tsx

Attempting to fix the intermittent streaming issues with the onebox setup

Split chunks up by newline + handle partial chunks

---

web/src/components/icons/icons.tsx
web/src/components/search/SearchResultsDisplay.tsx
web/src/components/search/SearchSection.tsx
web/src/components/search/types.tsx

Just display docs if QA fails

---

web/next.config.js
web/package-lock.json
web/package.json
web/src/app/admin/connectors/confluence/page.tsx
web/src/app/admin/layout.tsx
web/src/components/admin/connectors/Field.tsx
web/src/components/admin/connectors/Form.tsx
web/src/components/icons/icons.tsx
web/src/components/search/SearchResultsDisplay.tsx
web/src/components/source.tsx
web/src/lib/types.ts

RE using react-icons: phosphoricons doesn't have the confluence logo

Add confluence connector page + add react-icons

---

backend/danswer/server/manage.py
backend/danswer/server/models.py
backend/danswer/server/search_backend.py
web/src/app/page.tsx
web/src/components/search/Filters.tsx
web/src/components/search/SearchResultsDisplay.tsx
web/src/components/search/SearchSection.tsx
web/src/components/search/interfaces.tsx

Add Filters to UI

---

web/src/app/admin/connectors/confluence/page.tsx
web/src/app/admin/connectors/github/page.tsx
web/src/app/admin/connectors/google-drive/page.tsx
web/src/components/admin/connectors/table/ConnectorsTable.tsx
web/src/lib/connector.ts

Fix bug with revoking of credentials + adding new credential + adding back connector for google drive AND Force users to provide access token before creating connector for Github/Confluence

QoL improvements / bug fixes to admin flows

---

backend/danswer/connectors/web/connector.py

Handled by checking where the page is redirected to

DAN-139 web connector recursion

---

backend/danswer/configs/constants.py
backend/danswer/connectors/factory.py
backend/danswer/connectors/slab/connector.py
backend/requirements/dev.txt

Does not include comments
Does not include topics

DAN-158 Slab Connector

---

backend/danswer/connectors/slack/connector.py

Previously, we fetched all messages, THEN batched them. This means for the initial index, all messages would be stored in memory.

Proper slack message batching

---

backend/danswer/connectors/slab/connector.py

May need more of these in the future as well

Tiny fix for certain doc names

---

backend/danswer/auth/users.py

trying to login with a nonwhitelisted account now looks like this. Also prevents any further actions or any endpoints that requires a user

DAN-169 Users whitelist

---

web/src/app/user/connectors/GoogleDriveCard.tsx

Fix typo in GoogleDriveCard.tsx

---

backend/danswer/configs/constants.py
backend/danswer/connectors/bookstack/client.py
backend/danswer/connectors/bookstack/connector.py
backend/danswer/connectors/factory.py
backend/danswer/connectors/google_drive/connector.py
backend/danswer/connectors/models.py
backend/danswer/connectors/notion/connector.py
backend/danswer/connectors/productboard/connector.py
backend/danswer/utils/timing.py
web/src/app/admin/connectors/productboard/page.tsx
web/src/app/admin/layout.tsx
web/src/components/icons/icons.tsx
web/src/components/search/Filters.tsx
web/src/components/source.tsx
web/src/lib/types.ts

Also fixes a mypy issues across the repo

Product board connector

---

backend/danswer/connectors/google_drive/connector.py
backend/requirements/default.txt
backend/setup.cfg

I needed this for my org and may be useful to others

Added support for docx in Google Drive

---

web/src/app/admin/connectors/google-drive/ConnectorEditPopup.tsx
web/src/app/admin/connectors/google-drive/GoogleDriveConnectorsTable.tsx
web/src/app/admin/connectors/google-drive/page.tsx
web/src/components/admin/connectors/Field.tsx
web/src/lib/types.ts

Allow shared files for drive connector

---

backend/alembic/versions/d7111c1238cd_remove_document_ids.py
backend/alembic/versions/d7111c1238cd_remove_document_index.py
backend/danswer/background/update.py
backend/danswer/datastores/indexing_pipeline.py
backend/danswer/db/index_attempt.py
backend/danswer/db/models.py

Also removes saving all document IDs to postgres

Add ingestion metrics

---

backend/danswer/connectors/slack/connector.py
web/src/app/admin/connectors/slack/page.tsx
web/src/components/admin/connectors/ConnectorForm.tsx
web/src/lib/types.ts

Hi @yuhongsun96 and @Weves ,
Here's a go at allowing channels to be specified for the slack connector. Feedback most welcome!
I didn't have an easy/non-invasive way to test that not specifying channels still works. Is this something you can easily test?

Allow slack channels to be specified

---

web/src/app/admin/connectors/slack/page.tsx
web/src/app/admin/indexing/status/page.tsx

Better display of connector metadata on main status page

---

backend/danswer/configs/constants.py
backend/danswer/configs/model_configs.py
backend/danswer/direct_qa/__init__.py
backend/danswer/direct_qa/local_llm.py
backend/danswer/direct_qa/local_transformers.py

A very simple local llm. Not as good as OpenAI but works as a drop-in replacement for on premise deployments.

add simple local llm

---

web/src/components/search/SearchResultsDisplay.tsx

Also changes the case where no answer is returned from "GPT hurt itself in it's confusion :(" -> "Information not found"

Make docs show up immediately rather than wait until first answer token

---

backend/danswer/configs/model_configs.py
backend/danswer/direct_qa/open_ai.py
deployment/docker_compose/docker-compose.dev.yml
deployment/docker_compose/env.prod.template

necessary env variables:
**Example:**
API_BASE_OPENAI=https://example-endpoint.openai.azure.com
API_TYPE_OPENAI=azure
API_VERSION_OPENAI=2023-05-15
AZURE_DEPLOYMENT_ID=deployment-name
Verified Azure endpoint works as well as normal endpoint. Note that the deployment_id attribute and "engine" attribute can be used interchangeably with the OpenAI package.
Also allows setting only an API base which allows for custom endpoints that follow the OpenAI API Schema.

Azure OpenAI integration

---

backend/danswer/configs/app_configs.py
backend/danswer/connectors/google_drive/connector.py
backend/scripts/reset_postgres.py
web/src/app/admin/connectors/google-drive/ConnectorEditPopup.tsx
web/src/app/admin/connectors/google-drive/GoogleDriveConnectorsTable.tsx
web/src/app/admin/connectors/google-drive/page.tsx
web/src/lib/types.ts

This PR does the following:
1. Allows you to select if shortcuts encountered should be followed and indexed
2. Fixes an issue where if the file is in shared drive, it is not picked up

Google drive shared files fix + shortcuts

---

backend/danswer/datastores/indexing_pipeline.py

Fix typo in indexing_pipeline.py

---

backend/danswer/background/update.py
backend/danswer/search/search_utils.py

Otherwise the first indexing is slow and it makes me upset because I think something is broken

Warm up models before first document indexed

---

backend/danswer/db/users.py
backend/danswer/main.py
backend/danswer/server/manage.py
backend/danswer/server/users.py
web/src/app/admin/layout.tsx
web/src/app/admin/users/page.tsx
web/src/components/icons/icons.tsx

Add user management page

---

backend/danswer/connectors/confluence/connector.py

fix(confluence): add missing import

---

backend/danswer/connectors/google_drive/connector.py

- Fix https://github.com/danswer-ai/danswer/issues/353

Force gdrive connector to ignore encrypted pdf file (#353)

---

.github/workflows/docker-build-push-backend-container-on-tag.yml
.github/workflows/docker-build-push-web-container-on-tag.yml

Faster and hopefully stops hitting the Out of Memory issues

Split the build on Tag actions into two jobs

---

backend/danswer/background/update.py

- Prevents creating a new indexing job if one is already ongoing
- Cleans up frozen jobs (e.g. jobs that have not been updated in the last hour)

Fix indexing job cleanup

---

backend/danswer/datastores/vespa/store.py

These documents are invalid and there is a fix upstream to prevent these bad docs from being indexed. However some users already have these documents from a previous indexing so this ensures they do not run into this.

Fix Vespa Issue where Documents with no Content could be retrieved via Vector Search

---

backend/danswer/bots/slack/blocks.py
backend/danswer/bots/slack/handlers/handle_feedback.py
backend/danswer/bots/slack/handlers/handle_message.py
backend/danswer/bots/slack/listener.py
backend/danswer/bots/slack/utils.py
backend/danswer/chunking/models.py
backend/danswer/configs/app_configs.py
backend/danswer/configs/constants.py
backend/danswer/db/feedback.py
backend/danswer/direct_qa/answer_question.py
backend/danswer/direct_qa/qa_block.py
backend/danswer/direct_qa/qa_utils.py
backend/danswer/search/semantic_search.py
backend/danswer/secondary_llm_flows/answer_validation.py
backend/danswer/server/models.py
backend/danswer/utils/text_processing.py

Includes document level feedback, reformatting outputs, including snippets, reworked highlighting

Slack Bot Interface Rework

---

backend/alembic/versions/dba7f71618f5_danswer_custom_tool_flow.py
backend/danswer/chat/chat_llm.py
backend/danswer/chat/chat_prompts.py
backend/danswer/chat/personas.py
backend/danswer/chat/personas.yaml
backend/danswer/chat/tools.py
backend/danswer/db/chat.py
backend/danswer/db/models.py

Toolcalling with Danswer has a special flow to improve the recall via retrieval. Aside from that, also includes some prompt changes etc.

Special Danswer flow for Chat

---

backend/danswer/connectors/web/connector.py

1. Allow for non-recursive website indexing
2. Enable pointing to a sitemap.xml url and parsing all pages listed there
3. Allow for file upload where each line is a new page to index (this is nonrecursive)

Add more flexibility to the Web Connector

---

backend/alembic/versions/767f1c2a00eb_count_chat_tokens.py
backend/danswer/chat/chat_llm.py
backend/danswer/chat/chat_prompts.py
backend/danswer/chat/personas.yaml
backend/danswer/configs/model_configs.py
backend/danswer/db/chat.py
backend/danswer/db/models.py
backend/danswer/llm/build.py
backend/danswer/llm/openai.py
backend/danswer/server/chat_backend.py

Handle message roll-over/expiration
Handle user input problems like too long prompt etc
Handle failure cases like wrong tool called, wrong llm format
Added related configurations via env variables. Not enabled for docker compose dev

Chat Backend API edge cases handled

---

backend/danswer/background/update.py
backend/danswer/configs/model_configs.py
backend/danswer/direct_qa/qa_block.py
backend/danswer/main.py
backend/danswer/search/search_utils.py
backend/danswer/search/semantic_search.py
backend/tests/regression/answer_quality/sample_questions.yaml
deployment/docker_compose/docker-compose.dev.yml

Also adds configurability for the embedding model and boosting

Make Cross Encoders Optional

---

web/src/app/admin/bot/SlackBotConfigCreationForm.tsx
web/src/app/admin/bot/page.tsx
web/src/app/admin/documents/sets/DocumentSetCreationForm.tsx
web/src/app/admin/documents/sets/hooks.tsx
web/src/app/admin/documents/sets/page.tsx
web/src/app/page.tsx
web/src/components/HoverPopup.tsx
web/src/components/icons/icons.tsx
web/src/components/search/Filters.tsx
web/src/components/search/SearchSection.tsx
web/src/lib/search/interfaces.ts
web/src/lib/search/qa.ts
web/src/lib/search/streamingQa.ts
web/src/lib/search/utils.ts
web/src/lib/types.ts

Add document set-based filters in UI

---

backend/danswer/connectors/file/connector.py
backend/danswer/connectors/file/utils.py
web/src/app/admin/connectors/file/page.tsx

This pull request will help to use **_pdf_** file in File Connector

Allow pdf file in File Connector

---

backend/danswer/configs/app_configs.py
backend/danswer/main.py

Add OAuth configurability

---

backend/danswer/bots/slack/blocks.py
backend/danswer/bots/slack/config.py
backend/danswer/bots/slack/handlers/handle_message.py
backend/danswer/bots/slack/listener.py
backend/danswer/bots/slack/utils.py
backend/danswer/configs/app_configs.py
backend/danswer/db/models.py
backend/danswer/server/models.py
backend/danswer/server/slack_bot_management.py
web/src/app/admin/bot/SlackBotConfigCreationForm.tsx
web/src/app/admin/bot/lib.ts
web/src/app/admin/bot/page.tsx
web/src/app/admin/connectors/hubspot/page.tsx
web/src/lib/types.ts

includes @danswer, /danswer, configuring to only message the team members, or only to respond to sender.

Support more Slack Config Options

---

backend/danswer/bots/slack/handlers/handle_message.py
backend/danswer/db/models.py
backend/danswer/server/models.py
backend/danswer/server/slack_bot_management.py
web/src/app/admin/bot/SlackBotConfigCreationForm.tsx
web/src/app/admin/bot/lib.ts
web/src/app/admin/bot/page.tsx
web/src/components/admin/connectors/Field.tsx
web/src/components/admin/connectors/Popup.tsx
web/src/lib/types.ts

Replace 'respond_sender_only' with 'respond_tag_only' + prettify UI

---

backend/danswer/configs/model_configs.py
backend/danswer/direct_qa/qa_utils.py
backend/danswer/llm/azure.py
backend/danswer/llm/openai.py

Make the environment key a global backup. UI config should take priority as it's presented that way in UI, otherwise it's misleading.

Default to API key in file

---

backend/danswer/datastores/vespa/store.py

In the case where it does not have expected format, log for further debugging. Also handle error case, optimistically

Vespa edge case ID does not follow expected format

---

backend/danswer/bots/slack/constants.py
backend/danswer/bots/slack/handlers/handle_message.py
backend/danswer/bots/slack/listener.py
backend/danswer/bots/slack/models.py
backend/danswer/bots/slack/utils.py
backend/danswer/configs/app_configs.py

- Reacts to message with eyes, then removes them after the answer comes through
- Respond to /danswerbot messages as soon as processing
- Dedupe @danswerbot messages
- Reworks some parts of the flow and also gives a failure message if something goes wrong

Slack Bot to respond very quickly to acknowledge seeing the question

---

backend/danswer/connectors/document360/connector.py
backend/danswer/connectors/github/connector.py
backend/danswer/connectors/hubspot/connector.py
backend/danswer/server/manage.py
web/src/app/admin/connectors/github/page.tsx

Fix a couple connector polling offset bugs
Make check for Gen AI key based on UTC timestamps

Favor tz aware objects

---

backend/danswer/bots/slack/blocks.py
backend/danswer/bots/slack/utils.py
backend/danswer/connectors/slack/connector.py
backend/danswer/connectors/slack/utils.py

Also added better slack parsing during indexing.

SlackBot still tagging groups

---

backend/alembic/versions/30c1d5744104_persona_datetime_aware.py
backend/danswer/chat/chat_llm.py
backend/danswer/chat/personas.py
backend/danswer/chat/personas.yaml
backend/danswer/db/chat.py
backend/danswer/db/models.py

Also minor change included for default personas to not overwrite other UI created personas as new default personas are added in.

Personas to have option to be aware of current date and time

---

backend/danswer/connectors/file/connector.py
backend/danswer/connectors/google_drive/connector.py
backend/danswer/connectors/web/connector.py
backend/requirements/default.txt

Also allows encrypted pdfs on the backend now

Replace PyPDF2 with pypdf

---

backend/danswer/connectors/cross_connector_utils/file_utils.py
backend/danswer/connectors/file/connector.py
backend/danswer/connectors/google_drive/connector.py
backend/danswer/connectors/web/connector.py

Specifically this should get past the encrypted PDFs issue on google drive

Use shared PDF utility function to not error on encrypted PDFs

---

backend/danswer/server/search_backend.py

Really ugly to show a stack trace to the users, it's in the logs anyway

Fix LLM error reporting

---

deployment/docker_compose/docker-compose.dev.yml
deployment/docker_compose/docker-compose.prod-no-letsencrypt.yml
deployment/docker_compose/docker-compose.prod.yml
deployment/kubernetes/vespa-service-deployment.yaml

Need this so when people already have Vespa 8 it still upgrades to a version allowing global normalizing

Pin Vespa Version

---

backend/danswer/connectors/gong/connector.py
web/src/app/admin/connectors/gong/page.tsx

Gong to accept workspace IDs

---

deployment/docker_compose/docker-compose.prod.yml

The prod docker-compose was using the dev template, this points nginx to the correct environment template

Fix nginx conf in docker-compose.prod

---

web/src/app/admin/connectors/google-drive/page.tsx
web/src/lib/types.ts

This code fixes a bug with Google Drive where Step 3 don't appear, and it's impossible to index files from Google Drive,
this is caused by the find loop not being able to find the Gdrive credentials from the credentials array due to the line 
`credential.credential_json?.google_drive_tokens && credential.user_id === null` as none of the credentials matches this condition 
this fix will pull the current user credentials and matches his ID to provide him with the right credentials

Google Drive step3 indexing not starting bug fix

---

backend/danswer/server/search_backend.py
web/src/app/admin/documents/explorer/Explorer.tsx
web/src/app/admin/documents/explorer/lib.ts
web/src/app/admin/documents/explorer/page.tsx
web/src/components/admin/Title.tsx
web/src/components/search/DocumentDisplay.tsx
web/src/components/search/DocumentUpdatedAtBadge.tsx
web/src/components/search/SearchSection.tsx
web/src/components/search/filtering/FilterDropdown.tsx
web/src/components/search/filtering/Filters.tsx
web/src/lib/hooks.ts
web/src/lib/search/interfaces.ts
web/src/lib/search/utils.ts
web/src/lib/search/utilsSS.ts

Enhance document explorer

---

README.md
backend/danswer/chat/chat_llm.py
backend/danswer/configs/app_configs.py
backend/danswer/configs/chat_configs.py
backend/danswer/configs/constants.py
backend/danswer/danswerbot/slack/blocks.py
backend/danswer/danswerbot/slack/handlers/handle_message.py
backend/danswer/db/chat.py
backend/danswer/direct_qa/answer_question.py
backend/danswer/direct_qa/qa_utils.py
backend/danswer/llm/chat_llm.py
backend/danswer/llm/custom_llm.py
backend/danswer/llm/gpt_4_all.py
backend/danswer/llm/interfaces.py
backend/danswer/main.py
backend/danswer/prompts/secondary_llm_flows.py
backend/danswer/search/models.py
backend/danswer/search/search_runner.py
backend/danswer/secondary_llm_flows/chunk_usefulness.py
backend/danswer/server/models.py
backend/danswer/server/search_backend.py
backend/danswer/utils/telemetry.py
backend/danswer/utils/threadpool_concurrency.py
deployment/docker_compose/docker-compose.dev.yml
web/src/components/search/DocumentDisplay.tsx

Use LLM to determine which chunks are relevant to the user query

LLM Chunk Filtering

---

backend/danswer/connectors/google_site/connector.py

Hi @yuhongsun96 and @Weves
This reconstructs the URL correctly. Can you see if this also works for you?

google site connector: Fix for reconstructing URL

---

backend/danswer/danswerbot/slack/handlers/handle_message.py
backend/danswer/db/document_set.py
backend/danswer/direct_qa/answer_question.py
backend/danswer/document_index/vespa/index.py
backend/danswer/search/models.py
backend/danswer/search/search_runner.py
backend/danswer/server/document_set.py
backend/danswer/server/models.py

Allow Slackbots to have non-public docs configured by the admin.

Slack Role Override

---

backend/danswer/direct_qa/qa_block.py
backend/danswer/llm/chat_llm.py
backend/danswer/llm/utils.py
backend/danswer/search/search_nlp_models.py
backend/requirements/default.txt
backend/scripts/test-openapi-key.py

Update LLM related Libs

---

backend/danswer/direct_qa/answer_question.py
backend/danswer/document_index/vespa/index.py
backend/danswer/expert_recommendation/heuristics_based.py
backend/danswer/indexing/models.py
backend/danswer/server/models.py
backend/danswer/utils/text_processing.py

Most basic implementation of expert recommendation backend

Expert Recommendation Heuristic Only

---

backend/danswer/search/search_runner.py

Fixes the following TypeError #788 
api_server_1     |   File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
api_server_1     |     return await get_asynclib().run_sync_in_worker_thread(
api_server_1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api_server_1     |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
api_server_1     |     return await future
api_server_1     |            ^^^^^^^^^^^^
api_server_1     |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
api_server_1     |     result = context.run(func, *args)
api_server_1     |              ^^^^^^^^^^^^^^^^^^^^^^^^
api_server_1     |   File …

Copy SearchQuery model with updated attribute due to Config.frozen=True

---

backend/danswer/configs/app_configs.py
backend/danswer/secondary_llm_flows/query_validation.py
backend/danswer/server/chat/search_backend.py

Applies to Ollama specifically but the removed check wouldn't be meaningful with a weak model anyway

Fix Weak Models Concurrency Issue

---

backend/danswer/chat/prompts.yaml
backend/danswer/prompts/chat_prompts.py
backend/danswer/secondary_llm_flows/choose_search.py

Changed the prompts so it searches in more cases for chat

Search more frequently

---

backend/danswer/connectors/cross_connector_utils/file_utils.py

Files that are the pdf type may not actually be pdf so when opening with pdfreader, it will throw an exception. In such cases, just keep the file title and keep contents empty like other failed Drive files.

Google Drive handle invalid PDFs

---

deployment/docker_compose/docker-compose.dev.yml
deployment/docker_compose/docker-compose.prod-no-letsencrypt.yml
deployment/docker_compose/docker-compose.prod.yml
deployment/kubernetes/vespa-service-deployment.yaml

Bump Vespa to 8.277.17

---

backend/danswer/connectors/confluence/connector.py

Hi,
The Confluence API exports the pages by replacing the Confluence user (ex: @matthieu.boret) with its internal user ID (referred to as 'account-it' or 'userKey'). Ex: `<ac:link><ri:user ri:account-id="5aa2706ad2bbf025fcdf39ac" /></ac:link>`
Our Confluence pages usually define the (lead) contributors in charge of the task/project/... 
By replacing the Confluence 'User ID' with the real Display Name, Danswer can answer questions like "Who is the Lead Contributor of the XXXX offer?"

Replace user id by the user display name in the exported Confluence page

---

backend/danswer/danswerbot/slack/blocks.py
backend/requirements/default.txt
backend/requirements/dev.txt

Add the latest document update to the Slack bot answer

---

backend/requirements/default.txt
backend/requirements/model_server.txt

Bump Transformer Version

---

backend/danswer/configs/app_configs.py
backend/danswer/danswerbot/slack/listener.py
backend/danswer/db/feedback.py

This was triggering mypy errors, updating to make sure we've got an int for this config value.

fix: parse INDEX_BATCH_SIZE to an int

---

backend/danswer/auth/users.py
backend/danswer/configs/app_configs.py
backend/danswer/server/manage/get_state.py
backend/danswer/server/manage/models.py
backend/danswer/server/manage/users.py
deployment/docker_compose/docker-compose.dev.yml
deployment/docker_compose/env.prod.template
deployment/kubernetes/env-configmap.yaml
web/src/app/auth/lib.ts
web/src/app/auth/login/EmailPasswordForm.tsx
web/src/app/auth/login/page.tsx
web/src/app/auth/signup/page.tsx
web/src/app/auth/verify-email/Verify.tsx
web/src/app/auth/verify-email/page.tsx
web/src/app/auth/waiting-on-verification/RequestNewVerificationEmail.tsx
web/src/app/auth/waiting-on-verification/page.tsx
web/src/app/chat/ChatPage.tsx
web/src/app/search/page.tsx
web/src/lib/constants.ts
web/src/lib/user.ts
web/src/lib/userSS.ts

Add support for basic auth on FE

---

backend/danswer/background/celery/celery.py

reduced redunduncy and changed concatenation of strings to f-strings

reduced redunduncy and changed concatenation of strings to f-strings

---

backend/danswer/server/query_and_chat/chat_backend.py
backend/danswer/server/query_and_chat/models.py
web/src/app/chat/Chat.tsx
web/src/app/chat/ChatIntro.tsx
web/src/app/chat/ChatPage.tsx
web/src/app/chat/ChatPersonaSelector.tsx
web/src/app/chat/interfaces.ts
web/src/app/chat/page.tsx
web/src/components/Modal.tsx

Revamp new chat screen for chat UI

---

backend/danswer/danswerbot/slack/handlers/handle_message.py
backend/danswer/search/request_preprocessing.py
backend/supervisord.conf

Also includes a supervisord seek fix

Slack LLM Filter Enabled by Default

---

backend/danswer/danswerbot/slack/blocks.py
web/src/app/admin/bot/SlackBotConfigCreationForm.tsx
web/src/app/admin/bot/lib.ts
web/src/components/admin/connectors/Field.tsx
web/src/lib/types.ts
web/tailwind.config.js

Slack confirmation UI

---

web/src/app/chat/Chat.tsx
web/src/app/chat/ChatIntro.tsx
web/src/components/search/SearchSection.tsx
web/src/lib/filters.ts
web/src/lib/sources.ts

Makes it so the initial Chat display upon selecting a persona shows the correct sources + only offers filters that are valid.

Fix connected sources display

---

.github/workflows/pr-python-tests.yml
backend/tests/unit/danswer/connectors/cross_connector_utils/test_html_utils.py

I've noticed that the tests are not running as part of the CI, so I am suggesting this addition if you want :)
You can see the new check below.

CI: Run Python tests

---

backend/danswer/configs/app_configs.py
backend/danswer/connectors/google_drive/connector.py
web/src/app/admin/connectors/google-drive/ConnectorEditPopup.tsx
web/src/app/admin/connectors/google-drive/GoogleDriveConnectorsTable.tsx
web/src/app/admin/connectors/google-drive/page.tsx
web/src/lib/types.ts

Google Drive Connector option to only include documents shared org wide

Option to only include Domain/Org wide docs

---

backend/danswer/connectors/danswer_jira/connector.py
web/src/app/admin/connectors/jira/page.tsx
web/src/lib/types.ts

Hello, guys!
Just created PR related to [this](https://github.com/danswer-ai/danswer/issues/508) issue.
Could you please check it?

Add Jira Server connector form

---

CONTRIBUTING.md

This update enhances the CONTRIBUTING.md guide by providing clear, separate instructions for activating the Python virtual environment on Windows, tailored for both Command Prompt and PowerShell users. Previously, the guide only included a generic command, which might not work across different shells without slight modifications. This change aims to make the setup process more accessible and straightforward for contributors using Windows, ensuring they have the correct commands for their specific environment. By reducing potential setup hurdles, we hope to streamline the initial contribution process for new developers.

Improve Virtual Env Activation Instructions for Windows

---

backend/danswer/db/engine.py

This reverts commit d07345c5330605c17f4ba66b71b32e4384541f2f.

Revert "Trace sqla get_session"

---

backend/alembic/versions/0a2b51deb0b8_add_starter_prompts.py
backend/danswer/chat/load_yamls.py
backend/danswer/db/chat.py
backend/danswer/db/models.py
backend/danswer/db/slack_bot_config.py
backend/danswer/server/features/persona/api.py
backend/danswer/server/features/persona/models.py
web/src/app/admin/personas/HidableSection.tsx
web/src/app/admin/personas/PersonaEditor.tsx
web/src/app/admin/personas/interfaces.ts
web/src/app/admin/personas/lib.ts
web/src/app/chat/Chat.tsx
web/src/app/chat/ChatIntro.tsx
web/src/app/chat/StarterMessage.tsx

Add ability to add starter messages

---

backend/danswer/connectors/danswer_jira/connector.py
backend/danswer/connectors/danswer_jira/utils.py
backend/danswer/connectors/models.py
web/src/app/admin/connector/[ccPairId]/ConfigDisplay.tsx
web/src/app/admin/connectors/jira/page.tsx
web/src/lib/types.ts

- Add feature exclude comments from particular users
- Add feature common and custom fields to jira tasks
Fix bug on web in ConfigDisplay.tsx

Jira connector improvements

---

deployment/helm/.gitignore
deployment/helm/.helmignore
deployment/helm/Chart.lock
deployment/helm/Chart.yaml
deployment/helm/templates/NOTES.txt
deployment/helm/templates/_helpers.tpl
deployment/helm/templates/api-deployment.yaml
deployment/helm/templates/api-hpa.yaml
deployment/helm/templates/api-service.yaml
deployment/helm/templates/background-deployment.yaml
deployment/helm/templates/background-hpa.yaml
deployment/helm/templates/configmap.yaml
deployment/helm/templates/connector-pvc.yaml
deployment/helm/templates/dynamic-pvc.yaml
deployment/helm/templates/ingress.yaml
deployment/helm/templates/secret.yaml
deployment/helm/templates/serviceaccount.yaml
deployment/helm/templates/tests/test-connection.yaml
deployment/helm/templates/vespa-service.yaml
deployment/helm/templates/vespa-statefulset.yaml
deployment/helm/templates/webserver-deployment.yaml
deployment/helm/templates/webserver-hpa.yaml
deployment/helm/templates/webserver-service.yaml
deployment/helm/values.yaml

Hi,
Has started on PR #1177 from @JayGhiya, i've also made a Helm Chart. May be we can merge our work to made a good chart for Danswer.

feat: add Helm chart

---

backend/danswer/db/engine.py
backend/danswer/llm/utils.py
backend/danswer/one_shot_answer/answer_question.py
backend/danswer/search/models.py

Save One Shot Docs

---

backend/danswer/configs/constants.py
backend/danswer/server/manage/administrative.py
backend/danswer/server/query_and_chat/query_backend.py
backend/danswer/server/query_and_chat/token_budget.py
web/src/app/admin/keys/openai/page.tsx
web/src/app/admin/personas/PersonaEditor.tsx

https://github.com/danswer-ai/danswer/pull/1077, but rebased to resolve conflicts

Token budgets

---

backend/alembic/versions/0a98909f2757_enable_encrypted_fields.py
backend/danswer/auth/users.py
backend/danswer/configs/app_configs.py
backend/danswer/connectors/gmail/connector_auth.py
backend/danswer/connectors/google_drive/connector_auth.py
backend/danswer/danswerbot/slack/tokens.py
backend/danswer/db/models.py
backend/danswer/dynamic_configs/interface.py
backend/danswer/dynamic_configs/store.py
backend/danswer/main.py
backend/danswer/server/danswer_api/ingestion.py
backend/danswer/utils/encryption.py
backend/danswer/utils/telemetry.py
backend/danswer/utils/variable_functionality.py
deployment/docker_compose/docker-compose.dev.yml
deployment/kubernetes/env-configmap.yaml

MIT version doesn't actually encrypt

Encrypted Sensitive Fields

---

deployment/README.md
deployment/docker_compose/README.md
deployment/docker_compose/docker-compose.gpu-dev.yml

Like discussed with @yuhongsun96 , here is my first draft with additions to 
- description with GPU support in docker compose dev 
- documentation with new README.md file
Open for any feedback about where the location of files should be.

add gpu support and README for documentation

---

backend/danswer/danswerbot/slack/blocks.py

Split slack messages up to 3K chars

---

backend/danswer/danswerbot/slack/handlers/handle_message.py

Useful to at least know that Danswer tried to answer the user's question.

Set follow-up emoji on an invalid answer

---

backend/danswer/connectors/danswer_jira/connector.py

- Implement `extract_text_from_content` to parse nested text elements from comment bodies.
- Modify `_get_comment_strs` to use the new text extraction method, improving handling of various content structures.

Refactor comment extraction in JIRA connector to handle nested content

---

backend/danswer/connectors/gitlab/connector.py

This Merge Request resolves an issue with the GitLab connector that was impeding the proper indexing of documents.
Related issues : 
- https://github.com/danswer-ai/danswer/issues/1100
- https://github.com/danswer-ai/danswer/issues/1109
Thanks to @m0wer and @herveleclerc for the solution.

Fix gitlab-connector - Wrong datetime format

---

backend/danswer/connectors/confluence/connector.py
backend/danswer/file_processing/extract_file_text.py

Some git mistakes have led me to merge the changes from [this](https://github.com/danswer-ai/danswer/pull/1343) pr here

Confluence: Add page attachments indexing

---

backend/Dockerfile
backend/danswer/db/document.py
backend/scripts/deletion_script.py

Relevant docs in [this PR](https://github.com/danswer-ai/danswer-docs/pull/91)

add forced connector deletion

---

web/src/components/health/healthcheck.tsx
web/src/lib/fetcher.ts

Adds basic handling of 403 requests in healthcheck.

add basic 403 support for healthcheck

---

web/src/components/Status.tsx

small bug: https://linear.app/danswer/issue/DAN-40/show-connector-error-on-hover
Before and after

fix wrapping in error hover connector

---

web/src/components/admin/connectors/table/SingleUseConnectorsTable.tsx

add basic table wrapping

---

backend/danswer/connectors/discourse/connector.py

- Update topic polling
- Implement rate limiting based on https://meta.discourse.org/t/available-settings-for-global-rate-limits-and-throttling/78612

fix discourse connector rate limiting + topic fetching

---

web/src/components/search/SearchBar.tsx
web/src/components/search/SearchSection.tsx

show "analysis"

---

web/src/app/assistants/gallery/page.tsx
web/src/app/chat/shared_chat_search/FixedLogo.tsx

- adds untracked file which left previously fixed issue in a page

minor update

---

web/src/app/chat/modal/configuration/AssistantsTab.tsx
web/src/app/chat/shared_chat_search/FixedLogo.tsx

- Assistants tab size
- Fixed logo -> absolute

minor fixes

---

backend/danswer/connectors/discourse/connector.py
web/src/app/chat/ChatBanner.tsx
web/src/app/chat/ChatPage.tsx
web/src/app/chat/sessionSidebar/HistorySidebar.tsx
web/src/app/chat/shared_chat_search/FixedLogo.tsx
web/src/app/chat/shared_chat_search/FunctionalWrapper.tsx
web/src/app/search/page.tsx
web/src/components/Logo.tsx
web/src/components/admin/Layout.tsx
web/src/components/admin/connectors/AdminSidebar.tsx
web/src/components/chat_search/Header.tsx
web/src/components/header/Header.tsx

https://github.com/user-attachments/assets/042688a8-75c9-4179-995b-7dddedb2d16b
https://github.com/user-attachments/assets/3be9e5f9-54dc-4fe6-abf6-ec25e08e62bd
https://github.com/user-attachments/assets/7ef15342-2ad3-4178-a9b3-6df3541034bf

everything functional

---

web/src/app/admin/assistants/AssistantEditor.tsx

Slightly clearer description of model settings in assistants creation tab

---

web/src/app/chat/shared/[chatId]/SharedChatDisplay.tsx
web/src/components/header/Header.tsx

Adds files to explicitly shared chats

add files (images)

---

backend/danswer/chat/process_message.py

This PR fixes [this](https://github.com/danswer-ai/danswer/issues/1946) issue where common user being unable to interact with custom assistants.

Issue 1946 fix

---

web/src/app/admin/connectors/[connector]/AddConnectorPage.tsx

Fixed the default indexing frequency
I created a connector and printed out the indexing frequency

Fixed default indexing frequency

---

backend/alembic/versions/8a87bd6ec550_associate_index_attempts_with_ccpair.py

Removes unnecessary drop of index which could cause issues with downgrading migrations in the future.
Upgrading and downgrading from previous commit SHAs.

Remove unnecessary index drop

---

backend/tests/unit/danswer/connectors/mediawiki/test_wiki.py

fix removed parameter in MediaWikiConnector

---

backend/danswer/background/update.py

avoid reindexing secondary indexes after they succeed

---

backend/danswer/db/persona.py
web/src/app/admin/assistants/AssistantEditor.tsx
web/src/app/admin/assistants/lib.ts
web/src/app/admin/connectors/[connector]/AddConnectorPage.tsx
web/src/app/chat/sessionSidebar/ChatSessionDisplay.tsx
web/src/app/chat/sessionSidebar/HistorySidebar.tsx
web/src/app/chat/sessionSidebar/PagesTab.tsx
web/src/app/chat/shared_chat_search/FixedLogo.tsx
web/src/components/assistants/AssistantIconCreation.tsx
web/src/components/chat_search/Header.tsx
web/src/components/header/Header.tsx

Make chat page layout cleaner + fix updating assistant images

---

backend/alembic/versions/8a87bd6ec550_associate_index_attempts_with_ccpair.py

Fix index attempt migration where no credential ID

---

backend/danswer/indexing/indexing_pipeline.py

Minor update- process null titles

---

web/src/app/admin/assistants/AssistantEditor.tsx
web/src/components/admin/connectors/Field.tsx

Add proper default values for assistant editing / creation

---

web/src/app/layout.tsx
web/src/components/UserDropdown.tsx

Fix user dropdown font

---

backend/danswer/llm/answering/answer.py
backend/danswer/llm/answering/prompts/build.py
backend/danswer/llm/chat_llm.py
backend/danswer/llm/utils.py
backend/danswer/tools/images/prompt.py

Fixes:
- Doubling up of tool calls ("too long ID" being passed to OpenAI)
- Describing incorrect image set
- No images generated at all

Fix image generation

---

backend/danswer/background/indexing/job_client.py

syntax changes to make indexing tasks actually run in a process
Observed code and logging correctly updating only in the new process

pass function to Process correctly instead of running it inline

---

web/src/app/admin/documents/explorer/Explorer.tsx
web/src/app/chat/input/ChatInputBar.tsx
web/src/components/search/SearchBar.tsx

Detect foreign key composition sessions

---

web/src/app/chat/ChatPage.tsx
web/src/app/chat/input/ChatInputBar.tsx

- Disallow reply cancellation 
- Create popup when new question is submitted mid reply
- Visually validated on local build:
- A new query can not be sent while response is in progress
- Send button is set to inactive color while response is in progress
- Warning popup visible if query submission is attempted while response is in progress
- Ran prettier formatter
None known
N/A

Remove partially implemented reply cancellation

---

web/src/app/admin/models/embedding/page.tsx

Should never have a `<div>` within a `<p>` tag

Fix minor html error

---

web/src/app/chat/message/CodeBlock.tsx

Fix code pasting formatting

---

backend/danswer/natural_language_processing/search_nlp_models.py

Adds some basic retries + a better error message.
With the embedding model integration test

Harden embedding calls

---

backend/danswer/prompts/llm_chunk_filter.py
backend/danswer/search/postprocessing/postprocessing.py
backend/danswer/secondary_llm_flows/chunk_usefulness.py
web/src/components/search/SearchResultsDisplay.tsx
web/src/components/search/SearchSection.tsx

Ensure consistency of answers/history + update llm relevance prompting

---

web/src/app/admin/connectors/[connector]/AddConnectorPage.tsx
web/src/app/admin/connectors/[connector]/pages/Create.tsx
web/src/app/admin/indexing/status/CCPairIndexingStatusTable.tsx
web/src/app/chat/sessionSidebar/HistorySidebar.tsx

Remove non-EE public connector options

---

backend/danswer/db/connector.py
web/src/app/admin/connectors/[connector]/AddConnectorPage.tsx
web/src/app/admin/connectors/[connector]/pages/Create.tsx
web/src/app/assistants/gallery/AssistantsGallery.tsx
web/src/app/assistants/mine/AssistantsList.tsx
web/src/app/assistants/mine/page.tsx
web/src/app/chat/ChatPage.tsx
web/src/app/chat/modal/configuration/AssistantsTab.tsx
web/src/app/chat/sessionSidebar/HistorySidebar.tsx
web/src/components/assistants/AssistantCards.tsx
web/src/components/chat_search/Header.tsx
web/src/components/search/SearchSection.tsx
web/src/components/table/DraggableTable.tsx
web/src/lib/assistants/updateAssistantPreferences.ts
web/src/lib/chat/fetchChatData.ts

Better assistant interactions + UI

---

web/src/app/chat/message/Messages.tsx
web/src/components/search/SearchSection.tsx
web/src/components/search/results/QuotesSection.tsx

Remove "quotes" section when unused

---

web/src/app/assistants/mine/AssistantsList.tsx
web/src/components/assistants/AssistantCards.tsx

Fix assistant drag transform effect

---

web/src/app/chat/shared/[chatId]/SharedChatDisplay.tsx
web/src/components/admin/connectors/AdminSidebar.tsx

"back to danswer" -> "back to [name]"

Whitelabelling consistency

---

web/src/app/assistants/ToolsDisplay.tsx

Update tool display bubbles to have cursor-default

---

web/src/app/chat/documentSidebar/ChatDocumentDisplay.tsx
web/src/app/chat/documentSidebar/DocumentSidebar.tsx

Doc sidebar width fix

---

backend/danswer/chat/process_message.py

Somewhat clearer API errors

---

backend/danswer/db/chat.py
backend/danswer/server/query_and_chat/chat_backend.py
web/src/app/chat/ChatPage.tsx
web/src/app/chat/files/images/InMessageImage.tsx
web/src/app/chat/message/Messages.tsx
web/src/app/chat/modal/ShareChatSessionModal.tsx
web/src/app/chat/sessionSidebar/HistorySidebar.tsx
web/src/app/chat/sessionSidebar/types.ts
web/src/app/chat/shared/[chatId]/SharedChatDisplay.tsx
web/src/app/chat/shared/[chatId]/page.tsx
web/src/components/chat_search/Header.tsx

- show ai generated images
- proper sizing

Improve shared chat page

---

backend/ee/danswer/server/seeding.py

Seeding now supports (in addition to previous functioanlity)
- White labelling configuration
- Analytics script
- We can remove this.

Improve seeding (includes all enterprise features)

---

web/src/app/chat/sessionSidebar/HistorySidebar.tsx
web/src/components/chat_search/Header.tsx
web/src/components/header/LogoType.tsx

Previously, new chat was purely a button- now can adopt a ReactJS standard for linking + button reset.
https://github.com/user-attachments/assets/e333fd1b-2fd6-4c3b-94af-d7be5af0c3dc
New behavior is in the attached video

Improve new chat button redirects

---

web/src/app/chat/ChatPage.tsx

Add proper delay for assistant switching

---

backend/danswer/one_shot_answer/answer_question.py
backend/danswer/search/pipeline.py
backend/danswer/server/documents/connector.py
backend/danswer/server/documents/models.py
backend/danswer/tools/search/search_tool.py
web/src/app/admin/add-connector/page.tsx
web/src/app/admin/connector/[ccPairId]/ConfigDisplay.tsx
web/src/app/admin/connector/[ccPairId]/page.tsx
web/src/app/admin/connectors/[connector]/AddConnectorPage.tsx
web/src/app/chat/modal/configuration/AssistantsTab.tsx
web/src/app/globals.css
web/src/components/admin/connectors/ConnectorForm.tsx
web/src/components/assistants/AssistantCards.tsx
web/src/components/icons/icons.tsx
web/src/components/search/DocumentDisplay.tsx
web/src/components/search/DocumentFeedbackBlock.tsx
web/src/components/search/QAFeedback.tsx
web/src/components/search/SearchResultsDisplay.tsx
web/src/components/search/SearchSection.tsx
web/src/components/search/results/QuotesSection.tsx
web/src/components/search/results/ResponseSection.tsx
web/src/lib/search/streamingQa.ts

• Show advanced connector options in the view connector details/runs page
• Show only if they overwrote it?
• Fixed height answer that become scrollable with a text clickable on the top right "expand" to make it uncapped in size like it is right now
• Can we have a "See Connectors" button on the add connectors page, similar to how we have it on the existing connectors page?
• Eyeglass for focus/show-all in search?
• Need a bit more time for the different steps for fast/agent search (they can even start a bit early artificially if needed, like the generating analysis)
• Tab wrapping
• Scrollable assistants tab
• Web edge case public?
• Also for that I think we can say "Running analysis" then "Generating answer"?
• I'm not sure about the quotes text being italicized
• The thumbs up/down …

Admin UX updates

---

backend/danswer/chat/process_message.py
backend/danswer/search/pipeline.py
backend/danswer/search/utils.py
backend/ee/danswer/server/query_and_chat/query_backend.py

Handle saved search docs in eval flow

---

backend/danswer/configs/app_configs.py
backend/danswer/db/engine.py

Added POSTGRES_POOL_PRE_PING and POSTGRES_POOL_RECYCLE variables.

add postgres configuration

---

backend/danswer/danswerbot/slack/blocks.py
backend/danswer/llm/answering/stream_processing/quotes_processing.py
backend/tests/unit/danswer/llm/answering/stream_processing/test_quote_processing.py

Account for empty links + fix quote processing

---

.vscode/launch.template.jsonc

modified the launch.template.jsonc to include a combination of all major configs to run in one click.
Also naming each config in their respective console.

quality of life improvements for the launch.json template

---

backend/danswer/llm/utils.py
web/src/app/chat/ChatPage.tsx
web/src/app/chat/message/Messages.tsx
web/src/lib/llm/utils.ts

Fixes image encoding issue by properly selecting assistant override in chat page

Select proper assistant override

---

web/src/app/chat/ChatPage.tsx
web/src/app/chat/files/images/InMessageImage.tsx

1-liner to make switching more robust for id 0

Fix model override for persisting default assistant

---

web/src/app/chat/files/images/InMessageImage.tsx

Image -> img

---

backend/danswer/llm/llm_provider_options.py
web/src/lib/hooks.ts

Add new gpt-4o model

---

web/src/app/globals.css

Fix edge case with simpler code block + python formatting

---

backend/danswer/natural_language_processing/search_nlp_models.py
backend/danswer/search/postprocessing/postprocessing.py
backend/model_server/encoders.py
backend/model_server/main.py
backend/model_server/management_endpoints.py
backend/shared_configs/configs.py
backend/shared_configs/model_server_models.py

Rework reranker

---

backend/danswer/natural_language_processing/search_nlp_models.py
backend/danswer/natural_language_processing/utils.py

Tested through the search eval pipeline and confirmed to work
Will need to be replaced with permanent fix later

Openai encoding temp hotfix

---

backend/danswer/connectors/google_drive/connector.py

Add support for google slides

---

web/src/app/admin/indexing/status/CCPairIndexingStatusTable.tsx
web/src/app/chat/ChatPage.tsx
web/src/app/chat/modal/FeedbackModal.tsx
web/src/components/icons/icons.tsx
web/src/components/search/SearchAnswer.tsx
web/src/components/search/SearchSection.tsx

- Separate `SearchAnswer` into its own  component (considering our recent decision to focus on the separate flows + general code quality)
- Filter `NA` source types in indexing status view
- Cleaner modal for feedback + more aligned with reset of UI (screenshot below)
- None

(Minor) Add cleaner search, feedback model, and connector view

---

backend/danswer/llm/answering/stream_processing/citation_processing.py
backend/tests/unit/danswer/llm/answering/stream_processing/test_citation_processing.py

Fixes edge case where LLMs manually generate their own citations (as opposed to our `citation_processing` doing it for htem)

improve llm-generated citations (account for edge case)

---

web/src/app/chat/documentSidebar/ChatDocumentDisplay.tsx

https://www.loom.com/share/ccb2413b70dd42f5ac90a7cd9d083e74?sid=5ec9296d-9d77-4e5c-92a5-651e41d49b97

open chatdocument links in a new tab instead of overriding danswers tab

---

web/src/app/admin/assistants/AssistantEditor.tsx

Enable assistant renaming

---

backend/alembic/versions/7477a5f5d728_added_model_defaults_for_users.py
backend/danswer/db/models.py
backend/danswer/indexing/chunker.py
backend/danswer/indexing/embedder.py
backend/danswer/natural_language_processing/search_nlp_models.py
backend/danswer/natural_language_processing/utils.py
backend/danswer/server/manage/embedding/models.py
backend/model_server/constants.py
backend/model_server/encoders.py
backend/shared_configs/enums.py
backend/shared_configs/model_server_models.py
backend/tests/integration/embedding/test_embeddings.py
web/src/app/admin/models/embedding/modals/SelectModelModal.tsx

Adds more guarantee to code correctness

Propagate Embedding Enum

---

backend/danswer/main.py

Provider type default to none

---

backend/danswer/connectors/slack/utils.py

Adding more retries + better logging

Slack improvements

---

web/src/components/search/SearchResultsDisplay.tsx
web/src/components/search/SearchSection.tsx

Add cleaner / consolidate `no docs found` message

---

web/src/app/chat/ChatPage.tsx
web/src/app/chat/message/Messages.tsx
web/src/components/search/SearchSection.tsx

https://github.com/user-attachments/assets/3f6b045a-3f5b-4078-9cf3-b9af3e822b89

Add scrollbar to search / chat

---

web/src/components/search/SearchAnswer.tsx

Minor fix for quote overflowing in search bar
- Update overflow / expansion check + remove overflow if expanded

Fix overflow for quotes in search section

---

web/src/components/search/SearchBar.tsx
web/src/components/search/SearchSection.tsx

https://github.com/user-attachments/assets/f3d2d238-2962-4584-8e76-105c73a0f6eb

Always show search filters

---

web/src/app/admin/users/page.tsx

Minor update to clarify user adding

---

backend/ee/danswer/server/saml.py
web/src/app/auth/saml/callback/route.ts

SAML improvements

---

backend/scripts/force_delete_connector_by_id.py

Account for new`DELETING` state

Update force deletion script

---

backend/alembic/versions/4a951134c801_moved_status_to_connector_credential_.py
backend/danswer/indexing/indexing_pipeline.py

Cohere No Large Chunks

---

backend/danswer/chat/models.py
backend/danswer/chat/process_message.py
backend/danswer/llm/utils.py
web/src/app/admin/connector/[ccPairId]/IndexingAttemptsTable.tsx
web/src/app/chat/ChatPage.tsx
web/src/app/chat/interfaces.ts
web/src/app/chat/message/Messages.tsx
web/src/components/modals/ExceptionTraceModal.tsx

- Display custom error responses for each possible exception
- Robustified assistant switching (now accounts for search_params and initial assistant loading) 

Add verbose error messages + robustify assistant switching

---

backend/ee/danswer/server/enterprise_settings/store.py
backend/ee/danswer/server/seeding.py

Enable seeding of analytics via file path

---

backend/danswer/db/persona.py
backend/danswer/server/features/persona/models.py
backend/ee/danswer/server/seeding.py
web/src/app/admin/assistants/AssistantEditor.tsx
web/src/app/admin/assistants/lib.ts
web/src/app/chat/sessionSidebar/PagesTab.tsx
web/src/components/assistants/AssistantIconCreation.tsx

Enable persistence / removal of assistant icons + remove accidental regression

---

backend/alembic/versions/8a87bd6ec550_associate_index_attempts_with_ccpair.py

Accounts for deletion script scenario where index attempt is fully stranded

Extremely robustified Index Attempt migration

---

backend/ee/danswer/server/seeding.py

Make it so models / personas are always seeded

improve model seeding

---

backend/danswer/configs/app_configs.py
backend/danswer/db/engine.py

Add PG query logging

---

backend/danswer/chat/chat_utils.py
backend/danswer/chat/models.py
backend/danswer/chat/process_message.py
backend/danswer/db/chat.py
backend/danswer/llm/answering/answer.py
backend/danswer/server/query_and_chat/chat_backend.py
web/src/app/chat/ChatPage.tsx
web/src/app/chat/input/ChatInputBar.tsx
web/src/app/chat/interfaces.ts
web/src/app/chat/lib.tsx
web/src/app/chat/message/Messages.tsx
web/src/app/chat/sessionSidebar/ChatSessionDisplay.tsx
web/src/app/chat/sessionSidebar/HistorySidebar.tsx
web/src/app/chat/sessionSidebar/PagesTab.tsx
web/src/app/chat/types.ts
web/src/components/icons/icons.tsx
web/src/lib/search/streamingUtils.ts
web/tailwind-themes/tailwind.config.js

Add `stop generating` functionality

---

web/src/app/chat/message/Messages.tsx

Prevent empty doc link click

---

web/src/components/chat_search/hooks.ts

https://github.com/user-attachments/assets/9f6f34ec-e036-409e-b4d1-f6cdca7fcd20

Remove history sidebar on mouse exiting window

---

backend/danswer/chat/process_message.py

Show full stack trace

---

web/src/app/chat/message/Messages.tsx
web/src/lib/search/streamingUtils.ts

When SSE streams are slow, they split up the JSON they return- we need to accomodate this on our SSE handler to gather packets before sending them back to chat's consumer!

Update SSE handling to accommodate slow networks

---

backend/danswer/connectors/guru/connector.py

Added collection name and type for each card to the metadata

added collection and collection type to Guru metadata

---

backend/alembic/versions/d9ec13955951_remove__dim_suffix_from_model_name.py
backend/danswer/db/embedding_model.py
backend/danswer/indexing/models.py
backend/danswer/server/manage/search_settings.py
backend/model_server/encoders.py

- Removes suffix in prior model names
- Removes custom handling for suffixes
- Uses index name directly (as before)

Simplify index and model name swap logic

---

backend/Dockerfile.model_server
backend/model_server/custom_models.py

Avoid having 2 caches and issues of model downloading on server startup
Ran the containers with no network

Fix Model Server

---

backend/alembic/versions/4b08d97e175a_change_default_prune_freq.py

Update alembic version (for rebase)

---

web/src/components/credentials/actions/CreateCredential.tsx
web/src/components/credentials/lib.ts
web/src/lib/connectors/credentials.ts

Single interface for Jira cloud + Data Center versoin.

Jira email optional + PAT

---

web/src/app/layout.tsx
web/src/components/settings/lib.ts

Remove settings cache

---

backend/danswer/background/indexing/run_indexing.py
backend/danswer/background/update.py
backend/danswer/db/deletion_attempt.py
backend/danswer/db/enums.py

https://linear.app/danswer/issue/DAN-458/fix-deleting-connectors-running

Fix connectors running while deleting

---

backend/danswer/auth/users.py
backend/danswer/server/manage/models.py
web/src/app/layout.tsx
web/src/components/settings/lib.ts

Currently, those who have set up OIDC + used the `oidc_expiry` can get trapped in perma loops where they login, but then are redirected back to the login page. This resolves that. 
Tested by replicating then verifying it's no longer there after this change.
Additionally, there was an issue that a logged out user would get the `Settings Unavailable` page 😓

Fix OIDC expiry issues

---

backend/danswer/chat/process_message.py
backend/danswer/configs/chat_configs.py
backend/danswer/configs/model_configs.py
backend/danswer/db/models.py
backend/danswer/db/persona.py
backend/danswer/llm/answering/models.py
backend/danswer/llm/answering/prune_and_merge.py
backend/danswer/llm/utils.py
backend/danswer/search/models.py
backend/danswer/search/pipeline.py
backend/danswer/search/preprocessing/preprocessing.py
backend/danswer/search/retrieval/search_runner.py
backend/danswer/tools/search/search_tool.py
backend/ee/danswer/server/query_and_chat/chat_backend.py
backend/ee/danswer/server/query_and_chat/query_backend.py

Add above/below settings for chunk retrieved for search
Verified working search/chat/slack flows locally

Enable Surrounding Context

---

backend/alembic/versions/ee3f4b47fad5_added_alternate_model_to_chat_message.py
backend/danswer/chat/chat_utils.py
backend/danswer/chat/process_message.py
backend/danswer/db/chat.py
backend/danswer/db/models.py
backend/danswer/llm/utils.py
backend/danswer/server/query_and_chat/chat_backend.py
backend/danswer/server/query_and_chat/models.py
web/src/app/chat/ChatPage.tsx
web/src/app/chat/RegenerateOption.tsx
web/src/app/chat/interfaces.ts
web/src/app/chat/lib.tsx
web/src/app/chat/message/Messages.tsx
web/src/components/Dropdown.tsx
web/src/components/Hoverable.tsx
web/src/components/icons/icons.tsx

Enables regeneration
- New `regeneration` argument which regenerates AI message based on parent ID
- Stores given LLM override in the database as `overridden_model`
https://github.com/user-attachments/assets/99fcded5-121f-49c7-83f6-d85582082e99
- Many various models for regeneration and verified correct models stored + used during genreation

Regenerate (branch of stop)

---

web/src/app/admin/configuration/llm/CustomLLMProviderUpdateForm.tsx

Clarify requirements with a useful link on custom models page.

clarify what model and provider name should be for custom models

---

web/src/components/search/DocumentDisplay.tsx

Account for empty text in highlighting edge case

---

web/src/app/layout.tsx
web/src/components/chat_search/Header.tsx
web/src/components/settings/lib.ts

No need to check for 404s as we can now gracefully handle misconfigured Danswer instances (just by showing a little popup)

slightly updated settings error

---

backend/ee/danswer/server/query_history/api.py

Downloaded the CSV successfully + saw the new columns as expected

Add chat_session_id + message_pair_num

---

backend/alembic/versions/f17bf3b0d9f1_embedding_provider_by_provider_type.py

Alembic once again

---

web/src/app/chat/ChatPage.tsx
web/src/app/chat/message/Messages.tsx
web/src/app/chat/message/SearchSummary.tsx
web/src/components/admin/ClientLayout.tsx

- Updates packet processing logic to set query / tool call values as early as possible
- Removes rebase artifact (search settings tooltip)
Before and after
https://github.com/user-attachments/assets/f374f881-5c69-4ff5-a409-c81ba16701d5
https://github.com/user-attachments/assets/250df2d8-eec4-4f41-925b-484804bc15f1

Update search tool selection

---

web/src/app/ee/admin/whitelabeling/WhitelabelingForm.tsx

Related docs PR: https://github.com/danswer-ai/danswer-docs/pull/112

Update white-labelling to be clearer (advanced settings)

---

web/src/app/admin/assistants/PersonaTable.tsx
web/src/app/admin/connectors/[connector]/AddConnectorPage.tsx
web/src/app/admin/connectors/[connector]/pages/Create.tsx
web/src/app/admin/connectors/[connector]/pages/gdrive/GoogleDrivePage.tsx
web/src/app/admin/connectors/[connector]/pages/gmail/GmailPage.tsx
web/src/app/admin/documents/sets/page.tsx
web/src/app/chat/ChatPage.tsx
web/src/app/chat/modal/SetDefaultModelModal.tsx
web/src/app/chat/page.tsx
web/src/app/ee/admin/groups/[groupId]/GroupDisplay.tsx
web/src/app/ee/admin/groups/page.tsx
web/src/app/layout.tsx
web/src/components/IsPublicGroupSelector.tsx
web/src/components/context/ChatContext.tsx
web/src/components/credentials/actions/CreateCredential.tsx
web/src/components/user/UserProvider.tsx

Adds a (client side) user provider for use in children components.

User provider hook

---

web/src/app/chat/documentSidebar/DocumentSidebar.tsx
web/src/app/chat/input/ChatInputBar.tsx
web/src/app/chat/message/Messages.tsx

Add `id` to each major section

Add CSS identifiers to main sections

---

backend/danswer/db/slack_bot_config.py
backend/danswer/search/preprocessing/preprocessing.py
backend/danswer/server/manage/slack_bot.py

This change propagates the autofilters setting down to the slack bot persona creation

Fixed slack bot auto filters for document sets

---

web/src/components/header/LogoType.tsx
web/src/components/search/DateRangeSelector.tsx
web/src/components/search/SearchBar.tsx
web/src/components/search/SearchSection.tsx
web/src/components/search/filtering/FilterDropdown.tsx
web/src/components/search/filtering/Filters.tsx

https://linear.app/danswer/issue/DAN-459/bugs
https://github.com/user-attachments/assets/555f7c67-3ce3-44c7-a7f1-17340f9ad7df

Add some quick search filter logic (UX)

---

backend/danswer/db/document_set.py
backend/danswer/server/features/document_set/api.py
backend/tests/integration/common_utils/document_sets.py
web/src/app/admin/documents/sets/hooks.tsx
web/src/lib/assistants/fetchPersonaEditorInfoSS.ts

Combined the admin and non admin endpoints for retrieving document sets and just applied the filters based on the users permissions

Combined the get document set endpoints

---

web/src/app/chat/ChatPage.tsx

Constant refresh is useful when editing image settings constantly, but not for general display case

Remove logotype constant refresh artifact

---

backend/danswer/connectors/confluence/connector.py

Handle missing email more gracefully

---

web/src/app/admin/documents/sets/DocumentSetCreationForm.tsx
web/src/components/IsPublicGroupSelector.tsx

Filter by user for docset display

---

.github/workflows/pr-python-checks.yml
.github/workflows/pr-python-tests.yml
.github/workflows/pr-quality-checks.yml

Add other checks to merge queue

---

.github/workflows/pr-quality-checks.yml

Fix pr quality checks

---

backend/danswer/configs/app_configs.py
backend/danswer/connectors/confluence/connector.py

https://linear.app/danswer/issue/DAN-487/fix-confluence-indexing-permissions-issue
Tested with my 👀

Confluence improvements

---

backend/danswer/auth/users.py
web/src/app/admin/connectors/[connector]/AddConnectorPage.tsx
web/src/app/ee/admin/groups/UserGroupsTable.tsx
web/src/app/ee/admin/groups/[groupId]/GroupDisplay.tsx
web/src/components/IsPublicGroupSelector.tsx

changes:
- fixed some frontend logic errors
- improved logging

Some additional curator polish

---

web/src/app/admin/indexing/status/CCPairIndexingStatusTable.tsx

Change search input background

---

backend/danswer/configs/model_configs.py
backend/danswer/llm/chat_llm.py
backend/danswer/llm/custom_llm.py
backend/danswer/llm/utils.py
backend/danswer/prompts/prompt_utils.py
backend/danswer/tools/search/search_tool.py

Adjusts maximum input size based on the actual context window

Get accurate model output max

---

backend/alembic/env.py

alembic keeps trying to modify kombu tables because it doesn't know about them. they are generated by celery automatically.
This tells alembic to ignore the tables when generating migrations.
We should do an entire pass across all the tables alembic doesn't recognize when creating migrations and reconcile them.

ignore kombu tables used by celery in alembic

---

web/src/app/chat/shared_chat_search/FunctionalWrapper.tsx
web/src/components/icons/icons.tsx
web/src/lib/browserUtilities.tsx

Update command keys / header

---

web/src/app/admin/configuration/llm/CustomLLMProviderUpdateForm.tsx
web/src/app/admin/configuration/llm/LLMProviderUpdateForm.tsx
web/src/components/admin/connectors/Field.tsx

Add better spacing

---

backend/danswer/background/indexing/run_indexing.py
backend/danswer/db/connector_credential_pair.py

Account for edge case in indexing times with connectors

---

web/src/components/chat_search/Header.tsx

Minor simplification to chat header

---

web/src/app/admin/connectors/[connector]/pages/Advanced.tsx
web/src/app/admin/connectors/[connector]/pages/DynamicConnectorCreationForm.tsx
web/src/app/admin/embeddings/RerankingFormPage.tsx
web/src/app/admin/embeddings/modals/ProviderCreationModal.tsx
web/src/app/admin/embeddings/pages/EmbeddingFormPage.tsx

Allow users to de-select reranking

allow users to deselect reranking

---

backend/danswer/connectors/README.md

Update connector creation docs

---

backend/danswer/file_processing/extract_file_text.py

Add typing to pdf extraction

---

web/src/components/UserDropdown.tsx

Very minor update to divider logic

---

backend/danswer/llm/llm_provider_options.py

Switches to use claude 3.5 by default

Update default anthropic / bedrock models

---

web/src/app/admin/configuration/search/UpgradingPage.tsx
web/src/app/admin/embeddings/modals/ProviderCreationModal.tsx
web/src/components/embedding/ReindexingProgressTable.tsx

Prevent jumping around in indexing status table.

Ordered indexing status

---

web/src/app/chat/message/CodeBlock.tsx

update code block

---

backend/danswer/connectors/confluence/rate_limit_handler.py
backend/danswer/connectors/web/connector.py
backend/danswer/db/auth.py
backend/danswer/file_store/utils.py
backend/danswer/search/postprocessing/postprocessing.py
backend/danswer/tools/tool_runner.py

Add proper typing such that tests pass mypy

---

backend/tests/integration/tests/connector/test_connector_deletion.py

Add back test

---

web/src/app/admin/connectors/[connector]/AddConnectorPage.tsx
web/src/app/admin/connectors/[connector]/ConnectorWrapper.tsx
web/src/app/admin/connectors/[connector]/page.tsx
web/src/app/admin/indexing/status/CCPairIndexingStatusTable.tsx
web/src/app/chat/ChatIntro.tsx
web/src/lib/connectors/connectors.ts
web/src/lib/connectors/credentials.ts
web/src/lib/sources.ts
web/src/lib/types.ts

Prevents page from crashing in the case that a connector with source `INGESTION_API` is setup.
It also fixes typing for `ValidSources` + fixes a small bug with the google sites connector.

Add ingestion as a "Source" for the FE + improve typing

---

web/src/components/llm/LLMList.tsx

Prevent accidental submission

---

backend/danswer/configs/app_configs.py
web/src/app/admin/configuration/search/UpgradingPage.tsx
web/src/app/admin/embeddings/EmbeddingModelSelectionForm.tsx
web/src/app/admin/embeddings/RerankingFormPage.tsx
web/src/app/admin/embeddings/pages/CloudEmbeddingPage.tsx
web/src/app/chat/ChatPage.tsx

Minor search setting clarity

---

backend/danswer/db/index_attempt.py

This improves performance quite a bit on the indexing status summary page

made connectors summary page faster

---

deployment/docker_compose/init-letsencrypt.sh

Rename cert directory if needed

---

backend/danswer/db/chat.py
backend/danswer/server/query_and_chat/query_backend.py
web/src/app/admin/connectors/[connector]/AddConnectorPage.tsx
web/src/app/admin/connectors/[connector]/pages/ConnectorInput/SelectInput.tsx
web/src/app/assistants/ToolsDisplay.tsx
web/src/app/chat/sessionSidebar/ChatSessionDisplay.tsx
web/src/components/search/SearchAnswer.tsx
web/src/components/search/SearchSection.tsx
web/src/lib/search/streamingQa.ts

Proper popover behavior, no showing queries with no docs, + bubbles

---

backend/danswer/server/manage/users.py
web/src/components/admin/users/InvitedUserTable.tsx
web/src/components/admin/users/SignedUpUserTable.tsx
web/src/lib/admin/users/userMutationFetcher.ts

Add ability to delete users

---

web/src/app/admin/configuration/llm/LLMProviderUpdateForm.tsx
web/src/app/chat/ChatPage.tsx

Fixes [DAN-569
](https://linear.app/danswer/issue/DAN-569/odd-behavior-on-first-chat-in-cloud)

Minor QOL improvement on first chat

---

web/src/app/chat/ChatPage.tsx

Squash misc UX bugs

---

backend/danswer/connectors/danswer_jira/connector.py

Fix formatting

---

web/next.config.js
web/src/app/api/[...path]/route.ts

Allows local dev with auth enabled + using streaming endpoints

Fix streaming auth locally

---

web/src/app/chat/ChatPage.tsx
web/src/app/chat/input/ChatInputBar.tsx
web/src/app/chat/message/Messages.tsx

Fixes Dan-575
Link to videos of issues fixed: https://linear.app/danswer/issue/DAN-575/annoying-cut-off-in-message-edits

address pablo's nits

---

web/src/components/search/SearchBar.tsx
web/src/components/search/SearchResultsDisplay.tsx
web/src/components/search/SearchSection.tsx
web/src/lib/connectors/connectors.ts

Prevent spam search

---

web/src/app/admin/embeddings/pages/EmbeddingFormPage.tsx

`selectedProvider` may contain stale data we want `advancedEmbeddingDetails` to override

Update spread order

---

backend/danswer/background/indexing/run_indexing.py
backend/danswer/background/update.py
backend/danswer/utils/logger.py

Add ccpair id to logging

---

web/src/app/chat/ChatPage.tsx

Simplify unnecessary display logic

---

web/src/lib/llm/utils.ts

Add image support

---

backend/danswer/background/celery/celeryconfig.py

quick bugfix for redis scheme setting

fix setting redis_scheme

---

backend/danswer/redis/redis_pool.py

another quick fix for the general use redis pool

fix enabling ssl in connection pool

---

web/src/app/chat/message/Messages.tsx
web/src/app/globals.css
web/tailwind-themes/tailwind.config.js

Updates theming to be best practice and extensible.

Reformatted tailwind config

---

backend/danswer/db/search_settings.py
web/src/app/admin/embeddings/RerankingFormPage.tsx

Warm up reranker on model switch

---

web/src/app/chat/ChatPage.tsx

Delete chat session immediately

---

web/src/app/admin/embeddings/modals/ProviderCreationModal.tsx
web/src/app/admin/embeddings/pages/EmbeddingFormPage.tsx
web/src/app/chat/page.tsx
web/src/app/layout.tsx
web/src/app/search/page.tsx
web/src/components/initialSetup/welcome/WelcomeModal.tsx

Update refresh + robustify embeddings

---

backend/alembic/versions/1f60f60c3401_embedding_model_search_settings.py

Update multipass indexing server default

---

web/src/app/admin/assistants/AssistantEditor.tsx
web/src/app/chat/ChatPage.tsx
web/src/lib/llm/utils.ts

Minor update to llm image ability tracking

---

backend/danswer/chat/process_message.py
backend/danswer/tools/custom/custom_tool.py
backend/danswer/tools/models.py
web/src/app/admin/tools/ToolEditor.tsx

Fixes Dan-607
https://github.com/danswer-ai/danswer-docs/pull/125

Add custom tool chat session / message ID dynamic prompting

---

web/src/app/admin/bot/SlackBotConfigCreationForm.tsx
web/src/app/admin/bot/SlackBotTokensForm.tsx
web/src/app/admin/bot/new/page.tsx
web/src/components/admin/connectors/Field.tsx

First go at simplifying the Slack Bot creation flow. Still not amazing, but quite a bit better than before.
New:
Old:

Slack flow improvements

---

web/src/app/admin/connector/[ccPairId]/IndexingAttemptsTable.tsx
web/src/app/admin/connectors/[connector]/AddConnectorPage.tsx
web/src/app/admin/connectors/[connector]/NavigationRow.tsx

Update indexing status clarity

---

backend/danswer/db/search_settings.py
web/src/app/chat/ChatBanner.tsx
web/src/app/chat/ChatPage.tsx
web/src/app/chat/lib.tsx
web/src/app/chat/message/Messages.tsx

Very minor polish

---

web/src/app/admin/prompt-library/modals/AddPromptModal.tsx
web/src/app/globals.css
web/src/components/Modal.tsx
web/src/components/modals/ModalWrapper.tsx
web/tailwind-themes/tailwind.config.js

Add some minor ux updates

---

web/src/app/api/[...path]/route.ts

Fix stop generating locally

---

backend/danswer/search/models.py
web/src/app/admin/configuration/search/page.tsx

Just realized fix for this model was in PR off a PR (graphs)! Best to get this in sooner

Ensure disabled gets propagated

---

web/src/components/Modal.tsx
web/src/components/modals/ExceptionTraceModal.tsx

Previously would not scroll. 
Now:
https://github.com/user-attachments/assets/3e1709e6-ecac-4ec1-aba3-ebae1cfac24f

Add back scrolling to ExceptionTraceModal

---

web/src/app/chat/ChatPage.tsx
web/src/app/chat/lib.tsx
web/src/app/chat/searchParams.ts

Change user-message to user-prompt

---

backend/alembic/versions/35e6853a51d5_server_default_chosen_assistants.py

harden migration

---

backend/danswer/chat/process_message.py
backend/danswer/tools/images/image_generation_tool.py

Handle tool errors in display properly (can show `valueError` to user)

---

web/src/app/admin/connectors/[connector]/AddConnectorPage.tsx
web/src/lib/connectors/connectors.ts

Updates defaults for connector creation flow (30 days / 30 minutes for pruning / refresh respectively)

Minor clarity update for connectors

---

web/src/app/chat/message/CodeBlock.tsx
web/src/app/chat/message/MemoizedTags.tsx
web/src/app/chat/message/MemoizedTextComponents.tsx
web/src/app/chat/message/Messages.tsx
web/src/components/chat_search/MinimalMarkdown.tsx

Fixes text / code highlighting. Both highlighting types in the attached video are currently not functional.
https://github.com/user-attachments/assets/bf91ef0d-88ed-417c-9850-7dcb31ee9639

Memoize AI message component

---

backend/danswer/main.py
backend/danswer/server/settings/models.py
web/src/app/admin/embeddings/RerankingFormPage.tsx
web/src/app/admin/settings/interfaces.ts
web/src/components/settings/lib.ts

Warn users of gpu-sensitive operation

---

backend/ee/danswer/server/query_and_chat/chat_backend.py
backend/ee/danswer/server/query_and_chat/models.py

Request from customer for backwards compatibility. Will remove the extra fields once they have switched over.

Add back llm_chunks_indices

---

backend/danswer/configs/app_configs.py

small clarification of ssl_cert_reqs

clarify ssl cert reqs

---

backend/danswer/configs/constants.py
backend/ee/danswer/server/query_history/api.py
web/src/app/ee/admin/performance/query-history/[id]/page.tsx
web/src/app/ee/admin/performance/usage/types.ts
web/src/lib/types.ts

Add flow to query history CSV

---

web/src/app/chat/message/Messages.tsx

Proper z index for chat bubbles

---

web/src/app/admin/connectors/[connector]/NavigationRow.tsx

Fix parentheses

---

backend/danswer/llm/answering/answer.py
backend/danswer/llm/answering/prompts/citations_prompt.py
backend/danswer/prompts/direct_qa_prompts.py

This adds the chat history to the prompt for slack messages. Worth looking at what other flows this impacts before we merge it though...

Citations prompt for slack now includes thread history

---

backend/alembic/versions/797089dfb4d2_persona_start_date.py
backend/danswer/db/models.py
backend/danswer/db/persona.py
backend/danswer/search/preprocessing/preprocessing.py
backend/danswer/server/features/persona/models.py
web/src/app/admin/assistants/AssistantEditor.tsx
web/src/app/admin/assistants/interfaces.ts
web/src/app/admin/assistants/lib.ts
web/src/components/admin/connectors/Field.tsx

Allows you to specify a start date for a persona if it has a search tool enabeld
Fixes dan-139

Add start date to persona

---

backend/alembic/versions/bd2921608c3a_non_nullable_default_persona.py

Align alembic

---

.github/workflows/docker-build-push-backend-container-on-tag.yml

try adding build essential

---

web/src/components/search/SearchSection.tsx

update default search assistant selection

---

web/src/components/initialSetup/welcome/WelcomeModal.tsx
web/src/components/llm/ApiKeyForm.tsx
web/src/components/llm/ApiKeyModal.tsx

Updated modals for clarity

---

backend/danswer/db/llm.py
backend/danswer/server/manage/llm/api.py
web/src/app/admin/configuration/llm/LLMProviderUpdateForm.tsx

Currently, attempting to create an LLM Provider with the same name takes user to a very confusing state.

Begin distinguishing upsert operations for clarity

---

backend/danswer/db/llm.py
backend/danswer/server/manage/llm/api.py
backend/ee/danswer/server/enterprise_settings/models.py
backend/ee/danswer/server/seeding.py
web/src/app/admin/settings/interfaces.ts
web/src/components/UserDropdown.tsx

Support svg navigation items

---

backend/danswer/llm/answering/answer.py
web/src/middleware.ts

Take 2. People are still running into this, and this is the last place where we could have been sending ToolCallKickoffs to the stream handler.
Tested by running a chat message and seeing that it streamed correctly + a chat which uses a tool.

Fix misc tool call errors

---

.github/workflows/docker-build-push-backend-container-on-tag.yml
.github/workflows/docker-build-push-model-server-container-on-tag.yml
.github/workflows/docker-tag-latest.yml
.github/workflows/pr-helm-chart-testing.yml.disabled.txt
.github/workflows/pr-python-checks.yml
.github/workflows/pr-python-connector-tests.yml
.github/workflows/pr-python-tests.yml
.github/workflows/pr-quality-checks.yml
.github/workflows/run-it.yml

test self hosted runner

---

backend/danswer/db/tag.py
backend/danswer/server/query_and_chat/query_backend.py

Previously this would have given 0 results.

Allow = in tag filter

---

web/src/app/assistants/mine/AssistantsList.tsx

Fixes https://linear.app/danswer/issue/DAN-693/make-the-look-of-active-assistants-consistent

Flex none for assistant display

---

web/src/app/chat/folders/FolderList.tsx

Update folder list

---

web/src/components/UserDropdown.tsx

https://linear.app/danswer/issue/DAN-715/add-open-in-new-tab-for-custom-links

Add open in new tab for custom links

---

backend/danswer/connectors/confluence/rate_limit_handler.py

clamp retry to max_delay

---

.github/workflows/tag-nightly.yml

Fixes DAN-720.  Needs to be iterated on live.

try user deploy key approach to tagging

---

.github/workflows/tag-nightly.yml

don't write a nightly tag to the same commit more than once

---

web/src/app/admin/connectors/[connector]/AddConnectorPage.tsx

Prevent `nextFormStep` unless credential fully set up

---

web/src/app/chat/ChatPage.tsx
web/src/lib/assistants/utils.ts
web/src/lib/chat/fetchChatData.ts

https://linear.app/danswer/issue/DAN-726/fix-bug-where-private-assistants-could-not-be-made-as-default

Fix default assistant

---

.github/workflows/tag-nightly.yml

it's better to tag late at night since we're not in the midst of heavy daytime development.

run the nightly tag overnight relative to pacific time

---

web/src/components/initialSetup/welcome/WelcomeModal.tsx
web/src/lib/chat/fetchChatData.ts

Welcome flow minor fix

---

backend/requirements/default.txt

bump celery for potential fix to redis disconnection behavior

---

.github/workflows/pr-python-checks.yml
.github/workflows/pr-python-tests.yml
.github/workflows/run-it.yml

sync up when checks run with branch protection required checks

---

.github/workflows/pr-python-model-tests.yml
backend/danswer/llm/chat_llm.py
backend/requirements/default.txt
backend/tests/daily/conftest.py
backend/tests/daily/llm/test_bedrock.py

^
Also added tests that run daily to make sure bedrock still works.

Update litellm to fix bedrock models

---

web/src/lib/connectors/connectors.ts

Dropbox->Linear in Linear connector

fix typo in Linear Connector page

---

web/src/app/prompts/page.tsx
web/src/app/search/page.tsx

Dupe welcome modal logic

---

backend/ee/danswer/background/celery/tasks/vespa/tasks.py

Match document set / deletion log format closer (e.g. include "progress" in all of them)

[tiny] adjust user group sync log

---

backend/requirements/default.txt

updates celery to 5.5.0b4 for redis reconnection fixes.

bump celery

---

backend/danswer/background/connector_deletion.py
backend/danswer/document_index/interfaces.py
backend/danswer/document_index/vespa/index.py

makes deleting vespa docs, especially larger ones, performant again.

hotfix for vespa delete performance

---

backend/supervisord.conf
deployment/docker_compose/docker-compose.dev.yml
deployment/docker_compose/docker-compose.gpu-dev.yml
deployment/docker_compose/docker-compose.prod-no-letsencrypt.yml
deployment/docker_compose/docker-compose.prod.yml
deployment/docker_compose/docker-compose.search-testing.yml
deployment/kubernetes/postgres-service-deployment.yaml

Allows folks with large Vespa deployments to speed up syncing

Allow config of background concurrency

---

backend/requirements/default.txt

bump celery to 5.5.0b4

---

backend/alembic/env.py

Multi tenant alembic

---

backend/shared_configs/configs.py

Prevent empty string from being CORS

docker deployment cors update

---

backend/danswer/background/update.py
backend/danswer/configs/app_configs.py
backend/danswer/db/engine.py
backend/danswer/main.py

To allow higher QPS setups.
https://linear.app/danswer/issue/DAN-772/allow-pool-size-pool-overflow-to-be-configured-via-env-variable-for

Add option to adjust pool size

---

web/src/app/chat/message/CodeBlock.tsx

remove left-over `memo`

---

web/src/components/initialSetup/welcome/WelcomeModal.tsx

Minor update to initial modal

---

backend/scripts/dev_run_background_jobs.py

Remove Perm Sync Script Dev

---

backend/supervisord.conf

rely on stdout redirection for supervisord logging

---

backend/danswer/background/update.py
backend/danswer/db/engine.py
backend/danswer/db/search_settings.py
backend/danswer/db/swap_index.py
backend/danswer/document_index/interfaces.py
backend/danswer/document_index/vespa/app_config/schemas/danswer_chunk.sd
backend/danswer/document_index/vespa/index.py
backend/danswer/document_index/vespa/indexing_utils.py
backend/danswer/document_index/vespa/shared_utils/vespa_request_builders.py
backend/danswer/document_index/vespa_constants.py
backend/danswer/main.py
backend/danswer/search/models.py
backend/danswer/search/preprocessing/preprocessing.py
backend/danswer/setup.py
backend/shared_configs/configs.py
backend/shared_configs/model_server_models.py

Multi tenant vespa

---

web/src/app/admin/assistants/PersonaTable.tsx
web/src/components/IsPublicGroupSelector.tsx

(minor) catch leftover dependency fix

---

web/src/app/admin/assistants/AssistantEditor.tsx
web/src/lib/llm/utils.ts

Better support for image generation capable models

---

backend/danswer/background/celery/celeryconfig.py

Fixes DAN-782.
Tested with the password in https://github.com/celery/celery/issues/1553.

urlencode redis passwords when creating url's for celery

---

.github/workflows/docker-build-push-web-container-on-tag.yml
backend/tests/integration/connector_job_tests/slack/test_permission_sync.py
backend/tests/integration/tests/dev_apis/test_knowledge_chat.py

try porting docker web build to runs-on

---

.github/workflows/hotfix-to-release-branches.yml

Experimental changes to fix DAN-767.

experimental workflow to auto merge hotfixes to release branches.

---

web/src/lib/hooks.ts

Remove mildly annoying groups fetch

---

.github/workflows/hotfix-release-branches.yml

more hotfix workflow testing

---

web/src/app/admin/indexing/status/CCPairIndexingStatusTable.tsx
web/src/app/admin/indexing/status/page.tsx

Add sync status

---

backend/danswer/background/celery/tasks/vespa/tasks.py

Prints various celery queue lengths ... useful to debug ongoing progress.

print various celery queue lengths

---

backend/ee/danswer/external_permissions/google_drive/doc_sync.py

Removed the trashed check since there is no trash check at the connector level either

google drive permission sync cleanup

---

backend/danswer/llm/chat_llm.py
backend/requirements/default.txt

backport Update litellm to fix bedrock models (#2649)

---

backend/supervisord.conf

update indexing and slack bot to use stdout options

---

web/src/app/chat/ChatPage.tsx
web/src/lib/chat/fetchChatData.ts

Ensure shared assistants accessible via query params

---

backend/danswer/danswerbot/slack/handlers/handle_regular_answer.py

https://linear.app/danswer/issue/DAN-800/fix-slack-bot-follow-up-questions

Fix slack responses

---

backend/ee/danswer/external_permissions/confluence/doc_sync.py
backend/ee/danswer/external_permissions/permission_sync.py

This should help us troubleshoot any issues with confluence permission syncing and make the code easier to debug

Improved logging and added comments

---

web/src/lib/connectors/connectors.tsx

Fix web connector

---

web/src/app/admin/connector/[ccPairId]/IndexingAttemptsTable.tsx
web/src/app/admin/connector/[ccPairId]/page.tsx

Indexing back button functional

---

web/src/app/chat/ChatPage.tsx
web/src/app/chat/lib.tsx

Ensure scroll works with pasting

---

.github/workflows/pr-Integration-tests.yml
.github/workflows/pr-python-checks.yml
.github/workflows/pr-python-connector-tests.yml
.github/workflows/pr-python-model-tests.yml
.github/workflows/pr-python-tests.yml
.github/workflows/pr-quality-checks.yml

update several github actions to silence github deprecation warnings

---

web/src/app/admin/configuration/search/UpgradingPage.tsx

Fixes https://linear.app/danswer/issue/DAN-808/swapping

slightly cleaner loading

---

web/src/components/search/filtering/TagFilter.tsx

Fix tag background

---

backend/danswer/llm/chat_llm.py
backend/tests/unit/danswer/llm/test_chat_llm.py

Previously, we would occasionally fail if OpenAI gave back parallel tool calls.
UT used to fail, now it succeeds!

Fix parallel tool calls

---

backend/danswer/document_index/vespa/indexing_utils.py

Ensure we still log indexing url

---

backend/danswer/connectors/notion/connector.py
backend/pyproject.toml
backend/requirements/dev.txt

Notion Connector Improvements

---

backend/danswer/background/indexing/run_indexing.py

Fix stopping of indexing runs when pausing a connector

---

backend/danswer/connectors/google_drive/connector.py
web/src/app/admin/connectors/[connector]/pages/ConnectorInput/ListInput.tsx

^
https://linear.app/danswer/issue/DAN-813/handle-cannotexportfile-from-google-drive-gracefully
https://linear.app/danswer/issue/DAN-812/all-list-type-form-fields-are-broken

Handle 'cannotExportFile' + fix forms

---

web/src/app/chat/RegenerateOption.tsx
web/src/app/chat/message/Messages.tsx
web/src/components/tooltip/CustomTooltip.tsx

https://github.com/user-attachments/assets/1bbfebb1-7c00-4012-be4a-56ca7f491fbe

Ensure regenerate has dropdown too

---

web/src/app/chat/shared/[chatId]/page.tsx

Ensure assistant response parsed correctly

---

backend/requirements/default.txt
backend/requirements/model_server.txt

bump litellm

---

backend/danswer/background/celery/tasks/shared/tasks.py
backend/danswer/background/celery/tasks/vespa/tasks.py

Should be using update single for better sync performance.

fix sync to use update_single

---

backend/danswer/main.py

multitenant setup

---

backend/alembic/env.py
backend/alembic/versions/6756efa39ada_id_uuid_for_chat_session.py

Allows us to specify an x-argument to run upgrade for all schemas (necessary for EKS job which will handle migration)

Add all-tenants migration for K8 job

---

backend/model_server/encoders.py
backend/shared_configs/configs.py
backend/tests/daily/embedding/test_embeddings.py

Also added a test for the litellm embedder.
Not really required, but it was something I did while looking into adding embedding batch limits (which turned out to not be necessary, since we already had a way to do it 😓)

Refactor + add global timeout env variable

---

backend/danswer/background/indexing/run_indexing.py
backend/danswer/db/index_attempt.py

use with for update instead of serializable

---

backend/danswer/server/query_and_chat/query_backend.py
web/src/components/search/SearchSection.tsx

Add errors to search

---

backend/Dockerfile
backend/Dockerfile.model_server
web/Dockerfile

Update default tag version

---

backend/ee/danswer/background/task_name_builders.py

missing tenant_id as optional param

---

web/package-lock.json
web/package.json

Ensure **all** sharp-related packages installed for new standalone output config in NextJS, which is required in NextJS 14

Minor- standalone output build 

---

backend/danswer/server/query_and_chat/chat_backend.py

Docstring Update for Docs

---

web/src/components/search/results/QuotesSection.tsx

(minor) quote overflow

---

backend/danswer/document_index/vespa/chunk_retrieval.py

Minor vespa standardization

---

web/src/app/admin/configuration/llm/CustomLLMProviderUpdateForm.tsx
web/src/app/admin/configuration/llm/LLMProviderUpdateForm.tsx
web/src/components/initialSetup/search/NoSourcesModal.tsx
web/src/components/initialSetup/welcome/WelcomeModal.tsx
web/src/components/llm/ApiKeyForm.tsx
web/src/components/llm/ApiKeyModal.tsx

Make modals slightly clearer
- Remove double button on welcome modal and ugly overlapping toast.

Modal onboarding clarity

---

backend/danswer/background/celery/tasks/indexing/tasks.py
backend/danswer/background/celery/tasks/shared/tasks.py
backend/danswer/background/celery/tasks/vespa/tasks.py
backend/danswer/connectors/web/connector.py
backend/danswer/document_index/vespa/indexing_utils.py
backend/tests/integration/common_utils/managers/cc_pair.py

tighter signaling to prevent indexing cleanup from hitting tasks that are just starting

---

backend/danswer/connectors/confluence/utils.py

Tiny confluence fix

---

web/src/app/admin/connectors/[connector]/AddConnectorPage.tsx
web/src/components/credentials/actions/ModifyCredential.tsx

Fixes https://linear.app/danswer/issue/DAN-854/fix-scroll-on-too-many-credentials

sticky credential description

---

backend/danswer/db/credentials.py
backend/danswer/server/documents/connector.py
backend/danswer/server/documents/credential.py

Temporary fix for empty Google App credentials

---

backend/danswer/auth/users.py
backend/danswer/background/celery/apps/app_base.py
backend/danswer/background/celery/apps/beat.py
backend/danswer/background/celery/apps/primary.py
backend/danswer/background/celery/celery_utils.py
backend/danswer/background/celery/tasks/connector_deletion/tasks.py
backend/danswer/background/celery/tasks/indexing/tasks.py
backend/danswer/background/celery/tasks/pruning/tasks.py
backend/danswer/background/celery/tasks/vespa/tasks.py
backend/danswer/connectors/file/connector.py
backend/danswer/danswerbot/slack/listener.py
backend/danswer/db/credentials.py
backend/danswer/db/engine.py
backend/danswer/key_value_store/store.py
backend/danswer/redis/redis_pool.py
backend/danswer/search/preprocessing/preprocessing.py
backend/danswer/server/documents/cc_pair.py
backend/danswer/server/documents/connector.py
backend/danswer/server/manage/users.py
backend/danswer/server/query_and_chat/token_limit.py
backend/ee/danswer/background/celery/apps/beat.py
backend/ee/danswer/background/celery/apps/primary.py
backend/ee/danswer/server/middleware/tenant_tracking.py
backend/ee/danswer/server/tenants/api.py
backend/ee/danswer/server/tenants/billing.py
backend/shared_configs/configs.py

Multitenant redis update

---

backend/danswer/llm/chat_llm.py
backend/danswer/llm/factory.py
backend/danswer/server/manage/llm/api.py
backend/danswer/server/manage/llm/models.py
backend/requirements/model_server.txt

Clearer azure models

---

backend/ee/danswer/server/query_history/api.py
backend/scripts/chat_feedback_dump.py

working chat feedback dump script (with api addition)

---

backend/danswer/db/persona.py
web/src/app/admin/assistants/AssistantEditor.tsx
web/src/app/admin/assistants/PersonaTable.tsx
web/src/app/admin/assistants/page.tsx
web/src/app/assistants/gallery/page.tsx
web/src/app/assistants/mine/page.tsx
web/src/app/chat/page.tsx
web/src/app/layout.tsx
web/src/app/search/page.tsx
web/src/components/context/AppProvider.tsx
web/src/components/context/AssistantsContext.tsx
web/src/lib/chat/fetchAssistantdata.ts
web/src/lib/chat/fetchChatData.ts

Global assistants context with notifications for all

Add global assistants context

---

backend/danswer/background/celery/apps/primary.py

can't add to primary_worker_locks if it doesn't exist

---

backend/danswer/background/celery/apps/app_base.py

try hiding celery task spam

---

backend/danswer/db/engine.py

Silence unnecessary debug log

---

backend/danswer/__init__.py

Trivial improvement for testing backport
N/A
N/A
N/A

Harmless Backport

---

backend/tests/integration/conftest.py
backend/tests/integration/tests/dev_apis/test_simple_chat_api.py

Fix IT fixture ordering

---

.github/workflows/pr-backport-autotrigger.yml

Backport Branch Fix

---

backend/danswer/background/celery/apps/app_base.py
backend/danswer/configs/app_configs.py
backend/danswer/main.py
backend/model_server/main.py
web/next.config.js
web/sentry.client.config.ts
web/sentry.edge.config.ts
web/sentry.server.config.ts
web/src/app/chat/ChatPage.tsx
web/src/app/global-error.tsx

Update Sentry configuration
- Explicitly focus on exceptions in web 
- Decrease sample rate in backend
Relevant Sentry Docs: 
- https://docs.sentry.io/platforms/javascript/guides/nextjs/manual-setup/#extend-your-nextjs-configuration
- https://docs.sentry.io/platforms/python/configuration/sampling/

feat: sentry updates

---

web/next.config.js

ensure proper sentry silencing

---

.github/workflows/pr-backport-autotrigger.yml

Backport Permissions

---

backend/danswer/main.py

No-op change to test backport functionality
Not Needed
N/A
N/A

Harmless Backport Test

---

backend/danswer/setup.py

Backport Test

---

.github/workflows/pr-backport-autotrigger.yml

Backport Correct Branch

---

backend/danswer/background/celery/apps/app_base.py

Harmless Backport Test
N/A
N/A
N/A

Backport Test Final

---

backend/danswer/auth/users.py
backend/danswer/configs/app_configs.py
backend/danswer/db/engine.py
backend/ee/danswer/configs/app_configs.py
backend/ee/danswer/server/middleware/tenant_tracking.py
backend/tests/integration/common_utils/managers/user.py
web/src/app/auth/logout/route.ts

Previously, we used two separate cookies `tenant_details` and `fastapiusersauth`- this was not necessary. This consolidation simplifies the cookie management (as well as some downstream applications coming soon)

Tenant aware JWT strategy

---

backend/danswer/connectors/gitlab/connector.py

Test Workflow Trigger

---

backend/danswer/connectors/gitlab/connector.py

Backport Tag Test

---

.github/workflows/pr-backport-autotrigger.yml

GHA Trigger

---

.github/workflows/pr-backport-autotrigger.yml

Echo Merge Commit

---

backend/danswer/connectors/slab/connector.py

Backport Test 4

---

backend/danswer/connectors/slack/connector.py

Backport Test 5

---

backend/danswer/connectors/slack/load_connector.py

Backport Test 6

---

backend/danswer/redis/redis_pool.py

add srem and sadd to tenant wrapper

---

backend/danswer/redis/redis_pool.py

scard missing in TenantRedis
N/A
N/A

missing scard

---

web/src/app/chat/ChatPage.tsx
web/src/app/chat/sessionSidebar/ChatSessionDisplay.tsx
web/src/app/chat/sessionSidebar/HistorySidebar.tsx
web/src/app/chat/shared_chat_search/FixedLogo.tsx
web/src/app/chat/shared_chat_search/FunctionalWrapper.tsx
web/src/components/BasicClickable.tsx
web/src/components/header/HeaderTitle.tsx
web/src/components/search/SearchAnswer.tsx
web/src/components/search/SearchBar.tsx
web/src/components/search/SearchSection.tsx

Fixes https://linear.app/danswer/issue/DAN-874/improve-color-customization-options

add additional configuration options

---

backend/danswer/utils/logger.py

Tiny logging clarity improvement

---

backend/danswer/document_index/vespa/chunk_retrieval.py

Temp fix to add retries to get_all_vespa_ids_for_document_id

---

backend/danswer/background/celery/apps/beat.py
backend/danswer/background/celery/apps/heavy.py
backend/danswer/background/celery/apps/primary.py
backend/danswer/background/indexing/job_client.py

Fixes DAN-883
Fixes DAN-879
N/A
N/A

init sqlalchemy in child process

---

web/src/app/admin/connectors/[connector]/AddConnectorPage.tsx

Minor bugfix - allow 0 to disable pruning / refreshing

Pruning + Refresh Clarity

---

.github/workflows/pr-python-model-tests.yml

Fix model test action name

---

README.md

Done some changes in readme to make it more appealing.
Added a back to top button , Added the section of star history chart of the repo and the contributors section
N/A
N/A

chore: Added back to top , contributors section and star history graph

---

backend/danswer/server/documents/credential.py

Remove unused endpoint

---

web/src/lib/connectors/connectors.tsx

Add Gdrive Interface

---

backend/danswer/db/auth.py
backend/danswer/server/manage/users.py
backend/ee/danswer/db/api_key.py

Do not count API keys as users

---

backend/danswer/auth/users.py
backend/danswer/configs/app_configs.py
backend/danswer/connectors/file/connector.py
backend/danswer/danswerbot/slack/listener.py
backend/danswer/db/engine.py
backend/danswer/key_value_store/store.py
backend/danswer/server/auth_check.py
backend/danswer/server/manage/models.py
backend/danswer/server/manage/users.py
backend/danswer/server/query_and_chat/token_limit.py
backend/danswer/utils/logger.py
backend/ee/danswer/auth/users.py
backend/ee/danswer/background/celery/apps/primary.py
backend/ee/danswer/db/api_key.py
backend/ee/danswer/db/query_history.py
backend/ee/danswer/server/middleware/tenant_tracking.py
backend/ee/danswer/server/tenants/api.py
backend/ee/danswer/server/tenants/models.py
backend/shared_configs/configs.py
backend/shared_configs/contextvars.py
web/src/app/auth/impersonate/page.tsx
web/src/app/auth/login/LoginText.tsx
web/src/components/auth/AuthFlowContainer.tsx
web/src/components/user/UserProvider.tsx
web/src/lib/types.ts

Add super user for specified users
https://github.com/user-attachments/assets/12422fee-624f-4151-bc1c-cbe4ffc38055

Super user

---

backend/tests/daily/connectors/google_drive/test_google_drive_oauth.py

Include File 61 temporarily

---

backend/tests/daily/connectors/google_drive/test_google_drive_oauth.py
web/package-lock.json

Revert temporary modifications

---

backend/danswer/chat/prompts.yaml

Currently, image assistant consistently asks for more details (almost unusable)

slight upgrade to image generation prompts

---

backend/danswer/prompts/prompt_utils.py

Occasionally some flows fail because last message is too large, need more information to resolve
N/A
N/A
N/A

Last Message Too Large Logging

---

backend/danswer/configs/app_configs.py
backend/danswer/db/engine.py

add POSTGRES_IDLE_SESSIONS_TIMEOUT

---

backend/danswer/chat/models.py
backend/danswer/chat/process_message.py
backend/danswer/llm/utils.py
backend/danswer/one_shot_answer/answer_question.py
backend/danswer/tools/tool_implementations/custom/custom_tool.py
backend/danswer/tools/tool_implementations/custom/prompt.py
backend/tests/unit/danswer/tools/custom/test_custom_tools.py
web/src/app/chat/ChatPage.tsx
web/src/app/chat/interfaces.ts
web/src/app/chat/lib.tsx

Carbon copy of approved PR https://github.com/danswer-ai/danswer/pull/3041/files

add multiple formats to tools

---

web/src/components/admin/connectors/Field.tsx
web/src/components/ui/select.tsx

https://linear.app/danswer/issue/DAN-924/llm-provider-form-dropdowns-are-all-funky + https://linear.app/danswer/issue/DAN-925/fix-slack-bot-creation-form-assistant-selector
Now:

Fix slack bot form + LLM provider form

---

backend/danswer/background/celery/apps/primary.py

Ensure we reset all

---

backend/danswer/db/engine.py

Fixes DAN-888 (in another spot).
N/A
N/A

add to async get session as well

---

web/src/components/ErrorCallout.tsx
web/src/components/ui/callout.tsx

ensure props aligned

---

web/src/app/ee/admin/performance/usage/DanswerBotChart.tsx
web/src/app/ee/admin/performance/usage/FeedbackChart.tsx
web/src/app/ee/admin/performance/usage/QueryPerformanceChart.tsx
web/src/components/admin/CardSection.tsx
web/src/components/admin/connectors/Field.tsx
web/src/components/credentials/actions/CreateCredential.tsx
web/src/components/ui/areaChart.tsx

Improve form

---

backend/danswer/background/celery/tasks/indexing/tasks.py
backend/danswer/background/celery/tasks/vespa/tasks.py

fix stale indexing tasks being allowed to run after a restart

---

backend/danswer/document_index/vespa/index.py

need to see vespa url for container debugging

---

backend/scripts/restart_containers.sh

PG Dev Max Connections

---

backend/danswer/connectors/file/connector.py

Enable Overwriting the source type at a per document level
N/A
N/A
N/A

File Connector Metadata
