backend/alembic/versions/47433d30de82_create_indexattempt_table.py, backend/danswer/db/models.py
Modifying existing migration to not create an unnecessary one line migration. Since this is not deployed for production use cases yet, it should be fine
=> Fix time_updated default :sweat:

backend/Dockerfile, backend/Dockerfile.background
Need to install `libpq-dev` to be able to `pip install psycopg2`.
=> Fix backend Dockerfiles

backend/danswer/connectors/slack/connector.py
We were pulling in messages like channel join etc. which do not provide any info.
=> Fix slack message indexing bug

backend/danswer/connectors/slack/connector.py, backend/danswer/connectors/slack/utils.py, backend/danswer/listeners/slack_listener.py
Tags are returned as `<@{USER_ID}>` by the Slack APIs. This PR replaces `<@{USER_ID}>` with `{DISPLAY_NAME}` to improve the display in the UI.
=> Replace IDs with names in Slack connector

backend/danswer/configs/constants.py, backend/danswer/connectors/bookstack/client.py, backend/danswer/connectors/bookstack/connector.py, backend/danswer/connectors/factory.py, web/src/app/admin/connectors/bookstack/page.tsx, web/src/app/admin/layout.tsx, web/src/components/icons/icons.tsx, web/src/components/search/Filters.tsx, web/src/components/source.tsx, web/src/lib/types.ts
This PR adds a connector for [BookStack](https://www.bookstackapp.com/).
Specifically, it uses the BookStack REST API and loads in the details for shelves, books and chapters (hierarchical items that have names and descriptions) in adding to pages (main HTML-based user content within BookStack).
If it helps to understand things, there is a [live demo for BookStack here](https://demo.bookstackapp.com/).
For this connector I've been following the existing confluence connector as a general guide.
I have tested this again a local instance of mine, and all seems to be working as expected and sensible, as far as I can tell.
The trickest part I had was trying to think about how settings & credentials are used for this connector.
I ended up putting all the required API details, including instance …
=> BookStack connector

CONTRIBUTING.md
A few other things while I was setting up my local dev env setup:
1. Had to install `libpq-devel` to install psycopg2
2. pre-commit yaml is not in root of repo. How do you get pre-commit to load it from `danswer/backend`?
3. Do we want to add [mypy](https://github.com/pre-commit/mirrors-mypy) in precommit?
4. Do we want to add `prettier` to `package.json` under devDependencies?
```
"devDependencies": {
"prettier": "3.0.0"
}
```
Please let me know if I should add/make any of these changes.
=> Added missing instructions to CONTRIBUTING.md

deployment/docker_compose/docker-compose.dev.yml
Otherwise we will redownload all models on every start. This speeds up image start significantly.
=> cache models for faster development cycles in docker compose

backend/danswer/connectors/slack/connector.py
Prevent the Slack connector from including archived channels.
Solves https://github.com/danswer-ai/danswer/issues/205
=> Fix: Don't include archived Slack channels

backend/danswer/background/update.py
Danswer background crashes when the index task for a deleted source is still in the task queue. Without this is won't recover without manual database cleanup.
=> catch crash when deleting a datasource

backend/danswer/configs/constants.py, backend/danswer/connectors/factory.py, backend/danswer/connectors/notion/connector.py, web/src/app/admin/connectors/notion/page.tsx, web/src/app/admin/layout.tsx, web/src/components/icons/icons.tsx, web/src/components/search/Filters.tsx, web/src/components/source.tsx, web/src/lib/types.ts
Adds a connector to Notion. Resolves #170 
Takes inspiration from the Notion Loader in Llamahub, but decided against outright using the loader because the Notion Search API seemed more convenient to load all pages in a Notion workspace in bulk, instead of needing to specify a Notion database.
=> Notion connector

backend/danswer/chunking/chunk.py, backend/danswer/configs/app_configs.py, backend/danswer/connectors/web/connector.py, backend/danswer/direct_qa/open_ai.py, backend/danswer/search/semantic_search.py, backend/requirements/default.txt, backend/tests/unit/qa_service/chunking/test_chunk.py
This change introduces 2 new things:
1. Intelligent chunking would sometimes introduce too many new tokens because of the way words are broken up. Sometimes due to parsing issues, words are not separated so the default 5 overlap words introduce too many tokens. Set a strict limit on forward and backwards inclusions for every chunk.
2. Use Tiktoken library from OpenAI to unsure that the prompts never fail due to too many tokens.
=> Prevent too many tokens to GPT

CONTRIBUTING.md
**Getting error when trying to start frontend on windows**
**Solution:**
Added command which can run enable frontend in windows
=> Added shell command to start frontend for windows

backend/danswer/background/update.py, backend/danswer/connectors/google_drive/connector.py, backend/danswer/connectors/utils.py, backend/danswer/db/connector_credential_pair.py, backend/danswer/db/engine.py, backend/danswer/db/index_attempt.py
- Adds some offset to the `start` for the Google Drive connector to give time for `modifiedTime` to propagate so we don't miss updates
- Moves fetching folders into a separate call since folder `modifiedTime` doesn't get updated when a file in the folder is updated
- Started to use `connector_credential_pair.last_successful_index_time` instead of `updated_at` to determine the `start` for poll connectors
=> Fix a few bugs with Google Drive polling

backend/danswer/search/semantic_search.py
This is a workaround around intermittent issues where sementic_identifier becomes None for some reason. It usually recovers when documents are rescraped.
Obviously, we do not yet understand the issue and are interested in a better solution.
=> prevent crash when semantic_identifier is None

backend/alembic/versions/465f78d9b7f9_larger_access_tokens_for_oauth.py, backend/danswer/auth/users.py, backend/danswer/configs/app_configs.py, backend/danswer/db/models.py, backend/danswer/main.py, deployment/docker_compose/docker-compose.dev.yml, web/src/app/auth/login/page.tsx, web/src/app/auth/oauth/callback/route.ts, web/src/lib/constants.ts, web/src/lib/userSS.ts
This allow using Danswer in typical (non-google) enterprise environments.
* Access Tokens can be very large. A token without claims is already 1100 bytes for me (larger than allowed in danswer by default). With roles I got a 12kB token. For that reason I changed the field to TEXT in the database.
* Danswer used to swallow most errors when OIDC would fail. Nodejs forwards a request to the backend and swallows all errors. Even within the backend we catched all ValueErrors and only returned the last exception with the request. Added full stack trace logging to allow debugging issues with userinfo and other endpoints.
* Allow changing name of the login provider on the login button.
* Changed variables and URLs to generic OAUTH_XX (without google in the name) but kept compatibility with the …
=> add support for openid connect

backend/danswer/configs/model_configs.py, backend/danswer/direct_qa/__init__.py, backend/danswer/direct_qa/huggingface_inference.py, backend/requirements/default.txt
Adds support for models running on the Huggingface Inference API or Inference Endpoints, and models that are backed by the text-generation-inference backend.
With these internal models, you can directly call Huggingface models that are publicly/privately hosted on Huggingface, but more excitingly, you can run your own models using the [text-generation-inference](https://github.com/huggingface/text-generation-inference) library, (deploying locally or in the cloud).
Theoretically, its also possible to use any backend that simulates the text-generation-inference backend, like [vllm](https://github.com/vllm-project/vllm).
You can do this by setting GEN_AI_MODEL_VERSION to equal any HTTP model endpoint.
The "chat" inference isn't great. Chat models are optimized for specific chat formats with …
=> Huggingface Inference backend internal models

backend/alembic/versions/5e84129c8be3_add_docs_indexed_column_to_index_.py, backend/alembic/versions/e6a4bbc13fe4_add_index_for_retrieving_latest_index_.py, backend/danswer/background/connector_deletion.py, backend/danswer/background/update.py, backend/danswer/connectors/slack/connector.py, backend/danswer/db/connector_credential_pair.py, backend/danswer/db/index_attempt.py, backend/danswer/db/models.py, backend/danswer/server/manage.py, backend/danswer/server/models.py, web/src/app/admin/indexing/status/page.tsx, web/src/components/admin/connectors/table/ConnectorsTable.tsx, web/src/components/icons/icons.tsx, web/src/lib/indexAttempt.ts, web/src/lib/types.ts
Adds:
- actual error message in UI for indexing failure
- if a connector is disabled, stops indexing immediately (after the current batch of documents) to allow for deletion
- adds num docs indexed for the current run + a speed
=> Improve indexing status display

backend/danswer/bots/slack/handlers/handle_message.py, web/src/app/page.tsx, web/src/components/search/SearchTypeSelector.tsx
=> Default to semantic search on web + slack

backend/danswer/bots/slack/blocks.py, backend/danswer/bots/slack/handlers/handle_feedback.py, backend/danswer/bots/slack/handlers/handle_message.py, backend/danswer/bots/slack/listener.py, backend/danswer/bots/slack/utils.py, backend/danswer/connectors/slack/utils.py
- Gives some feedback when a user thumbs up / thumbs down a message.
- Stops giving "previews" for every source, which makes the message response very very long
- Fixes some broken source links
=> Misc slack bot improvements

backend/danswer/configs/app_configs.py, backend/danswer/connectors/web/connector.py
Lots of doc sites using Mintlify can be cleaned up in the same way.
Default turned on for other sites because it's fairly generally applicable.
Also allowing Headers to be included in website parsing again as sometimes the info is relevant.
=> Cleanup for Mintlify Websites

backend/danswer/bots/slack/blocks.py, backend/danswer/bots/slack/utils.py, backend/danswer/datastores/vespa/store.py
Because Slack has some interesting formatting rules. We need to avoid tagging people or groups by accident and make sure all the highlights are parsed correctly. This change covers that.
=> Clean up Slack Bot formatting

backend/danswer/direct_qa/answer_question.py, backend/danswer/direct_qa/gpt_4_all.py, backend/danswer/direct_qa/huggingface.py, backend/danswer/direct_qa/interfaces.py, backend/danswer/direct_qa/local_transformers.py, backend/danswer/direct_qa/models.py, backend/danswer/direct_qa/open_ai.py, backend/danswer/direct_qa/qa_block.py, backend/danswer/direct_qa/request_model.py, backend/danswer/llm/utils.py, backend/danswer/search/keyword_search.py, backend/danswer/search/models.py, backend/danswer/search/semantic_search.py, backend/danswer/utils/callbacks.py, backend/tests/regression/answer_quality/eval_direct_qa.py
For system transparency, test flow is now able to logs the top docs/chunks fetched, the scores both bi-encoder and cross-encoder, and the number of tokens used in the prompt and response from LLM.
=> Add Metrics to Regression Test

backend/danswer/bots/slack/blocks.py, backend/danswer/bots/slack/utils.py, backend/danswer/connectors/slack/utils.py
Add whitespace after the @ symbol so that it never matches the special slack pattern
=> Fix Slackbot Tagging people or groups

backend/danswer/llm/build.py
User wanted to use the self hosted FastAPI to run the LLM as a model endpoint. Reenabling the support for it.
=> Reenable Google Colab Model

backend/danswer/utils/text_processing.py
Handle quotes with '\xa0' inside (Azure OpenAI answer - GPT3.5-turbo). Avoids to get the error:
```
Error occurred in call to LLM - Invalid \escape: line 1 column 1364 (char 1363) - Traceback (most recent call last):
File "/app/danswer/direct_qa/answer_question.py", line 147, in answer_qa_query
d_answer, quotes = qa_model.answer_question(
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/danswer/direct_qa/qa_block.py", line 281, in answer_question
return self._qa_handler.process_llm_output(model_out, trimmed_context_docs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/danswer/direct_qa/qa_block.py", line 171, in process_llm_output
return process_answer(
^^^^^^^^^^^^^^^
File "/app/danswer/direct_qa/qa_utils.py", line 162, in process_answer
answer, quote_strings = …
```
=> fix: remove \xa0 from code blocks

backend/danswer/configs/model_configs.py, backend/danswer/search/semantic_search.py
If a single doc is returned, the normalize before boosting step causes divide by zero if reranking is skipped.
Also for reranking this could happen with bad model configs, though this is unlikely
=> Fix Divide by Zero Edge Case

backend/danswer/chat/chat_llm.py, backend/danswer/configs/chat_configs.py
This only has an effect for contextual chat.  However, we can forcibly use the tools prompt now even if no tools are configured.
=> Provide Env variable to have chat flow always use the tools prompt

backend/danswer/configs/app_configs.py, backend/danswer/datastores/vespa/store.py, backend/danswer/search/keyword_search.py, deployment/docker_compose/docker-compose.dev.yml
Use nltk to remove stopwords highlighting from vespa query (only for semantic search)
Also some stopword option updates for keyword queries
=> Remove Stopword Highlighting

backend/danswer/configs/app_configs.py
More advanced and less used options for configuring the Slack Bot are only configurable via Environment variables. This PR adds descriptions since the Danswer docs will just refer the user to the file directly
=> Comments on advanced DanswerBot options

backend/Dockerfile, backend/danswer/background/update.py
Since the images now have too many layers/cache inflation, we can't build on GitHub's default runners. Also don't want to distribute larger than necessary images for faster upgrades etc.
Also disables the ACL migration by default
=> Dockerfile to build smaller Images

web/src/app/admin/connectors/document360/page.tsx, web/src/app/admin/connectors/linear/page.tsx, web/src/app/admin/connectors/slab/page.tsx
New pages now available on https://docs.danswer.dev/
This change points the page references in the UI to the new pages
=> Update Danswer Docs Pointers

backend/danswer/connectors/slack/connector.py
Stops indexing bot messages, including DanswerBot. Does not remove existing instances from index.
=> Slack Connector to not Index Bots

backend/danswer/connectors/slack/utils.py
cases of <> could lead to failures, now handling correctly
=> Fix Slack Link Parsing

backend/danswer/direct_qa/llm_utils.py
Openapi API key verification timeout is too short and can causes an error that increasing the timeout solves.
=> Increasing OpenAi  api key verification timeout

backend/danswer/connectors/google_drive/connector.py
"modifiedTime" attribute is missing from file object and making the Gdrive connector unable to index shared files
=> Google Drive shared files indexing fix

web/src/app/admin/connector/[ccPairId]/IndexingAttemptsTable.tsx, web/src/app/admin/connector/[ccPairId]/ReIndexButton.tsx, web/src/app/admin/connector/[ccPairId]/page.tsx, web/src/app/admin/indexing/status/CCPairIndexingStatusTable.tsx, web/src/components/HoverPopup.tsx, web/src/components/Status.tsx, web/src/lib/documentDeletion.ts, web/src/lib/utilsSS.ts
- Addresses mismatch between `Total Documents Indexed` and `Num New Docs` in individual connector page
- Changes `Running` to `Active` for non-disabled connectors
- Disables kicking off indexing jobs for disabled connectors
- Turns off caching for individual connector page, which was causing outdated info to be displayed 
- `Time` => `Time Created` for improved clarity
- FIxes mismatch between deletion status on main status page vs individual connector page
=> Small UI fixes

backend/danswer/background/update.py, backend/danswer/main.py, backend/supervisord.conf
Dask was retrying jobs that kept failing, and when its due to a worker dying, it doesn't always count it as an error so it keeps trying.
=> Fix Indexing Frozen

web/src/app/admin/connectors/web/page.tsx, web/src/components/icons/icons.tsx
New: <img width="1390" alt="SCR-20231113-jvhx" src="https://github.com/danswer-ai/danswer/assets/6219801/5970cdd7-8981-400f-88f2-08b2ddfd71f3">
specifically 
Added a gear icon that links to the connector's configuration page. The base URL still links to the base URL, but now features an external link indicator icon.
Previously: 
This change was made with the goal of improving UX and general usability. It reduces admin confusion when navigating the indexing status and web connectors pages, as the connector URLs on those pages both link to different places (external base url and connector configuration).
=> Added connector configuration link and external link icon to web connectors page.

backend/Dockerfile.model_server
The model_server dockerfile is out of date of the dependencies required to run it.
Point of clarification:
Is there any utility for having this be a separate image? Would it make more sense to just add the model_server to the primary backend image just like `background` and `api-server`.
=> add missing dependencies in model_server dockerfile

backend/scripts/sources_selection_analysis.py
Hi,
I made this script to track the changes easily at the source selection level with a pre-defined set of queries. It stays focused on the top 5 selected sources.
The initial run, with a set of queries, will be used next as a reference to compare with the new iterations.
An analysis for the moment does the following:
- check if the top 5 documents have the same order
- check if the score for each selected document is the same
When a check fails, it tries to get some inputs to understand the drift by checking if the "updated-at"  or the "boost  values" have changed.
The result is displayed straight into the shell.
It allows us to check if the selected sources are the same for a pre-set of queries.
Example: I would like to track the source selection for the queries:
1. "How to create a new …
=> Add script to analyse the sources selection

deployment/docker_compose/docker-compose.dev.yml, deployment/docker_compose/docker-compose.prod-no-letsencrypt.yml, deployment/docker_compose/docker-compose.prod.yml, deployment/kubernetes/vespa-service-deployment.yaml
Vespa `8.249.12` contains a vulnerable Zookeeper version (https://nvd.nist.gov/vuln/detail/CVE-2023-44981) and should be updated to resolve.
=> Update Vespa to 8.267.29

backend/danswer/connectors/confluence/connector.py
Allows more clarity to LLM as to what is going on with the user names that are replaced
=> Confluence add tag to replaced names

backend/danswer/configs/danswerbot_configs.py, backend/danswer/danswerbot/slack/blocks.py, backend/danswer/danswerbot/slack/constants.py, backend/danswer/danswerbot/slack/handlers/handle_feedback.py, backend/danswer/danswerbot/slack/listener.py, backend/danswer/danswerbot/slack/utils.py, backend/danswer/db/feedback.py
Hi,
This PR is a rework of the source feedback, as the presentation was not... optimal, from my point of view :) 
This also adds the support to hide the source. I'm using a Slack view as the cleanest way to handle it. Furthermore, we could extend it in the future (like by letting the end-user write a feedback message explaining why he has down-voted it).
=> Slack bot improve source feedback

.gitignore, backend/danswer/configs/app_configs.py, deployment/docker_compose/docker-compose.dev.yml, deployment/docker_compose/env.prod.template, deployment/kubernetes/env-configmap.yaml, web/README.md
This commit replaces the default value of WEB_DOMAIN from "http://localhost:3000" to "http://127.0.0.1:3000" in several config files. I'm using windows and for some reason, it won't load with localhost. Others my have the problem, so I thought it might be good to idiotproof it.
=> Change WEB_DOMAIN default to 127.0.0.1 instead of localhost

.gitignore
In order to prevent local development changes from appearing in git diff and being committed
=> Add deployment/data/nginx/app.conf to .gitignore

backend/danswer/connectors/cross_connector_utils/file_utils.py, backend/danswer/connectors/file/connector.py, backend/danswer/connectors/google_site/connector.py
Adding support for setting metadata via the file connector in a `.danswer_metadata.json` file instead of manipulating the files in a ZIP archive.
This PR closes #860
=> Add metadata file loader to ZIP file connector

backend/danswer/auth/users.py, backend/danswer/configs/app_configs.py, deployment/docker_compose/docker-compose.dev.yml, deployment/docker_compose/env.prod.template, deployment/kubernetes/env-configmap.yaml
Add possibility to add `MAIL_FROM` setting with fallback to `SMTP_USER`, as `SMTP_USER` not always a valid email address.
=> Add MAIL_FROM env variable

backend/danswer/danswerbot/slack/handlers/handle_buttons.py
When someone marks a thread as resolved, we give the name of the user who did this and remove the previous message which has the button to mark the thread resolved
=> Slack Give Resolver Name

backend/danswer/danswerbot/slack/listener.py, backend/danswer/server/manage/administrative.py
When running locally, NLTK is downloaded during boot here `backend/danswer/main.py`  and cached to `model_cache_nltk` docker-compose volume. When running danswerbot and backend in different hosts (or k8s pods), danswerBot raise an exception about missing nltk data missing. This PR addresses the issue
=> Moshe.download nltk data on start

backend/danswer/chat/models.py, backend/danswer/one_shot_answer/answer_question.py, backend/danswer/one_shot_answer/interfaces.py, backend/danswer/one_shot_answer/models.py
This PR adds optional `return_contexts` parameter to `/api/query/stream-answer-with-quote` endpoint. If set to `true`, list of contexts are returned back as an additional output. `DanswerContexts` implementation and handling is similar to `DanswerQuotes`.
Returned contexts are useful for evaluating RAG pipelines (notably the retrieval part) with tools like [ragas](https://github.com/explodinggradients/ragas)
I might add some scripts for easy evaluation with ragas since that might be useful for others, but not sure where to place them yet (don't want to add new dependencies here).
I'll leave some comments to the code where your input would be appreciated.
=> Add return contexts

.github/workflows/pr-quality-checks.yml
This check validates that the contributor ran & passed `pre-commit` locally, by running it remotely with his changes. That way we:
* Makes the reviewer's life easier, by reviewing only if all checks passed.
* Makes sure that any new change passes & meets the quality code standards.
* Failures will be available for the contributor via the "Action" tab to see what needs to be fixed (like in a local run). Here is a fake example I've created:
You can see the new check in the checks list below 👇
=> CI: new pre-commit check

backend/danswer/connectors/notion/connector.py
=> Notion connector now skips reading ai_block blocks instead of erroring out (Notion API currently doesn't support ai_blocks)

backend/alembic/versions/5f4b8568a221_add_removed_documents_to_index_attempt.py, backend/danswer/background/connector_deletion.py, backend/danswer/background/indexing/run_indexing.py, backend/danswer/db/index_attempt.py, backend/danswer/db/models.py, backend/danswer/server/documents/models.py, web/src/app/admin/connector/[ccPairId]/IndexingAttemptsTable.tsx, web/src/lib/types.ts
Closes #938 
This implements deletion of documents which are not returned  from a connector anymore.
Known Limitations:
- only works for `LoadConnector`, not `PollConnector`
- does not batch deletions
=> Remove documents from index which are not returned by connector

backend/danswer/connectors/document360/connector.py
expects primary_owners to be a list of dictionaries, but it's being provided with a list of strings instead.
https://github.com/danswer-ai/danswer/issues/1111
=> Update Document360 Connector

backend/danswer/db/engine.py
Wraps `get_session()` in a trace span so we can monitor db connection latency.
=> Trace sqla get_session

deployment/data/nginx/app.conf.template, deployment/data/nginx/app.conf.template.dev, deployment/data/nginx/app.conf.template.no-letsencrypt
This PR addresses the routing issue described in [#1134](https://github.com/danswer-ai/danswer/issues/1134), where accessing the `/api/docs` endpoint failed to load the OpenAPI definition due to an incorrect path for fetching `/openapi.json`. By updating the Nginx configuration, both the `/api/*` and `/openapi.json` paths are now correctly routed, ensuring the documentation UI functions as expected.
- Modified the Nginx configuration to match both `/api/*` and `/openapi.json` with a single rule.
- Added a rewrite rule for `/api` prefixed paths to correctly route API requests without affecting the `/openapi.json` endpoint.
- Resolves the documentation UI issue by allowing `/api/docs` to successfully fetch the OpenAPI definition.
- Simplifies the routing logic in the Nginx configuration, …
=> Fix: Correctly route /openapi.json and /api/* paths in Nginx config

backend/danswer/connectors/web/connector.py
Added logic to check a page's HTTP response status code and skip any pages returning a 5XX or 4XX response
To cover the cases where a 404 page may have additional URL's to recursively index, the skip is implemented after `get_internal_links()`
=> Update Web Connector: Skip indexing pages returning HTTP 4XX & 5XX codes

backend/danswer/connectors/file/connector.py
This fixes issue #1195 
Please check to see if additional lines where the reference to metadata.get() should be file_metadata.get(), as described in the issue.
=> Fix broken link when specified in metadata

backend/danswer/connectors/web/connector.py
The sitemap extractor assumes URLs integrity and will fail to navigate relative URLs in cases where `<loc>` tags are not absolute.
Index https://karpenter.sh/docs/sitemap.xml
```
connector.py 233 : [Attempt ID: 40] Failed to fetch '/v0.35/concepts/nodeclasses/': Protocol error (Page.navigate): Cannot navigate to invalid URL
connector.py 172 : [Attempt ID: 40] Visiting /v0.34/concepts/nodeclasses/
connector.py 233 : [Attempt ID: 40] Failed to fetch '/v0.34/concepts/nodeclasses/': Protocol error (Page.navigate): Cannot navigate to invalid URL
connector.py 172 : [Attempt ID: 40] Visiting /v0.33/concepts/nodeclasses/
connector.py 233 : [Attempt ID: 40] Failed to fetch '/v0.33/concepts/nodeclasses/': Protocol error (Page.navigate): Cannot navigate to invalid URL
```
- Defined …
=> fix: sitemap connector URLs extraction integrity 

backend/danswer/connectors/confluence/connector.py, web/src/app/admin/connectors/confluence/page.tsx
The current confluence cloud connector only support <company name>.atlassian.net host name.
My company has a <company name>.jira.com Confluence Cloud domain. The proposed fix allows to parse Confluence properly.
=> Bugfix: Support more Confluence Cloud hostname (*.jira.com)

backend/danswer/connectors/web/connector.py
Fix for issue #1161 
Runs `check_internet_connection()` before indexing any documents with playwright and raises an Exception if you are unable to reach cloudflare and google DNS. The raised exception keeps existing documents from being overwritten in the event that there is no internet connection.
=> Fix: Added check for internet connection to web connector

backend/danswer/db/engine.py, backend/danswer/one_shot_answer/answer_question.py, backend/danswer/server/query_and_chat/query_backend.py
Endpoints that use Depends(get_session) with a StreamingResponse have the problem that Depends() releases the session again after the endpoint function returns. At that point, the streaming response is not finished yet but still holds a reference to the session and uses it. However, there is no cleanup of the session after the answer stream finishes which leads to the connections accumulating in state "idle in transaction".
This was due to a breaking change in FastAPI 0.106.0 https://fastapi.tiangolo.com/release-notes/#01060
Still TODO and I would appreciate some support here:
=> WIP: Do not obtain DB session via Depends()

backend/danswer/connectors/web/connector.py
Hey there! 🙋‍♂️
So, I dove into the "Web connector - documents deleted when no internet connection" issue (#1161).
I've modified the check_internet_connection(current_url) to actually use the target URL and not TCP/53. Then added a call in load_from_state. Now, before attempting to load the state, we're ensuring that there's a valid connection to that URL. If not, the method will raise an exception and prevent the documents from being deleted. Here's the core bit:
```python
def check_internet_connection(url: str) -> None:
try:
response = requests.get(url, timeout=3)
response.raise_for_status()
except (requests.RequestException, ValueError):
raise Exception(f"Unable to reach {url} - check your internet connection")
```
Looking forward to hearing your thoughts on this. Catch you on …
=> Fixed: Web connector - documents deleted when no internet #1161

backend/danswer/connectors/notion/connector.py
After some discovery on how the Notion connector works it seems like the `poll_source` keeps fetching using the `_search_notion` method, even when the `_filter_pages_by_time` returns not pages. As the search uses the sort parameter, we can assume that when the filter returns an empty list, we can just `break` the flow, as all following calls will return documents older than the `end`, hence doing a lot of not required API calls to the Notion API.
Actually, in the `load_from_state` function it's done similarly 
https://github.com/danswer-ai/danswer/blob/b59912884bed7a32a0858d2e634d5402647c5ea6/backend/danswer/connectors/notion/connector.py#L405
in fact, in this case you could think that the `_filter_pages_by_time` has an infinitely past `end`, hence always returning all the pages from the …
=> fix: Stop reading Notion pages on polling

backend/danswer/connectors/hubspot/connector.py
Consider the case where the Hubspot ticket note body value might be `None`, and
only adding to the list when it's set.
Example object returned
```json
...
"id": "19203161741",
"properties": {
"hs_createdate": "2022-02-09T17:23:27.436Z",
"hs_lastmodifieddate": "2022-02-09T17:23:27.436Z",
"hs_object_id": "19203161741"
...
```
=> fix: Consider  Hubspot ticket notes body

backend/danswer/connectors/document360/connector.py, backend/danswer/connectors/document360/utils.py
Issue 1: Currently, the connector traverses through only one level deep child categories. But, the depth of child categories in document360 is arbitrary. Hence, a lot of documents which are part of nested child categories are skipped.
Issue 2: If the content of a document is completely blank, connector fails while parsing it.
This PR fixes these issues.
=> Support to loop through all nested subcategories

backend/.gitignore
Tiniest PR to ensure versioning is tidied up by fixing the ignoring of the celery-generated file in dev mode (currently not working properly).
=> fix(gitignore): properly ignore celery-generated file

backend/danswer/connectors/document360/connector.py
1. Fixed incorrect document base url
2. Articles sometime have an external url, save it if available.
=> Save correct document url from document360

backend/danswer/configs/danswerbot_configs.py, backend/danswer/danswerbot/slack/blocks.py, backend/danswer/danswerbot/slack/handlers/handle_buttons.py, backend/danswer/danswerbot/slack/handlers/handle_message.py, backend/danswer/danswerbot/slack/listener.py
Hi,
For us, the users' feedback is essential to improve Danswer and our internal documentation. Most of our users forget to give feedback. This PR uses the Slack message scheduler feature to schedule a DM to remind the user to give feedback. The delay (in minutes) is configurable.
=> Add Slack feedback reminder

backend/danswer/configs/app_configs.py
This PR resolves an issue on certain machines where deployment fails because the `api_server` fails to connect to the `postgres` server inside the `relational_db` container due to how `asyncpg` handles the database URL.
This issue was observed on a DigitalOcean droplet running Ubuntu with Docker 25.0.3 (8 vCPUs, 16G RAM, 480GB disk), following the "[Deploy to Digital Ocean](https://docs.danswer.dev/production/digitalocean)" guide. The failure manifested as the Let's Encrypt script hanging with the message: `Nginx is not ready yet, retrying in 5 seconds...`.
Logs from the `nginx` container pointed to an issue in the `api_server`, where Alembic encountered an error:
```
...
socket.gaierror: [Errno -2] Name or service not known
```
The issue was resolved by URL-encoding the database password …
=> fix(config): password auth to be url-encoded to avoid Digital Ocean deployment errors

backend/danswer/configs/app_configs.py, backend/danswer/prompts/answer_validation.py
Hi,
Using custom persona and so, custom prompts, we must adapt the auto-control prompt by updating the conditions otherwise some valid answers are marked as invalid.
This PR allows custom "conditions" definitions to validate a query/answer pair.
=> Allow to define custom conditions for the answer validation prompt

backend/danswer/server/manage/users.py, web/src/app/admin/users/page.tsx
This PR is a small addition to provide the ability to _demote_ an admin user. Currently, there is no means within the UI to revoke this permission.
**The following is a demonstration. The left screen is `test@test.com` and the right is `test2@test.com`:**
In order to prevent a case where there are _no_ admins, admins cannot demote themselves. 
This partially addresses https://github.com/danswer-ai/danswer/issues/1300
=> User Management: Add User Demotion Functionality

deployment/kubernetes/charts/danswer-stack/Chart.lock, deployment/kubernetes/charts/danswer-stack/Chart.yaml, deployment/kubernetes/charts/danswer-stack/templates/_helpers.tpl, deployment/kubernetes/charts/danswer-stack/templates/api-deployment.yaml, deployment/kubernetes/charts/danswer-stack/templates/background-deployment.yaml, deployment/kubernetes/charts/danswer-stack/templates/configmap.yaml, deployment/kubernetes/charts/danswer-stack/templates/danswer-secret.yaml, deployment/kubernetes/charts/danswer-stack/templates/indexing-model-deployment.yaml, deployment/kubernetes/charts/danswer-stack/templates/inference-model-deployment.yaml, deployment/kubernetes/charts/danswer-stack/templates/webserver-deployment.yaml, deployment/kubernetes/charts/danswer-stack/values.yaml
This PR helps separate some secrets out from the standard configmap, the changes include:
- Adding an auth section to the helm values yaml
- Adding to the auth section keys to fill in for various secrets
- Adding these secrets to the various deployments as env vars, to avoid any changes to the backend code
- Incrementing chart version
Fixes #1540 and helps with #971
=> adding secrets to helm

backend/danswer/connectors/sharepoint/connector.py, backend/requirements/default.txt
Hi,
Currently, the Sharepoint connector returns only 200 drive item objects. This issue is related to the Office365 library (https://github.com/vgrem/Office365-REST-Python-Client/issues/844). 
This PR upgrades the library and sets the highest limit.
=> fix sharepoint connector missing objects

deployment/docker_compose/init-letsencrypt.sh
Sometimes a user wants to specify an explicit subdomain for the establishment of the SSL certificate. In this case, you do not want to append www to the domain in the list of domains to test the Let's Encrypt certification process against.
=> Update init-letsencrypt.sh to support subdomain configurations

backend/danswer/connectors/sharepoint/connector.py, web/src/app/admin/connectors/sharepoint/page.tsx, web/src/components/admin/connectors/Field.tsx
This commit enhances the SharePoint Connector with the following features:
1. **Support for Sites.Selected Permissions:**
- Enables granular access control by supporting Sites.Selected permissions.
- The existing method using Sites.Read.All permissions remains unchanged and fully functional.
- Allows administrators to specify certain SharePoint sites which enhances security and compliance with organizational policies.
2. **Subfolder Selection Capability:**
- Adds functionality to select individual subfolders within a SharePoint site.
- Provides users with more precise data management options.
=> Added support for Sites.Selected permissions to the SharePoint Connector and enabled the selection of individual subfolders

backend/danswer/connectors/file/connector.py
Relates to #1195.
This fixes an issue where metadata specified in a #DANSWER_METADATA line in a file read by the file connector is ignored.
To test this:
- Index a file using the file connector that contains a `#DANSWER_METADATA` tag
- Without this fix the metadata like 'link' or 'file_display_name' are ignored and when you do a search the default information is used.
- With this fix the display name and link in search results will be taken from the metadata tag.
=> Set ignore_danswer_metadata=False when calling read_text_file in fille connector

deployment/helm/values.yaml
Vespa is not working because this configuration
As you can see in this Issue https://github.com/unoplat/vespa-helm-charts/issues/20
You have to use these podLabels to be in accord with the other configuration.
vespa:
podLabels:
app: vespa
app.kubernetes.io/instance: danswer
=> Changed the vespa podLabels to work properly

deployment/kubernetes/api_server-service-deployment.yaml, deployment/kubernetes/secrets.yaml
Without adding the env vars to the API Server deployment, the google secrets cannot be used for authentication.
Fixes #1406
=> Add OAuth env vars to API Server deployment

deployment/helm/values.yaml
Contrary to the comments in `values.yaml` claiming that specifying default resources is left out to the user, resources are being specified for some deployments. The resources for `background`, for example, are too low and cause process restarts in the container.
On the other hand, no resources are specified for `vespa`, and the Vespa Helm chart [specifies resources](https://github.com/unoplat/vespa-helm-charts/blob/e7db599f1272d3ff4752298dba1db14d05b70409/charts/vespa/values.yaml#L90) that are too low.
This PR does the following:
1. Comment out resource specifications for all deployments except `vespa` and fix code style of the commented-out blocks
2. Override resource specifications for `vespa` to allow Vespa to run.
=> Fix Helm chart run failures due to low resources

backend/danswer/configs/danswerbot_configs.py, backend/danswer/danswerbot/slack/listener.py, backend/danswer/danswerbot/slack/utils.py, backend/danswer/prompts/miscellaneous_prompts.py
Hello,
We've been utilizing Danswer to actively monitor and respond to user Slack messages, but we've encountered poor results because often the end user doesn't craft their messages with the understanding that a bot is interpreting them.
To enhance the quality of our responses, this Pull Request introduces an additional step that rephrases user messages for clarity before processing.
=> Slack: add support to rephrase user message

deployment/helm/values.yaml
The change made in https://github.com/danswer-ai/danswer/pull/1536 only changed the Vespa pod resource requests and not the corresponding limits. This means that Kubernetes refuses to created the Vespa pod because the requests must be less than or equal to the limits. This changes fixes the limits to match the requests by default.
=> Fix Helm Vespa resource limits

backend/danswer/configs/app_configs.py, backend/danswer/file_processing/enums.py, backend/danswer/file_processing/html_utils.py
adds an app config `ZENDESK_CONNECTOR_TRANSFORM_LINKS` that can be set to `strip` (default) or `markdown`. when set to strip links are turned into plain text with the link dropped, when set to markdown html links become markdown links.
unsure of docker setup, do we need to add `ZENDESK_CONNECTOR_TRANSFORM_LINKS` somewhere so that the environment variable can be passed through?
=> Transform HTML links to markdown behind config option

.github/workflows/docker-build-backend-container-on-merge-group.yml, .github/workflows/docker-build-web-container-on-merge-group.yml
This adds GitHub workflows that will trigger docker builds (no pushes) on merge group events (which fire off when we enable merge queues for PR's).  The workflows are slimmed down versions of the build and push workflows that run on tag events.
So far, just doing backend and web, model server might be next.
This is following a pattern in Github's docs about this feature which checks against both pull requests on submission as well as when being integrated by the merge queue into main. Thoughts on if we want to limit this to the merge queue only?  Some googling suggest this is possible with a bit of magic syntax.
https://stackoverflow.com/questions/76655935/when-does-a-github-workflow-trigger-for-merge-group-and-is-it-restricted-by-bran
=> add workflows that automate docker builds against merge group events

web/src/app/chat/ChatPage.tsx, web/src/app/chat/lib.tsx, web/src/app/chat/message/CodeBlock.tsx, web/src/app/chat/message/Messages.tsx
Fixes:
- New chats causing a "refresh" which takes the user back to the top of the chat history
- "Loading bubbles" disappearing too early for search enabled
- When using any non-danswer assistant, it would show up as "Danswer" due to alternate assistant being cast to `0`,
- single "\`" chars were being treated as code blocks (triple ```) rather than the expected mild code highlighting (e.g. `<CODE>`)
- When switching between chats, it didn't scroll to the bottom immediately
=> Fix misc chat bugs

backend/danswer/danswerbot/slack/handlers/handle_message.py
On my Danswer installation I noticed this error in the background service when I sent a direct message to the bot user:
```
06/28/2024 09:40:19 AM          listener.py 415 : Failed to process slack event
File "/app/danswer/danswerbot/slack/listener.py", line 413, in process_slack_event
File "/app/danswer/danswerbot/slack/listener.py", line 353, in process_message
File "/app/danswer/danswerbot/slack/handlers/handle_message.py", line 277, in handle_message
if respond_slack_group_list:
UnboundLocalError: cannot access local variable 'respond_slack_group_list' where it is not associated with a value
```
I'm not familiar with the code or why the error is occuring now but this minor change should fix it (I already tested it on my installation)
=> Fix "cannot access local variable" for bot direct messages

backend/danswer/connectors/notion/connector.py
I think the date filter is wrong, it scans too many files as `compare_time <= end` is always true if you're just trying to get the most recent documents? This causes the connector to run for a long time on each run if your Notion workspace is large.
=> Notion date filter fix

web/src/lib/llm/utils.ts
Fixes image generation issue with custom providers.
We were comparing compatible image models and providers (e.g. `openai`) against user-named "providers" (aka their keys).
=> fix gpt-4o image issue

backend/danswer/server/query_and_chat/chat_backend.py
At least my navigator (Mozilla/5.0 Gecko/20100101 Firefox/128.0) sends `text/xml` and not `application/xml`, making it impossible to upload XML files in the chat since an error was raised.
=> Fix bug XML files in chat

backend/danswer/configs/app_configs.py, backend/danswer/connectors/zendesk/connector.py
use case: some articles may not be draft articles, but also not appropriate/useful to be indexed. one example is template articles.
this PR adds an env config `ZENDESK_CONNECTOR_SKIP_ARTICLE_LABELS` which accepts a comma delimited list of label names to skip when indexing in the zendesk connector.
=> Add config to skip zendesk article labels

backend/danswer/llm/llm_provider_options.py, backend/danswer/tools/utils.py, backend/scripts/test-openapi-key.py, web/src/lib/llm/utils.ts
This adds support for `gpt-4o-mini` at roughly 25 times a lower cost then GPT-4, note this doesn't set 4o-mini to the default but that should be a next step as the accuracy is near identical, max token input is the same, the model runs faster, and saves a massive amount when churning through large amounts of data.
=> Add GPT-4o-Mini & fix a missing GPT-4o in Model Tests

backend/danswer/document_index/vespa/index.py, backend/danswer/indexing/embedder.py, backend/danswer/indexing/models.py, backend/danswer/natural_language_processing/search_nlp_models.py, backend/danswer/search/retrieval/search_runner.py, backend/danswer/server/danswer_api/ingestion.py, backend/model_server/encoders.py, backend/shared_configs/model_server_models.py
What this PR does:
- Robustifies embedding classes to maintain updates to 3rd party models
- Deal with empty strings passed to emebdders 
Approach to empty strings:
- Dealt with in `embed_text` to limit need to handling matching indices, etc. in requests to model server or in embedding models themselves
1. Don't pass indices which have no content to the embedding models (instead replace at end with `null`
2.  Deal with `null`s (currently) by replacing with title vector
=> Fix empty / reverted embeddings

backend/danswer/connectors/web/connector.py
Hey 👋, just checked out Danswer's code! I found an issue with indexing my website that was being mis-diagnosed by Danswer.
---
My website (https://shukantpal.com) uses Let's Encrypt certificates, which aren't accepted by the Python urllib certificate verifier for some reason. My website is set up correctly otherwise (https://www.sslshopper.com/ssl-checker.html#hostname=www.shukantpal.com)
This change adds a fix so the correct traceback is shown in Danswer, instead of a generic "unable to connect, check your Internet connection".
---
=> Handle SSL error tracebacks in site indexing connector

backend/danswer/llm/chat_llm.py
This allows the removal of the explicit max_output_tokens. By setting GEN_AI_MAX_OUTPUT_TOKENS=0 the actual max_output_tokens will be whatever the value supported by the model in use.
Change deployed and tested with different models with different output token values (Ie. gpt-4: 4096, gemini-1.5-pro: 8192)
None known
None
=> Allow removal of max_output_tokens by setting GEN_AI_MAX_OUTPUT_TOKENS=0

backend/danswer/chat/chat_utils.py, backend/danswer/db/models.py, backend/danswer/llm/answering/models.py, backend/danswer/llm/utils.py, backend/danswer/tools/images/image_generation_tool.py, backend/danswer/tools/images/prompt.py, web/src/app/chat/files/images/InMessageImage.tsx
This fixes a bug where after the first image generation in a chat session, all future messages will fail with 
`Image URLs are only allowed for messages with role \'user\', but this message with role \'assistant\' contains an image URL.\\",`
I used an image generation enabled assistant (using gpt4-o) to generate an image.
If you ask a follow up about the previously generated images, then it won't be able to reference them.
N/A
=> Fix image generation follow up q

backend/danswer/auth/users.py, backend/danswer/server/manage/users.py, backend/danswer/tools/custom/openapi_parsing.py
If the OIDC token has expired, treat the user as not authenticated. Currently, the "needs to login" popup appears if you come back to the app after not using for a while, but we should just auto-log them in.
Tested OIDC via Okta locally.
N/A
N/A
=> Fix flow where oidc_expiry is different from token expiry

web/src/lib/sources.ts
Adds back `not_applicable` to the `SOURCE_METADATA_MAP` so that if any connectors of this source type are setup it doesn't crash things + so that the web search tool works on chat. 
E.g. fixes:
Visited the admin panel + tried a web search enabled assistant.
N/A
N/A
=> Fix not_applicable

backend/danswer/connectors/zendesk/connector.py
We cache all content_tags and then check if each document has any content_tag_ids. if it does, we get the content_tags that have a matching id from the cache and add it to the document metadata
I added a tag to the document and then searched for the tag name in the  
We are using the requests library raw to grab the content_tags because the zenpy library does not support retrieving the content_tags
=> Added content tags to zendesk connector

backend/danswer/background/celery/celery_app.py, backend/danswer/background/update.py, backend/danswer/db/document_set.py
Fixes DAN-379.
secondary indexes need dedupe checking as well. We didn't run into this bug before because all the indexing code was running inside the dispatch loop.
Switched models on main and observed job count rising unnecessarily.  Implemented fix and job count is no longer rising.
=> enforce index attempt deduping on secondary indexing.

web/src/app/chat/ChatPage.tsx, web/src/lib/hooks.ts
Adds improved default temperatures to search
Upon visiting a new assistant, we now decide a "default" temperature which users can modify in the chat input bar.
- If user has set search param for temperature, we adopt that as the default
- Else, if assistant has search tool - default to 0
- Else, default to 0.7
=> Add proper default temperature + overrides

backend/danswer/chat/process_message.py, web/src/app/chat/ChatPage.tsx
- Removes check for "error message in last index" before updating message history
This makes the entire error handling process much smoother as the chat message history doesn't break like it used to 
- Now uses a new ref that tracks the actual state of the chat messages + session loading to determine when to erase the previous errors
=> Don't persist error perennially

web/src/app/chat/ChatPage.tsx, web/src/app/globals.css, web/tailwind-themes/tailwind.config.js
Improves code formatting and fixes math for chat input bar padding.
We can modify as needed later, now that we have isolated the relevant class names.
=> Improve code block formatting

backend/danswer/llm/answering/stream_processing/quotes_processing.py, backend/tests/unit/danswer/llm/answering/stream_processing/test_quote_processing.py
- Fixes occasional break in quote processing for search 
- Adds test case
Issue: 
- LLM responds with lengthy pre-amble to search queries `this is my json response \n\n..` and unnecessarily hits character limit
=> quote processing for lengthy intros

backend/danswer/llm/chat_llm.py
These settings are just the default and may throw off other LLM providers accessed via an OpenAI compatible API.
=> Remove unnecessary LLM settings

web/src/app/chat/message/Messages.tsx
Add `plaintext` language demarcation to code blocks without any language demarcation
=> Fix formatting for non-langauge-demarcated code blocks

backend/danswer/background/indexing/run_indexing.py, backend/danswer/background/indexing/tracer.py, backend/danswer/configs/app_configs.py
Adds configurable memory tracing between intervals of batches during indexing via INDEXING_TRACER_INTERVAL.
Examples attached.
[connector_tracer_example.txt](https://github.com/user-attachments/files/16618861/connector_tracer_example.txt)
=> add configurable support for memory tracing during indexing

backend/danswer/llm/utils.py
The LLM configuration passed to `get_llm_max_tokens` can be poorly formatted (e.g. `bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0`) which handicaps the token limit estimation process. This simply adds an extra case to attempt to account for this kind of configuration error (and become compatible with https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json#L3324)
=> Add handling for poorly formatting model names

backend/danswer/background/celery/celery_app.py, backend/danswer/configs/constants.py
Fixes DAN-430. kombu_message table was expanding without bound, causing certain queries to be excessively slow.
=> add kombu message cleanup task

backend/model_server/encoders.py, web/src/app/admin/embeddings/pages/EmbeddingFormPage.tsx
Model suffix stripping should be applied for cloud embedding models as well as self-hosted ones
=> Pull out stripping of model suffix

web/src/app/assistants/SidebarWrapper.tsx, web/src/app/chat/ChatPage.tsx, web/src/app/chat/sessionSidebar/HistorySidebar.tsx, web/src/app/chat/shared_chat_search/FixedLogo.tsx, web/src/components/chat_search/Header.tsx, web/src/components/header/LogoType.tsx, web/src/components/search/SearchSection.tsx
Explicitly closes sidebar on manually clicking `unpin`
https://github.com/user-attachments/assets/66adb6c4-b4b6-4f82-9e73-9fda1c4ad807
Separate thought: noticing a lot of shared logic for history sidebar in the 3 places it is used (search chat, "personal settings")- have added to my task list some time to group the shared logic
=> Untoggle sidebar fully on untoggling

web/src/components/search/filtering/FilterDropdown.tsx, web/src/components/search/filtering/Filters.tsx
Must be able to customize dropdown's widths/classnames in terms of 
- Overarching width
- Dropdown elements' widths (as a group_
- And individual dropdown element's classnames
=> Add granularity to filter widths

backend/alembic/versions/4b08d97e175a_change_default_prune_freq.py, backend/danswer/background/celery/celery_utils.py, web/src/app/admin/connector/[ccPairId]/ConfigDisplay.tsx, web/src/app/admin/connectors/[connector]/AddConnectorPage.tsx, web/src/app/admin/connectors/[connector]/pages/Advanced.tsx
This sets the default pruning time to 30 days and also sets all existing prune_freq that were 1 day to 30 days. Also, it is now shown in days instead of minutes
I tested this by adding a connector on main (using pruning defaults), switching to the branch, running alembic upgrade, and ensuring that the connector's prune frequency updated to 30 days. I also checked the defaults for new connectors
=> Updated pruning defaults

backend/danswer/connectors/confluence/connector.py
Fixes DAN-441.
Confluence - attachments not embedded within a page will be indexed as separate documents.
=> support indexing attachments as separate docs when not part of a page

backend/ee/danswer/server/query_and_chat/chat_backend.py
Fixes DAN-445. message passing was using rephrased query instead of the original query.
Observed raw queries to the LLM before and after the change
=> fix message param to use query instead of rephrased query

web/src/components/settings/lib.ts
Currently, if we load any page as a non-EE user, we will get the blank "settings could not be fetched" page- we should allow 404s from non EE users, as they will not have access to the enterprise edition endpoints
=> Allow graceful 404s when fetching enterprise settings

backend/alembic/versions/f17bf3b0d9f1_embedding_provider_by_provider_type.py, backend/danswer/background/update.py, backend/danswer/danswerbot/slack/listener.py, backend/danswer/db/embedding_model.py, backend/danswer/db/llm.py, backend/danswer/db/models.py, backend/danswer/indexing/models.py, backend/danswer/main.py, backend/danswer/natural_language_processing/search_nlp_models.py, backend/danswer/server/manage/embedding/api.py, backend/danswer/server/manage/embedding/models.py, backend/danswer/server/manage/search_settings.py, backend/shared_configs/configs.py, web/src/app/admin/configuration/search/UpgradingPage.tsx, web/src/app/admin/configuration/search/page.tsx, web/src/app/admin/embeddings/EmbeddingModelSelectionForm.tsx, web/src/app/admin/embeddings/modals/ChangeCredentialsModal.tsx, web/src/app/admin/embeddings/modals/DeleteCredentialsModal.tsx, web/src/app/admin/embeddings/modals/ProviderCreationModal.tsx, web/src/app/admin/embeddings/pages/CloudEmbeddingPage.tsx, web/src/app/admin/embeddings/pages/EmbeddingFormPage.tsx, web/src/components/embedding/interfaces.tsx
Modify embedding interface to be provider ID agnostic and use basic enums for identification instead (OpenAI, etc).
This involves migrating from a provider-based system, where each provider has
- `id`
- `default_model_id`
- `name` (better described as provider
To simply
- `provider_type`
On this branch
1. Creating various embedding providers
2. Switching between them
3. Embedding 
4. Using chat flows (both cloud + self-hosted)
Upgrade/downgrade tests
1. Creating embedding providers on main
2. Upgrading to this branch - testing + creating + switching
3. Downgrading to main - testing + creating + switching
=> Update embedding interface

backend/danswer/background/indexing/run_indexing.py, backend/danswer/connectors/connector_runner.py
Wraps all calls to connectors to catch the exception and log the state of all local vars at the time of the exception
=> Add better logging for connectors

web/src/app/assistants/SidebarWrapper.tsx, web/src/app/chat/ChatPage.tsx, web/src/app/chat/sessionSidebar/HistorySidebar.tsx, web/src/app/chat/shared_chat_search/FixedLogo.tsx
Instead of logotype toggling the sidebar, now redirects to default page
https://github.com/user-attachments/assets/c0553b3e-054a-4e13-8ac6-3a5b493ec847
=> Logotype from toggle -> redirect

web/src/lib/assistants/fetchPersonaEditorInfoSS.ts
Fixes #2025
Switch the icons for AWS and Azure.
Tested the UI - icons are now correct.
-
#2025
=> Fix icons in personas (assistants) - AWS and Azrue were mixed up

backend/danswer/configs/app_configs.py, backend/danswer/connectors/confluence/connector.py, backend/tests/daily/connectors/confluence/test_confluence_basic.py
Large files (e.g. 10MB log files) can cause indexing to freeze. Adding a cap to the # of chars a confluence attachment can have to be considered.
Also added a test (which in the future can automatically run at an interval) to test the basics of the confluence connector.
=> Fix freezing

web/src/app/admin/connectors/[connector]/AddConnectorPage.tsx, web/src/lib/connectors/connectors.ts
Prevents people from accidentally using uppercase in their specified slack channels -> indexing nothing
=> Lowercase slack channels automatically

backend/danswer/configs/danswerbot_configs.py, backend/danswer/danswerbot/slack/listener.py, backend/danswer/danswerbot/slack/utils.py
This adds a rate limit to the slack bot configurable by env variable
Turned the limit/time period down to 2 messages per 30 seconds and tried exceeding it.
High traffic at the end of one period and start of another could cause
the limit to be exceeded.
=> Added DanswerBot response limit environment variables

backend/danswer/server/documents/cc_pair.py, backend/danswer/server/documents/connector.py, backend/shared_configs/configs.py, web/src/app/admin/add-connector/page.tsx, web/src/app/admin/connectors/[connector]/AddConnectorPage.tsx, web/src/app/admin/connectors/[connector]/pages/ConnectorInput/NumberInput.tsx, web/src/app/admin/embeddings/RerankingFormPage.tsx, web/src/app/admin/embeddings/interfaces.ts, web/src/app/admin/embeddings/pages/AdvancedEmbeddingFormPage.tsx, web/src/app/admin/embeddings/pages/EmbeddingFormPage.tsx, web/src/app/admin/indexing/status/CCPairIndexingStatusTable.tsx, web/src/app/chat/ChatBanner.tsx, web/src/components/IsPublicGroupSelector.tsx, web/src/components/admin/connectors/Field.tsx, web/src/components/chat_search/Header.tsx, web/src/components/search/filtering/Filters.tsx, web/src/components/search/filtering/TagFilter.tsx, web/src/components/user/UserProvider.tsx
- Proper fadeout aligned with chat banner
- Tags now appear earlier in selection and are scrollable (to avoid odd long tag selection pages)
- Standardized search input 
- Don't show user group selection if no user groups exist
=> Minor search UX improvements + Critical connector fixes

backend/danswer/connectors/file/connector.py, backend/danswer/connectors/google_drive/connector.py, backend/danswer/connectors/web/connector.py, backend/danswer/file_processing/extract_file_text.py
=> Add metadata to pdf extraction

.github/workflows/pr-python-connector-tests.yml
Runs the connector tests on every PR (non-blocking) + daily tests that alert us on Slack in the #alerts channel
=> Connector tests

backend/danswer/file_processing/extract_file_text.py, backend/danswer/main.py, backend/danswer/utils/gpu_utils.py, web/src/app/chat/ChatPage.tsx
=> Detect GPU on startup for default multi-pass indexing value

backend/danswer/chat/models.py, backend/danswer/search/pipeline.py, backend/danswer/secondary_llm_flows/agentic_evaluation.py, web/src/components/search/DocumentDisplay.tsx, web/src/components/search/SearchSection.tsx, web/src/lib/search/streamingQa.ts
=> Catch LLM Eval Failures

backend/danswer/indexing/indexing_pipeline.py
Fixes DAN-547.  Document keyerror exception.  Fixes the immediate crash but larger problem could be due to a race condition which we have plans to address in an architectural overhaul.
=> fail safely if lookup for document fails

backend/ee/danswer/server/enterprise_settings/models.py, backend/ee/danswer/server/seeding.py, web/src/app/admin/settings/interfaces.ts, web/src/app/chat/ChatPage.tsx, web/src/app/chat/message/Messages.tsx, web/src/app/ee/admin/whitelabeling/WhitelabelingForm.tsx, web/src/components/UserDropdown.tsx, web/src/components/admin/connectors/AdminSidebar.tsx, web/src/components/icons/DynamicFaIcon.tsx
Allow people to configure user dropdown custom links / icons / titles
A couple of perfectly valid possible approaches (for the icon side specifically)
- User uploads image during seeding -> render image
- User specifies name from predefined list -> render from map
- (went with this one) User specific name from FaIcon/react https://fontawesome.com/icons/react and we dynamically load, cache, and render the specific icon 
Sample environment variable: `ENV_SEED_CONFIGURATION='{"enterprise_settings": {"custom_nav_items": [{"title": "Documentation", "link": "https://docs.example.com", "icon": "Book"}, {"title": "Support", "link": "https://support.example.com", "icon": "phone"}]}}'` …
=> Add user dropdown seed-able list

.github/workflows/run-it.yml, backend/danswer/configs/constants.py, backend/danswer/main.py, backend/danswer/utils/telemetry.py
This pr adds a field called instance_domain to the anonymous_telemetry. This is only sent if EE features are enabled and telemetry is also enabled. the purpose is to help us track usage of our enterprise users per org (not per user)
=> Added instance domain to telemetry

backend/danswer/db/index_attempt.py, backend/danswer/server/documents/cc_pair.py, backend/danswer/server/documents/connector.py, backend/danswer/server/documents/models.py, web/src/app/admin/connector/[ccPairId]/IndexingAttemptsTable.tsx, web/src/app/admin/connector/[ccPairId]/page.tsx, web/src/app/admin/connector/[ccPairId]/types.ts, web/src/lib/ss/ccPair.ts
This should greatly improve load times by:
- loading connector info then index attempts
- fetch and catch the pages in  batches, prefetching +- 1 batch around the current page
=> Paginate connector page

backend/danswer/main.py
^
Now returns something like:
`{detail: "REGISTER_USER_ALREADY_EXISTS"}` instead of `{detail: "400: ErrorCode.LOGIN_BAD_CREDENTIALS"}`
=> Fix responses for HTTPExceptions

backend/danswer/connectors/confluence/connector.py, backend/danswer/connectors/confluence/rate_limit_handler.py, web/src/app/admin/connectors/[connector]/AddConnectorPage.tsx, web/src/components/IsPublicGroupSelector.tsx, web/src/lib/connectors/connectors.ts
=> Minor Confluence Fixes for Robustification

backend/danswer/danswerbot/slack/handlers/handle_regular_answer.py
When user interacts with DanswerBot in Slack DM, we want to use the user's information such that the user gets information about their private files. We use the email address tied to the Slack event to get user information and use it in the `get_search_answer` request.
- Add private connector for a file.
- Danswerbot cannot answer question about the file in public channel.
- Danswerbot can answer question about the file in DM.
Added requests to Slack and database.
=> Use user information in Slack bot DMs

backend/danswer/file_processing/extract_file_text.py, backend/requirements/default.txt
Right now, tables in Word files are completely skipped from indexing. This PR unwraps any simple tables (no nested tables, no omitted cells) on a row-by-row basis to include them with the indexed text. Some assumptions are made along the way:
1. The first row of the table is the heading
2. Entity attributes are in the table columns, with each table row representing an isolated entity.
Each unwrapped table row may look as follows:
```
No.: 2
Issue: The CD doesn’t play
Comments: The CD doesn’t start playback upon insertion into the drive. Furthermore, the drive LED doesn’t turn on.
```
=> Implement indexing of simple tables in Word files

backend/danswer/connectors/danswer_jira/connector.py
This PR fixes accessing the non-existent `emailAddress` attribute of a `User` object in the JIRA connector which lead to errors of this sort in the logs:
```
connector.py  83 : [Attempt ID: 127] Failed to process comment due to an error: <class 'jira.resources.User'> object has no attribute 'emailAddress' ('User' object is not subscriptable)
```
=> Fix JIRA comment author email access

backend/danswer/connectors/web/connector.py
Adds the ability to set `Doument.doc_updated_at` when `Last-Modified` is a valid date format. format defined in:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Last-Modified
=> Web Connector - Get doc_updated_at from `Last-Modified` header

backend/danswer/connectors/danswer_jira/connector.py
This PR fixes the following issues with content extraction from JIRA issues:
1. When using API version 2, comment body text is not extracted.
2. When using API version 3, issue description is not extracted.
This is because API version 3 returns [ADF](https://developer.atlassian.com/cloud/jira/platform/apis/document/structure/) for issue descriptions and comment bodies, whereas API version 2 returns plain text. #1329 addressed the problem with comments for API version 3 but broke comment extraction when using API version 2.
Note that this PR does not address the problem with the currently used ADF conversion function being broken (#1677), so using JIRA API version 3 still isn't advised.
=> Fix content extraction from JIRA with API v2 vs. v3

backend/danswer/connectors/sharepoint/connector.py
Hi,
Using the "get" method, we currently retrieve only the first 200 sites. To get all Sites the "get_all" method must be used.
=> Sharepoint: fix get all sites

backend/danswer/connectors/notion/connector.py
The commit skips reading 'external_object_instance_page' blocks in the NotionConnector due to the lack of support in the Notion API. This change is in response to the issue #1761.
=> Notion Connector to skip reading external blocks in NotionConnector

backend/alembic/versions/f7e58d357687_add_has_web_column_to_user.py, backend/danswer/auth/schemas.py, backend/danswer/auth/users.py, backend/danswer/danswerbot/slack/handlers/handle_buttons.py, backend/danswer/danswerbot/slack/handlers/handle_message.py, backend/danswer/danswerbot/slack/handlers/handle_regular_answer.py, backend/danswer/danswerbot/slack/listener.py, backend/danswer/danswerbot/slack/models.py, backend/danswer/db/models.py, backend/danswer/db/users.py, backend/ee/danswer/server/saml.py, web/src/app/auth/login/EmailPasswordForm.tsx
Add capability to add user when someone interacts with a Slack bot without having logged in via the UI. This invovles:
- Adding a `has_web_login` column to `user` table. This allows us to have logic where we allow a user to set their password with basic auth. Otherwise, a user would not know the placeholder password we set for them.
More database calls / Slack APIs in Slack bot + login flows.
=> Add user when they interact outside of UI (e.g. Slack bot)

backend/danswer/connectors/zendesk/connector.py, web/src/lib/connectors/connectors.ts
I updated the Zendesk connector to support a new required dropdown selection between "articles" and "tickets" with "articles" as the default for backward compatibility. If you already have a Zendesk connector set up, it will continue to work normally. If you set up a new one, you can choose "tickets" to have that connector sync all non-deleted Zendesk tickets. Therefore, you have the ability to create two separate Zendesk connectors using the same shared credentials, one for articles and one for tickets, which I felt would be useful in the creation of different Document Sets down the line (If you want both in the same Document Set, you can, but you can also easily separate knowledge of articles and tickets in the case where you want a Sales Assistant that only trains on articles, but a …
=> Zendesk tickets

CONTRIBUTING.md
Small documentation change to add instructions for installing Python 3.11 and confirm that GitHub contribution workflow works.
Documentation change
In the future, if the macOS instructions diverge, it may make sense to reconcile the two documents
=> Add link to macOS contributions doc for installing Python 3.11

backend/danswer/db/index_attempt.py
Fixes DAN-608. Foreign key entries need to be removed.
Ran a deletion on a connector with failed index attempts and observed FK error. Added cleanup code and deletion succeeded.
=> fixes a bug with deleting connectors and foreign keys

CONTRIBUTING.md
Catch-all PR for improving CONTRIBUTING.md documentation. Each commit is a self-contained group of related edits. Cherry-pick commits if desired.
Documentation change
Documentation staleness
?
=> Misc clarifications for CONTRIBUTING.md

backend/danswer/server/documents/connector.py
Make connector re-index failure page more intelligible for large customers. Instead of displaying those which need reindexing, dispaly those with failed reindex attempts.
=> Display only failed re-index attempts

backend/danswer/background/celery/celeryconfig.py, backend/danswer/configs/app_configs.py, backend/danswer/redis/redis_pool.py
=> add SSL parameter support for redis

web/src/app/admin/connector/[ccPairId]/IndexingAttemptsTable.tsx, web/src/components/tooltip/Tooltip.tsx
=> (minor) add a tiny bit of clarity to index doc counts

deployment/docker_compose/docker-compose.dev.yml, deployment/docker_compose/docker-compose.gpu-dev.yml, deployment/docker_compose/docker-compose.prod-no-letsencrypt.yml, deployment/docker_compose/docker-compose.prod.yml, deployment/docker_compose/docker-compose.search-testing.yml, deployment/kubernetes/redis-service-deployment.yaml
Fixes DAN-579.
Turns out the default docker container behavior is somewhat persistent, despite nearly all articles on the internet stating otherwise.
Observed incorrect persistence behavior, then removed volume and forced command line and finally saw keys removed between restarts.
=> ephemeral behavior for redis

backend/Dockerfile, backend/Dockerfile.model_server, backend/danswer/utils/logger.py
Current method of detecting containerization by checking for `/.dockerenv` is unreliable in Kubernetes environments, particularly EKS, leading to incorrect log file paths. 
=> Add fix for logging

backend/danswer/llm/answering/answer.py
Addresses:
```
"/app/danswer/llm/answering/stream_processing/citation_processing.py", line 72, in extract_citations_from_stream
raw_out += raw_token
TypeError: can only concatenate str (not "ToolCallKickoff") to str
```
=> Fix concatenate string with toolcallkickoff issue

backend/alembic/versions/35e6853a51d5_server_default_chosen_assistants.py, web/src/app/assistants/mine/AssistantsList.tsx, web/src/lib/assistants/orderAssistants.ts
Updates so default assistants list (from `null`) is all those which are.
It's okay if includes visible assistants which aren't accessible to user, as upon first re-ordering will refresh to be those which user has access to.
Additionally, I think it's still okay to set server default to our assistants - users can add any additional assistants in the assistant gallery on first startup (and if none are available- we'll display all visible as was the previous behavior). Alternative would be to modify how we handle chosen assistants or set the list on user creation.
=> Update default assistants to all visible

backend/danswer/auth/users.py, web/src/lib/user.ts
Basic auth was broken by recent update to class - anybody could log in with a verified email with any password.
Relevant code: https://github.com/fastapi-users/fastapi-users/blob/42ddc241b965475390e2bce887b084152ae1a2cd/fastapi_users/manager.py#L636
=> Fix basic auth

backend/danswer/chat/process_message.py, backend/danswer/llm/answering/stream_processing/citation_processing.py, backend/tests/unit/danswer/llm/answering/stream_processing/test_citation_processing.py
Our existing implementation to handle code blocks without any languages is to dynamically insert a `plaintext` tag as we process the content.
This causes issues with the way React Markdown processes content, yet we still need some way of inserting a language for code blocks that were created (by the LLM) without any (so that React Markdown can process the code block accordingly. )
This adds processing at the citation processing layer to insert the plaintext marker at the lowest level possible, so React markdown is **always** fed the correct version of the data.
=> Move code block default language creation to citation processing

backend/alembic/versions/1b8206b29c5d_add_user_delete_cascades.py, backend/danswer/db/models.py, backend/danswer/server/manage/users.py, web/src/components/admin/users/SignedUpUserTable.tsx, web/src/components/modals/DeleteEntityModal.tsx
This one has been sitting in the task queue for a while - existing implementation doesn't handle foreign keys for more than a spot fix (meant for users that were created / never used, but should be functional for deleting users in general now)
=> Non-spotfix deletion of users

backend/danswer/server/manage/users.py, web/src/components/admin/users/SignedUpUserTable.tsx, web/src/lib/admin/users/userMutationFetcher.ts
=> Saml account fastapi deletion

web/src/app/admin/assistants/lib.ts, web/src/app/assistants/mine/AssistantsList.tsx
Re-name admin specific route 
- Created ticket to synthesize with other utils - having admin route which does similar logic / naming surrounding assistants likely leaves this error prone
=> Route name

backend/danswer/db/users.py
If a user first logs in via web, then sends a message on Slack (and their slack email is capitalized differently), then they will have two user rows associated with them.
This fixes that.
=> Fix duplicate users from slack / web

.github/workflows/pr-quality-checks.yml, .github/workflows/run-it.yml
- github.head_ref: Works for pull_request events and provides the source branch name of the PR.
- github.event.workflow_run.head_branch: Works for workflows triggered by merge_group events. Branch which initiated the run
- run_id: fallback 
=> Update merge queue logic

backend/danswer/configs/app_configs.py, backend/danswer/redis/redis_pool.py
otherwise, if ssl is enabled it will look for the cert on an empty path and fail.
Fixes DAN-712.
=> ssl_ca_certs should default to None, not "".

.github/workflows/docker-build-push-backend-container-on-tag.yml, .github/workflows/docker-build-push-model-server-container-on-tag.yml, .github/workflows/docker-build-push-web-container-on-tag.yml, .github/workflows/docker-tag-latest.yml, .github/workflows/tag-nightly.yml
Fixes DAN-714.
This will push to latest whenever a git tag is created with "latest" in the name. A nightly tag of the form "nightly-latest-YYYYMMDD" will also ensure a "latest" image is pushed nightly.  This will also skip the behavior of just pushing to latest on any tag whatsoever, which is no longer desirable with our release strategy.
=> push to docker latest when git tag contains "latest", and tag nightly

web/src/app/ee/admin/groups/[groupId]/GroupDisplay.tsx, web/src/components/admin/users/SignedUpUserTable.tsx, web/src/lib/types.ts
=> Minor role display refactor

backend/danswer/configs/app_configs.py, backend/danswer/connectors/danswer_jira/connector.py, backend/tests/unit/danswer/connectors/jira/test_large_ticket_handling.py
Prevents really large tickets from crashing / freezing indexing.
=> Add size limit to jira tickets

backend/ee/danswer/db/user_group.py, backend/tests/integration/tests/permissions/test_whole_curator_flow.py, backend/tests/integration/tests/usergroup/test_user_group_deletion.py
Global Curator status is now check when creating objects
A test for Global Curators was added
=> Global Curator Fix + Testing

web/src/app/admin/configuration/search/UpgradingPage.tsx, web/src/app/admin/configuration/search/page.tsx
Current behavior: show empty screen if switching search settings and no connectors exist
=> Show transition card if no connectors

backend/danswer/background/indexing/run_indexing.py, backend/danswer/indexing/chunker.py, backend/danswer/indexing/embedder.py, backend/danswer/indexing/indexing_heartbeat.py, backend/danswer/indexing/indexing_pipeline.py, backend/danswer/natural_language_processing/search_nlp_models.py, backend/tests/unit/danswer/indexing/conftest.py, backend/tests/unit/danswer/indexing/test_chunker.py, backend/tests/unit/danswer/indexing/test_embedder.py, backend/tests/unit/danswer/indexing/test_heartbeat.py
Prevents really huge documents triggering `Indexing run frozen`. 
Tested with UT + verifying that the heartbeat was triggered.
=> Add heartbeat to indexing

backend/danswer/danswerbot/slack/handlers/handle_regular_answer.py, web/src/app/admin/assistants/PersonaTable.tsx, web/src/app/chat/ChatPage.tsx, web/src/app/chat/modal/SetDefaultModelModal.tsx, web/src/lib/hooks.ts
Fixes https://linear.app/danswer/issue/DAN-736/default-model-improvements https://linear.app/danswer/issue/DAN-738/can-edit-built-in-personas-editing-them-breaks-them
=> add default model + minor fixes

web/src/app/chat/ChatPage.tsx, web/src/app/chat/input/ChatInputBar.tsx, web/src/app/chat/modal/configuration/AssistantsTab.tsx, web/src/components/user/UserProvider.tsx
Fixes https://linear.app/danswer/issue/DAN-742/fix-bug-where-assistant-ordering-doesnt-get-updated-till-you-refresh
=> Clean, memoized assistant ordering

web/src/app/admin/assistants/PersonaTable.tsx
Update a small label to avoid confusing people
=> Add clarity around assistants and names

backend/tests/integration/tests/dev_apis/test_knowledge_chat.py
Fixes DAN-765. flaky knowledge chat test.
=> disable another flaky assert

backend/danswer/background/celery/celery_app.py, backend/danswer/background/connector_deletion.py, backend/danswer/background/indexing/run_indexing.py, backend/danswer/background/update.py, backend/danswer/document_index/interfaces.py, backend/danswer/document_index/vespa/index.py
Improves vespa update performance.
backports some small fixes for issues that were fixed in a larger pending PR 
=> update_single should be optimized for a single call now

backend/danswer/llm/answering/answer.py, backend/tests/regression/answer_quality/run_qa.py, backend/tests/unit/danswer/llm/answering/test_skip_gen_ai.py
the /search/answer-with-quote endpoint has long had a skip_gen_ai_answer_question flag that did not do anything; now it correctly skips only the code portions that query an LLM.
I ran my local version of the backend with `assert False` in the functions in interfaces.py that wrap all LLM invocations. Confirmed that the assertions are hit without my changes and that they are not hit with my changes. The run_qa scripts in backend/tests/regression/answer_quality completes much faster too: 65 seconds to retrieve docs for 664 questions.
Wrote a unit test for the backend's use of the `skip_gen_ai_answer_question` flag; confirmed that LLM `stream()` is called when it is off and not called when it is on.
[If applicable, link to the …
=> disabled llm when skip_gen_ai_answer_question set

web/src/app/admin/embeddings/RerankingFormPage.tsx, web/src/app/admin/embeddings/pages/EmbeddingFormPage.tsx
Fixes https://linear.app/danswer/issue/DAN-756/cant-remove-re-ranker
=> Enable removal of reranking + navigate back to search settings

web/src/components/search/SearchSection.tsx
=> (minor) Update disabling logic

web/src/app/admin/assistants/AssistantEditor.tsx, web/src/app/admin/configuration/search/page.tsx, web/src/app/admin/connectors/[connector]/AddConnectorPage.tsx, web/src/app/admin/embeddings/pages/EmbeddingFormPage.tsx, web/src/app/admin/indexing/status/page.tsx, web/src/components/context/EmbeddingContext.tsx, web/src/components/context/FormContext.tsx, web/src/components/popup/PopupFromQuery.tsx
- Improved back button experience
- Centralized search param popup handling
Fixes https://linear.app/danswer/issue/DAN-757/does-not-take-the-user-back-when-they-click-update-search
=> back button + popups

web/src/app/admin/connectors/[connector]/AddConnectorPage.tsx, web/src/app/chat/message/CodeBlock.tsx, web/src/components/context/EmbeddingContext.tsx, web/src/components/context/FormContext.tsx
=> Inline code + effect clarity

backend/supervisord.conf
=> backport: rely on stdout redirection for supervisord logging (#2711)

web/src/app/admin/connector/[ccPairId]/page.tsx, web/src/app/admin/indexing/status/page.tsx
=> ensure all timeout -> hook

backend/danswer/llm/answering/answer.py
=> Temp patch to remove multiple tool calls

backend/danswer/llm/answering/answer.py
=> Temp patch to remove multiple tool calls (#2720)

backend/Dockerfile, backend/Dockerfile.model_server, backend/tests/integration/Dockerfile, web/Dockerfile
=> Fix all LegacyKeyValueFormat docker warnings

web/src/app/admin/connector/[ccPairId]/IndexingAttemptsTable.tsx
=> Handle bug with initial connector page display

web/src/app/chat/ChatBanner.tsx
Previously, ellipsis at the very edge of being necessary would not quite be caught by our edge detection
Fixes https://linear.app/danswer/issue/DAN-778/banner-width-bug
=> More robust edge detection

backend/danswer/configs/app_configs.py, backend/danswer/configs/model_configs.py, backend/danswer/document_index/vespa/index.py, backend/danswer/indexing/chunker.py, backend/danswer/main.py, backend/model_server/encoders.py, backend/shared_configs/configs.py, deployment/docker_compose/docker-compose.dev.yml, deployment/docker_compose/docker-compose.gpu-dev.yml
=> add vespa + embedding timeout env variables

backend/supervisord.conf
=> backport update indexing and slack bot to use stdout options (#2752)

web/src/app/chat/ChatPage.tsx, web/src/components/BasicClickable.tsx, web/src/components/modals/NoAssistantModal.tsx
=> account for no visible assistants

backend/danswer/background/update.py
=> Fix indexing model server port for warmup

web/src/lib/constants.ts
=> Remove dev update

backend/danswer/connectors/google_drive/connector.py
Previously would fail for .doc, .ppt, or spreadsheets that are over 5MB due to an API limitation.
https://danswer.slack.com/archives/C056265VB1N/p1728895185750569
=> Fix file too large error

backend/danswer/connectors/confluence/rate_limit_handler.py, backend/danswer/connectors/interfaces.py, backend/danswer/connectors/mediawiki/family.py, backend/tests/unit/danswer/connectors/confluence/test_rate_limit_handler.py
Fixes DAN-817.
Longer term this should be pulled into some sort of rate limiting service provided by the base connector class that can coordinate across workers running on multiple machines.  But this is a start.
=> Rate limiting confluence through redis

web/src/app/admin/connector/[ccPairId]/IndexingAttemptsTable.tsx, web/src/app/admin/connector/[ccPairId]/page.tsx
=> fix index attempt refreshing automatically

backend/Dockerfile
Required steps
- Create cert
- Make available
- Run `update-ca-certificates`
Usage
```
--build-arg CA_CERT_CONTENT="$(cat path/to/your/ca.crt)" \
```
=> add ca option

backend/danswer/configs/app_configs.py, web/src/app/chat/message/Messages.tsx, web/src/app/chat/message/codeUtils.ts
=> improved code block copying

backend/danswer/connectors/notion/connector.py
Notion connector exception handling
Issue not reproducible sadly, not sure why empty properties on our own pages don't result in this issue
N/A
N/A
=> Notion Empty Property Fix

backend/danswer/connectors/notion/connector.py
In Notion pages nested in databases, sometimes a property field can be null leading to a NoneType instead of a final value to be extracted
Issue has been replicated and patched
N/A
N/A
=> Notion Recurse Empty Final Field

backend/danswer/db/index_attempt.py
Fixes DAN-826. Or tries to.
This error may be just the tip of the iceberg in terms of transaction failures and we will need to review the code thoroughly.
sqlalchemy.exc.OperationalError: (psycopg2.errors.SerializationFailure) could not serialize access due to read/write dependencies among transactions
DETAIL:  Reason code: Canceled on identification as a pivot, during write.
HINT:  The transaction might succeed if retried.
[SQL: UPDATE index_attempt SET status=%(status)s, error_msg=%(error_msg)s, full_exception_trace=%(full_exception_trace)s, time_updated=now() WHERE index_attempt.id = %(index_attempt_id)s]
[parameters: {'status': 'FAILED', 'error_msg': 'Rate limit exceeded.', 'full_exception_trace': 'Traceback (most recent call last):\n  File …
=> lock to avoid rare serializable errors

backend/danswer/danswerbot/slack/formatting.py, backend/danswer/danswerbot/slack/handlers/handle_regular_answer.py, backend/danswer/danswerbot/slack/utils.py, backend/requirements/default.txt
Refer to https://api.slack.com/reference/surfaces/formatting
Before
After
=> add slack markdown formatting

web/src/app/admin/connectors/[connector]/AddConnectorPage.tsx, web/src/app/admin/connectors/[connector]/pages/DynamicConnectorCreationForm.tsx, web/src/components/admin/connectors/AccessTypeForm.tsx
Changes:
- removed accesstypeform for curators (they can only create private)
- moved advanced options to the bottom of the page for all users
Before:
After:
=> Cleanup connector form

backend/danswer/db/engine.py, web/src/components/chat_search/MinimalMarkdown.tsx
=> (minor) search memoization + context

backend/danswer/connectors/loopio/connector.py
=> loopio connector: entry["id"] can apparently be a number, so convert to str

.github/workflows/pr-backport-autotrigger.yml
=> Backport Test

.github/workflows/pr-backport-autotrigger.yml
=> Backport Auth

web/src/app/admin/connectors/[connector]/Sidebar.tsx, web/src/app/chat/page.tsx, web/src/app/layout.tsx, web/src/components/context/AppProvider.tsx, web/src/components/user/UserProvider.tsx
Standardizing the fetching of user
=> Move user fetching to SS + parallelize some server-side calls

backend/alembic/env.py, backend/danswer/auth/users.py, backend/danswer/background/celery/tasks/indexing/tasks.py, backend/danswer/configs/app_configs.py, backend/danswer/configs/constants.py, backend/danswer/db/engine.py, backend/danswer/db/swap_index.py, backend/danswer/document_index/factory.py, backend/danswer/document_index/vespa/index.py, backend/danswer/key_value_store/store.py, backend/danswer/main.py, backend/danswer/search/preprocessing/preprocessing.py, backend/danswer/server/manage/users.py, backend/danswer/setup.py, backend/danswer/utils/logger.py, backend/ee/danswer/background/celery/apps/primary.py, backend/ee/danswer/main.py, backend/ee/danswer/server/middleware/tenant_tracking.py, backend/ee/danswer/server/tenants/api.py, backend/shared_configs/configs.py
Logs now look like the following in API routes (unchanged for non multi tenant scenario or background/model server)
```
INFO:     10/26/2024 11:04:20 AM                    h11_impl.py  499: ::1:0 - "POST /chat/send-message HTTP/1.1" 200
DEBUG:    10/26/2024 11:04:20 AM                       utils.py  351: [t:f18c51e1] Using model object for gpt-4
INFO:     10/26/2024 11:04:20 AM                       utils.py  367: [t:f18c51e1] Max tokens for gpt-4: 8192 (from max_input_tokens)
DEBUG:    10/26/2024 11:04:21 AM             process_message.py  785: [t:f18c51e1] Reached end of stream
DEBUG:    10/26/2024 11:04:21 AM             process_message.py  851: [t:f18c51e1] Committing messages
INFO:     10/26/2024 11:04:21 AM                      timing.py   76: [t:f18c51e1] stream_chat_message took …
```
=> Feat: add clean logging for api routes

web/src/app/chat/ChatPage.tsx, web/src/app/chat/modal/ShareChatSessionModal.tsx, web/src/app/chat/searchParams.ts
Allows for sharing of current state of a session
- Overridden model
- Message in input bar (if exists, automatically submit on page load)
- Assistant id
https://github.com/user-attachments/assets/5ffd8233-1c6f-4acf-ada7-59708406f483
=> Add cloning of message state

backend/danswer/background/celery/apps/beat.py, backend/danswer/document_index/vespa/index.py, backend/danswer/document_index/vespa/indexing_utils.py, backend/danswer/document_index/vespa_constants.py, backend/danswer/main.py, backend/danswer/seeding/load_docs.py, backend/danswer/setup.py, backend/ee/danswer/server/tenants/api.py
=> tenant seeding docs

backend/danswer/server/features/persona/api.py, backend/danswer/server/features/persona/models.py, web/src/app/admin/assistants/AssistantEditor.tsx, web/src/components/context/AssistantsContext.tsx
Previously, if users had azure enabled but not Azure Dalle via env variable, they could select image generation tool but not use. This fixes that and clean up the assistant provider / unused form functions
=> avoid image generation tool confusion

.github/workflows/docker-build-push-backend-container-on-tag.yml, .github/workflows/pr-backport-autotrigger.yml
=> Trigger from Workflow

backend/danswer/connectors/notion/connector.py
For reasons unknown sometimes a child block can fail to fetch with a 400, nothing we can do.
Cannot be reproduced
Slight risk of loss of data
N/A
=> Notion Child Block Fix

backend/tests/unit/danswer/connectors/mediawiki/test_wiki.py
=> Backport Test 7

backend/danswer/server/manage/models.py, backend/danswer/server/manage/users.py, web/src/components/user/UserProvider.tsx, web/src/lib/types.ts
Track which tenant a user / session replay belongs to (tenant id).
Eventually, this should be organization name rather than tenant id (separate PR)
=> Distinguish users in posthog

web/src/lib/chat/fetchAssistantdata.ts
Improved error handling in `fetchAssistantData` to gracefully handle service outages. System now degrades gracefully instead of failing completely when backend services are unavailable.
=> fail gracefully on provider fetch

backend/danswer/connectors/confluence/connector.py
=> fixed label filter 

backend/danswer/background/celery/tasks/pruning/tasks.py, backend/danswer/utils/logger.py
Fixes DAN-877.
Adds logs of the form
`INFO:     10/29/2024 10:04:51 PM                   connector.py  291: [CC Pair: 2] [Prune: connectorpruning+generator_2_77e92d1e-d68b-46cf-ba44-125b037e0a17] Visiting http://localhost:8889/contact.html`
Could still be improved to be consistent across the task logger as well, but the task logger already has the task id in it and it's going to require some research to figure out what the issues are with that, so this is fine as a quick fix for now.
N/A
N/A
- If there are new environment …
=> add extra tags to pruning logs

web/src/app/chat/RegenerateOption.tsx, web/src/app/chat/message/Messages.tsx
- Enable resubmit same message
- Swap out icon
=> add regeneration clarity

backend/ee/danswer/auth/api_key.py
Helps in the cases that orgs have internal auth systems that also use the `Authorization` header.
https://linear.app/danswer/issue/DAN-882/add-alternative-api-key-header
=> Add alternative auth header

web/src/app/assistants/SidebarWrapper.tsx, web/src/app/chat/ChatPage.tsx, web/src/app/chat/sessionSidebar/ChatSessionDisplay.tsx, web/src/app/chat/shared/[chatId]/SharedChatDisplay.tsx, web/src/app/chat/shared_chat_search/FixedLogo.tsx, web/src/components/BasicClickable.tsx, web/src/components/admin/ClientLayout.tsx, web/src/components/admin/connectors/AdminSidebar.tsx, web/src/components/header/HeaderTitle.tsx, web/src/components/header/LogoType.tsx, web/src/components/search/SearchSection.tsx, web/tailwind-themes/tailwind.config.js
Theming
https://github.com/user-attachments/assets/09aac465-6a09-40af-ae2a-d2ce5f71d84c
=> Minor theming

backend/danswer/connectors/cross_connector_utils/miscellaneous_utils.py, backend/danswer/connectors/gmail/connector.py
fixes both:
Testing it on an instance that is running into this
N/A
N/A
=> Gmail Connector Robustify

backend/danswer/db/engine.py, backend/danswer/server/manage/users.py
=> Proper tenant reset

backend/danswer/configs/app_configs.py, backend/ee/danswer/auth/api_key.py, backend/ee/danswer/db/api_key.py, backend/ee/danswer/server/middleware/tenant_tracking.py
=> Basic multi tenant api key

backend/alembic/versions/5b29123cd710_nullable_search_settings_for_historic_.py, backend/danswer/background/indexing/run_indexing.py, backend/danswer/db/models.py
We should allow users to delete search settings. This fixes a foreign key dependency that would cause any attempts to delete providers to fail (previously unnoticeable because we always persisted the providers).
=> minor foreign key update

backend/alembic/versions/33cb72ea4d80_single_tool_call_per_message.py, backend/danswer/chat/process_message.py, backend/danswer/db/chat.py, backend/danswer/db/models.py, backend/danswer/file_store/utils.py, backend/danswer/llm/answering/models.py, backend/danswer/llm/chat_llm.py, backend/danswer/server/query_and_chat/models.py, web/src/app/chat/ChatPage.tsx, web/src/app/chat/interfaces.ts, web/src/app/chat/lib.tsx, web/src/app/chat/message/Messages.tsx
One tool call per message
First in a sequence of changes
=> Tool call per message

backend/danswer/connectors/google_drive/connector.py, backend/danswer/connectors/google_drive/connector_auth.py, backend/danswer/connectors/google_drive/doc_conversion.py, backend/danswer/connectors/google_drive/google_utils.py, backend/danswer/connectors/google_drive/resources.py, backend/danswer/connectors/google_drive/section_extraction.py, backend/ee/danswer/external_permissions/google_drive/doc_sync.py, backend/ee/danswer/external_permissions/google_drive/group_sync.py, backend/tests/daily/connectors/google_drive/conftest.py, backend/tests/daily/connectors/google_drive/helpers.py, backend/tests/daily/connectors/google_drive/test_google_drive_oauth.py, backend/tests/daily/connectors/google_drive/test_google_drive_sections.py, backend/tests/daily/connectors/google_drive/test_google_drive_service_acct.py, backend/tests/daily/connectors/google_drive/test_google_drive_slim_docs.py
Adds links to each header in a google doc.
=> Add drive sections

backend/danswer/background/celery/tasks/indexing/tasks.py
=> add sentry to spawned indexing task

deployment/docker_compose/docker-compose.dev.yml, deployment/docker_compose/docker-compose.prod.yml, deployment/kubernetes/background-deployment.yaml
=> Certificate improvements

backend/danswer/db/engine.py, backend/danswer/db/search_settings.py, backend/danswer/tools/tool_implementations/custom/custom_tool.py
https://peps.python.org/pep-0661/
Distinguish `None` and no arg passed (which should maintain the previous context)
=> Evaluate None to default

backend/danswer/danswerbot/slack/listener.py
=> adjust default postgres schema for slack listener

backend/alembic/versions/b72ed7a5db0e_remove_description_from_starter_messages.py
Existing upgrade will work for anybody with well formatted json arrays as starter messages. 
This PR accounts for the case where users have modified their starter messages or they no longer properly represent the format we expect.
N/A
N/A
- Author has done a final read through of the PR right …
=> Account for malformatted starter messages

.github/workflows/pr-Integration-tests.yml
=> fix saving docker logs

backend/danswer/db/engine.py, backend/danswer/natural_language_processing/utils.py, backend/danswer/server/manage/embedding/api.py, web/src/app/admin/embeddings/modals/ChangeCredentialsModal.tsx, web/src/app/admin/embeddings/modals/ProviderCreationModal.tsx, web/src/app/admin/embeddings/pages/utils.ts
Reenable OpenAI Tokenizer
This is used for
- Processing messages / text content for GPT models
- Embeddings (specifically defined in the `EmbeddingModel` init)
References:
1. [OpenAI Cookbook](https://cookbook.openai.com/examples/how_to_count_tokens_with_tiktoken)
2. [LiteLLM tokenizing](https://github.com/BerriAI/litellm/blob/81d265b0f04948d2084b70809387150015cf4123/litellm/utils.py) 
3. [Previous branch
](https://github.com/danswer-ai/danswer/blob/6177795711821dbc1815b04c8e895233ee6e7fbb/backend/danswer/natural_language_processing/utils.py)
N/A
This tokenizer has caused issues before but it is significantly different from the other one we use which leads to problems at embedding time.
N/A
- If there …
=> Reenable OpenAI Tokenizer

.github/workflows/docker-build-push-backend-container-on-tag.yml, .github/workflows/docker-build-push-cloud-web-container-on-tag.yml, .github/workflows/docker-build-push-model-server-container-on-tag.yml, backend/danswer/background/celery/apps/app_base.py, backend/danswer/background/celery/apps/beat.py, backend/danswer/background/celery/apps/heavy.py, backend/danswer/background/celery/apps/indexing.py, backend/danswer/background/celery/apps/light.py, backend/danswer/background/celery/apps/primary.py, deployment/cloud_kubernetes/keda/celery-worker-auth.yaml, deployment/cloud_kubernetes/keda/celery-worker-indexing-scaledobject.yaml, deployment/cloud_kubernetes/keda/celery-worker-light-scaledobject.yaml, deployment/cloud_kubernetes/keda/celery-worker-primary-scaledobject.yaml, deployment/cloud_kubernetes/keda/keda-redis-secret.yaml, deployment/cloud_kubernetes/workers/beat.yaml, deployment/cloud_kubernetes/workers/heavy_worker.yaml, deployment/cloud_kubernetes/workers/indexing_worker.yaml, deployment/cloud_kubernetes/workers/light_worker.yaml, deployment/cloud_kubernetes/workers/primary.yaml
- Ensure cloud tags point to private Dockerhub images to prevent confusion for open source users
- Initial KEDA configurations (limits are set very conservatively, but I am actively iterating on them- best to simply get the base configuration in the repo for maintainability)
=> Robustify cloud deployment + include initial KEDA configuration

backend/danswer/auth/users.py, backend/danswer/utils/variable_functionality.py
Should clean up the usage of async fallbacks / make this functionality clearer generally.
Tested with various tenancy-specific flows
N/A
N/A
Note: You have to check that the action passes, otherwise resolve the conflicts …
=> Cleaner EE fallback for no op

web/src/app/admin/connector/[ccPairId]/page.tsx, web/src/app/admin/indexing/status/CCPairIndexingStatusTable.tsx, web/src/app/admin/users/page.tsx, web/src/components/admin/ClientLayout.tsx, web/src/components/ui/button.tsx
- Remove left-over border from indexing page
- Ensure tooltips don't cause scrollable on x axis in connector page (or any page)
- Center "Invite Users"
- Submit text color -> white
=> moderate component fixes

backend/danswer/auth/users.py, backend/danswer/main.py, backend/ee/danswer/main.py, backend/ee/danswer/server/tenants/models.py, backend/ee/danswer/server/tenants/provisioning.py, backend/tests/integration/common_utils/managers/tenant.py, backend/tests/integration/multitenant_tests/syncing/test_search_permissions.py, backend/tests/integration/multitenant_tests/tenants/test_tenant_creation.py, web/src/app/admin/indexing/status/CCPairIndexingStatusTable.tsx, web/src/app/admin/users/page.tsx, web/src/app/auth/login/EmailPasswordForm.tsx, web/src/app/auth/login/SignInButton.tsx, web/src/app/auth/signup/ReferralSourceSelector.tsx, web/src/app/auth/signup/page.tsx, web/src/components/admin/ClientLayout.tsx, web/src/lib/user.ts, web/src/lib/userSS.ts
Add referral source for both cloud flow (create / auth callback)
- Create: pass to the user manager function request
- Oauth callback: use state param + headers (similar to next URL)
Tested with Google/basic auth with and without EE.
N/A
N/A
- Author has done a final read through of the PR right …
=> Add referral source to cloud on data plane

backend/danswer/natural_language_processing/utils.py
=> Improved tokenizer fallback

backend/alembic/versions/dfbe9e93d3c7_extended_role_for_non_web.py, backend/danswer/auth/schemas.py, backend/danswer/auth/users.py, backend/danswer/background/celery/tasks/doc_permission_syncing/tasks.py, backend/danswer/danswerbot/slack/handlers/handle_message.py, backend/danswer/db/auth.py, backend/danswer/db/models.py, backend/danswer/db/users.py, backend/danswer/server/manage/users.py, backend/ee/danswer/db/external_perm.py, backend/ee/danswer/server/saml.py, web/src/components/admin/users/SignedUpUserTable.tsx, web/src/lib/types.ts
Externally permissioned users no longer show up in the billing/admin panel. 
Slack users now show up distincly
https://github.com/user-attachments/assets/e71572ef-ebb2-474a-98c7-1447328adb80
Note: You have to check that the action passes, otherwise resolve the conflicts manually …
=> Made external permissioned users and slack users show diff

backend/danswer/background/celery/tasks/pruning/tasks.py, backend/danswer/redis/redis_connector_prune.py
=> improve logging around pruning

web/src/components/admin/connectors/Field.tsx, web/src/components/llm/LLMList.tsx
Adds default max height
https://github.com/user-attachments/assets/cbdb8f75-b790-4d69-b66c-57fc6e258f9d
N/A
N/A
=> ensure everything has a default max height in selector form field

.github/workflows/docker-build-push-cloud-web-container-on-tag.yml, web/src/app/layout.tsx, web/src/lib/constants.ts
Adds Google Tag manager to cloud builds
N/A
N/A
=> Add Google Tag Manager for Web Cloud Build

backend/danswer/connectors/confluence/connector.py, backend/danswer/connectors/confluence/onyx_confluence.py, backend/danswer/connectors/confluence/utils.py, backend/ee/danswer/external_permissions/confluence/group_sync.py
- we now log all calls
- links and page within pages are now captured separately 
- we deal with problematic retrievals
- we now track all pages fetched recursively to prevent infinite loops
- iterables now yield one at a time for cleaner code
- confluence client is now a property
=> added logging and bugfixing to conf

web/src/app/chat/folders/FolderList.tsx, web/src/app/chat/sessionSidebar/ChatSessionDisplay.tsx, web/src/app/chat/sessionSidebar/PagesTab.tsx
https://linear.app/danswer/issue/DAN-1018/folders-ui-weirdness
- Let users share / delete chats within folder
- Clearer copy (chats aren't deleted if folder is)
- Persist the delete popup for chats even if cursor is not hovering folder
https://github.com/user-attachments/assets/8c034b04-98b8-4a94-9d36-48b4e6549137
N/A
N/A
- Docker images build and …
=> Folder clarity

backend/ee/danswer/db/user_group.py
admins cant be set  as curator on backend
=> admins cant be set  as curator on backend

backend/danswer/background/celery/tasks/external_group_syncing/tasks.py, backend/danswer/connectors/confluence/connector.py, backend/danswer/connectors/confluence/onyx_confluence.py, backend/danswer/connectors/confluence/utils.py, backend/ee/danswer/external_permissions/confluence/group_sync.py, backend/ee/danswer/external_permissions/sync_params.py
=> replace deprecated confluence group api endpoint

backend/danswer/background/celery/apps/primary.py, backend/danswer/background/celery/tasks/indexing/tasks.py, backend/danswer/background/celery/tasks/vespa/tasks.py, backend/danswer/db/index_attempt.py, web/tests/e2e/admin_performance_query_history.spec.ts, web/tests/e2e/admin_performance_usage.spec.ts
…attern for all indexing error checks
Fixes DAN-961. (Hopefully)
N/A
N/A
=> implement double check pattern for error conditions

web/src/app/chat/ChatPage.tsx, web/src/lib/hooks.ts
=> llm provider causing re render in effect

backend/ee/danswer/server/query_history/api.py, backend/tests/integration/common_utils/managers/chat.py, backend/tests/integration/common_utils/test_models.py, backend/tests/integration/tests/query-history/test_query_history.py
=> Add start/end date ability for query history as CSV endpoint

backend/danswer/indexing/chunker.py, backend/danswer/natural_language_processing/search_nlp_models.py, backend/danswer/utils/text_processing.py
section texts are now scrubbed for all llm providers during indexing.
=> Each section is now cleaned before being chunked

backend/danswer/connectors/confluence/connector.py
=> Increased slim doc batch size for confluence connector

backend/danswer/configs/chat_configs.py, backend/danswer/llm/answering/prompts/quotes_prompt.py, backend/danswer/one_shot_answer/models.py, backend/danswer/prompts/direct_qa_prompts.py, backend/danswer/secondary_llm_flows/query_validation.py, backend/danswer/server/query_and_chat/models.py, backend/danswer/server/query_and_chat/query_backend.py
=> Remove Dead Code

backend/danswer/configs/app_configs.py, backend/danswer/llm/answering/stream_processing/answer_response_handler.py, backend/danswer/llm/interfaces.py, deployment/docker_compose/docker-compose.dev.yml
Add option to log individual tokens. Needed for tracking why some citations fail to process
Ran app
N/A
N/A
=> Token Level Log

backend/danswer/llm/answering/answer.py, backend/danswer/llm/answering/prompts/build.py, backend/danswer/llm/answering/tool/tool_response_handler.py, backend/danswer/tools/tool_implementations/search_like_tool_utils.py
Non Function Call LLMs need to not have the task prompt when determining whether or not to use the tool. This is because the "tool call decision" is a separate call and this would otherwise just introduce noise (and UI ugliness).
Tested tool-call and non-tool-call LLMs
N/A
N/A …
=> Fix Prompt for Non Function Calling LLMs

backend/danswer/auth/users.py, backend/danswer/db/api_key.py, backend/ee/danswer/auth/users.py, backend/ee/danswer/db/saml.py, backend/ee/danswer/server/saml.py
Previously, the logic to actually check for an API key was in the EE version of `optional_user_`. This meant that for MIT users, the API keys would never work.
Additionally, in this PR I switched to use an async engine. Due to FastAPI Users, this flow must be async, and it's generally good practice to use async engines during async flows to avoid mistakenly blocking the event loop.
=> Fix API keys for MIT users

backend/danswer/db/persona.py, backend/danswer/server/features/persona/api.py, backend/danswer/server/manage/users.py, web/src/app/admin/assistants/AssistantEditor.tsx, web/src/app/admin/assistants/lib.ts, web/src/app/assistants/gallery/AssistantsGallery.tsx, web/src/app/assistants/mine/AssistantsList.tsx, web/src/lib/assistants/fetchPersonaEditorInfoSS.ts
=> Assistant cleanup

web/src/app/admin/connectors/[connector]/AddConnectorPage.tsx, web/src/app/admin/connectors/[connector]/pages/ConnectorInput/FileInput.tsx, web/src/app/admin/connectors/[connector]/pages/DynamicConnectorCreationForm.tsx, web/src/app/admin/connectors/[connector]/pages/FieldRendering.tsx, web/src/app/admin/connectors/[connector]/pages/utils/files.ts, web/src/components/admin/connectors/FileUpload.tsx, web/src/lib/connectors/connectors.tsx
=> File handling cleanup

backend/danswer/background/celery/apps/primary.py, backend/danswer/background/celery/tasks/indexing/tasks.py, backend/danswer/db/enums.py, backend/danswer/db/index_attempt.py, web/src/app/admin/configuration/search/UpgradingPage.tsx, web/src/app/admin/connector/[ccPairId]/IndexingAttemptsTable.tsx, web/src/components/Status.tsx, web/src/components/ui/badge.tsx, web/src/lib/types.ts
Fixes DAN-1046.
This adds a new greyed out "canceled" status to index attempts in the UI and changes the messaging slightly to be about leftover index attempts.
N/A
N/A
Note: You have to check that the action passes, otherwise …
=> improve messaging and UI around cleanup of leftover index attempts

backend/danswer/db/users.py, backend/ee/danswer/external_permissions/confluence/doc_sync.py
- better logging
- emails are now lowercased before comparison
=> Improved logging for confluence doc sync and robust user creation

web/src/app/admin/assistants/AssistantEditor.tsx, web/src/app/admin/assistants/PersonaTable.tsx
Generally speaking, we should treat router.refresh() as an antipattern (unless we truly want to re-render the entire page). Instead, we should prefer using context provider refreshes for more localized (and reliable) state updates.
Fixes https://linear.app/danswer/issue/DAN-1047/assistant-visibility-doesnt-refresh-the-page 
N/A
N/A
- Docker images …
=> refresh router -> refresh assistants

backend/danswer/background/celery/tasks/external_group_syncing/tasks.py, backend/danswer/natural_language_processing/exceptions.py, backend/danswer/natural_language_processing/search_nlp_models.py, backend/model_server/encoders.py, backend/tests/daily/embedding/test_embeddings.py
Graceful handling for rate limited embedding. Only applies at background-embedding time, since we don't want to have a user wait forever (it should just immediately fail).
=> Add handling for rate limiting

web/src/app/chat/modal/FeedbackModal.tsx
If the env vars `NEXT_PUBLIC_POSITIVE_PREDEFINED_FEEDBACK_OPTIONS` and `NEXT_PUBLIC_NEGATIVE_PREDEFINED_FEEDBACK_OPTIONS` do not exist, their values are `""` by default. 
Because `""?.split(",")` evaluates to `[""]` which is truthy, this breaks the default list of negative/positive feedback options, causing an empty button to appear in the feedback modal.
My fix checks the truthiness of the variables before splitting or assigning default values, which accounts for the above case and the existing case when the var is null/undefined.
Docker compose dev
N/A
N/A
- If there are …
=> Fix default feedback options appearing incorrectly

backend/danswer/configs/model_configs.py, backend/danswer/llm/chat_llm.py, backend/danswer/llm/factory.py, backend/danswer/llm/utils.py, backend/requirements/default.txt
A few fixes:
(1) Ollama previously used a default context size of 2048. Upping that a bit.
(2) The older version of LiteLLM had a bug which made ollama + danswer error out intermittently. Fixed by upgrading (required some small changes to chat_llm accommodate for small behavior changes).
=> Improve model token limit detection

backend/danswer/llm/answering/stream_processing/citation_processing.py, backend/tests/unit/danswer/llm/answering/stream_processing/test_citation_processing.py
- Citations where the LLM produces double brackets do not work, for example [[, 4, ]]
- Citations that have some characters in the token after the end of the citation, for example [, 1, ].
Unit tests haven't broken and a new test was added to cover these two cases
That code is complicated and brittle, hopefully no new bugs
N/A
- Author has done a …
=> Fix Citation Minor Bugs

web/src/app/auth/login/EmailPasswordForm.tsx, web/src/components/context/AppProvider.tsx
=> hard refresh on auth

backend/danswer/llm/factory.py, web/src/app/admin/configuration/llm/interfaces.ts, web/src/app/chat/ChatPage.tsx, web/src/app/chat/RegenerateOption.tsx, web/src/app/chat/modal/configuration/LlmTab.tsx, web/src/components/chat_search/AssistantSelector.tsx, web/src/components/llm/LLMList.tsx, web/src/lib/hooks.ts
- Pass temperature to custom models (specifically when retrieving default persona's LLM)
- Cleaner llm override temperature management
- Remove unnecessary effects
- Restrict Anthropic range to 0-1.0
N/A
N/A
Note: You have to …
=> Temperature

backend/danswer/db/persona.py
=> Add comments for clarity

web/src/components/context/AssistantsContext.tsx, web/src/lib/assistants/utils.ts, web/src/lib/chat/fetchAssistantdata.ts
Fixes https://linear.app/danswer/issue/DAN-1042/assistant-gallery-my-assistants-is-inconsistent
N/A
N/A
=> Shared filter utility for clarity

backend/danswer/background/celery/apps/primary.py, backend/danswer/background/celery/tasks/indexing/tasks.py, backend/danswer/background/celery/tasks/pruning/tasks.py
Fixes DAN-1073. disable thread_local when we aren't using the lock end to end in a single call (in callbacks for example)
N/A
N/A
Note: You have to check that the action passes, otherwise resolve the conflicts manually and tag …
=> disable thread local locking in callbacks

backend/danswer/access/models.py, backend/danswer/background/celery/tasks/doc_permission_syncing/tasks.py, backend/danswer/background/celery/tasks/external_group_syncing/tasks.py, backend/danswer/connectors/confluence/utils.py, backend/danswer/redis/redis_connector_doc_perm_sync.py, backend/ee/danswer/db/connector_credential_pair.py, backend/ee/danswer/db/document.py, backend/ee/danswer/external_permissions/sync_params.py, backend/scripts/orphan_doc_cleanup_script.py
- relates permission only docs to cc_pair
- adds script to cleanup orphan docs
=> Related permission docs to cc_pair to prevent orphan docs

backend/danswer/document_index/vespa/app_config/schemas/danswer_chunk.sd
- https://docs.vespa.ai/en/attributes.html
- Significantly improves chunk retrieval speed  (`get_all_vespa_ids_for_document_id`)
N/A
N/A
Note: You have to check that the action passes, otherwise resolve the conflicts manually …
=> Ensure we can quickly filter by doc id

backend/danswer/server/manage/users.py
Fix https://linear.app/danswer/issue/DAN-1078/re-sending-invite-email-to-existing-users-when-adding-new-users-to-the
N/A
N/A
Note: You have to check that the action passes, otherwise resolve the conflicts manually and tag the …
=> update email invites

backend/danswer/background/celery/tasks/external_group_syncing/tasks.py, backend/ee/danswer/db/analytics.py, backend/ee/danswer/server/analytics/api.py, web/src/app/ee/admin/performance/lib.ts, web/src/app/ee/admin/performance/usage/PersonaMessagesChart.tsx, web/src/app/ee/admin/performance/usage/page.tsx
=> Add persona stats

backend/danswer/connectors/confluence/connector.py, backend/danswer/connectors/confluence/utils.py, backend/ee/danswer/external_permissions/confluence/doc_sync.py, backend/tests/daily/connectors/confluence/test_confluence_permissions_basic.py
- Added filetype filter to slim connector attachments
- Added logging for space permissions
=> Added filter to slim connector and logging for space permissions

backend/shared_configs/configs.py
^
With notice, it doesn't even show the API calls going through the API server.
=> Change default log level back to info

backend/danswer/auth/users.py, backend/danswer/configs/app_configs.py
"external" users when trying to create accounts in the web UI get redirected to a page waiting on email verification if the deployment is using SAML (and possibly other auth methods).
This has not been reproduced but the logic for email verification seems wrong and should prevent this.
N/A
N/A
- Author has done a final read through of the PR …
=> Fix Email Verification for external IdPs

backend/danswer/connectors/confluence/onyx_confluence.py
=> Fix Confluence perm sync for cloud users

backend/danswer/llm/chat_llm.py, web/src/app/admin/configuration/llm/CustomLLMProviderUpdateForm.tsx
Adds support for specifying the service account JSON directly via the UI.
Also cleans up the form a bit (previously the custom configs only took up ~1/4 of the width and the buttons had no spacing):
=> Add better vertex support + LLM form cleanup

backend/danswer/danswerbot/slack/utils.py
=> Temp slackbot url error Fix

backend/requirements/default.txt, backend/requirements/model_server.txt
=> Bump litellm to support Nova models from AWS

backend/danswer/danswerbot/slack/handlers/handle_regular_answer.py
/danswerbot command now responds privately to the user
tested by asking a /danswerbot question and ensuring only the asker could see the response by looking at the chat with another account
also tested the normal qa flow to make sure that was unaffected
also checkted @danswerbot flow to make sure that was unaffected
=> fixed ephemeral slackbot messages

backend/danswer/connectors/slack/connector.py, backend/danswer/danswerbot/slack/blocks.py, backend/danswer/danswerbot/slack/utils.py
Fixes https://linear.app/danswer/issue/DAN-1119/citations-are-not-clickable-on-slack-a-large-chunk-of-the-time
Semantic ID for slack connector could contain newlines which caused issues for Slackbot formatting
Before and After
N/A
N/A
- Author has done a final read through of the PR right before …
=> strip text for slackbot

backend/ee/danswer/db/external_perm.py
- This fixes an issue where when we create a user in the db, the email is converted to lowercase but we still use the upercase one to match
=> made external group emails lowercase

web/src/app/chat/modal/SetDefaultModelModal.tsx
The escape key was closing the user dropdown rather than the modal on top
Verified locally
N/A
N/A
=> Allow user to close out of User Setting modal with escape

backend/danswer/server/documents/standard_oauth.py, deployment/docker_compose/docker-compose.dev.yml
The base_url is non https:// for some reason on our cloud (likely due to loadbalancer)
=> Small tweaks to get Egynte to work on our cloud

web/src/app/chat/ChatBanner.tsx, web/src/app/chat/ChatPage.tsx, web/src/app/chat/documentSidebar/ChatFilters.tsx, web/src/app/chat/sessionSidebar/HistorySidebar.tsx, web/src/app/chat/shared_chat_search/FixedLogo.tsx, web/src/components/admin/ClientLayout.tsx, web/src/components/admin/connectors/AdminSidebar.tsx, web/src/components/chat_search/AssistantSelector.tsx, web/src/components/chat_search/Header.tsx, web/src/components/header/LogoType.tsx
Fixes https://linear.app/danswer/issue/DAN-1157/make-it-so-the-danswer-doesnt-change-position-when-switching-between
Fixes https://linear.app/danswer/issue/DAN-1121/button-layout-is-ugly-here
N/A
N/A
Note: You have to check that …
=> Various clean ups

backend/danswer/llm/utils.py, web/src/app/chat/ChatPage.tsx, web/src/app/chat/types.ts, web/src/components/tools/CSVContent.tsx, web/src/components/tools/ExpandableContentWrapper.tsx
Fixes https://linear.app/danswer/issue/DAN-1017/csv-upload-no-error-message
Additional "uploading" chat state
N/A
N/A
=> clean up csv prompt + frontend

backend/danswer/chat/answer.py, backend/danswer/chat/process_message.py, backend/danswer/chat/stream_processing/answer_response_handler.py, backend/danswer/chat/stream_processing/citation_processing.py, backend/danswer/tools/tool_implementations/search/search_tool.py, backend/danswer/tools/tool_implementations/search_like_tool_utils.py, backend/tests/unit/danswer/chat/stream_processing/test_citation_processing.py, backend/tests/unit/danswer/chat/stream_processing/test_citation_substitution.py
When document order presented to LLM differs from order shown to user, wrong doc numbers are cited.
Fix:
- SearchTool.get_search_result  returns now final and initial ranking
- initial ranking is passed through a few objects and used for replacement in citation processing
Notes:
- the citation_num in the CitationInfo() object has not been changed.
N/A
N/A
- If there are new APIs …
=> Mismatch issue of Documents shown and Citation number in text fix

backend/danswer/setup.py, web/src/app/chat/message/MemoizedTextComponents.tsx, web/src/components/search/DocumentDisplay.tsx, web/src/components/search/results/Citation.tsx
- Fixes https://linear.app/danswer/issue/DAN-1130/bad-citation-cards
- Fixes https://linear.app/danswer/issue/DAN-1125/citation-cards-unclickable-anywhere-only-the-bubble-is
https://github.com/user-attachments/assets/6ca873e7-5201-4b31-9106-0e8b6bfec6b1
N/A
N/A
- Author has done a final read …
=> Clean citation cards

backend/danswer/connectors/egnyte/connector.py, backend/danswer/connectors/interfaces.py, backend/danswer/server/documents/standard_oauth.py
=> Fixes issue on cloud with Egnyte redirect URI during token fetching

backend/danswer/connectors/web/connector.py
Fixes https://linear.app/danswer/issue/DAN-1182/ssrf-leads-to-partial-local-file-read-open
N/A
N/A
=> Prevent SSRF risk

backend/alembic/versions/94dc3d0236f8_make_document_set_description_optional.py, backend/danswer/db/models.py, backend/danswer/server/features/document_set/models.py, web/src/app/admin/documents/sets/DocumentSetCreationForm.tsx
Fixes https://linear.app/danswer/issue/DAN-1128/adding-doc-set-or-persona-with-doc-set-breaks-slackbot
Tested by creating a doc set with no description
=> made description optional for document sets

web/src/components/admin/connectors/Field.tsx, web/src/components/modals/EditPropertyModal.tsx
Need a bit more handling around spacing
Previous
Update
N/A
N/A
=> Labels nit

backend/onyx/server/manage/users.py, web/src/components/Modal.tsx, web/tests/e2e/chromaticSnpashots.json
- Detect modal closure using overlay, not !(element click)
- Properly count pages in pagination
Fixes https://linear.app/danswer/issue/DAN-1194/user-pagination-overcounts-users
Fixes https://linear.app/danswer/issue/DAN-1192/user-group-adding-user-breaks-modals
- Various numbers of invited users
- Various modal + dropdown configurations
N/A
N/A
- …
=> Improved invited users

backend/onyx/setup.py
=> Reenable Seeding

backend/alembic/versions/91a0a4d62b14_milestone.py, backend/ee/onyx/configs/app_configs.py, backend/ee/onyx/server/tenants/provisioning.py, backend/ee/onyx/utils/telemetry.py, backend/onyx/auth/noauth_user.py, backend/onyx/auth/users.py, backend/onyx/background/indexing/run_indexing.py, backend/onyx/chat/process_message.py, backend/onyx/configs/constants.py, backend/onyx/db/milestone.py, backend/onyx/db/models.py, backend/onyx/server/documents/connector.py, backend/onyx/server/features/persona/api.py, backend/onyx/server/manage/slack_bot.py, backend/onyx/server/query_and_chat/chat_backend.py, backend/onyx/utils/telemetry.py, backend/requirements/dev.txt, backend/requirements/ee.txt, backend/scripts/restart_containers.sh
Add monitoring for certain milestones from different tenants on the MT cloud.
Tested against a different Posthog instance.
N/A
N/A
=> MT Cloud Monitoring

backend/onyx/auth/users.py, backend/onyx/configs/constants.py, backend/onyx/main.py, backend/tests/integration/common_utils/managers/user.py, web/src/app/auth/login/EmailPasswordForm.tsx, web/tests/e2e/constants.js
Fixes https://linear.app/danswer/issue/DAN-1184/login-bruteforce
- Log in with weak password
- Upgrade to these stricter password requirements 
- Verify can still log in with weak password
- Try to create an account with same weak password
- See error for various new password requirements
N/A
N/A
- Author has done a final read through of the PR …
=> Increase password requirements

backend/onyx/db/chat.py
Fixes https://linear.app/danswer/issue/DAN-1167/slackbot-threads-showing-in-chat-display
N/A
N/A
=> do not include slackbot sessions when fetching `chat sessions`

.pre-commit-config.yaml
Necessary to merge this in before we update
N/A
N/A
=> update pre-commit black version

backend/onyx/background/celery/apps/app_base.py, backend/onyx/background/celery/apps/beat.py, backend/onyx/background/celery/tasks/connector_deletion/tasks.py, backend/onyx/background/celery/tasks/indexing/tasks.py, backend/onyx/background/celery/tasks/pruning/tasks.py, backend/onyx/background/celery/tasks/shared/tasks.py, backend/onyx/background/celery/tasks/vespa/tasks.py
Sets our context var on the start of a task and resets at the end. Task logger uses this to print the tenant id from within tasks without exposing confusing terminology to open source users
=> remove tenant id logs

backend/onyx/chat/stream_processing/citation_processing.py, backend/tests/unit/onyx/chat/stream_processing/test_citation_processing.py
=> fix single quote block in llm answer

web/src/app/chat/ChatPage.tsx, web/src/app/chat/RegenerateOption.tsx, web/src/app/chat/modal/configuration/LlmTab.tsx, web/src/components/chat_search/AssistantSelector.tsx, web/src/lib/hooks.ts
Fixes case where user default model no longer exists
- Create user Default
- Delete provider
- Verify chat not broken
- Re-create provider
N/A
N/A
=> Update llm override defaults

web/src/app/admin/connectors/[connector]/Sidebar.tsx, web/src/app/chat/message/Messages.tsx, web/src/app/chat/shared_chat_search/FixedLogo.tsx, web/src/components/UserDropdown.tsx, web/src/components/assistants/AssistantBanner.tsx, web/src/components/header/LogoType.tsx, web/src/components/search/filtering/Filters.tsx, web/src/components/search/filtering/TagFilter.tsx, web/src/components/ui/calendar.tsx, web/tailwind-themes/tailwind.config.js
=> Improved theming

backend/onyx/db/persona.py, backend/onyx/seeding/load_yamls.py, web/src/lib/assistants/utils.ts
- Default assistant created in alembic migrations has `null` display priority and would not be overridden by yaml loading
- Display priority needs to update for existing assistants (if we decide to migrate
N/A
N/A
Note: You have …
=> Proper display priority seeding

backend/ee/onyx/configs/app_configs.py, backend/ee/onyx/server/tenants/provisioning.py, backend/onyx/auth/users.py
Update Hubspot tracking for the cloud.
- Send request to Hubspot form with user information (+ referral source)
Relevant docs: https://developers.hubspot.com/beta-docs/reference/api/marketing/forms/v3-legacy#submit-data-to-a-form
N/A
N/A
- Author has done a final read through of the PR right …
=> Update Hubpost tracking form submission

backend/model_server/main.py
Remove hardcoded root path for HF models, using user home dir instead
Model server started and correctly loaded models
```
NOTICE:   12/13/2024 08:27:53 PM               custom_models.py   99: Loaded model from local cache: /home/egomes/.cache/huggingface/hub/models--danswer--hybrid-intent-token-classifier/snapshots/54ed7e946f84a252c5d4e5d7a0bc839f466e9c64
```
N/A
N/A
=> Remove hardcoded root path for HF models

backend/alembic/versions/35e518e0ddf4_properly_cascade.py, backend/onyx/db/chat.py, backend/onyx/db/models.py, backend/onyx/server/query_and_chat/chat_backend.py, backend/onyx/server/query_and_chat/models.py, web/src/app/chat/ChatPage.tsx, web/src/app/chat/input/ChatInputBar.tsx, web/src/app/chat/lib.tsx, web/src/app/chat/sessionSidebar/HistorySidebar.tsx, web/src/app/chat/sessionSidebar/PagesTab.tsx, web/src/components/modals/DeleteEntityModal.tsx, web/src/lib/constants.ts
Enable client side when NEXT_PUBLIC_DELETE_ALL_CHATS_ENABLED is set
Fixes https://linear.app/danswer/issue/DAN-658/delete-all-chats-option
=> Add delete all chats option

backend/alembic/versions/c0aab6edb6dd_delete_workspace.py
Get old migration in + update slack bot downgrade to account for all credential associations
- Create various connectors on this version
- Downgrade to `748b79b0ef20ca7d25a208b9cff714e8f6ef8cf1` and verify both connectors work (with worksapce)
- Upgrade and ensure both connectors still work
Make sure to restart background processes!
N/A
N/A
- …
=> Old alembic migration + restore workspace

web/src/app/chat/documentSidebar/ChatDocumentDisplay.tsx, web/src/components/chat_search/sources/SourceCard.tsx, web/src/components/search/DocumentDisplay.tsx, web/src/components/search/results/Citation.tsx, web/src/lib/search/utils.ts
We need to ensure the metadata tags we support override the new `file preview` functionality  (https://github.com/onyx-dot-app/onyx/pull/3113)
- Metadata docs:`https://docs.onyx.app/connectors/file#adding-metadata`
- Various web sources, various .txt files with links, and various .txt files without links
N/A
N/A
- Author has done a final read …
=> Ensure metadata overrides file contents

backend/onyx/configs/constants.py, backend/onyx/db/connector_credential_pair.py, backend/onyx/server/documents/cc_pair.py, backend/onyx/server/onyx_api/ingestion.py
The ingestion endpoint assumes the default cc pair to attach the new documents to is 0. This seems to no longer be the case. The default one which is created on server startup or tenant creation has id 1 but ingestion endpoint assumes 0. Probably something changes at some point so that it's no longer created as 0
Only verified that the ingestion endpoint works now and that things start
N/A
N/A
- …
=> Fix Default CC Pair

backend/.webui_secret_key, backend/onyx/server/query_and_chat/chat_backend.py, backend/onyx/server/query_and_chat/models.py, web/src/app/chat/ChatPage.tsx, web/src/app/chat/documentSidebar/ChatDocumentDisplay.tsx, web/src/app/chat/documentSidebar/ChatFilters.tsx, web/src/app/chat/interfaces.ts, web/src/app/chat/message/MemoizedTextComponents.tsx, web/src/app/chat/message/Messages.tsx, web/src/app/chat/message/SearchSummary.tsx, web/src/app/chat/modal/ShareChatSessionModal.tsx, web/src/app/chat/shared/[chatId]/SharedChatDisplay.tsx, web/src/app/chat/shared/[chatId]/page.tsx, web/src/components/MetadataBadge.tsx, web/src/components/UserDropdown.tsx, web/src/components/assistants/AssistantIcon.tsx, web/src/components/chat_search/Header.tsx, web/src/lib/assistantIconUtils.tsx
- Pass documents to `AI Message` component in shared chat display
- Update props to be stricter for AI Message
On mobile, desktop:
- Create shared chat 
- View doc results
- Hover citations
N/A
N/A
Note: You have to check that the action passes, otherwise resolve the conflicts …
=> Update citations in shared chat display

backend/onyx/db/connector_credential_pair.py, backend/onyx/db/credentials.py, backend/onyx/server/documents/credential.py
Changed the logic to apply filters such that relating a credential to a connector doesnt count as editing
Created a curator public credential as admin and used it to create a cc pair as a curator. before this change this would not work and after it would.
=> associating credentials with connectors is not considered editing

web/src/app/ee/admin/groups/[groupId]/GroupDisplay.tsx
was like this:
where 'select group' is at the top of the role dropdown for some reason
This PR removes that
=> Fix group table

.github/pull_request_template.md
We want to fill out the description and testing but the mental checklist should probably get moved to a doc and given to people when they start working on the repo instead of crowding the description
=> Cleanup PR template to make it more concise

backend/onyx/llm/chat_llm.py, backend/onyx/server/manage/llm/api.py, deployment/docker_compose/docker-compose.prod.yml
- Filter out empty or None values in custom_config so we don’t set empty AWS credentials as environment variables.  
- Addresses an issue where Bedrock rejected requests that contained extraneous or empty credential fields (e.g., AWS_ACCESS_KEY_ID=“”).  
Should fix  https://github.com/onyx-dot-app/onyx/issues/3444
N/A
N/A
- Docker images build and …
=> AWS extraneous error fix

backend/onyx/connectors/confluence/connector.py
- cql attachment api call now includes a filter for these file extensions:
- "png","jpg","jpeg","gif","mp4","mov","mp3","wav",
- Also made it so if the recursive checkbox is None, it defaults to not being checked which is false
Tested by trying to index a page containing text and attachments before and after this change. before the change, it retrieved the images and then filtered it out after the fact and after the change it never retrieved the images, saving time/resources
=> Added filter to exclude attachments with unsupported file extensions

web/src/app/chat/shared_chat_search/FixedLogo.tsx, web/src/components/header/HeaderTitle.tsx, web/src/components/header/LogoWithText.tsx, web/src/components/logo/Logo.tsx
Fix this flickering logo issue ON P
https://github.com/user-attachments/assets/71858921-7929-4df7-878c-7c22e1fcb074
https://github.com/user-attachments/assets/7f8795e5-985f-4a97-bd80-8f06cd156c80
On mobile and desktop with various logotypes / white labelling
- Reload page on admin + chat page and watch logo
N/A
N/A
- Author has done a final read …
=> Fix logo flickering effect

backend/onyx/connectors/confluence/connector.py
now the recursive query also includes the top level page, not just the children
Tested on main with a recursive page on a page with no children and got 0 docs. after the change now i get 1 doc which is what is desired
=> Made sure confluence connector recursive by page includes top level page

backend/onyx/indexing/indexing_pipeline.py
=> Fix NUL character

backend/onyx/background/celery/tasks/indexing/tasks.py, backend/onyx/redis/redis_connector_index.py
=> raise activity timeout to one hour

backend/onyx/connectors/gmail/connector.py
- Currently, personal Oauth accounts in Gmail get an unhandled 404 when attempting to hit the admin user API (which we hit to list available users for impersonation)
=> Ensure gmail works for personal accounts

web/src/components/icons/icons.tsx
Previously, our div would cause issues with React Markdown's parsing. We should return Images as individual components
Before
Various logos
=> Fix logo rendering

backend/ee/onyx/db/user_group.py, backend/ee/onyx/server/user_group/api.py, backend/onyx/server/documents/cc_pair.py, backend/onyx/server/documents/connector.py, backend/onyx/server/documents/credential.py, backend/onyx/server/features/document_set/api.py, web/src/app/ee/admin/groups/[groupId]/GroupDisplay.tsx
Curators can now promote basic users to curators of a group and demote them 
curators can also demote themselves but a modal pops up asking for confirmation:
Watch the video. A in top right is admin. other 2 accounts are curator/basic
=> Curators can now update the curator relationship

backend/onyx/connectors/discourse/connector.py
Was off by 1, causing it to miss the first page.
Ran discourse connector on a dummy discourse. Before got 0 docs, now retrieves correct number.
=> Fix discourse connector

backend/onyx/connectors/google_drive/connector.py
For each impersonated user, first checks if they have access to the APIs. If they don't, then just move on (don't fail everything).
Also adds more logging.
Ran drive connector locally.
=> Additional error handling + logging for google drive connector

backend/onyx/background/celery/apps/app_base.py, backend/onyx/background/celery/apps/primary.py, backend/onyx/background/celery/tasks/connector_deletion/tasks.py, backend/onyx/background/celery/tasks/doc_permission_syncing/tasks.py, backend/onyx/background/celery/tasks/external_group_syncing/tasks.py, backend/onyx/background/celery/tasks/pruning/tasks.py, backend/onyx/background/celery/tasks/vespa/tasks.py
=> re-enable celery task execution logging in primary worker

backend/onyx/connectors/egnyte/connector.py
Fixes cases where file paths contain "#" or other chars that need to be URL encoded + removes logging of access token.
:eyes:
=> Small Egnyte tweaks

backend/shared_configs/configs.py
=> we didn't want to rename the alt index suffix, reverting

backend/onyx/configs/app_configs.py, backend/onyx/connectors/cross_connector_utils/miscellaneous_utils.py, backend/onyx/connectors/egnyte/connector.py, backend/onyx/connectors/linear/connector.py, backend/onyx/redis/redis_pool.py, backend/onyx/utils/retry_wrapper.py
OAuth for Linear since the user API tokens are end of life-ed
Works locally
=> Linear OAuth Connector

backend/onyx/background/celery/tasks/vespa/tasks.py, backend/onyx/redis/redis_connector_doc_perm_sync.py
- Added logging for permissions upsert queue length
- Increased queue priority for permission sync upsert
=> Added logging for permissions upsert queue length

backend/onyx/connectors/airtable/airtable_connector.py
Airtable pagination has a time limit. Therefore, we need to just fetch everything up front. This does make it so we can't index Airtable tables that are larger than what can fit in memory. 
Unit tests
=> Airtable improvement

backend/onyx/natural_language_processing/search_nlp_models.py
Fixes DAN-1227.
UnboundLocalError: cannot access local variable 'response' where it is not associated with a value
=> fix response logging

backend/onyx/background/celery/apps/app_base.py
=> the primary worker lock doesn't always exist

web/src/app/chat/message/codeUtils.ts
Fixes case where LLM outputs $ naturally and is incorrectly latex-formatted by plugin.
Now, as part of pre-processing text, we escape naturally occuring $s which occur outside of the context of latex equations
- Ask for various strings in response like `Respond with exactly $100 is more than $10" and various Latex equations- ensure all are formatted properly
=> Latex for $10 and $100

backend/ee/onyx/db/analytics.py, backend/ee/onyx/server/analytics/api.py, backend/onyx/db/persona.py, web/src/app/assistants/mine/AssistantsList.tsx, web/src/app/ee/admin/performance/usage/PersonaMessagesChart.tsx, web/src/app/ee/assistants/stats/[id]/AssistantStats.tsx, web/src/app/ee/assistants/stats/[id]/WrappedAssistantsStats.tsx, web/src/app/ee/assistants/stats/[id]/page.tsx, web/src/middleware.ts
=> Personal assistant usage graph

backend/ee/onyx/server/middleware/tenant_tracking.py, backend/ee/onyx/server/tenants/api.py, backend/onyx/auth/users.py, backend/onyx/configs/app_configs.py, backend/onyx/db/engine.py, backend/onyx/redis/redis_pool.py, web/src/app/admin/settings/SettingsForm.tsx, web/src/app/auth/login/page.tsx, web/src/lib/user.ts
=> JWT -> Redis

backend/onyx/connectors/airtable/airtable_connector.py, backend/onyx/file_processing/extract_file_text.py
Files with an uppercase .PDF extension weren't being parsed properly.   
Verified that a .PDF file from airtable can now be processed properly (previously was a bunch of gibberish).
=> Small airtable refactor + handle files with uppercase extensions

backend/onyx/chat/answer.py, backend/onyx/chat/stream_processing/answer_response_handler.py, backend/onyx/chat/stream_processing/citation_processing.py, backend/onyx/tools/tool_implementations/search/search_tool.py, backend/tests/unit/onyx/chat/stream_processing/test_citation_processing.py, backend/tests/unit/onyx/chat/stream_processing/test_citation_substitution.py
Purpose: Alignment & renaming of objects for initial (displayed) ranking and r…e-ranking/validation citations
Comments:
- renamed post-reranking/validation citation information consistently to final_... (example: doc_id_to_rank_map -> final_doc_id_to_rank_map)
- changed and renamed objects containing initial ranking information (now: display_...) consistent with final rankings (final_...). Specifically, {} to [] for displayed_search_results
- for CitationInfo, changed citation_num from 'x-th citation in response stream' to the initial position of the doc [NOTE: test implications]
-  changed tests: onyx/backend/tests/unit/onyx/chat/stream_processing/test_citation_processing.py onyx/backend/tests/unit/onyx/chat/stream_processing/test_citation_substitution.py
[Provide a brief description of …
=> Citation consistency in Citation Processing (initial ranking vs post validation/re-ranking)

backend/onyx/background/celery/apps/primary.py, backend/onyx/background/celery/tasks/beat_schedule.py, backend/onyx/background/celery/tasks/llm_model_update/tasks.py, backend/onyx/configs/app_configs.py, backend/onyx/configs/constants.py
See title.
Tested with LiteLLM proxy locally (`LLM_MODEL_UPDATE_API_URL=http://localhost:4000/model/info`).
=> Add support for auto-refreshing available models based on an API call

backend/alembic/versions/2955778aa44c_add_chunk_count_to_document.py, backend/onyx/connectors/models.py, backend/onyx/db/document.py, backend/onyx/db/models.py, backend/onyx/document_index/document_index_utils.py, backend/onyx/document_index/interfaces.py, backend/onyx/document_index/vespa/deletion.py, backend/onyx/document_index/vespa/index.py, backend/onyx/document_index/vespa/indexing_utils.py, backend/onyx/document_index/vespa_constants.py, backend/onyx/indexing/chunker.py, backend/onyx/indexing/indexing_pipeline.py, backend/onyx/indexing/models.py, backend/onyx/seeding/load_docs.py, backend/onyx/server/documents/connector.py, backend/scripts/force_delete_connector_by_id.py, backend/scripts/query_time_check/seed_dummy_docs.py, backend/tests/integration/common_utils/vespa.py, backend/tests/unit/onyx/indexing/test_embedder.py
For indexing:
- Document: new value `chunk_count`
- If no `chunk_count`, we can just assume that it has the old UUID system (including non tenancy):
- If large chunks enabled, generate the UUID based on the old UUID logic + large chunk reference IDs
- If `chunk_count`, can infer UUIDs + exact values for deletion
In multi tenant and single-tenant scenario:
- Index various docs
- Increase size of doc
- Decrease size of doc
- Ensure proper doc chunk IDs are deleted in Vespa
- Do the above specifically when migrating from main to this branch
=> Improved indexing

backend/ee/onyx/configs/app_configs.py, backend/ee/onyx/external_permissions/confluence/constants.py, backend/ee/onyx/external_permissions/confluence/doc_sync.py, backend/ee/onyx/external_permissions/confluence/group_sync.py, backend/onyx/connectors/confluence/connector.py
- Anonymous access is now properly handled for confluence server
- permissions now properly inherit across ancestors 
- tested on confluence server by changing permissions of a child/parent page for a non admin user
- tested by removing all group access from a space and still ensuring access is given to those where the space has anonymous access is enabled
=> Properly account for anonymous access in Confluence

backend/ee/onyx/server/tenants/billing.py, backend/onyx/auth/email_utils.py, backend/onyx/auth/users.py, backend/onyx/db/engine.py, web/src/app/auth/login/EmailPasswordForm.tsx, web/src/app/auth/signup/page.tsx
- User registration clarity:  Updated email and pre-populated auth page with their email
- Make sure each new transaction immediately sets the schema (search_path) to the tenant’s schema in async session
- Needed a workaround-ish solution for the above- "after_begin"  since we can't use direct async awaits.
Fixes  https://linear.app/danswer/issue/DAN-1232/cloud-user-invite-not-working 
Previously, we did this somewhat manually since FastAPI Users manually commits the transaction for the user db in various places. This led to some inconsistencies in auth flows
- Invite and login as a previously external permission user and Slack user
- Login and register in multi tenant scenario
=> Auth fix + Registration Clarity

web/src/app/ee/admin/whitelabeling/WhitelabelingForm.tsx
If user sets " " as text and then resets to default, still interpreted as empty string for browser tab name. This fixes that by requiring either empty input or properly set
=> fix white labelling empty string

backend/onyx/document_index/vespa/shared_utils/vespa_request_builders.py, backend/onyx/server/query_and_chat/query_backend.py, deployment/kubernetes/env-configmap.yaml
Fixes https://linear.app/danswer/issue/DAN-1238/document-explorer-not-showing-any-results
- Observe issue on main
- Observe fix on this branch
=> Doc explore fix

backend/onyx/connectors/discord/connector.py, web/src/components/icons/icons.tsx
=> Discord cleanup

backend/onyx/tools/built_in_tools.py, backend/onyx/tools/tool_constructor.py, web/next.config.js
In order to be able to update with built in tools for multi tenant set up, we should refer to built in tool by ID
Add built in tool in multi + single tenant setup
=> Built in tool cache with tool call id

backend/onyx/configs/app_configs.py, backend/onyx/main.py, backend/onyx/redis/redis_pool.py, backend/onyx/server/middleware/rate_limiting.py
Ensure SSL context is propagated for async Redis
=> Async Redis

backend/onyx/background/celery/tasks/vespa/tasks.py, backend/onyx/redis/redis_connector_credential_pair.py
reverting the hack used to mitigate repeated doc sync.
=> comment out the per doc sync hack

backend/tests/daily/connectors/google_drive/consts_and_utils.py, backend/tests/daily/connectors/google_drive/test_slim_docs.py
- now the thing being tested for is determined by the prefix of the test for google drive tests. This is done to allow other tests to be performed without breaking the existing tests.
=> prevent other tests from interfering with existing google drive tests

backend/onyx/server/documents/connector.py, backend/onyx/server/documents/models.py, web/src/app/admin/connectors/[connector]/pages/gdrive/GoogleDrivePage.tsx, web/src/app/admin/connectors/[connector]/pages/gmail/GmailPage.tsx, web/src/app/admin/documents/sets/DocumentSetCreationForm.tsx, web/src/app/admin/documents/sets/[documentSetId]/page.tsx, web/src/app/admin/documents/sets/new/page.tsx, web/src/app/admin/documents/sets/page.tsx, web/src/app/admin/indexing/status/CCPairIndexingStatusTable.tsx, web/src/app/admin/indexing/status/page.tsx, web/src/app/ee/admin/groups/ConnectorEditor.tsx, web/src/app/ee/admin/groups/UserGroupCreationForm.tsx, web/src/app/ee/admin/groups/[groupId]/AddConnectorForm.tsx, web/src/app/ee/admin/groups/[groupId]/GroupDisplay.tsx, web/src/app/ee/admin/groups/[groupId]/page.tsx, web/src/app/ee/admin/groups/page.tsx, web/src/lib/hooks.ts, web/src/lib/types.ts
Remove unnecessary usage of indexing status pages (use simpler endpoints where possible + fully remove where possible)
Fixes https://linear.app/danswer/issue/DAN-1239/indexing-status-latency
- Test speed before and after 
- Currently set up on test.danswer.dev
=> Speed up admin pages

.vscode/launch.template.jsonc, CONTRIBUTING.md, CONTRIBUTING_VSCODE.md
=> Improve contributing guide

backend/onyx/connectors/egnyte/connector.py
Yields files out as they are found rather then fetching the entire list up front.
👀 
=> Improve egnyte connector

backend/onyx/background/celery/tasks/indexing/tasks.py
=> add more debug logging for locking issue

backend/ee/onyx/db/token_limit.py, backend/onyx/db/connector_credential_pair.py, backend/onyx/db/credentials.py, backend/onyx/db/document_set.py, backend/onyx/db/feedback.py, backend/onyx/db/persona.py
^
- Reproduced error before and it went away after
=> added distinct when outer joining for user filters

backend/alembic/versions/be2ab2aa50ee_fix_capitalization.py, backend/ee/onyx/db/document.py, backend/ee/onyx/db/external_perm.py, backend/onyx/access/utils.py, backend/onyx/background/celery/tasks/doc_permission_syncing/tasks.py, backend/onyx/connectors/confluence/onyx_confluence.py, backend/tests/integration/common_utils/reset.py, backend/tests/integration/tests/migrations/test_migrations.py
- we now convert the retrieved group_id to lower case
- minor onyx_confluence reorg
=> fix group sync name capitalization

backend/onyx/background/celery/apps/app_base.py, backend/onyx/background/celery/apps/heavy.py, backend/onyx/background/celery/apps/indexing.py, backend/onyx/background/celery/apps/light.py, backend/onyx/background/celery/apps/primary.py, backend/onyx/background/celery/tasks/indexing/tasks.py, backend/onyx/background/indexing/job_client.py
Fixes DAN-1252.
Ran this in the cloud, sql errors way down. Also the code itself is logging the success or failure of the start methods.
=> figuring out why multiprocessing set_start_method isn't working.

backend/alembic/versions/c5eae4a75a1b_add_chat_message__standard_answer_table.py, backend/ee/onyx/onyxbot/slack/handlers/handle_standard_answers.py, backend/onyx/chat/answer.py, backend/onyx/chat/llm_response_handler.py, backend/onyx/chat/models.py, backend/onyx/chat/process_message.py, backend/onyx/chat/prompt_builder/answer_prompt_builder.py, backend/onyx/chat/prompt_builder/citations_prompt.py, backend/onyx/chat/tool_handling/tool_response_handler.py, backend/onyx/onyxbot/slack/handlers/handle_buttons.py, backend/onyx/onyxbot/slack/handlers/handle_message.py, backend/onyx/onyxbot/slack/handlers/handle_regular_answer.py, backend/onyx/onyxbot/slack/listener.py, backend/onyx/onyxbot/slack/models.py, backend/onyx/prompts/chat_prompts.py, backend/onyx/tools/base_tool.py, backend/onyx/tools/tool.py, backend/onyx/tools/tool_implementations/custom/custom_tool.py, backend/onyx/tools/tool_implementations/images/image_generation_tool.py, backend/onyx/tools/tool_implementations/internet_search/internet_search_tool.py, backend/onyx/tools/tool_implementations/search/search_tool.py, backend/onyx/tools/tool_implementations/search_like_tool_utils.py, backend/tests/unit/onyx/chat/conftest.py
1. Fixes follow ups in threads. A table was missing, which caused follows ups to fail (SQLAlchemy tries accessing a table that doesn't exist).
2.  Improves the prompt. Previously was a bit nasty (e.g. the final query would look like `nQUERY:\nChris Weaver said in Slack:\nhi'` which caused weird answers). Moves back to the single message history that happens before the task prompt + removes the `X said in Slack` part before the final query to simplify the tasks for the LLM.
Tested follow-ups, directly in channel, search assistant in web UI, and general assistant in web UI.
=> Fix follow ups in thread + fix user name

backend/ee/onyx/db/query_history.py, backend/ee/onyx/server/query_history/api.py, backend/ee/onyx/server/query_history/models.py, backend/onyx/configs/constants.py, backend/onyx/server/documents/models.py, backend/scripts/chat_feedback_dump.py, backend/tests/integration/common_utils/managers/chat.py, web/src/app/ee/admin/performance/DateRangeSelector.tsx, web/src/app/ee/admin/performance/lib.ts, web/src/app/ee/admin/performance/query-history/QueryHistoryTable.tsx, web/src/app/ee/admin/performance/query-history/[id]/page.tsx, web/src/app/ee/admin/performance/usage/types.ts, web/src/hooks/usePaginatedFetch.tsx, web/src/lib/types.ts
- Implemented server-side pagination for query history
- Modified API endpoint to accept pagination parameters and return PaginatedReturn generic
- Updated database queries from query to select
- Improved feedback filtering system
- Added "Mixed" feedback as a new filter option
- Fixed feedback filters to strictly match their types (Like/Dislike)
- Removed incorrect display of mixed feedback in single-type filters
- Modified date range selector to make date range on initial load optional
- Modified QueryHistoryTable to use the usePaginatedFetch hook
- Added factory method `from_chat_session()` to transform ChatSession into ChatSessionMinimal
- Fixed React key prop warning in development strict mode
- Added test coverage
Issues:
- If you send a message to an assistant and then quickly …
=> Paginate Query History table

backend/ee/onyx/external_permissions/google_drive/doc_sync.py, backend/ee/onyx/external_permissions/google_drive/group_sync.py, backend/onyx/connectors/google_drive/connector.py, backend/onyx/connectors/google_drive/doc_conversion.py, backend/onyx/connectors/google_drive/file_retrieval.py
- this now attaches the drive id as a group to the doc
- the external group job now also resolves the drive->users relationship
- tested against the end to end permission sync test in pr 3635
=> fixed group sync to account for changes in drive permissions

backend/alembic/versions/c7bf5721733e_add_has_been_indexed_to_.py, backend/onyx/background/indexing/run_indexing.py, backend/onyx/db/document.py, backend/onyx/db/models.py, backend/onyx/indexing/indexing_pipeline.py, backend/onyx/server/onyx_api/ingestion.py
Addresses two edge cases:
1. Permission syncing creating DocumentByConnectorCredentialPair objects before the indexing has occurred -> much larger count at the CC Pair level compared to the Index Attempt.
2. Docs that are filtered out were still counted as part of the Index Attempt cnt but not part of the CC Pair count.
Ran indexing locally, verified counts matched as expected.
=> Fix document counts

backend/onyx/llm/chat_llm.py
Allow passing in of a specific location to vertex AI. Needed for people using claude through vertex.
Tested using vertex locally.
=> Enable location support for Vertex AI

web/src/app/admin/assistants/AssistantEditor.tsx
Fixes https://linear.app/danswer/issue/DAN-1273/assistants-w-search-tool-enabled-have-knowledge-disabled-in-new-chat
=> Fix search tool bug

backend/onyx/connectors/airtable/airtable_connector.py, backend/tests/daily/connectors/airtable/test_airtable_basic.py
Attachments now get their own direct links in airtable.
Unit tests.
=> Enhance airtable connector

.github/pull_request_template.md, .github/workflows/pr-linear-check.yml
Fixes https://linear.app/danswer/issue/DAN-1280/enforce-linear-link-in-prs
- Automatically re-runs when description changes
=> Add linear check to PRs

backend/onyx/auth/users.py, backend/onyx/configs/app_configs.py
Fixes https://linear.app/danswer/issue/DAN-1288/jwt-logs-users-out-very-quickly-on-cloud
- On main vs on branch - JWT expiry 1D vs 7D
=> Update JWT expiry time config

backend/onyx/onyxbot/slack/config.py, backend/onyx/onyxbot/slack/listener.py
Fixes https://linear.app/danswer/issue/DAN-1275/slack-bot-not-working-with-on-our-cloud
Fixes cloud slackbot "acquiring" many tenants
- Centralize removal logic
- Use self.tenant_ids to track genuinely active tenants - only consider tenants with slackbots "active"
- Single tenant + multiple slackbots
- Multi tenant + multiple Slackbots + delete slackbots
=> Slackbot optimization

backend/onyx/key_value_store/factory.py, backend/onyx/key_value_store/store.py, backend/onyx/main.py, backend/onyx/utils/telemetry.py
We weren't passing in the right tenant ID for cloud-monitoring -> silent telemetry failures.
https://linear.app/danswer/issue/DAN-1296/fix-monitoring-telemetry-on-our-cloud
`kubectl cp`ed the files over to the monitoring pod and ran:
```
>>> from telemetry import optional_telemetry, RecordType
>>> data = {'metric_name': 'sync_start_latency_seconds', 'float_value': 0.0}
>>> optional_telemetry(record_type=RecordType.METRIC, data=data, user_id=None, tenant_id='<SOME_TENANT>')
```
Then verified we got the expected packet on the telemetry server.
=> Pass in tenant_id to kv_store in monitoring job

backend/onyx/background/celery/apps/app_base.py, backend/onyx/background/celery/apps/heavy.py, backend/onyx/background/celery/apps/indexing.py, backend/onyx/background/celery/apps/light.py, backend/onyx/background/celery/apps/primary.py, backend/onyx/document_index/vespa/shared_utils/utils.py, backend/onyx/seeding/load_docs.py
Fixes https://linear.app/danswer/issue/DAN-1290/vespa-exceptions-causes-api-server-to-fail-out-forever
Multi tenant + not:
- Vespa in poor state + authenticate
- Simply spin up all the resources from scratch - ensure waiting is functional
=> Fix exceptional seeding delay

backend/alembic/versions/f1ca58b2f2ec_add_passthrough_auth_to_tool.py, backend/onyx/db/models.py, backend/onyx/db/tools.py, backend/onyx/server/features/tool/api.py, backend/onyx/server/features/tool/models.py, backend/onyx/tools/tool_constructor.py, backend/onyx/tools/tool_implementations/custom/custom_tool.py, web/src/app/admin/tools/ToolEditor.tsx, web/src/lib/hooks.ts, web/src/lib/tools/edit.ts, web/src/lib/tools/interfaces.ts
Add support for passing through OAuth headers. 
https://linear.app/danswer/issue/DAN-1298/adding-passthrough-auth-for-tool-calls
Tested manually creating a tool using passthrough auth and verifying that we got the expected access token.
=> Add basic passthrough auth

backend/danswer/background/celery/apps/primary.py, backend/danswer/background/celery/tasks/beat_schedule.py, backend/danswer/background/celery/tasks/llm_model_update/tasks.py, backend/danswer/configs/app_configs.py, backend/tests/integration/tests/seeding/test_seeding.py, backend/tests/unit/danswer/celery/llm_model_update/test_llm_model_update.py
https://linear.app/danswer/issue/DAN-1305/support-automatic-llm-updates-for-netflix-specific-api-format-backport
This is ported over from main + adds support for a different API format.
UT + testing with LiteLLM proxy locally
=> Add model updates

web/src/app/assistants/mine/AssistantCard.tsx, web/src/components/assistants/AssistantIcon.tsx
Fixes https://linear.app/danswer/issue/DAN-1306/assistant-icons-not-shown-if-custom-in-explorer-specifically
With a very large email, create custom image for assistnat icon + open assistant modal + decrease screen size until icon disappears
- On main
- On this branch: verify functional
=> fix image edge case width screen size

backend/onyx/server/query_and_chat/chat_backend.py
Fixes https://linear.app/danswer/issue/DAN-1302/images-appearing-wonky
- Use image in linear, ensure first one doesn't appear
=> Fix image wonkiness

backend/onyx/auth/schemas.py, backend/onyx/auth/users.py, backend/onyx/configs/app_configs.py
https://linear.app/danswer/issue/DAN-1327/add-back-option-to-use-postgres-auth-backend
Tested locally with both postgres / redis backends with basic auth.
=> Add back postgres auth backend support

backend/ee/onyx/configs/app_configs.py, backend/ee/onyx/main.py
Allows you to override the scopes that are requested from the OIDC provider. Currently used when passing through access tokens to tool calls and the tool needs more scopes.
https://linear.app/danswer/issue/DAN-1323/add-support-for-requesting-additional-oidcoauth-scopes-via-env
Tested regular OIDC + set breakpoint and verified additional scopes were indeed passed in to the lib.
=> Add support for overridding scopes for OIDC

backend/onyx/chat/prompt_builder/answer_prompt_builder.py, backend/onyx/chat/prompt_builder/utils.py, backend/onyx/llm/utils.py, backend/onyx/tools/tool_implementations/images/image_generation_tool.py, backend/onyx/tools/tool_implementations/images/prompt.py, web/src/app/admin/assistants/AssistantEditor.tsx, web/src/app/chat/ChatPage.tsx, web/src/app/chat/input/LLMPopover.tsx, web/src/components/admin/connectors/Popup.tsx, web/src/lib/hooks.ts
Fixes https://linear.app/danswer/issue/DAN-1297/never-hide-non-image-assistants
https://github.com/user-attachments/assets/9e6006de-61c5-4223-81ac-56ac6442f22c
- Multiple providers, create images, switch models with images in chat from user
=> Allow all LLMs for image generation assistants

backend/onyx/background/celery/tasks/llm_model_update/tasks.py, backend/tests/unit/onyx/celery/llm_model_update/test_llm_model_update.py
https://linear.app/danswer/issue/DAN-1305/support-automatic-llm-updates-for-netflix-specific-api-format-backport
Applies the changes for ^ to main branch.
UT
=> Add support for more /models/list formats

backend/onyx/db/input_prompt.py, backend/onyx/server/features/input_prompt/api.py
Fixes https://linear.app/danswer/issue/DAN-1335/input-prompts-not-showing-up
=> Input shortcut fix in multi tenant case

backend/onyx/server/documents/connector.py, web/src/components/chat_search/TextView.tsx
Fixes https://linear.app/danswer/issue/DAN-1334/zip-files-cannot-be-viewed
Fixes https://linear.app/danswer/issue/DAN-1332/two-closing-crosses
Multi tenant + non:
- Upload zip, try to click into text view 
=> Unzip files + no double x

backend/onyx/agents/agent_search/deep_search_a/expanded_retrieval/nodes/doc_reranking.py, backend/onyx/agents/agent_search/deep_search_a/expanded_retrieval/nodes/doc_retrieval.py, backend/onyx/agents/agent_search/deep_search_a/expanded_retrieval/nodes/format_results.py, backend/onyx/agents/agent_search/deep_search_a/main/edges.py, backend/onyx/agents/agent_search/deep_search_a/main/nodes/agent_logging.py, backend/onyx/agents/agent_search/deep_search_a/main/nodes/agent_search_start.py, backend/onyx/agents/agent_search/deep_search_a/main/nodes/generate_initial_answer.py, backend/onyx/agents/agent_search/deep_search_a/main/nodes/generate_refined_answer.py, backend/onyx/agents/agent_search/models.py, backend/onyx/chat/process_message.py
Allowed basic search to run when the user is using an assistant without a search tool
Ran in UI
=> basic tools no search

backend/onyx/connectors/confluence/connector.py
Uncertain which version of Confluence this happens on but sometimes the info for a page does not follow expected format. Removing assumptions and allowing labels to be None if it fails to fetch them
N/A can't repro
=> Fix Confluence Missing Labels

backend/onyx/connectors/sharepoint/connector.py, web/src/components/admin/connectors/Field.tsx, web/src/lib/connectors/connectors.tsx
https://linear.app/danswer/issue/DAN-1342/sharepoint-cant-index-folders
Sharepoint Folders aren't getting parsed correctly
Verified against our own Sharepoint (with some hacks since data format has changed)
=> Fix Sharepoint Folder Parsing

backend/onyx/server/query_and_chat/chat_backend.py
increase timeout so the backend gets correct is_connected status from the frontend
tested in UI, huge reduction in async io timed out logger errors
=> increased timeout to get rid of asyncio logger errors

backend/onyx/tools/tool_implementations/internet_search/internet_search_tool.py, web/src/app/admin/assistants/AssistantEditor.tsx
Fixes https://linear.app/danswer/issue/DAN-539/handle-no-results-in-internet-search-tool-potential-issue-with-flow-in
Bing API doesn't return webPage key if no results https://stackoverflow.com/questions/44546052/issue-with-bing-search-api-which-returns-only-relatedsearches-and-not-webpages
- Obscure query before + after
=> Search tool no results bugfix

backend/onyx/connectors/slack/utils.py
Fixes https://linear.app/danswer/issue/DAN-1295/slack-error-response-internal-error
Ameliorates issue where slack connector fails due to internal slack error.
Attempted various fixes but seems like an issue on Slack's end
- Replicate with exact channel ID, configuration that failed, ensure we simply skip
=> Continue on internal error

web/src/app/chat/ChatPage.tsx, web/src/app/chat/input/LLMPopover.tsx, web/src/app/chat/modal/UserSettingsModal.tsx, web/src/lib/hooks.ts, web/src/lib/llm/utils.ts
Generally robustifies the llm provider selection process. Separate PR to unify the llm model name structuring
=> llm provider re-org

web/src/app/admin/assistants/AssistantEditor.tsx, web/src/app/admin/bots/[bot-id]/channels/SlackChannelConfigCreationForm.tsx, web/src/app/admin/bots/[bot-id]/channels/SlackChannelConfigFormFields.tsx, web/src/app/assistants/ToolsDisplay.tsx, web/src/app/chat/ChatPage.tsx, web/src/app/chat/lib.tsx, web/src/app/chat/tools/constants.ts, web/src/components/assistants/AssistantCards.tsx
Built in tools have equivalent `name` as `built_in_tool_id`, not the tool's `_NAME` attribute
=> Tool id constants

backend/onyx/agents/agent_search/deep_search_a/expanded_retrieval/nodes/doc_reranking.py
Previously we were passing in a SearchQuery with mostly default values when running the preprocessing needed before reranking. Most of what is done in preprocessing isn't really necessary for us, but there are things like filtering document sets based on persona that are important that we still do. Also, the previous code was making a new db call to get the search settings each time reranking was called; we fix that by passing in reranking
ran in UI
=> reranking improvement

backend/onyx/chat/process_message.py
https://linear.app/danswer/issue/DAN-1353/query-override-fix-for-api
- No more logic to run the original user message as-is. This wasn't actually happening in the current state of main, and we decided to leave it this way.
- Now query override actually works again, i.e. when one hits process_message.py through a message request, it makes the search tool use that query. This will now only happen when someone is directly hitting our API due to the first bullet point.
tested in UI and unit tested, although nothing works unless I set ToolCallSummary to have class Config: arbitrary_types_allowed = True. Didn't add that to the PR since I assume it's a package version thing, but we should probably look at it at some point.
Note: You have to check that the action passes, otherwise resolve the …
=> removed logic to search first message, fixed query override

backend/alembic/versions/4d58345da04a_lowercase_user_emails.py
There was a brief time a while ago where users could erroneously get a non-lowercase email input
=> Lowercase all user emails

backend/onyx/background/celery/tasks/doc_permission_syncing/tasks.py
Fixes DAN-1370.  https://linear.app/danswer/issue/DAN-1370/race-condition-in-permission-syncing-causes-things-to-get-stuck
=> fix race condition with permission sync and fences

backend/onyx/connectors/sharepoint/connector.py, backend/tests/daily/connectors/sharepoint/test_sharepoint_connector.py
https://linear.app/danswer/issue/DAN-1363/sharepoint-polling-doesnt-work
- graphql api doesnt support filtering by last modified time
- We now pull all files and then only pull the content+convert to document if it is within the polling time
- added a test for this
=> Fixed SharePoint connector polling

backend/ee/onyx/server/tenants/api.py, backend/onyx/db/persona.py
https://docs.sqlalchemy.org/en/13/orm/loading_relationships.html
-  Prevent the query result from exploding in size, so we no longer need `.distinct()`.  
Fixes https://linear.app/danswer/issue/DAN-1382/fix-slow-query
=> Optimize /persona query

backend/onyx/configs/app_configs.py, backend/onyx/connectors/airtable/airtable_connector.py, backend/onyx/connectors/connector_runner.py, backend/onyx/connectors/models.py, backend/onyx/indexing/indexing_pipeline.py, backend/onyx/natural_language_processing/search_nlp_models.py
Tries to make Airtable faster
https://linear.app/danswer/issue/DAN-1384/airtable-indexing-extremely-slow
Ran locally, it was faster.
=> Add more airtable logging

backend/onyx/connectors/airtable/airtable_connector.py
If a row in a batch didn't contain any attachments, then we would skip the batch.
ran locally
=> Airtable fix

backend/onyx/connectors/airtable/airtable_connector.py
https://linear.app/danswer/issue/DAN-1399/handle-airtable-attachments-that-expire-mid-way-through-indexing
Unit tests
=> Handle expiring attachments

backend/onyx/connectors/airtable/airtable_connector.py
https://linear.app/danswer/issue/DAN-1402/fix-airtable-refetch-attachment-round-2
Tested locally with expired Airtable link
=> another airtable fix

backend/onyx/agents/agent_search/deep_search/main/nodes/extract_entities_terms.py, backend/onyx/prompts/agent_search.py
Tell the LLM not to output extra stuff during subquestion gen, subquery gen, and verification steps. Generally only relevant for weaker models.
ran in UI
=> Prompt hardening

.github/workflows/pr-helm-chart-testing.yml, deployment/helm/charts/onyx/Chart.yaml, deployment/helm/charts/onyx/templates/api-deployment.yaml, deployment/helm/charts/onyx/templates/api-service.yaml, deployment/helm/charts/onyx/templates/indexing-model-deployment.yaml, deployment/helm/charts/onyx/templates/indexing-model-pvc.yaml, deployment/helm/charts/onyx/templates/indexing-model-service.yaml, deployment/helm/charts/onyx/templates/inference-model-deployment.yaml, deployment/helm/charts/onyx/templates/inference-model-pvc.yaml, deployment/helm/charts/onyx/templates/inference-model-service.yaml, deployment/helm/charts/onyx/templates/nginx-conf.yaml, deployment/helm/charts/onyx/templates/tests/test-connection.yaml, deployment/helm/charts/onyx/templates/webserver-deployment.yaml, deployment/helm/charts/onyx/templates/webserver-service.yaml, deployment/helm/charts/onyx/values.yaml
I used eksctl cli to provision a eks cluster in aws. The following is the config.yaml that I used to provision the cluster.  
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
name: onyx-cluster
region: us-west-1
nodeGroups:
- name: ng-1
instanceType: m5.large
desiredCapacity: 1
maxSize: 2
minSize: 1
volumeSize: 80
ssh:
allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
- name: ng-2
instanceType: m5.xlarge
desiredCapacity: 1
maxSize: 2
minSize: 1
volumeSize: 100
ssh:
publicKeyPath: ~/.ssh/id_rsa.pub
iam:
withAddonPolicies:
imageBuilder: true
autoScaler: true
externalDNS: true
certManager: true
appMesh: true
appMeshPreview: true
ebs: true
fsx: true
efs: true
awsLoadBalancerController: true
xRay: true …
=> Helm chart refactoring

backend/ee/onyx/server/oauth.py, backend/onyx/auth/users.py, backend/onyx/background/celery/tasks/indexing/tasks.py, backend/onyx/background/celery/tasks/indexing/utils.py, backend/onyx/background/celery/tasks/monitoring/tasks.py, backend/onyx/background/celery/tasks/shared/tasks.py, backend/onyx/background/celery/tasks/vespa/tasks.py, backend/onyx/background/indexing/run_indexing.py, backend/onyx/chat/process_message.py, backend/onyx/connectors/airtable/airtable_connector.py, backend/onyx/connectors/asana/asana_api.py, backend/onyx/connectors/google_utils/resources.py, backend/onyx/connectors/salesforce/doc_conversion.py, backend/onyx/db/document_set.py, backend/onyx/file_processing/extract_file_text.py, backend/onyx/indexing/chunker.py, backend/onyx/onyxbot/slack/listener.py, backend/onyx/onyxbot/slack/utils.py, backend/onyx/redis/redis_connector_doc_perm_sync.py, backend/onyx/redis/redis_connector_ext_group_sync.py, backend/onyx/redis/redis_connector_index.py, backend/onyx/server/manage/users.py, backend/scripts/chat_feedback_dump.py, backend/tests/daily/connectors/confluence/test_confluence_basic.py, backend/tests/daily/connectors/gmail/test_gmail_connector.py, backend/tests/integration/common_utils/managers/user.py, backend/tests/integration/connector_job_tests/google/test_google_drive_permission_sync.py
https://linear.app/danswer/issue/DAN-1407/mypy-fixes
=> Mypy random fixes

backend/onyx/agents/agent_search/orchestration/nodes/tool_call.py, backend/onyx/chat/process_message.py, backend/onyx/tools/tool_implementations/internet_search/internet_search_tool.py, web/src/app/chat/ChatPage.tsx
Tool calls fail silently and user is left confused with a broken chat session
Only tested locally
=> Tool Call Error Display

backend/onyx/llm/chat_llm.py, backend/onyx/llm/llm_provider_options.py, backend/requirements/default.txt, backend/requirements/model_server.txt, web/src/lib/hooks.ts
Fairly self-explanatory. LiteLLM/OpenAI hasn't patched a small parallel tool calls issue so we need ot circle back likely in the next few days to the `TODO`
=> Set GPT 4o as default and add O3 mini

backend/onyx/document_index/document_index_utils.py, backend/onyx/document_index/vespa/index.py, backend/onyx/document_index/vespa/indexing_utils.py, backend/onyx/document_index/vespa/shared_utils/utils.py, web/src/app/admin/connector/[ccPairId]/page.tsx
https://linear.app/danswer/issue/DAN-1414/file-connector-failing-due-to-successful-doc-ids-=-setupdatable-ids
Document ID modification internal to Vespa -> returning different document IDs than passed in -> causes 
```
successful_doc_ids = {record.document_id for record in insertion_records}
if successful_doc_ids != set(updatable_ids):
raise RuntimeError(
f"Some documents were not successfully indexed. "
f"Updatable IDs: {updatable_ids}, "
f"Successful IDs: {successful_doc_ids}"
)
```
to fail.
Also includes some additional comments + enabling re-indexing on the file connector.
Tested with a batch of files that I knew previously failed. Then verified it worked after the fix.
=> Fix issue causing file connector to fail

backend/onyx/server/query_and_chat/chat_backend.py
Fixes https://github.com/onyx-dot-app/onyx/issues/3888
There is a bug which breaks image uploads in chats:
I believe this was caused by a change in 2ad86aa which causes an IO stream based on an image file to be read again without resetting the stream back to the beginning (first read in chat_backend.py, [upload_files_for_chat](https://github.com/onyx-dot-app/onyx/blob/715359c12060957bb37b7df545359b4b444d8ab6/backend/onyx/server/query_and_chat/chat_backend.py#L716), and then again in pg_file_store.py, [create_populate_lobj](https://github.com/onyx-dot-app/onyx/blob/715359c12060957bb37b7df545359b4b444d8ab6/backend/onyx/db/pg_file_store.py#L53)). Non image files are treated differently and thus are unaffected.
Tested both PDF and image uploading.
Note: You have to check that the action …
=> Fix chat image upload double read

backend/onyx/agents/agent_search/basic/utils.py, backend/onyx/agents/agent_search/orchestration/nodes/basic_use_tool_response.py, backend/onyx/chat/answer.py, backend/onyx/chat/stream_processing/utils.py, backend/onyx/server/query_and_chat/chat_backend.py, backend/onyx/tools/tool_implementations/search/search_tool.py, backend/tests/integration/tests/dev_apis/test_simple_chat_api.py
https://linear.app/danswer/issue/DAN-1419/agent-search-failed-api-integration-test
When Agent Search was merged we didn't check that all non frontend APIs worked as normal. There was a regression in the `send-message-simple-with-history` endpoint in which we weren't returned cited documents when the request was made with selected sections. This fixes that and deletes some dead code left around from the agent search merge.
Ran in UI, passed failing integration test on local, passes unit tests
=> fixed citations when sections selected

backend/onyx/background/celery/tasks/doc_permission_syncing/tasks.py, backend/onyx/server/query_and_chat/chat_backend.py
Fixes DAN-1420.
https://linear.app/danswer/issue/DAN-1420/correcty-avoid-signaling-active-when-subtask-count-is-0
=> fix bug in validation logic

backend/onyx/db/document_set.py, web/src/app/ee/admin/groups/[groupId]/AddConnectorForm.tsx, web/src/app/ee/admin/groups/[groupId]/GroupDisplay.tsx, web/src/components/ui/button.tsx
Fix https://linear.app/danswer/issue/DAN-1418/connector-document-set-assignment-issue
- No directly adding sync connectors to user group
- Can add sync connector to doc set (which can be added to user groups now)
- Syncing tooltip
=> Minor misc docset updates

backend/alembic/versions/f5437cc136c5_delete_non_search_assistants.py, backend/onyx/db/persona.py, backend/onyx/db/slack_channel_config.py, backend/onyx/onyxbot/slack/blocks.py, backend/onyx/onyxbot/slack/handlers/handle_regular_answer.py, backend/onyx/onyxbot/slack/listener.py, backend/onyx/server/query_and_chat/chat_backend.py, web/package-lock.json, web/package.json, web/src/app/admin/bots/[bot-id]/SlackChannelConfigsTable.tsx, web/src/app/admin/bots/[bot-id]/channels/SlackChannelConfigCreationForm.tsx, web/src/app/admin/bots/[bot-id]/channels/SlackChannelConfigFormFields.tsx, web/src/components/admin/connectors/Field.tsx, web/src/components/ui/CheckField.tsx, web/src/components/ui/accordion.tsx
Allows for Slackbots that do not have search enabled
=> Allow no search

backend/ee/onyx/db/user_group.py, backend/onyx/background/celery/tasks/connector_deletion/tasks.py, backend/onyx/db/document.py, backend/onyx/db/document_set.py, backend/onyx/redis/redis_connector_credential_pair.py, backend/onyx/redis/redis_document_set.py, backend/onyx/redis/redis_usergroup.py
Fixes DAN-1423.
https://linear.app/danswer/issue/DAN-1423/tenant-is-blowing-up-celery-on-stale-task-doc-sync-generation
=> select only doc_id

backend/Dockerfile, backend/onyx/server/query_and_chat/chat_backend.py, backend/scripts/debugging/onyx_redis.py, backend/scripts/debugging/onyx_vespa.py
Various new utilities for Vespa / Redis based on what has been useful in the cloud for debugging
Various real world cases in cloud + single tenant customers
=> Improvements to Redis + Vespa debugging

backend/onyx/connectors/linear/connector.py, backend/onyx/server/documents/standard_oauth.py, web/src/app/admin/connectors/[connector]/AddConnectorPage.tsx, web/src/lib/connectors/connectors.tsx, web/src/lib/connectors/credentials.ts
Some code cleanup and a tiny change to allow users to connect multiple linear workspaces through the OAuth flow.
https://github.com/user-attachments/assets/e64ba58a-8504-472c-83cd-37bd85b3d3dd
TBD: make the OAuth Flow more intuitive?
TBD: handle OAuth refresh for all new type OAuth connectors?
tested extensively in UI
=> small linear connector improvements

backend/onyx/chat/prompt_builder/citations_prompt.py, backend/onyx/prompts/direct_qa_prompts.py, backend/onyx/tools/tool_implementations/internet_search/internet_search_tool.py, backend/onyx/tools/tool_implementations/search_like_tool_utils.py
Addresses
https://linear.app/danswer/issue/DAN-1427/internet-search-saying-cant-search-the-internet-after-searching-the
We tell the LLM that what it is seeing are internet search results so it knows not to erroneously tell the user that it can't search the internet
tested in UI with 4o and o1
=> added context type for when internet search tool is used

web/src/app/admin/api-key/page.tsx, web/src/app/admin/token-rate-limits/page.tsx, web/src/app/ee/admin/groups/page.tsx, web/src/app/layout.tsx, web/src/components/errorPages/CloudErrorPage.tsx, web/src/components/errorPages/ErrorPage.tsx, web/src/components/errorPages/ErrorPageLayout.tsx, web/src/components/logo/Logo.tsx, web/src/components/ui/createButton.tsx
=> Multi tenant specific error page

backend/onyx/llm/chat_llm.py, backend/onyx/llm/factory.py, backend/onyx/llm/llm_provider_options.py, backend/onyx/llm/utils.py, web/src/lib/hooks.ts
https://linear.app/danswer/issue/DAN-1436/different-timeout-for-reasoning-models
Tested locally, previously timed out -> doesn't timeout anymore.
=> Increase timeout for reasoning models + make o1 available by default

web/src/app/assistants/mine/AssistantCard.tsx
Previously became red.
https://linear.app/danswer/issue/DAN-1438/red-background-color-on-assistant-option-hover
Tested locally
=> Fix for red background

web/src/components/assistants/StarterMessage.tsx
https://linear.app/danswer/issue/DAN-1437/improve-overflow-on-starter-messages
Now looks like:
Locally
=> Fix starter message overflow

backend/onyx/connectors/airtable/airtable_connector.py, backend/tests/daily/connectors/airtable/test_airtable_basic.py, web/src/lib/connectors/connectors.tsx
https://linear.app/danswer/issue/DAN-1440/add-support-for-shares-in-airtable-connector
UT + local
=> Support share/view IDs for Airtable

backend/onyx/background/celery/tasks/shared/tasks.py, backend/onyx/redis/redis_connector_credential_pair.py, backend/onyx/redis/redis_connector_delete.py, backend/onyx/redis/redis_connector_doc_perm_sync.py, backend/onyx/redis/redis_connector_prune.py
Fixes DAN-1444.
https://linear.app/danswer/issue/DAN-1444/use-ignore-result-in-send-task-for-most-celery-tasks
This is filling up redis.
=> ignore result when using send_task on lightweight tasks

backend/onyx/agents/agent_search/deep_search/shared/expanded_retrieval/nodes/rerank_documents.py, backend/onyx/context/search/pipeline.py, backend/onyx/context/search/postprocessing/postprocessing.py
Updated reranking function to not require a whole SearchQuery, but a more narrow set
(query_str and rerank_settings)
Changes have been propagated up, staring with  semantic_reranking at the bottom.
Tested locally with one query and both Basic Search and Agent Search 
=> updated rerank function arguments

backend/scripts/debugging/onyx_vespa.py
Adds functionality for deleting documents by tenant (useful for inactive tenants we want to purge)
Tested with existing tenant 
=> Add delete all for tenants in Vespa

backend/ee/onyx/server/query_and_chat/query_backend.py, backend/onyx/agents/agent_search/deep_search/shared/expanded_retrieval/nodes/retrieve_documents.py, backend/onyx/agents/agent_search/shared_graph_utils/utils.py, backend/onyx/context/search/pipeline.py, backend/onyx/context/search/preprocessing/preprocessing.py, backend/onyx/natural_language_processing/utils.py, backend/onyx/server/gpts/api.py, backend/onyx/tools/base_tool.py, backend/onyx/tools/models.py, backend/onyx/tools/tool.py, backend/onyx/tools/tool_implementations/custom/custom_tool.py, backend/onyx/tools/tool_implementations/images/image_generation_tool.py, backend/onyx/tools/tool_implementations/internet_search/internet_search_tool.py, backend/onyx/tools/tool_implementations/search/search_tool.py
All parallel queries go through the intent model which is not needed. Only the initial user query should go through that one.
For Evan:
- Address all the TODOs
- Make sure the other flows do not use intent model
- Double check all Tools still work correctly
- Try to make the design maintainable (no string checks)
=> Fix Agent Slowness

backend/onyx/background/celery/tasks/doc_permission_syncing/tasks.py, backend/onyx/background/celery/tasks/monitoring/tasks.py, backend/onyx/connectors/slack/utils.py, backend/onyx/db/users.py, backend/onyx/document_index/vespa/index.py
This is a general pass at reducing the number of unnecessary / spammy error logs in our backgrounds pods. Each exception has a link to a relevant example in Grafana + the relevant change
[Tenant ID exceptions](https://g-dfa4b7be0c.grafana-workspace.us-east-2.amazonaws.com/explore?schemaVersion=1&panes=%7B%22g7r%22:%7B%22datasource%22:%22ce39t0tyjl6o0b%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bjob%3D%5C%22danswer%2Fcelery-worker-primary%5C%22%7D%20%7C%3D%20%60ERROR%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22ce39t0tyjl6o0b%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D%7D&orgId=1)
Fixed miscellaneous tenant ID exceptions
- Updated and added alerting in Alembic check to …
=> Reduce errors in workers

web/src/components/credentials/actions/CreateCredential.tsx
https://linear.app/danswer/issue/DAN-1450/weird-look-on-credential-form
=> Color fix / width

backend/Dockerfile
Fixes DAN-1449.
https://linear.app/danswer/issue/DAN-1449/add-vim-and-nano-to-backend-image
=> add nano and vim to base image

backend/onyx/background/celery/tasks/monitoring/tasks.py, backend/onyx/background/celery/tasks/vespa/tasks.py, backend/onyx/connectors/google_drive/connector.py, backend/onyx/db/chat.py, backend/onyx/main.py, backend/onyx/server/settings/store.py
1. **Lock Reacquisition Error**
- Leads to `Lock not owned on completion` for Vespa sync task
- Possibly caused by high latency operations (occurs for high doc count tenants)
- Added some logging
- Status: Unresolved
2. **Missing Sync Record**
- Caused by unsuccessful creation of sync records for doc sets
- Occurs in `monitor_document_set_taskset` function
- Status: Resolved (warning may persist temporarily)
3. **Non-initial Index Attempt**
4. **KV Store Settings Error**
- Empty custom Exception class not logging in error logs
- Status: Resolved / should be debuggable now
5. **API Server Spam**
6. **TTL Management Task Error**
- Improper handling of already deleted chat sessions
- Status: Resolved
7. [x] Minor logging improvements
- Deleted non-existent tenant accounts that were still …
=> Reduce background errors

backend/onyx/background/celery/tasks/shared/tasks.py, backend/onyx/document_index/vespa/deletion.py, backend/onyx/seeding/load_docs.py
Current issue:
- Chunk count not properly counted, not updated
- This leads to seeded docs not being deleted by our background processes as we assume their UUIDs were generated with the "old" system (we use presence of chunk counts to deleting the UUID process)
=> Seeding count issue

backend/onyx/agents/agent_search/deep_search/shared/expanded_retrieval/nodes/rerank_documents.py, backend/onyx/agents/agent_search/models.py, backend/onyx/chat/answer.py, backend/tests/unit/onyx/chat/test_answer.py, backend/tests/unit/onyx/chat/test_skip_gen_ai.py
If there is no GPU and a local reranking model is used, we will not rerank.
Implemented using:
-  rerank_settings.rerank_type is None
- gpu_status_request() used at the beginning of the  call. 
- new variable graph_config.behavior.allow_agent_reranking
as indicators
Linear: 
https://linear.app/danswer/issue/DAN-1454/disable-re-ranking-in-agent-search-if-local-model-wo-gpu-is-used
Tested locally on Mac w/ GPU and at scale.onyx w/o GPU. In the scale test, reranking was omitted.
=> no reranking if local model w/o GPU for Agent Search

backend/onyx/db/models.py, backend/onyx/db/slack_channel_config.py, backend/onyx/onyxbot/slack/handlers/handle_message.py, backend/onyx/onyxbot/slack/listener.py, backend/onyx/server/manage/models.py, backend/onyx/server/manage/slack_bot.py, web/src/app/admin/bots/[bot-id]/channels/SlackChannelConfigCreationForm.tsx, web/src/app/admin/bots/[bot-id]/channels/SlackChannelConfigFormFields.tsx, web/src/app/admin/bots/[bot-id]/lib.ts, web/src/lib/types.ts
Let users disable default slackbot 
=> Add  default slack bot disabling

backend/alembic/versions/1a03d2c2856b_add_indexes_to_document__tag.py, backend/onyx/db/models.py
Fixes DAN-1460.
https://linear.app/danswer/issue/DAN-1460/add-index-to-document-tagtag-id
=> add index to document__tag.tag_id

web/src/app/chat/input/LLMPopover.tsx
^
Tested locally, behavior is the same for standard use cases.
=> Adjust behavior when display_model_names is null

.github/workflows/pr-python-connector-tests.yml, backend/onyx/connectors/web/connector.py, backend/tests/daily/connectors/web/test_web_connector.py, web/src/lib/connectors/connectors.tsx
Fixes DAN-1462.
https://linear.app/danswer/issue/DAN-1462/add-advanced-setting-for-web-connector-to-scroll-before-scraping
=> support scrolling before scraping

backend/alembic/versions/acaab4ef4507_remove_inactive_ccpair_status_on_.py, backend/onyx/background/celery/tasks/indexing/tasks.py, backend/onyx/background/celery/tasks/pruning/tasks.py, backend/onyx/background/indexing/run_indexing.py, backend/onyx/connectors/dropbox/connector.py, backend/onyx/connectors/factory.py, backend/onyx/connectors/github/connector.py, backend/onyx/connectors/interfaces.py, backend/onyx/connectors/notion/connector.py, backend/onyx/connectors/onyx_jira/connector.py, backend/onyx/db/credentials.py, backend/onyx/db/enums.py, backend/onyx/server/documents/cc_pair.py, backend/onyx/server/documents/credential.py, backend/tests/integration/common_utils/managers/connector.py, web/src/app/admin/configuration/search/UpgradingPage.tsx, web/src/app/admin/connector/[ccPairId]/ReIndexButton.tsx, web/src/app/admin/connector/[ccPairId]/lib.ts, web/src/app/admin/connector/[ccPairId]/page.tsx, web/src/app/admin/connector/[ccPairId]/types.ts, web/src/app/admin/connectors/[connector]/AddConnectorPage.tsx, web/src/app/admin/indexing/status/CCPairIndexingStatusTable.tsx, web/src/components/HoverPopup.tsx, web/src/components/Status.tsx, web/src/components/credentials/CredentialSection.tsx, web/src/components/ui/badge.tsx, web/src/components/ui/button.tsx, web/src/lib/ccPair.ts, web/src/lib/types.ts
Adds connector validation for ccpair creation / credential swapping.
New enum for ccpair status: `invalid`- marks ccpairs which have an invalid configuaiton
https://github.com/user-attachments/assets/50b80ccb-e2e8-4648-ae0c-6b27fea31edd
=> Connector validation

backend/onyx/chat/chat_utils.py, backend/onyx/chat/models.py, backend/onyx/chat/process_message.py, backend/onyx/llm/models.py, web/src/app/chat/ChatPage.tsx, web/src/app/chat/interfaces.ts, web/src/app/chat/lib.tsx
https://linear.app/danswer/issue/DAN-1464/use-refined-answer-if-improvement-in-history-in-agent-search
Use the refined answer as message history when it is better, otherwise stick with the original answer
to be tested by joachim
=> Agent search history displayed answer

backend/onyx/connectors/gitbook/connector.py
Didn't handle nested pages / un-edited pages.
https://linear.app/danswer/issue/DAN-1468/fix-gitbook-connector-issues
Tested locally.
=> Fix gitbook connector issues

web/src/app/chat/lib.tsx
minor fix for use_agentic_search param type
n/a
=> coerce useLanggraph to boolean

backend/scripts/debugging/onyx_redis.py
Fixes DAN-1472.
https://linear.app/danswer/issue/DAN-1472/fix-redis-tool
=> tool fixes

backend/model_server/encoders.py
Fixes DAN-1478.
https://linear.app/danswer/issue/DAN-1478/dont-spam-the-logs-with-embedding-text-when-we-get-auth-errors-to-a
=> don't spam the logs with texts on auth errors

web/src/app/chat/ChatPage.tsx
Improves auto scroll
- If auto scroll enabled, typical behavior
- If not, scroll and leave gap such that human message is at top and then no auto scrol
=> Improved auto scroll

backend/ee/onyx/server/query_and_chat/token_limit.py, backend/onyx/chat/process_message.py, backend/onyx/file_store/utils.py, backend/onyx/server/query_and_chat/token_limit.py, backend/onyx/utils/threadpool_concurrency.py, backend/tests/unit/onyx/utils/test_threadpool_contextvars.py
https://linear.app/danswer/issue/DAN-1471/parallelism-should-respect-contextvars
Our utils for running functions with thread-level parallelism didn't pass contextvars through, i.e. tenant id. Now they do! Should be safe to use with i.e. acquiring a db session, although in most cases there isn't a need to acquire sessions in parallel.
New unit tests; they fail without the code changes
=> thread utils respect contextvars

backend/onyx/chat/process_message.py, backend/onyx/chat/prompt_builder/answer_prompt_builder.py, backend/onyx/prompts/chat_prompts.py, backend/tests/unit/onyx/chat/test_answer.py
Addresses https://linear.app/danswer/issue/DAN-1479/gpt-o-series-code-blocks
Added to the default system prompt construction to tell the model to use markdown code blocks. To get o3 mini to work, I had to explicitly specify the use of backticks
Tested in UI; without the changes Our code block parser often gets some of it right but misses parts that lead to unreadable code and comments that are interpreted as markdown headings.
=> Fix gpt o-series code block formatting

web/src/app/admin/assistants/AssistantEditor.tsx, web/src/app/assistants/edit/[id]/page.tsx, web/src/app/assistants/new/page.tsx
We expose name / message as a single value for end-users (built in starter messages can modify both). Currently, updated message doesn't update name– should both have same value.
=> Fix starter message editing

backend/onyx/server/manage/slack_bot.py, web/src/app/admin/bots/[bot-id]/channels/SlackChannelConfigCreationForm.tsx, web/src/app/admin/bots/[bot-id]/channels/SlackChannelConfigFormFields.tsx
Fixes https://github.com/onyx-dot-app/onyx/issues/4095
Very slow API from Slack for listing channels- if >200 channels, let users input their channel name
With slack bot configuration
- Mock having more than 200 channels
=> Fix slackbot rate limit on selection of channels

web/src/app/chat/input/LLMPopover.tsx, web/src/app/chat/sessionSidebar/HistorySidebar.tsx, web/src/components/ui/truncatedText.tsx, web/src/lib/hooks.ts
=> Text overflow logic

backend/alembic/versions/da42808081e3_migrate_jira_connectors_to_new_format.py, backend/onyx/connectors/onyx_jira/connector.py, backend/tests/daily/connectors/jira/test_jira_basic.py, web/src/lib/connectors/connectors.tsx
https://linear.app/danswer/issue/DAN-1482/add-ability-to-pull-in-all-jira-projects-with-a-single-connector
- creating a connector with main + upgrading to this new version + verifying old connector still works 
- creating a connector with no project specfieid
- creating a connector with a project specified
=> Add option to index all Jira projects

backend/onyx/connectors/github/connector.py, web/src/components/admin/connectors/ConnectorTitle.tsx, web/src/lib/connectors/connectors.tsx
https://linear.app/danswer/issue/DAN-1485/add-ability-to-have-a-single-connector-index-all-of-github
Tested locally with single repo / everything (our org).
=> Add ability to index all of Github

backend/onyx/db/connector_credential_pair.py, backend/onyx/db/document.py, backend/onyx/db/engine.py, backend/onyx/db/index_attempt.py, backend/onyx/redis/redis_connector_index.py, backend/onyx/server/documents/cc_pair.py, backend/onyx/server/documents/connector.py, backend/onyx/server/documents/models.py
https://linear.app/danswer/issue/DAN-1477/fix-slowness-of-manageadminconnectorindexing-status
Improve the performance of the /manage/admin/connector/indexing-status endpoint.
Main optimizations:
- eager loading of relationships
- letting sql handle loops (i.e. moving db queries out of for loops)
- thread level parallelism
tested in UI: ~2000 connectors and 10mil index attempts yields 3.5-5.5s endpoint runtimes. roughly split by 1/3 first batch of parallel queries, 1/3 second batch of parallel queries, 1/3 remaining code.
=> faster indexing status at scale plus minor cleanups

backend/ee/onyx/external_permissions/sync_params.py, backend/onyx/connectors/confluence/onyx_confluence.py, backend/onyx/connectors/confluence/utils.py
Pagination wasn't working for either data center or cloud -> when you had more than 200 users you would only get a partial group sync. This fixes that.
Tested with data center with 502 users + cloud with 8 users but manually setting page size to 1.
=> Fix confluence permission syncing at scale

backend/onyx/connectors/google_drive/doc_conversion.py, backend/onyx/connectors/google_drive/models.py
Problem:
Based on the Slack thread: https://onyx-dot-app.slack.com/archives/C056265VB1N/p1739853716830199?thread_ts=1733379700.624259&cid=C056265VB1N
Spreadsheets that are uploaded to Google Drive (which get a MIME of `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet`) end up having empty content, resulting inaccurate search results.
Solution:
Download the file and use pandas to extract the data and apply the same transforms as if it is a `application/vnd.google-apps.spreadsheet`.
Smoke tested the following and all passed.
- Created a Google Drive connector for a specific folder with a mix of `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet` and  `application/vnd.google-apps.spreadsheet` files which was then connected to a bot and it correctly performed …
=> Content of .xlsl are not properly read during indexing.

backend/onyx/background/celery/tasks/shared/tasks.py
Fixes DAN-1488.
https://linear.app/danswer/issue/DAN-1488/log-num-processed-tenant
=> log processed tenant count

backend/onyx/db/persona.py
Thank you to Emesron!
Fix an issue with the visibility filters for personas:
1. Previously, the code first OR'd `is_public` then AND'd `is_visible` to the entire `where_clause`, which didn't correctly group the conditions. Now we properly group them together to ensure personas must be both public AND visible.
Users should be able to see:
- Public and visible personas
- Personas shared with them via user groups
- Personas they created directly
=> Improve viewable assistant logic

backend/onyx/background/indexing/job_client.py, backend/onyx/onyxbot/slack/blocks.py, backend/onyx/onyxbot/slack/handlers/handle_buttons.py, backend/onyx/onyxbot/slack/handlers/handle_message.py, backend/onyx/onyxbot/slack/handlers/handle_regular_answer.py, backend/onyx/onyxbot/slack/listener.py, backend/onyx/onyxbot/slack/utils.py
=> Improved tenant handling for slack bot

web/src/app/chat/input-prompts/InputPrompts.tsx, web/src/app/chat/input-prompts/PromptCard.tsx, web/src/app/chat/input/ChatInputBar.tsx, web/src/app/chat/modal/UserSettingsModal.tsx, web/src/components/user/UserProvider.tsx, web/src/lib/types.ts
- Minor update so no flashing in Prompt shortcuts on editing 
- Clean up user setting logic (inherits from workspace setting) + make sure users can set their temperature override
=> User setting clean up

backend/onyx/db/chat.py, backend/onyx/server/query_and_chat/models.py, web/src/app/chat/lib.tsx
Agent Search retrieval from get-chat-session was broken bc we switched to the (correct) way of using is_agentic to determine the display method for agentic messages, but (incorrectly) didn't propagate the value of is_agentic on backend and frontend (oops).
tested in UI
=> fix propagation of is_agentic

backend/ee/onyx/db/user_group.py, backend/ee/onyx/server/tenants/billing.py
We should not update roles of non-curators on relationship changes (edge case where user used to be curator and now is admin)
Locally, edge case before and after
=> Fix user group edge case

backend/onyx/db/persona.py
Curators should be able to edit featured assistants if they own them. They should NOT be able to modify the "featured" status
=> Fix curator default persona editing

web/src/app/admin/connector/[ccPairId]/page.tsx, web/src/components/ui/alert.tsx
Fixes the below 
Updated to the following
=> Cleaner palette for dark mode index attempt failure

web/src/app/admin/configuration/document-processing/page.tsx
The url for https://unstructured.io/docs has been updated on their site to https://docs.unstructured.io/welcome
visually 
=> Update Unstructured documentation URL to new location

backend/ee/onyx/onyxbot/slack/handlers/handle_standard_answers.py, backend/onyx/connectors/slack/utils.py, backend/onyx/db/models.py, backend/onyx/onyxbot/slack/blocks.py, backend/onyx/onyxbot/slack/constants.py, backend/onyx/onyxbot/slack/handlers/handle_buttons.py, backend/onyx/onyxbot/slack/handlers/handle_message.py, backend/onyx/onyxbot/slack/handlers/handle_regular_answer.py, backend/onyx/onyxbot/slack/handlers/utils.py, backend/onyx/onyxbot/slack/listener.py, backend/onyx/onyxbot/slack/models.py, backend/onyx/onyxbot/slack/utils.py, backend/onyx/server/manage/models.py, backend/onyx/server/manage/slack_bot.py, backend/scripts/document_seeding_prep.py, web/src/app/admin/bots/[bot-id]/channels/SlackChannelConfigCreationForm.tsx, web/src/app/admin/bots/[bot-id]/channels/SlackChannelConfigFormFields.tsx, web/src/app/admin/bots/[bot-id]/lib.ts, web/src/lib/types.ts
We want to enable our customers to configure an Onyx bot for a channel such that the bot is able to respond as an ephemeral message to the user who is asking the question. That provides us with the ability to leverage documents for the search that a user has private access to, not just documents that are public to everyone.  
See details in the current design doc.
Ticket: https://linear.app/danswer/issue/DAN-1489/enable-ephemeral-replies-by-answer-bot-in-group-channels
Locally:
- set up new bot in test mode
- configured two channels, one with the new is_ephemeral parameter=True, the other one set to false
- for each, I sent a request to the bot from
- the channel
- a thread
- in the channel with the ephemeral setting I check for both question sources (channel vs thread) the button clicks …
=> Ephemeral slack messages as responses to user questions

backend/ee/onyx/main.py, backend/onyx/main.py
Fixes DAN-1526.
https://linear.app/danswer/issue/DAN-1526/oauth-endpoint-went-missing-causing-auth-popups-to-reset-constantly
=> oauth router went missing?

backend/ee/onyx/server/oauth/confluence_cloud.py
Fixes DAN-1521.
https://linear.app/danswer/issue/DAN-1521/add-needed-oauth-scope-for-confluence-permissions-sync
=> add scope needed for permission sync

backend/onyx/agents/agent_search/deep_search/initial/generate_initial_answer/nodes/generate_initial_answer.py, backend/onyx/agents/agent_search/deep_search/main/nodes/generate_validate_refined_answer.py, backend/onyx/agents/agent_search/deep_search/main/operations.py, backend/onyx/agents/agent_search/deep_search/shared/expanded_retrieval/nodes/format_results.py, backend/onyx/agents/agent_search/deep_search/shared/expanded_retrieval/nodes/retrieve_documents.py, backend/onyx/agents/agent_search/orchestration/nodes/call_tool.py, backend/onyx/agents/agent_search/orchestration/nodes/choose_tool.py, backend/onyx/agents/agent_search/orchestration/nodes/use_tool_response.py, backend/onyx/agents/agent_search/orchestration/states.py, backend/onyx/agents/agent_search/shared_graph_utils/constants.py, backend/onyx/chat/llm_response_handler.py, backend/onyx/chat/stream_processing/citation_processing.py, backend/onyx/context/search/models.py, backend/onyx/context/search/pipeline.py, backend/onyx/context/search/preprocessing/preprocessing.py, backend/onyx/context/search/retrieval/search_runner.py, backend/onyx/tools/models.py, backend/onyx/tools/tool_implementations/search/search_tool.py, backend/onyx/tools/tool_implementations/search/search_utils.py, backend/onyx/tools/tool_runner.py, backend/onyx/utils/threadpool_concurrency.py, backend/tests/unit/onyx/utils/test_threadpool_concurrency.py, backend/tests/unit/onyx/utils/test_threadpool_contextvars.py
Before this PR, if a user did basic search with
- old "Agentic" search (LLM-based document filtering) enabled
- a reranking model enabled
The time-to-first-docs was pretty high because we were running filtering and reranking before sending docs. 
We also decided to look for other opportunities to reduce latency. In particular, the first LLM call we make to decide what tool and args to use (if any) often takes as long as a second. In that time, we now run 
- our intent model (classifying the query as keyword or non-keyword)
- query embedding (for use in vector db retrieval)
in parallel with tool choice.
All told, there used to be 1-2 seconds of latency after choosing a tool that is down to 0.1-0.2s with these changes, with the caveat that at worst the newly introduced parallelism makes the …
=> improved basic search latency

web/src/app/admin/configuration/llm/interfaces.ts, web/src/app/admin/indexing/status/FilterComponent.tsx, web/src/components/icons/icons.tsx
- Consistent icons + minor dark mode nit
=> Ensure consistent UX

backend/onyx/context/search/retrieval/search_runner.py
SearchQuery is frozen, can't update like that.
:eyes:
=> Fix frozen model issue

backend/onyx/background/celery/memory_monitoring.py, backend/onyx/background/celery/tasks/indexing/tasks.py, backend/supervisord.conf, deployment/docker_compose/docker-compose.dev.yml, deployment/docker_compose/docker-compose.gpu-dev.yml, deployment/docker_compose/docker-compose.multitenant-dev.yml, deployment/docker_compose/docker-compose.prod-cloud.yml, deployment/docker_compose/docker-compose.prod-no-letsencrypt.yml, deployment/docker_compose/docker-compose.prod.yml, deployment/docker_compose/docker-compose.search-testing.yml
Fixes https://linear.app/danswer/issue/DAN-1544/add-basic-memory-loggin
Ran docker compose locally, verified I saw the logs as expected in the dir I expected + verified that on container restart the logs were persisted.
=> Add basic memory logging

backend/onyx/connectors/models.py
^
Log is here: https://github.com/danswer-ai/danswer/blob/main/backend/onyx/background/indexing/run_indexing.py#L430-L432
Tested indexing locally
=> Eliminate extremely long log line for large checkpointds

backend/alembic/versions/4d58345da04a_lowercase_user_emails.py
Fixes DAN-1574.
https://linear.app/danswer/issue/DAN-1574/email-lowercase-conflicts
=> handle conflicts on lowercasing emails

backend/alembic_tenants/versions/3b45e0018bf1_add_new_available_tenant_table.py, backend/ee/onyx/server/tenants/provisioning.py, backend/ee/onyx/server/tenants/schema_management.py, backend/ee/onyx/server/tenants/user_mapping.py, backend/onyx/background/celery/apps/light.py, backend/onyx/background/celery/apps/monitoring.py, backend/onyx/background/celery/tasks/beat_schedule.py, backend/onyx/background/celery/tasks/tenant_provisioning/tasks.py, backend/onyx/configs/app_configs.py, backend/onyx/configs/constants.py, backend/onyx/db/models.py
Maintain a list of ready tenants on standby to provision new tenants / users into. Mitigates the 9+ second latency on first-time registration.
---
Fixes https://linear.app/danswer/issue/DAN-1212/separate-page-for-users-during-creation-of-onyx-some-indication-that
=> Tenants on standby

backend/alembic/versions/df46c75b714e_add_default_vision_provider_to_llm_.py, backend/onyx/configs/app_configs.py, backend/onyx/connectors/vision_enabled_connector.py, backend/onyx/context/search/postprocessing/postprocessing.py, backend/onyx/db/llm.py, backend/onyx/db/models.py, backend/onyx/file_processing/image_summarization.py, backend/onyx/llm/factory.py, backend/onyx/prompts/image_analysis.py, backend/onyx/server/manage/llm/api.py, backend/onyx/server/manage/llm/models.py, web/src/app/admin/configuration/llm/interfaces.ts, web/src/app/admin/settings/SettingsForm.tsx, web/src/app/admin/settings/hooks/useVisionProviders.ts, web/src/app/admin/settings/interfaces.ts, web/src/app/chat/message/Messages.tsx, web/src/components/llm/LLMSelector.tsx, web/src/lib/api/visionLLM.ts, web/src/lib/llm/visionLLM.ts
Fixes https://linear.app/danswer/issue/DAN-1552/support-custom-promptsmodel-selection-for-image-embedding 
- Relevant Docs PR: https://github.com/onyx-dot-app/documentation/compare/llm_vision_overrides?expand=1
Locally, env variables set, various vision compatible llms during indexing + query-time
=> Support image indexing customization

backend/alembic/versions/df46c75b714e_add_default_vision_provider_to_llm_.py, backend/onyx/db/models.py
Fixes DAN-1579.
https://linear.app/danswer/issue/DAN-1579/fix-broken-vision-unique-constraint
=> unique constraint here doesn't work

backend/onyx/connectors/confluence/utils.py
Fixes DAN-1578.
https://linear.app/danswer/issue/DAN-1578/handle-mediatype-in-confluence-connector-safely
=> safe handling for mediaType in confluence connector in all places

backend/onyx/connectors/slack/connector.py
Fixes DAN-1582.
https://linear.app/danswer/issue/DAN-1582/reduce-slack-parallelism
=> change max workers to 2 for the moment

backend/onyx/connectors/google_drive/connector.py
Fixes https://linear.app/danswer/issue/DAN-1564/drive-folder-url-id-parsing
If a user accidentally or purposefully includes params in the drvie folder url they want connected, we should strip off the params when extracting the folder id.
hopefully integration tests cover this, if not I'll run it in the UI
=> better drive url cleaning

web/src/components/credentials/lib.ts
Fixes DAN-1584.
https://linear.app/danswer/issue/DAN-1584/fix-salesforce-credential-validator
didn't work properly with boolean field, form could not submit unless sandbox checkbox was manually modified
=> add proper boolean validation to field

backend/onyx/auth/users.py
Fixes https://linear.app/danswer/issue/DAN-1587/users-cannot-login-with-basic-auth
Tested basic auth locally with ee off
=> Fix basic auth for non-ee

web/src/components/Modal.tsx
noticed that lots of modals overflow past the max height, which makes the modal unusable.
relates to: https://github.com/onyx-dot-app/onyx/issues/698
opened devtools and added `overflow-auto`, which let me scroll to the remaining content
=> add overflow-auto to show all content in Modal

backend/onyx/chat/answer.py, backend/onyx/setup.py, backend/onyx/utils/gpu_utils.py, backend/tests/unit/onyx/chat/test_answer.py, backend/tests/unit/onyx/chat/test_skip_gen_ai.py
Fixes https://linear.app/danswer/issue/DAN-1628/fix-ramp-gpu-status-request-failure
IT
=> Fix GPU status request in sync flow

backend/onyx/onyxbot/slack/handlers/handle_message.py, backend/onyx/server/manage/slack_bot.py
Fixes https://linear.app/danswer/issue/DAN-1624/investigate-slack-bot-not-answering-for-frc.
Also switches default slack bot behavior to not show "Still needs help" option.
Tested locally
=> Small slack bot fixes

backend/onyx/configs/app_configs.py, backend/onyx/connectors/google_drive/connector.py, backend/onyx/connectors/google_drive/doc_conversion.py, backend/tests/daily/connectors/google_drive/conftest.py, backend/tests/daily/connectors/google_drive/consts_and_utils.py, backend/tests/daily/connectors/google_drive/test_admin_oauth.py, backend/tests/daily/connectors/google_drive/test_service_acct.py, backend/tests/daily/connectors/google_drive/test_user_1_oauth.py
Fixes DAN-1631.
https://linear.app/danswer/issue/DAN-1631/google-drive-size-threshold-for-docs
=> add size threshold for google drive

backend/onyx/connectors/zendesk/connector.py
We were seeing some logs where we were requesting .../users/-1, which the code explicitly guards against. We believe the only way this is possible is if the value of author_id when it reaches _fetch_author was the int -1 instead of the expected string, so we simply cast it during the check to catch this case.
Going to rely on automated tests for this one, as all it does is codify our assumption that the id used is a string
=> typing fix

backend/onyx/background/celery/apps/app_base.py, backend/onyx/background/celery/apps/primary.py
Fixes DAN-1641.
https://linear.app/danswer/issue/DAN-1641/correct-redis-key-namespace-for-some-celery-stuff
=> use correct namespace in redis for certain keys

backend/onyx/background/celery/tasks/connector_deletion/tasks.py, backend/onyx/db/document.py
Fixes https://linear.app/danswer/issue/DAN-1635/connector-deletion-task-fails-due-to-pk-dependency
Fixes https://github.com/onyx-dot-app/onyx/issues/4266
=> PK Dependency fix for deletion

backend/onyx/connectors/google_drive/connector.py
Fixes DAN-1651.
https://linear.app/danswer/issue/DAN-1651/google-drive-partial-function-call-broke
=> fix broken function call

deployment/data/nginx/run-nginx.sh
The docker container name is slightly wrong, and this commit fixes it.
No testing, it's a string change
=> Fixes docker logs helper text in run-nginx.sh

backend/onyx/connectors/google_drive/connector.py, backend/onyx/connectors/google_drive/file_retrieval.py
We were overwriting the checkpoint map for service account indexing due to a last-minute change; this causes us to not overwrite those entries.
Tested in UI
=> fix issue with drive connector service account indexing

backend/onyx/onyxbot/slack/handlers/handle_buttons.py, backend/onyx/onyxbot/slack/listener.py, backend/onyx/onyxbot/slack/utils.py
Slack native rate limit handler
Fixes DAN-1665.
https://linear.app/danswer/issue/DAN-1665/use-slack-sdk-native-rate-limiter-in-the-bot
=> use slack's built in rate limit handler for the bot

backend/onyx/chat/process_message.py, backend/onyx/db/chat.py
Chat sessions are not updated their updated time when chat messages are inserted
Fixes https://linear.app/danswer/issue/DAN-1662/chat-history-ordering
=> Fix session touching

backend/onyx/connectors/google_drive/connector.py, backend/onyx/connectors/google_drive/doc_conversion.py, backend/onyx/connectors/google_drive/file_retrieval.py, backend/tests/daily/connectors/google_drive/consts_and_utils.py, backend/tests/daily/connectors/google_drive/test_service_acct.py, web/src/app/admin/connectors/[connector]/AddConnectorPage.tsx, web/src/lib/connectors/connectors.tsx
Fixes https://linear.app/danswer/issue/DAN-1655/proper-handling-for-include-files-shared-with-me-getting-files-out-of
We were retrieving the file by attempting to impersonate the file owner, who is not guaranteed to be part of the organization (i.e. not guaranteed to be impersonate-able by the service account). Now we use whichever user successfully found the folder, which will be the admin for oauth and an arbitrary impersonated user for service accounts.
Tested in UI, will write a connector test for this before merging
=> fixed shared folder issue

backend/onyx/background/celery/tasks/connector_deletion/tasks.py
Fixes https://linear.app/danswer/issue/DAN-1635/connector-deletion-task-fails-due-to-pk-dependency
=> Fix deletion

backend/onyx/connectors/highspot/client.py
This pull request includes a small but important change to the `backend/onyx/connectors/highspot/client.py` file. The change ensures that the `base_url` attribute always ends with a single slash, which helps prevent potential issues with URL concatenation.
* [`backend/onyx/connectors/highspot/client.py`](diffhunk://#diff-0672c9a2a137bd7353a70a5f9aad26c7157de341dec4cb1ad2c522bbcbf78436L78-R78): Modified the `base_url` initialization to ensure it always ends with a single slash by using `rstrip("/")` and appending a slash.## Description
Tested by running it in the terminal
=> fix: ensure base_url ends with a trailing slash

backend/ee/onyx/server/tenants/provisioning.py
Fixes https://linear.app/danswer/issue/DAN-1693/remove-duped-notifications-to-control-plane
=> Notify control plane once

backend/onyx/chat/prune_and_merge.py, backend/onyx/document_index/vespa/chunk_retrieval.py
We need to have additional debug logging to monitor the section merge process in order to trouble-shoot
some answers.
Added logging (numbers of document ids, numbers of sections, number of tokens, etc.) after Search Retrieval, Merging, and Pruning.
Here is the Linear link: https://linear.app/danswer/issue/DAN-1626/dalberg-projects-not-being-foundcited-as-expected
Locally
=> Additional logging for the path from Search Results to LLM Context

backend/onyx/natural_language_processing/utils.py
Fixes https://linear.app/danswer/issue/DAN-1701/unicode-encoding-errors-when-parsing-file
Occasionally when we retrieve the text of i.e. a pdf, the text contains unicode characters that some HuggingFaceTokenizers take issue with, raising a "TextInputSequence must be str" error despite the fact that the input is in fact a str. A workaround when this happens is to encode the string as ASCII ignoring unicode characters then decoding. We wouldn't want to do this all the time because in many cases it's an expensive no-op, hence the error handling approach.
tested in UI
=> fallback to ignoring unicode chars when huggingface tokenizer fails

.github/workflows/pr-mit-integration-tests.yml
Fixes DAN-1713.
https://linear.app/danswer/issue/DAN-1713/fix-job-name-for-mit-integration-tests
=> disambiguate job name from ee version

backend/onyx/connectors/fireflies/connector.py
Addresses https://linear.app/danswer/issue/DAN-1556/address-missing-fireflies-docs-in-our-cloud
Mostly comments for future connector users; it appears that in some cases the fireflies connector silently doesn't retrieve certain transcripts with certain (potentially old) API keys. I also noticed that even doing a full re-indexing with the old api key pulled in a few new transcripts, which might point to some small timing issues. 
Tested in UI
=> minor improvement to fireflies connector

web/src/app/admin/embeddings/RerankingFormPage.tsx
Fixes https://linear.app/danswer/issue/DAN-1592/aws-re-ranking-bugged
We previously allowed users to create a bedrock reranker with an empty API key, letting them finish updating their settings and only later during search getting an error that no API key was set.
tested in UI
=> ensure bedrock model contains API key

backend/onyx/redis/redis_connector_doc_perm_sync.py
Fixes DAN-1666 (missed one).
https://linear.app/danswer/issue/DAN-1666/revert-permission-sync-to-medium-priority
=> also set permission upsert to medium priority

backend/onyx/context/search/pipeline.py, backend/onyx/tools/tool_implementations/search/search_tool.py
In the Search pipeline, we need to first prune, and then merge. This desired behavior was not adhered to anymore and has been re-established.
prompt_config and contextual_pruning _config both need to be set for this to work.
This fix is also related to https://linear.app/danswer/issue/DAN-1626/dalberg-projects-not-being-foundcited-as-expected
Key changes:
- passed contextual_pruning_config to Search pipeline
- used prune_and_merge to create final chunks
- if prompt_config not done or contextual_pruning_config not available, default to earlier behavior of calling _merge_sections
Locally. Tested with default Search, and then also an Assistant that does not do AI filtering
=> Prune First, then Merge (Simpler Approach)

backend/alembic/versions/f71470ba9274_add_prompt_length_limit.py, backend/onyx/db/models.py, web/src/app/admin/assistants/AssistantEditor.tsx
Fixes https://linear.app/danswer/issue/DAN-1725/max-prompt-length-for-assistants
=> Max prompt length

backend/ee/onyx/external_permissions/post_query_censoring.py, backend/onyx/context/search/pipeline.py
Previously, we would re-order chunks in the salesforce perm sync (they would be grouped by source in a random order)
Tested running locally w/ salesforce.
=> Another fix for Salesforce perm sync

web/src/lib/llm/utils.ts
Fixes https://linear.app/danswer/issue/DAN-1738/vision-supporting-models-not-displayed-properly
=> Add more flexible vision support check

backend/onyx/connectors/google_drive/connector.py, backend/onyx/utils/threadpool_concurrency.py
Fixes https://linear.app/danswer/issue/DAN-1745/tons-of-gsuite-users-without-drive-access-cause-connector-to-timeout
Tested normal behavior with our drive.
=> Fix tons of users w/o drive access causing timeouts

backend/tests/unit/onyx/indexing/test_censoring.py
Fixes DAN-1741.
https://linear.app/danswer/issue/DAN-1741/test-censoring-chunks-and-ordering
=> unit tests for chunk censoring

backend/onyx/agents/agent_search/dc_search_analysis/nodes/a2_research_object_source.py
Using the question to focus the object search during the research phase, and adding a field called 'Research Topics' in the Agent Instructions that is used to focus search if question has not been provided.
This is a small fix to https://linear.app/danswer/issue/DAN-1750/simple-divide-and-conquer-assistant-to-support-some-customer-use-cases
Locally.
=> Adding research topics for better search context

backend/alembic/versions/cf90764725d8_larger_refresh_tokens.py, backend/onyx/db/models.py
Fixes https://linear.app/danswer/issue/DAN-1754/access-token-issue
=> Refresh token text limit

deployment/data/nginx/run-nginx.sh, deployment/docker_compose/docker-compose.resources.yml
Ref https://linear.app/danswer/issue/DAN-1670/resolve-alation-instance-crashing
Tested running compose locally with `docker compose -f docker-compose.dev.yml -f docker-compose.resources.yml -p onyx-stack up -d --build --force-recreate`
=> Update resource limits

backend/onyx/seeding/personas.yaml
^
Tested search assistant locally.
=> Adjusting default search assistant

backend/tests/daily/connectors/highspot/test_highspot_connector.py, backend/tests/integration/connector_job_tests/slack/test_permission_sync.py
Fixes DAN-1759.
https://linear.app/danswer/issue/DAN-1759/fix-slack-permission-tests-being-in-mit-tests
=> slack permission tests are enterprise only

web/src/app/chat/message/AgenticMessage.tsx, web/src/app/chat/message/Messages.tsx, web/src/app/chat/message/thinkingBox/ThinkingBox.css, web/src/app/chat/message/thinkingBox/ThinkingBox.tsx
^
Fixes https://linear.app/danswer/issue/DAN-1711/review-fix-up-ferdinands-thinking-mode-ui-pr
Tested locally
=> Small tweaks to thinking

backend/onyx/connectors/google_drive/connector.py
Should fix drive id not set in checkpoint; previously when a user failed to index a folder (which is fairly common due to permissions issues) the folder id was not set in the checkpoint. The necessary information for the checkpoint is yielded on error too, 
Tests tbd
=> unconditionally set completion

backend/onyx/connectors/highspot/connector.py, backend/tests/daily/connectors/highspot/test_highspot_connector.py, backend/tests/daily/connectors/highspot/test_highspot_data.json
This pull request includes updates to the Highspot connector and its associated tests. The changes focus on logging unsupported formats, updating test expectations, and modifying test data.
* Added a warning log for unsupported file formats in the `_get_item_content` method of the Highspot connector.
* Updated the `test_highspot_connector_poll_source`  to provide a more detailed explanation for the expected failure due to Highspot's handling of document updates.
* Modified the test data in `test_highspot_data.json` to reflect updated document identifiers and links.
By running test class.
=> update test expectations for Highspot connector

backend/onyx/llm/chat_llm.py
Fixes hardcoded "0" temperature
Checked correct temperature being sent to LLM
=> Fix hardcoded temperature

backend/onyx/agents/agent_search/deep_search/initial/generate_initial_answer/nodes/generate_initial_answer.py, backend/onyx/agents/agent_search/deep_search/main/nodes/generate_validate_refined_answer.py, backend/onyx/agents/agent_search/orchestration/nodes/choose_tool.py, backend/onyx/background/celery/tasks/doc_permission_syncing/tasks.py, backend/onyx/connectors/google_drive/connector.py, backend/onyx/connectors/google_drive/file_retrieval.py, backend/onyx/context/search/postprocessing/postprocessing.py, backend/onyx/server/features/tool/api.py, backend/pyproject.toml, backend/scripts/sources_selection_analysis.py, backend/tests/daily/connectors/salesforce/test_salesforce_connector.py, backend/tests/integration/common_utils/managers/persona.py, backend/tests/unit/onyx/chat/stream_processing/test_quotes_processing.py
https://linear.app/danswer/issue/DAN-1762/more-drive-id-not-set-fixes
More drive connector improvements to cover cases where "folder id not set in checkpoint" might occur. One such common case is that a user doesn't have access to the first several folders being indexed, so despite that user's completion stage being set to "folders", they don't yield any documents from the first few folders, leading to no information being set in the checkpoint.
Also added a mypy change and associated fixes to prevent broken equality checks for the future
tested in UI
=> Id not set in checkpoint2

backend/onyx/llm/utils.py
The code for token cost calculation fails in some cases when using a LiteLLM proxy due to mismatch with the provider+model naming. For now, just handle this exception and assume cost 0 when that happens instead of breaking the flow - A more precise, LiteLLM proxy based cost calculation (relying in the `/model/info`) LiteLLM Proxy implementation will be needed for accurate cost tracking.
Test enabling Contextual RAG LLM when a non-standard model name is used in the LLM connector (Ie. `claude-3.5-haiku@20241022`)
=> Handle exception for token cost calculation

backend/onyx/chat/process_message.py, backend/onyx/chat/prompt_builder/answer_prompt_builder.py, backend/onyx/chat/tool_handling/tool_response_handler.py, backend/onyx/llm/models.py, backend/tests/unit/onyx/chat/test_answer.py
Fixes https://linear.app/danswer/issue/DAN-1634/address-weird-tool-calling-behavior-with-claude-37
tested in UI + tests now cover this case (ensure that system message is in task prompt)
=> use persona info when creating tool args

backend/onyx/connectors/web/connector.py
Fixes https://linear.app/danswer/issue/DAN-1782/resolve-parsing-of-certain-websites-w-web-connector
Tested with a previously broken website.
=> Add stuff to better avoid bot-detection in web connector

backend/onyx/db/persona.py, backend/onyx/server/features/persona/api.py, backend/onyx/server/features/persona/models.py, web/src/app/admin/assistants/AssistantEditor.tsx
Fixes https://linear.app/danswer/issue/DAN-1780/document-sets-issue
=> Minor doc set fix

backend/ee/onyx/main.py, backend/onyx/main.py
The DB was not getting initialized before calling `seed_db` -> failures on startup if you had env-variable based seeding enabled.
Fixes https://linear.app/danswer/issue/DAN-1784/fix-seed-db-failures
Tested locally w/ env-variable based seeding.
=> Fix startup w/ seed_db

backend/onyx/auth/users.py, backend/onyx/chat/process_message.py, backend/onyx/server/query_and_chat/chat_backend.py
Fixes https://linear.app/danswer/issue/DAN-1777/track-latency-metrics
These should give us enough information to construct latency metrics in Grafana
=> Add latency metrics

.gitignore
This PR modifies the `.gitignore` file to ignore the Zed editor's configuration directory (named `.zed/`).
No testing required.
=> chore: Edit .gitignore file to add zed editor configurations

backend/tests/daily/llm/test_bedrock.py
Fixes DAN-1790.
https://linear.app/danswer/issue/DAN-1790/xfail-bedrock-model-test
=> xfail bedrock test

web/src/app/admin/configuration/llm/CustomLLMProviderUpdateForm.tsx
When adding a new custom LLM provider, the model contains an "Advanced Options" toggle at the bottom. However, for non-enterprise users, the dropdown will be empty. However, the *toggle* still exists; it just expands to *nothing*.
This PR removes that toggle if enterprise features are not enabled.
Addresses: https://linear.app/danswer/issue/DAN-1789/remove-advanced-options-toggle-if-paid-enterprise-features-are-not
UI fix; only visually tested.
Before:
After:
=> fix: Remove advanced options toggle if enterprise features are not enabled

backend/onyx/background/celery/tasks/beat_schedule.py
Fixes https://linear.app/danswer/issue/DAN-1786/user-file-folder-volume-issue
=> User file folder volume issue

backend/onyx/utils/threadpool_concurrency.py
=> parallel_yield clarity comment

backend/onyx/connectors/google_drive/file_retrieval.py
addresses https://linear.app/danswer/issue/DAN-1792/too-many-folder-retrieval-errors-gdrive
No longer throw a bunch of auth errors when a user doesn't have access to files in a folder; this can reasonably happen when someone shares only specific files from a folder in their My Drive.
testing in UI atm
=> don't yield expected auth errors

backend/ee/onyx/external_permissions/google_drive/group_sync.py, backend/onyx/connectors/google_drive/file_retrieval.py
Fixes https://linear.app/danswer/issue/DAN-1793/permissions-in-google-drive-specific-folders-dont-seem-to-be-working
Tested with a specific folder (https://drive.google.com/drive/u/1/folders/1kdUdS16nuqtWt4IvZnVncTGSFRP9XHCy)
=> Google drive perm sync fixes

web/src/app/chat/input/ChatInputBar.tsx
This PR modifies the Assistant functionality to correctly enforce the Document Sets specified in the Assistant's configuration. Previously, even when specific Document Sets were selected for an Assistant, the chat filter allowed users to select from all available Document Sets, effectively overriding the Assistant's configuration. This change restricts the chat filter's Document Set options to only those defined in the Assistant's configuration. If no Document Sets are specified in the Assistant's configuration, the filter retains its current behavior of displaying all available Document Sets, as per the help text.
The following tests were performed:
1.  Created an Assistant with specific Document Sets selected. Verified that the chat filter only displayed these selected Document Sets.
2. …
=> Fix: Limit chat filter of Document Sets to Assistant's configuration

backend/onyx/background/celery/apps/beat.py, backend/onyx/background/celery/tasks/indexing/utils.py
Fixes https://linear.app/danswer/issue/DAN-1798/beat-scheduler-not-starting-tasks-immediately
=> fix scheduler init

backend/onyx/connectors/google_drive/connector.py, backend/onyx/indexing/chunker.py
Most likely addresses https://linear.app/danswer/issue/DAN-1547/gdrive-missing-some-shared-drives-during-indexing
We weren't asking google for a nextPageToken in the drives list request, causing us to index at most 10 shared drives (the default pageSize)
tested in UI
=> fix max 10 drives issue

backend/onyx/indexing/chunker.py, backend/onyx/tools/tool_implementations/search/search_tool.py
Fixes https://linear.app/danswer/issue/DAN-1797/search-tool-retrieval-options-overwrite
Previously when an instance of the search tool was run, the search tool instance's retrieval options were overwritten by search-specific ones.Now we deepcopy so this doesn't happen.
n/a
=> ensure individual search tool runs do not affect each other

backend/onyx/connectors/confluence/onyx_confluence.py
Fixes https://linear.app/danswer/issue/DAN-1800/repeated-confluence-timeouts
👁️ 
=> Confluence timeout fix?

backend/onyx/agents/agent_search/orchestration/nodes/choose_tool.py, backend/onyx/agents/agent_search/shared_graph_utils/models.py, backend/onyx/configs/chat_configs.py, backend/onyx/context/search/models.py, backend/onyx/context/search/preprocessing/preprocessing.py, backend/onyx/context/search/retrieval/search_runner.py, backend/onyx/context/search/utils.py, backend/onyx/document_index/interfaces.py, backend/onyx/document_index/vespa/app_config/schemas/danswer_chunk.sd, backend/onyx/document_index/vespa/index.py, backend/onyx/prompts/chat_prompts.py, backend/onyx/tools/models.py, backend/onyx/tools/tool_implementations/search/search_tool.py, backend/scripts/query_time_check/test_query_times.py
PR for the expanded Basic Search. 
Linear: https://linear.app/danswer/issue/DAN-1806/new-query-expansion-for-basic-search
Core idea:
A) Create two search ranking profiles, one has phase 1 as semantic, the other keyword based
B) Modify Basic Search Pipeline 
- At the outset, for standard Search we get - parallelized - one additional keyword expansion and one additional semantic expansion. (No expansion for agentic search)
- if the the query is deemed to be 'keyword', we ignore the semantic expansion and just:
- search in the original form with original values  (where the first phase is semantic)
- Search with the keyword expansion, using the original embedding vector, but use a keyword 1st phase ranking
- combine the 2 results, each ranked by their scores
- if the the query is deemed to be …
=> Expanded basic search

backend/onyx/connectors/gitlab/connector.py
This PR fixes an issue in the Onyx GitLab connector where the branch was hardcoded as master. This caused 404 errors when working with repositories that use a different default branch, such as main.
The solution dynamically retrieves the repository's default branch using the GitLab API and replaces hardcoded master references throughout the connector.
Key changes include:
Using project.default_branch to fetch the correct branch dynamically.
Updating the file URL construction to use the dynamically determined branch.
Ensuring compatibility with repositories that do not use master as their default branch.
Manually tested the connector with repositories using main as the default branch.
Confirmed that the connector successfully fetches file content and constructs valid URLs for files in …
=> Fix #3764: Dynamically handle default branch in GitLab connector

web/src/components/health/healthcheck.tsx
Fixes https://linear.app/danswer/issue/DAN-1812/backend-unavailable-message-unreadable-in-dark-mode
Backend unavailable message was unreadable in dark mode
Ran in UI
=> fix font for dark mode

backend/onyx/background/indexing/checkpointing_utils.py, backend/onyx/connectors/confluence/connector.py, backend/onyx/connectors/connector_runner.py, backend/onyx/connectors/factory.py, backend/onyx/connectors/github/connector.py, backend/onyx/connectors/google_drive/connector.py, backend/onyx/connectors/interfaces.py, backend/onyx/connectors/mock_connector/connector.py, backend/onyx/connectors/onyx_jira/connector.py, backend/onyx/connectors/slack/connector.py, backend/onyx/connectors/web/connector.py, backend/onyx/connectors/zendesk/connector.py, backend/tests/daily/connectors/confluence/test_confluence_basic.py, backend/tests/daily/connectors/confluence/test_confluence_permissions_basic.py, backend/tests/daily/connectors/utils.py, backend/tests/daily/connectors/web/test_web_connector.py, backend/tests/integration/tests/connector/test_connector_creation.py, backend/tests/unit/onyx/connectors/confluence/test_confluence_checkpointing.py, backend/tests/unit/onyx/connectors/utils.py
Addresses https://linear.app/danswer/issue/DAN-1703/checkpointed-confluence-connector
Checkpointing for the confluence connector. Creates a new checkpoint each time the previous version of the connector would have finished a batch.
tested in UI and unit tests
=> checkpointed confluence

backend/onyx/connectors/google_drive/connector.py, backend/onyx/connectors/google_drive/doc_conversion.py
Addresses https://linear.app/danswer/issue/DAN-1817/logging-for-cases-where-user-can-see-but-not-download-from-drive
Extra logs for drive plus a small refactor. We've seen some cases where a user can list a file (i.e. they see it exists) but get a 403 when trying to download it. This logging will bring extra clarity about which users this is happening for and help us debug for a longer-term fix. 
n/a, will rely on connector tests for this since the change is relatively minor
=> extra logging for uncommon permissions cases

web/src/app/admin/configuration/llm/LLMProviderUpdateForm.tsx
When an LLM Provider is enabled, an `alert` is fired which prints a dict. This was probably left in during development. This PR removes that.
Addresses: https://linear.app/danswer/issue/DAN-1824/remove-alert-upon-enablement-editing-of-an-llm-provider.
This simply removes a print-out. Manually tested. No further testing required.
=> fix: Remove alert upon submission of LLM Provider

backend/ee/onyx/external_permissions/confluence/doc_sync.py, backend/tests/daily/connectors/confluence/test_confluence_permissions_basic.py
Fixes https://linear.app/danswer/issue/DAN-1822/fix-confluence-perm-sync-ancestry
Daily test
=> Fix confluence perm sync ancestry

backend/onyx/connectors/confluence/connector.py, backend/tests/unit/onyx/connectors/confluence/test_confluence_checkpointing.py, backend/tests/unit/onyx/connectors/utils.py
Fixes https://linear.app/danswer/issue/DAN-1830/confluence-duplicate-docs
The confluence API's granularity is only to the minute, so we were re-processing docs from the last checkpoint. This change skips docs seen in the previous checkpoint to avoid this issue. 
Tested in UI + unit tests
=> fix re-processing of previously seen docs Confluence

backend/onyx/connectors/confluence/connector.py, backend/onyx/connectors/confluence/utils.py
Fixes https://linear.app/danswer/issue/DAN-1816/confluence-image-attachments-being-downloaded-unexpectedly
=> small improvement to checking for image attachments

backend/onyx/llm/chat_llm.py
This PR fixes the error in which duplicate `vertex_credentials` kwargs would be passed into the call to `litellm.main.completion`. This resulted in an error being thrown while registering a custom LLM provider.
Addresses: https://linear.app/danswer/issue/DAN-1819/fix-duplicate-vertex-credentials-kwarg-error-while-creating-a-vertexai.
Ran through Custom LLM Provider registration process while also providing a "vertex_credentials" custom config key.
=> fix: Fix duplicate kwarg issue when calling `litellm.main.completion`

backend/onyx/connectors/onyx_jira/connector.py, backend/onyx/connectors/onyx_jira/utils.py, backend/tests/daily/connectors/blob/test_blob_connector.py, backend/tests/daily/connectors/confluence/test_confluence_permissions_basic.py, backend/tests/daily/connectors/jira/test_jira_basic.py
Fixes https://linear.app/danswer/issue/DAN-1834/pull-in-more-fields-for-jira
Connector tests + tested with Jira server locally.
=> Pull in more fields for Jira

backend/onyx/configs/constants.py, backend/onyx/connectors/file/connector.py, backend/onyx/connectors/google_site/connector.py, backend/onyx/db/user_documents.py, backend/onyx/file_processing/extract_file_text.py, backend/onyx/server/documents/connector.py, backend/onyx/server/documents/models.py, backend/onyx/server/query_and_chat/chat_backend.py, backend/onyx/server/user_documents/api.py, backend/tests/integration/common_utils/managers/connector.py, backend/tests/integration/tests/image_indexing/test_indexing_images.py, backend/tests/regression/answer_quality/api_utils.py, web/src/app/admin/connectors/[connector]/pages/utils/files.ts, web/src/app/admin/indexing/status/CCPairIndexingStatusTable.tsx, web/src/lib/connectors/connectors.tsx
Fixes https://linear.app/danswer/issue/DAN-1836/fix-file-connector-metadata
Tested in UI, daily connector test in the works
=> v1 file connector with metadata

backend/onyx/background/celery/tasks/indexing/utils.py, backend/onyx/background/indexing/run_indexing.py, backend/onyx/indexing/indexing_heartbeat.py
Ref https://linear.app/danswer/issue/DAN-1838/slack-timing-out-and-indexing-0-documents
=> ping with keep alive

backend/onyx/llm/llm_provider_options.py, backend/requirements/default.txt, backend/requirements/model_server.txt, web/src/lib/hooks.ts
Fixes https://linear.app/danswer/issue/DAN-1839/add-models-o3-o4-mini
=> Add o3 + o4 mini

backend/onyx/document_index/vespa/app_config/schemas/danswer_chunk.sd, backend/onyx/document_index/vespa/index.py, backend/scripts/debugging/onyx_vespa_schemas.py
Fixes https://linear.app/danswer/issue/DAN-1842/need-consistent-tool-to-generate-vespa-schemas-for-the-cloud
=> tool to generate vespa schema variations for our cloud

backend/onyx/connectors/web/connector.py, backend/tests/daily/connectors/web/test_web_connector.py
Kept seeing `Loading...` at the end of the retrieved content in failed cases. Giving it a bit of time to load 🙏 
=> Fix flakey web test

backend/onyx/connectors/confluence/connector.py, backend/tests/unit/onyx/connectors/confluence/test_confluence_checkpointing.py
Addresses https://linear.app/danswer/issue/DAN-1848/confluence-churning-forever-without-checkpointing
Address Behavior we've seen where a connector *appears* to just continuously get attachments. We now return a checkpoint after the outer for loop has attempted to process a batch of documents, whether they had errors or not. We also log when we start processing documents. This is intended to help with some 403s on attachment retrieval we've been seeing by surfacing the issue faster.
tests tbd
=> address getting attachments forever

backend/onyx/connectors/google_drive/connector.py, backend/onyx/connectors/google_drive/doc_conversion.py, backend/onyx/connectors/google_utils/google_utils.py, backend/onyx/db/llm.py, backend/onyx/utils/threadpool_concurrency.py, backend/tests/daily/connectors/google_drive/consts_and_utils.py, backend/tests/daily/connectors/google_drive/test_user_1_oauth.py, backend/tests/unit/onyx/utils/test_threadpool_concurrency.py
Addresses https://linear.app/danswer/issue/DAN-1814/indrive-drive-issues
we've seen many cases of our doc conversion threads failing to download a file from google drive impersonating the user that originally listed the file. In these cases, we now also try downloading using the admin email and the emails of all owners of the file.
Tested in the UI, and our connector tests are now indexing a file that a user can see but cannot download.
=> add emails to retry with on 403

web/src/app/ee/admin/performance/query-history/[id]/page.tsx
This PR adds the `assistant_name` to the "Chat Sessions Details" page inside of the "Query History" section.
Addresses: https://linear.app/danswer/issue/DAN-1796/add-assistant-into-query-history-display.
UI change; visually tested and confirmed to work.
=> feat: Add assistant name to UI

backend/onyx/agents/agent_search/orchestration/nodes/choose_tool.py, backend/onyx/chat/prune_and_merge.py, backend/onyx/context/search/retrieval/search_runner.py, backend/onyx/document_index/vespa/chunk_retrieval.py, backend/onyx/document_index/vespa/index.py, backend/onyx/prompts/chat_prompts.py
A number of logs were added to measure the expanded search procedure:
- logging got moved to info
- expansions are reported
- ranking profile is reported
Also, we run the original query through the 1st-phase keyword ranking as well. 
Locally.
=> Increased logging and update basic search expansion

backend/ee/onyx/server/tenants/product_gating.py, backend/ee/onyx/server/tenants/user_mapping.py, backend/onyx/background/indexing/job_client.py, backend/onyx/db/sync_record.py, backend/onyx/server/user_documents/api.py
wrong logger in a few places
possibly related to resource exhaustion
Fixes https://linear.app/danswer/issue/DAN-1867/wrong-logger-resource-exhaustion
=> wrong logger imported in a lot of wrong places

backend/alembic/versions/7a70b7664e37_add_model_configuration_table.py
It is possible for llm_provider.model_names to contain duplicate values (e.g., {model-a, model-a}. However, the new schema requires that the (provider_name, model_name) tuple be unique (i.e., no duplicate model names for a certain provider).
When migrating the llm_provider.model_names over to the new model_configurations table, the existence of duplicates will cause a problem in the uniqueness guarantees of the model_configurations table.
This PR solves that problem by converting the `llm_provider.model_names` into a set first in the migration script prior to inserting into the database table.
Addresses: https://linear.app/danswer/issue/DAN-1869/fix-duplicate-model-names-from-throwing-an-error-during-db-migration.
Ran migrations up and down.
=> fix: Fix the `add_model_configuration` migration by removing duplicate model-names during insertion

backend/onyx/context/search/retrieval/search_runner.py
Removal of 1st phase keyword search component
Tested locally
=> removal of keyword 1st phase

backend/onyx/connectors/google_drive/connector.py
https://linear.app/danswer/issue/DAN-1873/drive-id-not-set-in-checkpoint
Fix the remaining "id not set in checkpoint" issues; the last fix only addressed "folder not set in checkpoint" while this addresses "drive id not set in checkpoint". Also changes asserts -> conditional error throwing to align with our new code practices.
n/a, this is a tiny one
=> ensure drive id set in checkpoint

backend/onyx/onyxbot/slack/blocks.py, backend/onyx/onyxbot/slack/formatting.py
Fixes bug in which slack sources would not be formatted correctly if `<` or `>` characters were included in the document title.
Addresses: https://linear.app/danswer/issue/DAN-1815/bad-citing-in-slack-bot-for-docs-with-or-in-the-titleurl.
Visually tested through Slack.
=> fix: Slack formatting bug

backend/onyx/redis/redis_document_set.py, backend/onyx/redis/redis_usergroup.py
using different priorities here is causing the queue to starve out some tasks. Make them all medium.
Fixes https://linear.app/danswer/issue/DAN-1901/fix-some-sync-priority
=> fix priority on vespa metadata sync

backend/onyx/connectors/google_drive/file_retrieval.py, backend/onyx/connectors/linear/connector.py
Addresses https://linear.app/danswer/issue/DAN-1903/linear-dedupe-docs
We were sending batches with a single new doc to the indexing pipeline; now each batch has a full batch_size documents
tested in UI
=> linear dupe docs fix

backend/alembic/versions/7a70b7664e37_add_model_configuration_table.py, backend/onyx/llm/llm_provider_options.py
Migration did not address the case in which:
- `model_names = []` and `display_model_names = []`
- `default_model_name = "some-model"` and `fast_default_model_name = "some-fast-model"`
I.e., the case in which the default and fast-default models were specified, but they *did not* exist inside of the `model_names` or `display_model_names` lists.
The reason why this bug was pushed was because of incorrect assumptions; I assumed that `model_names` and `display_model_names` would *always* contain the `default_model_name` and `fast_default_model_name`. I.e., I assumed that:
$`(default\_model\_name \in model\_names)`$
and
$`(default\_model\_name \in display\_model\_names)`$
and
$`(fast\_default\_model\_name \in model\_name)`$
and
$`(fast\_default\_model\_name \in display\_model\_names)`$ …
=> fix: Fix migration issue in which display-model-names were not being appropriately set

web/src/app/chat/ChatPage.tsx, web/src/app/chat/lib.tsx
Fixes https://linear.app/danswer/issue/DAN-1875/fix-tool-choice
Tested an assistant with a tool before (would always search). Now it doesn't. 
=> Fix tool choice

backend/onyx/connectors/google_drive/connector.py, backend/tests/daily/connectors/google_drive/conftest.py, backend/tests/daily/connectors/google_drive/consts_and_utils.py, backend/tests/daily/connectors/google_drive/test_service_acct.py, web/src/app/admin/connectors/[connector]/pages/DynamicConnectorCreationForm.tsx, web/src/lib/connectors/connectors.tsx
Fixes https://linear.app/danswer/issue/DAN-1904/google-drive-specific-user-emails
New advanced option to allow users to specify a subset of the emails in their google workspace that they would like to use to retrieve files for their drive connector. This is intended to improve efficiency for workspaces with huge numbers of users that don't have access to much.
tested in UI + added connector tests 
=> specific user emails for drive connector

backend/alembic/versions/47a07e1a38f1_fix_invalid_model_configurations_state.py, backend/onyx/server/manage/llm/models.py, backend/tests/integration/tests/llm_provider/test_llm_provider.py, web/src/app/admin/assistants/AssistantEditor.tsx, web/src/app/admin/configuration/llm/interfaces.ts, web/src/app/chat/ChatPage.tsx, web/src/app/chat/input/LLMPopover.tsx, web/src/components/llm/LLMSelector.tsx, web/src/lib/chat/fetchAssistantdata.ts, web/src/lib/chat/fetchSomeChatData.ts, web/src/lib/llm/utils.ts
Fixes https://linear.app/danswer/issue/DAN-1909/make-gemini-image-capable
Tested various image capable models locally. Ideally, would add a test for this, but need seeding capability for playwright tests.
=> Single source of truth for image capability

backend/alembic/versions/da42808081e3_migrate_jira_connectors_to_new_format.py, backend/tests/integration/tests/migrations/test_migrations.py
Addresses https://linear.app/danswer/issue/DAN-1910/fix-jira-migration-with-tests
Test for https://github.com/onyx-dot-app/onyx/pull/4614
Turns out the downgrade had a small bug
TODO: skip the integration test once confirmed to work on the cloud
Ran the integration test locally
=> fix migration and add test

backend/onyx/server/manage/llm/api.py, backend/onyx/server/manage/llm/models.py, web/src/app/admin/configuration/llm/CustomLLMProviderUpdateForm.tsx, web/src/app/admin/configuration/llm/LLMProviderUpdateForm.tsx
Fixes a few things:
1. Model configurations were getting wiped on every update (set to empty list).
2. You could not edit an LLM provider easily. If you tried to re-submit, it would try and use the "masked key" and fail.
3. We ran the "test" call on every update, even if nothing had changed.
Fixes https://linear.app/danswer/issue/DAN-1912/fix-misc-model-configuration-stuff
Tested locally. In the future, might want to add e2e tests for these.
=> Fix LLM API key

backend/onyx/connectors/google_drive/connector.py, backend/onyx/connectors/google_drive/file_retrieval.py, backend/onyx/connectors/google_drive/models.py, backend/tests/daily/connectors/google_drive/test_service_acct.py
Addresses https://linear.app/danswer/issue/DAN-1851/duplicate-docs-in-google-drive-connector
previously, multiple threads could work on a shared folder at once and yield back the same doc multiple times. Now, we only yield docs that haven't been yielded previously.
tested in UI + added a connector test
=> no more duplicate files during folder indexing

backend/ee/onyx/external_permissions/confluence/doc_sync.py
Fixes https://linear.app/danswer/issue/DAN-1863/confluence-permission-sync-weirdness
Haven't been able to re-create this situation, so it's mostly just 👀 
=> Add support for restrictions w/o any access

backend/onyx/background/indexing/checkpointing_utils.py, backend/onyx/connectors/confluence/connector.py, backend/onyx/connectors/confluence/onyx_confluence.py, backend/onyx/connectors/confluence/utils.py, backend/tests/daily/connectors/confluence/test_confluence_basic.py, backend/tests/daily/connectors/confluence/test_confluence_user_email_overrides.py, backend/tests/unit/onyx/connectors/confluence/test_confluence_checkpointing.py
Addresses https://linear.app/danswer/issue/DAN-1899/confluence-documents-indexed-not-matching-total-docs
(and a series of other confluence customer issues)
There's an issue with the Confluence Server API; there doesn't appear to be a consistent field in page responses that mirrors the "lastmodified" key used during the query. This means that sometimes the field in response pages that we use for lastmodified can be outside the specified range. To fix this, we're switching to page-start-based checkpointing for confluence server.
Confluence Cloud  ALSO returns slightly wrong lastmodified values (though in testing they were less off than server), and uses cursor-based pagination. We currently believe that confluence uses a stateless model for cursor pagination, so the cursors never expire. …
=> Confluence server api time fix

backend/ee/onyx/external_permissions/google_drive/group_sync.py
https://linear.app/danswer/issue/DAN-1921/drive-permission-sync-group-pagination
add page token to drive groups sync, should allow us to paginate more than 10 groups
TBD
=> page token for drive group sync

backend/alembic/versions/7a70b7664e37_add_model_configuration_table.py, backend/onyx/connectors/slack/connector.py, backend/onyx/connectors/slack/utils.py
Fixes https://linear.app/danswer/issue/DAN-1913/archived-channel-failures
Created channel, set breakpoint at `client.conversations_join` in `_get_messages`, then archived it. Verified the index attempt was a success.
=> Fix race condition with archived channels

web/src/app/chat/input/ChatInputBar.tsx
Removes the info hoverable icon when a specific assistant has been "@"-ed. The info hoverable was not displaying any useful information anyways.
Addresses: https://linear.app/danswer/issue/DAN-1882/info-icon-is-clickable-and-hoverable-but-does-nothing.
UI change; does not need any testing.
=> Remove info hoverable

web/src/app/admin/connector/[ccPairId]/IndexingAttemptsTable.tsx
This PR removes `cursor-help` as an attribute for the tooltip hoverable.
Addresses: https://linear.app/danswer/issue/DAN-1888/only-on-this-info-hover-we-change-the-cursor-to-a-question-mark-lets.
This is a pure UI change; manually tested to make sure cursor doesn't turn into a question mark.
Before:
After:
=> fix: Remove `cursor-help` for tooltip

backend/onyx/connectors/highspot/client.py, backend/onyx/connectors/highspot/connector.py
`counts_total` can be None, despite having spots.
Ran locally.
=> fix highspot

backend/ee/onyx/external_permissions/google_drive/doc_sync.py, backend/ee/onyx/external_permissions/google_drive/group_sync.py, backend/onyx/connectors/gmail/connector.py, backend/onyx/connectors/google_drive/connector.py, backend/onyx/connectors/google_utils/google_utils.py, backend/tests/daily/connectors/google_drive/test_slim_docs.py
It is not impossible for indexing to error because drive id is not set in checkpoint. I am convinced that these errors occur due to rare states where a user Just Finished their My Drive but has not started the next stage, meaning it is correct to simply continue on to the next stage when this happens.
n/a, this should only reduce errors.
=> id not set in checkpoint FINAL

backend/onyx/llm/utils.py
^
Compared speed of `/llm/provider` endpoint before/after. Is ~25x speedup (~2.5 seconds -> ~100ms).
=> Add LRU cache to get_model_map

backend/onyx/llm/llm_provider_options.py, web/playwright.config.ts, web/src/app/admin/configuration/llm/ConfiguredLLMProviderDisplay.tsx, web/src/app/admin/configuration/llm/LLMProviderUpdateForm.tsx, web/src/app/admin/configuration/llm/interfaces.ts, web/src/app/admin/configuration/llm/utils.ts, web/src/app/chat/input/ChatInputBar.tsx, web/src/app/chat/input/LLMPopover.tsx, web/src/components/llm/LLMSelector.tsx, web/src/lib/assistants/fetchPersonaEditorInfoSS.ts, web/src/lib/hooks.ts, web/tests/e2e/chat/llm_ordering.spec.ts
Fixes https://linear.app/danswer/issue/DAN-1939/fix-playwright-testsmodel-iconsdefault-display-icons
Tested with OpenAI/anthropic locally.
=> Fix test / display models

backend/ee/onyx/server/saml.py, backend/onyx/auth/users.py, backend/onyx/db/auth.py, backend/onyx/db/engine.py, backend/onyx/key_value_store/store.py, backend/shared_configs/configs.py
Previously, if you set the `POSTGRES_DEFAULT_SCHEMA` env variable, it wouldn't be respected in `PgRedisKVStore`, which causes issues.
Fixes https://linear.app/danswer/issue/DAN-1938/use-correct-schema-in-kv-store
Tested different schema locally.
=> Fix non-default schema in KV store

.github/workflows/docker-build-push-backend-container-on-tag.yml, .github/workflows/docker-build-push-cloud-web-container-on-tag.yml, .github/workflows/docker-build-push-model-server-container-on-tag.yml, .github/workflows/docker-build-push-web-container-on-tag.yml, .github/workflows/pr-integration-tests.yml, .github/workflows/pr-mit-integration-tests.yml, backend/onyx/background/celery/tasks/indexing/tasks.py
Fixes https://linear.app/danswer/issue/DAN-1935/fix-up-docker-image-caching-on-build.
=> restore caching and fix up some prefixing

backend/onyx/connectors/github/connector.py
Fixes https://linear.app/danswer/issue/DAN-1940/attributeerror-paginatedlist-object-has-no-attribute-nexturl
(hopefully)
Fix for attribute not found error likely due to python name mangling.
Automated tests because we have not yet reproduced this issue locally
=> possible mangling fix

backend/onyx/connectors/google_drive/doc_conversion.py
Fixes https://linear.app/danswer/issue/DAN-1947/drive-404s-on-file-retrieval
In some cases for read only files, retrievers get a 404 when trying to download. This PR lets us retry as other possible retrievers when this happens.
n/a, pretty basic. Ideally we could reproduce the 404s in our testing environment and add a connector test.
=> make 404s skippable

backend/onyx/background/celery/tasks/connector_deletion/tasks.py, backend/onyx/db/connector_credential_pair.py
Fixes https://linear.app/danswer/issue/DAN-1946/foreign-key-violation-when-deleting-connector
We were seeing a foreign key violation during attempts at connector deletion When there were still user files associated with the connector.
n/a, seems pretty basic
=> fixes foreign key violation

backend/onyx/connectors/google_drive/connector.py, backend/onyx/connectors/google_drive/doc_conversion.py
Fixes https://linear.app/danswer/issue/DAN-1945/make-drive-fast-again
We were seeing a lot of slowness with the drive connector, with occasional hangs that completely interrupted indexing. We believe this was due to many duplicate API calls, in some cases leading to some silent rate limiting from the google apis. We were running 50 generator threads in parallel to get 16 documents, returning a checkpoint, then entering with that checkpoint and starting 50 more generators... etc. Now we tie the number of threads to the number of user emails we process per checkpoint, and finish those users before returning a checkpoint. It remains to be seen whether this will work well across the board, but it will certainly greatly improve API call efficiency (and therefore speed).
Tested manually
Note: …
=> fix drive slowness

backend/ee/onyx/server/enterprise_settings/api.py
Fixes https://linear.app/danswer/issue/DAN-1952/enterprise-settings-needs-to-403-if-no-tenant
=> enterprise settings needs to 403 on tenant id absence

backend/ee/onyx/external_permissions/google_drive/group_sync.py
Fixes https://linear.app/danswer/issue/DAN-1954/resolve-oom-for-heavy-workers-during-group-sync
=> Try to reduce memory usage on group sync

backend/onyx/db/auth.py, backend/onyx/server/manage/users.py
Fixes https://linear.app/danswer/issue/DAN-1953/fix-user-count-for-billing
👀 
=> Fix user count

backend/onyx/connectors/github/connector.py, backend/requirements/dev.txt, backend/tests/unit/onyx/connectors/github/test_github_checkpointing.py
Fixes https://linear.app/danswer/issue/DAN-1950/github-cursor-pagination-infinite-loop-fix
Fix an issue where the cursor-based pagination for github resulted in an infinite loop due to returning a checkpoint too early
tested manually, automated test of no infinite loop tbd
=> fix github cursor pagination infinite loop

backend/onyx/connectors/salesforce/sqlite_functions.py
Fixes https://linear.app/danswer/issue/DAN-1958/csv-field-size-limit-fix
=> set field size limit

backend/onyx/background/celery/tasks/indexing/tasks.py, backend/onyx/background/indexing/run_indexing.py, backend/onyx/db/connector_credential_pair.py, backend/onyx/server/documents/models.py, backend/tests/integration/tests/indexing/test_polling.py
Fixes https://linear.app/danswer/issue/DAN-1964/fix-poll-range-start
Integration test.
=> Fix window_start

.github/workflows/docker-build-push-backend-container-on-tag.yml, .github/workflows/docker-build-push-cloud-web-container-on-tag.yml, .github/workflows/docker-build-push-model-server-container-on-tag.yml, .github/workflows/docker-build-push-web-container-on-tag.yml
Fixes https://linear.app/danswer/issue/DAN-1961/cloud-images-are-being-tagged-as-latest
=> ensure we don't tag 'latest' with cloud images

backend/ee/onyx/background/celery/apps/primary.py, backend/onyx/background/celery/apps/beat.py, backend/onyx/background/celery/apps/light.py
Fixes https://linear.app/danswer/issue/DAN-1966/beat-cloud-task-unregistered
In the recent decoupling of EE form non-EE, we ended up with an unregistered task: `cloud_generate_beat_tasks`. This fixes that (hopefully)
n/a
=> light worker discovers beat task

backend/onyx/background/celery/tasks/indexing/tasks.py, backend/onyx/background/indexing/checkpointing_utils.py, backend/onyx/background/indexing/run_indexing.py
Fixes https://linear.app/danswer/issue/DAN-1969/another-small-checkpointing-logic-fix
Tested locally
=> Fix initial checkpoint save

backend/onyx/connectors/github/connector.py
Fixes https://linear.app/danswer/issue/DAN-1970/fix-issue-w-github-all-repos-enterprise-saml
Previously it was possible to get stuck on issues and never retrieve any PRs when in PR only mode; this fixes that issue
tested in UI
=> reset to prs on next checkpoint

.github/workflows/pr-python-connector-tests.yml
Add Teams environment variables to workflow.
Addresses: https://linear.app/danswer/issue/DAN-1976/add-teams-environment-variables-to-connector-testing-workflow-file.
CI/CD change; doesn't need to be tested.
=> fix: Add Teams env-variables

backend/ee/onyx/db/usage_export.py, backend/ee/onyx/server/reporting/usage_export_generation.py, web/src/components/PageSelector.tsx
[DAN-1747](https://linear.app/danswer/issue/DAN-1747/dont-use-random-uids-for-ui)
- Changed `create_new_usage_report` and `get_all_usage_reports` to return the username of the person who made the report instead of their user_id in the requestor field.
- Changed frontend to disable and gray out arrows when they shouldn't be active (e.g., left arrow disabled on 1st page, right arrow disabled on last page)
- Tested UI with 0, 1, 2, and 3 pages of reports
- Tested system generated and user generated reports
=> Bugfix/usage report UUID

backend/onyx/connectors/google_drive/connector.py, backend/tests/daily/connectors/google_drive/consts_and_utils.py, backend/tests/daily/connectors/google_drive/test_service_acct.py
Fixes https://linear.app/danswer/issue/DAN-1979/drive-connector-broken
Drive connector tests were failing due to a deadlock in our shared drive indexing scheme and a file without an extensions that isn't being indexed anymore. This PR simplifies the logic and fixes the connector test.
connector tests
=> fix connector tests and drive indexing

web/src/components/admin/connectors/AdminSidebar.tsx
This pull request enhances the `AdminSidebar` component by introducing active link highlighting based on the current pathname. 
By looking into the UI.
Before:
After:
=> Highlight active link in AdminSidebar based on current pathname

backend/onyx/tools/utils.py, backend/requirements/default.txt, backend/requirements/model_server.txt
Use LiteLLM DB for determining model tool capability instead of using a hardcoded list.
This enables newer models (Ie. `gpt-4.1`, `gemini-2.5`) to use native tools.
Checked new models now can execute tools.
=> Use LiteLLM DB for determining model tool capability

backend/onyx/auth/users.py, backend/onyx/db/engine.py
Fixes https://linear.app/danswer/issue/DAN-1981/fix-oauth-with-ext-perm-user-on-cloud
Tested w/ multi-tenant set up locally.
=> Fix OAuth w/ ext_perm_user for multi-tenant

web/src/app/admin/connectors/[connector]/NavigationRow.tsx
Made it clearer that the button is disabled
=> Fix Continue Button in Connector

deployment/docker_compose/docker-compose.dev.yml, deployment/docker_compose/docker-compose.prod.yml
Fixes https://linear.app/danswer/issue/DAN-1982/docker-indexinginference-containers-should-be-restart-always
=> fix docker restart

backend/ee/onyx/background/celery/apps/heavy.py, backend/ee/onyx/server/query_history/api.py
Query history exporting fetches the entire history and populates it into memory. This causes significant pressure on memory, and can lead to OOMs for very large datasets.
This PR updates the logic to incrementally fetch pages of data, transform them, and write them to file, instead of fetching the entire dataset at once, transforming each row, and then writing it to file.
I.e., we don't fully collect / materialize the entire dataset, we do it in pages instead.
This PR also parallelizes the chat-session fetching logic (given that chat-session reading does not have any cross-thread dependencies [I think?]).
Addresses: https://linear.app/danswer/issue/DAN-1984/improve-performance-of-query-history-exporting.
This is performance change, not a feature-addition. We don't have much (if any) …
=> perf: Change query-exporting to use generators instead of expanding fully into memory

.gitignore, backend/tests/regression/search_quality/generate_search_queries.py, backend/tests/regression/search_quality/run_search_eval.py
Added extra error handling to the search quality test script.
Added files to gitignore
Merged two functions which share some steps
It runs
=> feat: error handling of search quality test

backend/Dockerfile
Fixes https://linear.app/danswer/issue/DAN-1985/nltk-punkt-deprecated
related to https://github.com/nltk/nltk/issues/3293
```
2025-05-19 08:53:43.267	
**********************************************************************
2025-05-19 08:53:43.267	
- '/usr/local/lib/nltk_data'
2025-05-19 08:53:43.267	
- '/usr/lib/nltk_data'
2025-05-19 08:53:43.267	
- '/usr/local/share/nltk_data'
2025-05-19 08:53:43.267	
- '/usr/share/nltk_data'
2025-05-19 08:53:43.267	
- '/usr/local/lib/nltk_data'
2025-05-19 08:53:43.267	
- '/usr/local/share/nltk_data'
2025-05-19 08:53:43.267	
- '/usr/local/nltk_data'
2025-05-19 08:53:43.267	
- '/root/nltk_data'
2025-05-19 08:53:43.267	
Searched in:
2025-05-19 08:53:43.267	
2025-05-19 08:53:43.267	
Attempted to load tokenizers/punkt_tab/english/
2025-05-19 08:53:43.267 …
```
=> fix nltk punkt

backend/onyx/connectors/google_drive/doc_conversion.py, backend/onyx/file_processing/extract_file_text.py
https://linear.app/danswer/issue/DAN-1991/drive-pptx-and-xlsx-invalid-zipfile
There are cases where .xlsx and .pptx files are invalid because they are actually recovery files. We don't need the connector to fail in these cases. So, we add limited error catching that lets us skip these files.
n/a, should be strictly an improvement as it's just error handling
=> don't fail on fake files

backend/alembic/versions/238b84885828_add_foreign_key_to_user__external_user_.py, backend/ee/onyx/external_permissions/google_drive/doc_sync.py, backend/ee/onyx/external_permissions/google_drive/group_sync.py, backend/ee/onyx/external_permissions/google_drive/models.py
Fixes https://linear.app/danswer/issue/DAN-1992/reduce-of-folders-found-during-drive-group-sync
Tested with our drive locally, # of unique groups went from 469 -> 69.
=> Improve drive group sync

backend/onyx/connectors/google_drive/connector.py, backend/onyx/connectors/google_drive/file_retrieval.py, backend/tests/daily/connectors/google_drive/test_drive_perm_sync.py
Fixes https://linear.app/danswer/issue/DAN-1994/drive-perm-sync-cutoff
Due to some recent changes, drive perm sync wasn't pulling in permissions for all documents. This fixes that.
Fixed connector test to address the issue; test failed before PR and passes after
=> full drive perm sync

backend/ee/onyx/external_permissions/slack/doc_sync.py, backend/onyx/connectors/slack/connector.py
Fixes https://linear.app/danswer/issue/DAN-1993/floqast-slack-permissions-not-sharing-retry-handler
=> make sure the permission client uses the proper retry handler

backend/onyx/auth/users.py
=> Fix ext_perm_user sign-up for non multi-tenant

backend/onyx/connectors/teams/connector.py, backend/tests/daily/connectors/teams/test_teams_connector.py
Previous PR left out the processing of replies to a message. This PR adds it back.
Addresses: https://linear.app/danswer/issue/DAN-1997/teams-replies-not-being-parsed-and-processed-in-document.
Tests were written in the previous PR. For this one, since replies are included, they have been updated to include the replies in the expected output.
=> fix: Add back Teams' replies processing

web/src/app/chat/sessionSidebar/PagesTab.tsx
Dragging chats within chat-groups was not possible before because of DOM layering issues. The context for dragging chats would be completely overlaid by the context for dragging chat-groups. This PR fixes that layering issue.
Addresses: https://linear.app/danswer/issue/DAN-1877/chats-cannot-be-dragged-out-of-the-group-theyre-in.
Pure UI change; no tests were written.
=> fix: Fix chats dragging issue

backend/ee/onyx/server/tenants/admin_api.py, backend/ee/onyx/server/tenants/user_mapping.py
current logging did not make the issue with an error here immediately obvious.
Fixes https://linear.app/danswer/issue/DAN-2004/improve-impersonation-logging.
=> improve impersonation logging slightly

backend/onyx/tools/utils.py, backend/tests/unit/onyx/tools/test_tool_utils.py
Fixes https://linear.app/danswer/issue/DAN-2008/bedrock-anthropic-models-tool-calling
Fix tool calling for anthropic models invoked through bedrock
tested in UI
=> fix tool calling for bedrock claude models

backend/ee/onyx/external_permissions/google_drive/doc_sync.py, backend/ee/onyx/external_permissions/google_drive/permission_retrieval.py, backend/onyx/connectors/google_drive/connector.py, backend/onyx/connectors/google_utils/resources.py
Fixes https://linear.app/danswer/issue/DAN-2012/refresh-drive-creds-during-perm-sync
When drive perm sync runs for a while, we sometimes get the following difficult-to-explain exception:
```
google.auth.exceptions.RefreshError: ('unauthorized_client: Client is unauthorized to retrieve access tokens using this method, or client not authorized for any of the scopes requested.', {'error': 'unauthorized_client', 'error_description': 'Client is unauthorized to retrieve access tokens using this method, or client not authorized for any of the scopes requested.'})
```
This can happen several hours into permission syncing despite the fact that drive tokens auto-refresh roughly every hour. So, presumably 1 or 2 refreshes succeed, then one fails. 
n/a
Note: You have to check that the action passes, …
=> v1 refresh drive creds during perm sync

backend/model_server/encoders.py
Fixes https://linear.app/danswer/issue/DAN-2010/print-sanitized-api-key-in-embedding-exceptions-to-help
=> print sanitized api key to help troubleshoot

backend/onyx/agents/agent_search/dc_search_analysis/nodes/a5_consolidate_research.py, backend/onyx/agents/agent_search/deep_search/initial/generate_individual_sub_answer/nodes/generate_sub_answer.py, backend/onyx/agents/agent_search/deep_search/initial/generate_initial_answer/nodes/generate_initial_answer.py, backend/onyx/agents/agent_search/deep_search/main/nodes/generate_validate_refined_answer.py, backend/onyx/agents/agent_search/shared_graph_utils/llm.py
Removed a lot of duplicate code on the way the llm answer is streamed
=> refactor: stream_llm_answer

web/src/app/admin/indexing/status/CCPairIndexingStatusTable.tsx
This pull request has updated logic for Status column to display the scheduled badge and changes for connector filtering.
Tested in UI
=> connector filter bug fix

backend/onyx/file_processing/extract_file_text.py
Address this issue in openpyxl: https://github.com/wireservice/csvkit/issues/834
n/a, just error handling
=> skip excel files that openpyxl fails on

backend/onyx/context/search/models.py, backend/onyx/context/search/preprocessing/preprocessing.py, backend/onyx/tools/tool_implementations/search/search_tool.py, web/src/app/chat/ChatPage.tsx
Fixes https://linear.app/danswer/issue/DAN-2016/dalberg-no-results-found
Tested running a search with a document selected locally.
=> Simplify passing in of file IDs for filtering

backend/ee/onyx/external_permissions/google_drive/doc_sync.py, backend/ee/onyx/external_permissions/google_drive/permission_retrieval.py, backend/onyx/access/models.py, backend/onyx/connectors/google_drive/connector.py, backend/onyx/connectors/google_drive/doc_conversion.py, backend/onyx/document_index/vespa_constants.py, backend/onyx/file_processing/extract_file_text.py, deployment/docker_compose/docker-compose.dev.yml, deployment/docker_compose/docker-compose.gpu-dev.yml, deployment/docker_compose/docker-compose.multitenant-dev.yml, deployment/docker_compose/docker-compose.prod-cloud.yml, deployment/docker_compose/docker-compose.prod-no-letsencrypt.yml, deployment/docker_compose/docker-compose.prod.yml, deployment/docker_compose/docker-compose.search-testing.yml, deployment/helm/charts/onyx/values.yaml
Fixes https://linear.app/danswer/issue/DAN-2027/drive-perm-sync-logging-and-db-shm-size
A bunch of small logging and fixes for google drive connector/permission syncing
Also some memory bumps and a vespa version upgrade that helps with queries containing many common words
most of it has been tested in UI, although the helm changes haven't been tested yet
=> drive perm sync logs + misc deployment improvements

backend/scripts/resume_paused_connectors.py
Creating a new script to resume all of the paused connectors that exist within your connectors. 
The script allows you to specify multiple sources (i.e. `google_drive`, `linear`) that you would only like to resume as well.
This was ran locally by running the following: 
Resume all paused connectors
`cd backend && python3 scripts/resume_paused_connectors.py`
Resume all of the google drive connectors 
`cd backend && python3 scripts/resume_paused_connectors.py --connector_sources google_drive`
Running Onyx locally
- Started by generating an API key from the UI.
- Ensured there were paused connectors.
- Ran the commands from above and validated that the connectors were ingesting …
=> [Connectors][Script] Resume Paused Connectors

backend/onyx/llm/llm_provider_options.py, web/src/lib/hooks.ts
Error selecting `gemini-2.5-pro-exp-03-25` as my LLM model
litellm.NotFoundError: VertexAIException - { "error": { "code": 404, "message": "Publisher Model `projects/xxx/locations/us-central1/publishers/google/models/gemini-2.5-pro-exp-03-25` not found.", "status": "NOT_FOUND" } }
I'm pretty sure google stopped providing this model and it should be `gemini-2.5-pro-preview-05-06`
https://cloud.google.com/vertex-ai/generative-ai/docs/models/gemini/2-5-pro
=> fix: updating gemini models

backend/onyx/connectors/models.py, backend/onyx/connectors/onyx_jira/connector.py, backend/tests/daily/connectors/jira/test_jira_basic.py
Added new metadata components for - in particular but not only - Knowledge Graph functinality.
Here is the ticket:
https://linear.app/danswer/issue/DAN-2015/augment-jira-connector-for-kg-usage
Here are the new fields:
parent (parent.key)
assignee_email	
creator_email	
updated	
resolution_date	 
Locally
=> New metadata for Jira for KG

backend/alembic/versions/495cb26ce93e_create_knowlege_graph_tables.py, backend/onyx/chat/process_message.py, backend/onyx/configs/kg_configs.py, backend/onyx/db/entities.py, backend/onyx/db/kg_config.py, backend/onyx/db/relationships.py, backend/onyx/document_index/vespa/index.py, backend/onyx/document_index/vespa/kg_interactions.py, backend/onyx/kg/clustering/clustering.py, backend/onyx/kg/extractions/extraction_processing.py, backend/onyx/kg/models.py, backend/onyx/kg/resets/reset_vespa.py
- Removed unnecessary extraction from other chunks of a document in extraction processing (we only look at 1 chunk now) now that vespa update got moved to clustering
- Moved vespa update at the end of clustering to speed up clustering
- Made vespa replace the entire kg_entity and kg_relationships info on update to better handle deleted entities/relationships, and fix issues of leftover info from previous runs
- Fixed vespa update for created parent child relationships
- Made parent-child relationship extraction depth configurable
Locally, on jira, github, linear, account, and opportunity entity types
=> KG Refactor V2

backend/requirements/default.txt
Upgrade asyncpg library to be able to install onyx on Python 3.12.
Reference: https://github.com/onyx-dot-app/onyx/issues/734
`pip install -r requirements/default.txt`
=> Upgrade asyncpg for Python 3.12

backend/onyx/connectors/sharepoint/connector.py, backend/tests/daily/connectors/sharepoint/test_sharepoint_connector.py
Sharepoint connector didn't correctly list sites in organization
Fixes https://linear.app/danswer/issue/DAN-2044/sharepoint-indexing-bug
Created Sharepoint connector with no sites specified
=> Fixed indexing when no sites are specified

backend/alembic/versions/cec7ec36c505_kgentity_parent.py, backend/onyx/db/entities.py, backend/onyx/db/models.py, backend/onyx/db/relationships.py, backend/onyx/kg/clustering/clustering.py
- Clustering no longer loads every staging entity, relationship, etc. into memory and clusters them
- Clustering does work in batches for memory efficiency and crash robustness
- Fixed issue where if a staging entity's parent is in the normalized table but not the staging table, a parent-child relationship will not be created
- Made parent child relationship generation parallel
Locally, on GitHub, Jira, Linear, and Salesforce. Both incrementally and in one go
Checked vespa to ensure the right information is there
=> Kg batch clustering

backend/onyx/configs/kg_configs.py, backend/onyx/db/models.py, backend/onyx/kg/extractions/extraction_processing.py, backend/onyx/kg/models.py, backend/onyx/kg/utils/extraction_utils.py
Autofills metadata possible values
Can be either a list or a single value.
If there are too many possible options, it is replaced with "any suitable value" or "list of any suitable values"
E.g.,
- "status": "one of: To Do, In Progress, Done"
- "created_at": "a suitable value"
- "labels": "a list with possible values: good first issue, enhancements"
- "assignees": "a list of any suitable values"
Locally, both incrementally and all at once
=> KG autofill metadata

backend/onyx/db/models.py
One-line PR that sorts the subquestions for a chat message.
here is the issue: https://linear.app/danswer/issue/DAN-2061/wrong-step-ordering-in-kg-ui-prototype
This is now addressed by ordering the sub-questions (level first, then level_question_num).
Locally in multi-tenant environment. Used standard Search, Agent Search, and KG Search.
=> Order sub-questions for chat message

backend/onyx/connectors/discourse/connector.py
The Discourse connector was incorrectly `break`ing after processing the first batch of topics (16) even though the API returns 30 topics per page. This caused the connector to miss processing the remaining topics from each page.
Noticed a discrepancy in the document count indexed when trying to sync my own discourse setup. I tested by making the changes and building the `background` service locally and running the sync again. 
=> fix(discourse): Remove early break that was limiting topics to indexing batch size

backend/onyx/connectors/google_drive/doc_conversion.py
Fixes https://linear.app/danswer/issue/DAN-2035/drive-connectorfailure-file-id-unknown
Recent minor regression; ConnectorFailures would have id "unknown" if the error occurred before the doc id was extracted
n/a
=> errors have correct file id

backend/onyx/connectors/google_drive/connector.py, backend/onyx/connectors/google_drive/doc_conversion.py, backend/onyx/connectors/google_drive/file_retrieval.py, backend/onyx/connectors/google_drive/models.py, backend/onyx/connectors/google_utils/google_utils.py, backend/tests/daily/connectors/google_drive/test_service_acct.py
Fixes https://linear.app/danswer/issue/DAN-2067/drive-smaller-checkpoints
We previously moved to chunkier drive checkpoints to improve efficiency of API calls. Unfortunately, this led to checkpoints that were sometimes thousands to tens of thousands of files apart. We have now overhauled the checkpointing system to maintain API call efficiency while also ensuring that each checkpoint is only a controlled number of API calls after the previous one.
Also saved pageToken between checkpoint runs to address edge cases around multiple repeated modified times
connector tests, test in custom env tbd
=> drive smaller checkpoints v1

backend/onyx/connectors/teams/connector.py
This PR removes threading from Teams connector. Specifically, the call to `parallel_yield`. Was causing issues (@Weves thinks the Teams library may be thread-unsafe).
Addresses: https://linear.app/danswer/issue/DAN-2077/remove-threading-from-teams-connector.
Not tested...
=> fix: Remove threading from Teams connector

backend/onyx/indexing/chunker.py, backend/onyx/utils/timing.py, backend/requirements/default.txt
Fixes https://linear.app/danswer/issue/DAN-2055/switch-to-chonkie
Existing UT
=> Switch to chonkie from llamaindex chunker

backend/onyx/connectors/google_drive/connector.py, backend/onyx/connectors/google_drive/doc_conversion.py, backend/onyx/file_processing/extract_file_text.py
Fixes https://linear.app/danswer/issue/DAN-2081/drive-large-excel-files
When a spreadsheet is uploaded to drive, sometimes it can have an enormous number of empty cells which we were previously converting into an endless sea of commas as a csv. Now we skip the rest of the file after seeing enough rows in sequence with this property.
tested in UI, huge speedup with a local deployment on massive (100,000+ rows with 16384 columns) excel files
=> skip large empty excel files

backend/onyx/chat/process_message.py, backend/onyx/kg/setup/kg_default_entity_definitions.py
This PR updates how the `populate_default_entity_types` function works internally, and what it returns. With this update, it returns all the entity-types (including the fresh, templatized defaults) which have been inserted into the DB.
Addresses: https://linear.app/danswer/issue/DAN-2080/edit-how-populate-default-entity-types-works-and-what-it-returns.
Not tested.
=> cleanup: Edit logic for default entity-types population

backend/onyx/agents/agent_search/orchestration/nodes/choose_tool.py, backend/onyx/background/celery/tasks/kg_processing/kg_indexing.py, backend/onyx/background/celery/tasks/kg_processing/tasks.py, backend/onyx/background/celery/tasks/kg_processing/utils.py, backend/onyx/chat/process_message.py, backend/onyx/configs/constants.py, backend/onyx/document_index/vespa/chunk_retrieval.py, backend/onyx/document_index/vespa/kg_interactions.py, backend/onyx/kg/resets/reset_source.py, backend/onyx/kg/resets/reset_vespa.py
Use a function to invoke celery tasks to reset the Knowledge graph or re-index. This is in preparation for the Admin UI.
Here is the Linear ticket: https://linear.app/danswer/issue/DAN-2076/move-on-demand-kg-re-index-functions-to-celery-tasks
Locally.
=> Prep KG on-demand indexing through celery

backend/scripts/hard_delete_chats.py
Fixes https://linear.app/danswer/issue/DAN-2087/script-for-hard-deleting-old-chats
For hard deleting chats that were deleted prior to HARD_DELETE_CHATS was enabled.
=> new script for hard deleting sessions

backend/onyx/connectors/blob/connector.py, web/src/components/credentials/actions/CredentialFieldsRenderer.tsx, web/src/lib/connectors/credentials.ts
This pull request introduces support for an "Assume Role" authentication method for S3 buckets and enhances the user interface to display descriptions for credential methods without fields.
By running the script that establishes a connection to S3 from the EC2 instance.
=> feat: Add support for Assume Role authentication in S3

backend/onyx/connectors/google_drive/connector.py, backend/onyx/file_processing/extract_file_text.py
small logging improvements to make g drive checkpoints more understandable and excel file processing less spammy
n/a
=> tiny connector logging tweaks

backend/Dockerfile
Add `psql` to backend containers for debugging.
Built backend container locally.
=> Add psql to backend containers

backend/alembic/versions/03bf8be6b53a_rework_kg_config.py, backend/onyx/background/celery/tasks/kg_processing/kg_indexing.py, backend/onyx/background/celery/tasks/kg_processing/tasks.py, backend/onyx/background/celery/tasks/kg_processing/utils.py, backend/onyx/chat/answer.py, backend/onyx/chat/chat_utils.py, backend/onyx/chat/process_message.py, backend/onyx/configs/constants.py, backend/onyx/db/kg_config.py, backend/onyx/db/models.py, backend/onyx/key_value_store/interface.py, backend/onyx/key_value_store/store.py, backend/onyx/kg/clustering/clustering.py, backend/onyx/kg/extractions/extraction_processing.py, backend/onyx/kg/models.py, backend/onyx/kg/resets/reset_source.py, backend/onyx/kg/resets/reset_vespa.py, backend/onyx/kg/setup/kg_default_entity_definitions.py, backend/onyx/kg/utils/extraction_utils.py, backend/onyx/server/kg/api.py, backend/onyx/server/kg/models.py, backend/tests/integration/tests/kg/test_kg.py
- Replaced kg config with key value store
- Used locks for managing mutual exclusion of kg processing/reset tasks on a per-tenant basis. Fixes issues where if a process dies in the middle of processing, the lock stays locked forever
- kg_p and other commands now only runs from the KG Beta assistant
Benefits
- faster access because cached
- considerably simpler code for accessing and modifying the config
Downsides-ish
- may need to migrate if we add/remove stuff to the kg config unless we're fine with filling missing values with null (which technically doesn't make it any different from the current setup, so not really a downside)
Single tenant:
Multi tenant:
=> Kg config refactor

backend/onyx/connectors/discourse/connector.py
When accessing a Discourse category via `<baseUrl>/c/<categoryId>.json?page={pageNumber}&sys=latest`, Discourse issues a redirect to `<baseUrl>/c/<categorySlug>/<categoryId>.json?....`. During this redirect, any numeric occurrence matching the `categoryId` in the query string is also rewritten - including the page parameter - causing incorrect behavior (e.g., `page=5` becoming `page=community/5`).
This PR updates the connector logic to use the correct category url to avoid the redirection ensuring that the query parameters remain intact.
Try opening this link https://meta.discourse.org/c/10.json?page=10&sys=latest in the browser.  It will throw a 400 Bad Request error. When we inspect the url, we will notice the page number has been replaced by the `slug/categoryId`.
The issue was found …
=> fix(discourse-connector): handle redirect issue 

backend/onyx/background/celery/tasks/beat_schedule.py
^
This one only takes care of beat. From a quick glance, other ee tasks/functions are not called in the first place without ee enabled.
Locally
=> fix celery beat from scheduling ee tasks

backend/onyx/connectors/gmail/connector.py
Fixes https://linear.app/danswer/issue/DAN-2108/gmail-no-subject-docs-caues-crash
=> Fix no subject gmail docs

backend/onyx/configs/app_configs.py, backend/onyx/document_index/vespa/chunk_retrieval.py
Adding an optional variable (VESPA_LANGUAGE_OVERRIDE) that defaults to None, but - if set - overrides Vespa language detection.
Here is the ticket: https://linear.app/danswer/issue/DAN-2110/provide-ability-to-override-vespa-language
The variable is for not now in env templates etc.
Locally. Simulated a customer situation and tried query for three settings: None (default), de, en. As far as possible to tell,  the behavior is as desired.
=> Forcing vespa language

backend/pyproject.toml, backend/requirements/dev.txt
This PR re-adds `ruff` back into the `dev.txt` requirements file.
Not tested.
=> build: Update ruff to latest version

web/src/app/admin/kg/page.tsx, web/src/app/admin/kg/utils.ts, web/src/components/admin/ClientLayout.tsx
This PR removes the constant refresh of the KG-exposed endpoint.
Addresses: https://linear.app/danswer/issue/DAN-2114/fix-fetching-of-kg-exposed-endpoint.
Not tested.
=> fix: Fix sidebar logic to hit kg-endpoint for admins only

backend/onyx/kg/clustering/normalizations.py
The "public" tenant name needed to be removed  in the entity normalization function.
locally
=> Fix single-tenant normalization

deployment/docker_compose/docker-compose.dev.yml, deployment/docker_compose/docker-compose.gpu-dev.yml, deployment/docker_compose/docker-compose.multitenant-dev.yml, deployment/docker_compose/docker-compose.prod-cloud.yml, deployment/docker_compose/docker-compose.prod-no-letsencrypt.yml, deployment/docker_compose/docker-compose.prod.yml, deployment/docker_compose/docker-compose.search-testing.yml
Changed the restart policy to `unless-stopped` to ensure containers automatically restart after failures or reboots but allow manual stop without immediate restart.
This is preferable over `always` because it prevents containers from restarting automatically after a manual stop, enabling controlled shutdowns and maintenance without unintended restarts.
1. start docker containers
2. stop docker containers
3. restart docker engine
4. see that it doesnt automatically restart
1. start docker containers
3. restart docker engine
4. see that it automatically restarts (like before)
=> Update Docker Compose restart policy to unless-stopped

backend/onyx/db/kg_temp_view.py
We covered only 1/2 of the cases how a document can be public. We also need to allow docs with connector_credential_pair.access_type = "PUBLIC"
Linear: https://linear.app/danswer/issue/DAN-2140/bug-definition-of-public-docs-incomplete-in-kg-views
Locally, using Github docs. Also explicitly removed email ownership (for test purposes) to make sure that the docs are allowed because of the connector_credential_pair.access_type = "PUBLIC" condition.
=> Extend (fix) definition of public docs in KG Views

backend/ee/onyx/server/query_history/api.py
=> Fix query history 2

backend/tests/daily/connectors/google_drive/test_drive_perm_sync.py
=> Fix test_gdrive_perm_sync_with_real_data patching

backend/onyx/tools/tool_implementations/search/search_tool.py
My Documents deleted some code that was critically important for search performance, this adds it back
tested in UI
=> search speedup

backend/onyx/connectors/mediawiki/wiki.py
- Wikipedia connector now normalizes user input for categories
=> account for category prefix added by user

backend/alembic/versions/c9e2cd766c29_add_s3_file_store_table.py
=> Fix migration

web/src/app/chat/input/ChatInputBar.tsx, web/src/app/chat/input/LLMPopover.tsx, web/src/lib/hooks.ts
This PR solves the issue in which the incorrect model icon was being shown.
Addresses: https://linear.app/danswer/issue/DAN-2159/fix-incorrect-model-icon-being-shown.
UI changes; no testing needed.
=> fix: Fix bug with incorrect model icon being shown

backend/onyx/connectors/fireflies/connector.py, backend/tests/daily/connectors/fireflies/test_fireflies_connector.py, backend/tests/daily/connectors/fireflies/test_fireflies_data.json
Added date + duration
Date is part of the context string (doc_updated_at) already, but it seems like the model doesn't make the connection that updated_at = time of the meeting. Also, duration is the length of the meeting in minutes, floored to the nearest integer. Even if the last half of the meeting is silent, it will still count towards the duration. I think this is fine in most cases though.
Before:
After:
=> fireflies metadata update

web/src/app/chat/my-documents/[id]/UserFolderContent.tsx
.epub files apparently were forgotten and were not allowed for upload in the frontend, even though the backend can process them.
Upload a .epub file
=> Re-adding .epub file support

backend/onyx/agents/agent_search/orchestration/nodes/choose_tool.py, backend/onyx/context/search/federated/slack_search.py, backend/onyx/context/search/models.py, backend/onyx/context/search/preprocessing/preprocessing.py, backend/onyx/prompts/federated_search.py, backend/onyx/tools/models.py, backend/onyx/tools/tool_implementations/search/search_tool.py
Added original_query field to SearchQuery model + improved prompting for a better slack search expansion
Locally
=> feat: original query + better slack expansion

backend/alembic/versions/12635f6655b7_drive_canonical_ids.py
the migration takes forever for currently unknown reasons, skipping it for the time being. Downside is until it is run, everyone will see duplicate drive docs being indexed
n/a
=> skip id migration based on env var

backend/onyx/server/manage/slack_bot.py, web/src/app/admin/bots/[bot-id]/channels/SlackChannelConfigFormFields.tsx, web/src/app/admin/bots/[bot-id]/lib.ts
Fixes https://linear.app/danswer/issue/DAN-2165/stop-fetching-channel-info-to-make-pages-load-faster
Previously took a few seconds to load the page + it only loaded a small subset of channels, which made it misleading.
Set up slack bot locally.
=> Stop fetching channel info to make pages load faster

backend/onyx/file_processing/extract_file_text.py
=> add docx fallback

backend/onyx/connectors/factory.py, backend/onyx/connectors/imap/connector.py, backend/onyx/connectors/imap/models.py
This PR makes the `recipients` field optional. It also adds the `ImapConnector` to the list of identified connectors.
Addresses: https://linear.app/danswer/issue/DAN-2168/fix-imap-backend-connector-failures.
Existing IMAP connector tests still pass.
=> fix: More small IMAP backend fixes

backend/onyx/db/persona.py
Fixes https://linear.app/danswer/issue/DAN-98/fix-creating-assistant-with-same-name-as-before
=> personas no longer overwrite when same name

backend/alembic/env.py, backend/alembic/versions/36e9220ab794_update_kg_trigger_functions.py, backend/alembic/versions/495cb26ce93e_create_knowlege_graph_tables.py, backend/onyx/db/engine/async_sql_engine.py, backend/onyx/db/engine/sql_engine.py, backend/onyx/kg/clustering/clustering.py, backend/onyx/kg/clustering/normalizations.py, backend/shared_configs/configs.py
^
Tested running migrations locally on a non-default schema
=> fix: improve support for non-default postgres schemas

backend/onyx/connectors/file/connector.py, backend/onyx/file_processing/extract_file_text.py
- Minio switch changed file ids to S3 UUID --> zip metadata relies on file name
- Unstructured file processing failure should fallback to default Onyx file processing
Fixes #5073 and #5074, credit @dloss 
locally
=> fix: onyx metadata minio ID + permissive unstructured fail

.github/CODEOWNERS
Adding a codeowner group for the `helm/` directory to ensure we are following best practices. 
This is to ensure that the semvar versioning is maintained and properly configured.
This is just a CODEOWNER group change to add my username to specifically the Helm directory
=> feat(infra): Codeowner for Helm directory

backend/alembic/versions/62c3a055a141_add_file_names_to_file_connector_config.py, backend/onyx/connectors/file/connector.py, backend/onyx/db/user_documents.py, backend/onyx/server/documents/connector.py, backend/onyx/server/documents/models.py, backend/onyx/server/manage/administrative.py, backend/onyx/server/query_and_chat/chat_backend.py, backend/onyx/server/user_documents/api.py, backend/scripts/force_delete_connector_by_id.py, backend/tests/daily/connectors/file/test_file_connector.py, backend/tests/integration/common_utils/managers/connector.py, backend/tests/integration/tests/image_indexing/test_indexing_images.py, backend/tests/integration/tests/indexing/file_connector/test_file_connector_zip_metadata.py, backend/tests/integration/tests/kg/test_kg_processing.py, backend/tests/regression/answer_quality/api_utils.py, web/src/app/admin/connector/[ccPairId]/ConfigDisplay.tsx, web/src/app/admin/connectors/[connector]/pages/utils/files.ts, web/src/lib/connectors/connectors.tsx, web/src/lib/fileUtils.ts
- minio changed file_id to a file store UUID (instead of file name) --> file connector showed this UUID instead of file name
- maintain filename is file connector specific config for display
locally
=> fix: minio file names

backend/ee/onyx/onyxbot/slack/handlers/handle_standard_answers.py, backend/onyx/onyxbot/slack/blocks.py, backend/onyx/onyxbot/slack/handlers/handle_buttons.py, backend/onyx/onyxbot/slack/handlers/handle_message.py, backend/onyx/onyxbot/slack/handlers/handle_regular_answer.py, backend/onyx/onyxbot/slack/listener.py, backend/onyx/onyxbot/slack/models.py
- /onyxbot should respond in ephemeral message, but instead sends to channel
locally
=> fix: slash command slackbot to respond in private msg

backend/onyx/onyxbot/slack/listener.py
- title, remove slack msg content from logs
locally
=> fix: sanitize slack payload before logging

web/src/lib/hooks.ts
=> fix: add gpt 5 display names

.github/workflows/helm-chart-releases.yml
There seems to have been an issue with the helm release pipeline because we are adding in the helm_version to the run function. We already install helm at an earlier step so removing it given it's duplicated. 
Link to failing github action: https://github.com/onyx-dot-app/onyx/actions/runs/16843711808/job/47719611239#step:2:20
This is an update to a broken Github Action
=> fix(infra): Removing invalid helm version

backend/onyx/auth/users.py, backend/onyx/configs/app_configs.py, backend/tests/unit/onyx/auth/test_verify_email_domain.py
We had an issue with a customer domain returning a non lowercase domain thus failing the casing issues when there were uppercase domains being returned by the IdP. 
This PR aims to fix this to ensure that we can handle all types of domains that are returned by any IdP.
Ran the local unit tests by running: 
`pytest -s backend/tests/unit/onyx/auth/test_verify_email_domain.py`
=> feat(auth): Fix OAuth Domain casing

backend/onyx/background/celery/tasks/docprocessing/heartbeat.py
We need to add additional logging in order to investigate why there are issues with the logging of the heartbeat and understand why there is an issue. 
=> feat(docprocessing): Adding additional logs

deployment/terraform/modules/aws/eks/main.tf, deployment/terraform/modules/aws/eks/variables.tf, deployment/terraform/modules/aws/onyx/main.tf, deployment/terraform/modules/aws/onyx/outputs.tf, deployment/terraform/modules/aws/onyx/variables.tf, deployment/terraform/modules/aws/postgres/main.tf, deployment/terraform/modules/aws/postgres/outputs.tf, deployment/terraform/modules/aws/postgres/variables.tf, deployment/terraform/modules/aws/vpc/main.tf
Adding new workflow to configure AWS IAM RDS Auth for your EKS cluster. This allows you to not use a password but rather an IAM token to access the database. This is to improve the security posture of Onyx. 
Ran an internal cluster deployment
Closes https://linear.app/danswer/issue/DAN-2330/iam-for-rds-permissions-codification
=> feat(infra): AWS IAM Terraform

web/src/app/admin/settings/SettingsForm.tsx, web/src/components/Field.tsx, web/src/components/credentials/CredentialFields.tsx, web/src/components/ui/CheckField.tsx, web/tests/e2e/assistants/create_and_edit_assistant.spec.ts
- Original issue: certain radios/checkboxes required users to click specifically just the box component
- Nested labels cause text to not be clickable
- Introduce htmlFor that associates html elements with the form input item using a unique id
- CheckField.tsx had bugged logic that reset the form value on click
- locally
=> fix: make radios and checkboxes actually clickable

web/src/app/chat/components/ChatPage.tsx, web/src/app/chat/components/starterMessages/StarterMessageDisplay.tsx
1. Bar is more centered
2. Bar doesn't shift based on whether or not starter messages are present
3. Background color on hover for starter messages is fixed for dark mode
=> feat: Small center bar improvements

backend/requirements/default.txt
We are using an old version of the Jira Python Client that has issues with the new path that is required in order to search against the cloud environments.
Tested that this works on Jira and Jira Datacenter and we are still able to index properly.
=> fix(jira): Upgrade the Jira Python Version

web/src/app/admin/add-connector/page.tsx
- show popular section when hiding + de-dupe results so they don't show twice
=> fix: allow web and file to show in results

backend/onyx/server/features/folder/api.py, web/src/app/chat/components/folders/FolderList.tsx, web/src/components/sidebar/ChatSessionDisplay.tsx, web/src/components/sidebar/PagesTab.tsx
- No way to move chats out of groups other than deleting the group
- Allow with new button in 3 dot menu --> identical to ChatGPT's adding chat to Project functionality
fixes: https://linear.app/danswer/issue/DAN-2306/moving-chat-into-group-is-one-way-cannot-remove
=> fix: allow chats to be moved out of chat groups

backend/alembic/versions/d09fc20a3c66_seed_builtin_tools.py
=> fix: tool seeding migration

.github/workflows/helm-chart-releases.yml
The chart releaser did not have the kedacore chart so it failed to build
Will run in CI
=> fix(infra): Update chart releaser

backend/onyx/connectors/slack/connector.py
=> fix(slack): swapped checkpoint index

web/src/app/chat/message/messageComponents/CitedSourcesToggle.tsx
=> Remove confusing text

.github/workflows/pr-integration-tests.yml, .github/workflows/pr-mit-integration-tests.yml
There have been some recent issues with the integration tests due to the blacksmith registry having caching issues. We are disabling the caching temporarily in order to unblock the CI. 
Context for the issue can be found here: https://onyx-company.slack.com/archives/C09DHFK3220/p1758734368330299
Tested by running the CI on a different PR with these same exact changes.
=> fix(github): Fix Integration Tests

deployment/helm/README.md, deployment/helm/charts/onyx/Chart.lock, deployment/helm/charts/onyx/Chart.yaml, deployment/helm/charts/onyx/templates/_helpers.tpl, deployment/helm/charts/onyx/templates/api-hpa.yaml, deployment/helm/charts/onyx/templates/api-scaledobject.yaml, deployment/helm/charts/onyx/templates/celery-worker-docfetching-hpa.yaml, deployment/helm/charts/onyx/templates/celery-worker-docfetching-scaledobject.yaml, deployment/helm/charts/onyx/templates/celery-worker-docprocessing-hpa.yaml, deployment/helm/charts/onyx/templates/celery-worker-docprocessing-scaledobject.yaml, deployment/helm/charts/onyx/templates/celery-worker-heavy-hpa.yaml, deployment/helm/charts/onyx/templates/celery-worker-heavy-scaledobject.yaml, deployment/helm/charts/onyx/templates/celery-worker-light-hpa.yaml, deployment/helm/charts/onyx/templates/celery-worker-light-scaledobject.yaml, deployment/helm/charts/onyx/templates/celery-worker-monitoring-hpa.yaml, deployment/helm/charts/onyx/templates/celery-worker-monitoring-scaledobject.yaml, deployment/helm/charts/onyx/templates/celery-worker-primary-hpa.yaml, deployment/helm/charts/onyx/templates/celery-worker-primary-scaledobject.yaml, deployment/helm/charts/onyx/templates/celery-worker-user-files-indexing-hpa.yaml, deployment/helm/charts/onyx/templates/celery-worker-user-files-indexing-scaledobject.yaml, deployment/helm/charts/onyx/templates/webserver-hpa.yaml, deployment/helm/charts/onyx/templates/webserver-scaledobject.yaml, deployment/helm/charts/onyx/values.yaml
Making KEDA an option that the customer can choose. This is to ensure that the dependency is not added. 
The customer is then in charge of adding the KEDA dependency and can manage that in their cluster. 
We needed to add HPA's for celery workers that did not have them previously to introduce autoscaling as well. 
Ran helm template commands to validate that the charts were provisioned properly.
=> feat(infra): Default to HPA w/ KEDA option

.github/workflows/pr-integration-tests.yml, .github/workflows/pr-mit-integration-tests.yml
We are now trying to test that caching is the issue that leads to integration tests being broken. This is a test PR
We are testing this with this PR
=> fix(github): Revert cache being turned off

backend/ee/onyx/server/auth_check.py, backend/ee/onyx/server/saml.py, web/src/app/auth/saml/callback/route.ts
SAML seemed to be only implemented to handle POST requests for the callback function. This may have worked for Okta and some other applications but for Entra ID it seems that we will need to handle the callback as a GET request not a POST request. 
Customer reported issue: 
Ran tests locally to ensure that the old workflow is still intact while supporting GET functions now moving forward.
=> fix(saml): GET Method for SAML Callback

backend/requirements/default.txt
- Mac OS update broke local web connector 
- 
=> chore: bump playwright version

.github/workflows/helm-chart-releases.yml, .github/workflows/pr-helm-chart-testing.yml, ct.yaml, deployment/helm/charts/onyx/Chart.lock, deployment/helm/charts/onyx/Chart.yaml, deployment/helm/charts/onyx/templates/configmap.yaml, deployment/helm/charts/onyx/values.yaml
Migrating away from the bitnami for our MinIO setup since this is going to cause another breaking change even though the OCI registry seems like it's still active. 
Validated that the values have been updated to match the new chart that is published to https://github.com/minio/minio/tree/master/helm-releases
Validated that the templating was generated properly and ran CT tests locally.
=> fix(helm): MinIO Migration from Bitnami

web/src/components/UserDropdown.tsx, web/src/lib/user.ts
Historically, if a customer was logged in with SSO and they clicked Log out, they would be instantly logged back into the product because they were still signed into their IdP. 
In theory this makes sense since they should be able to validly log back into the project without any issues but still this is not a great user experience. 
This PR aims to fix that workflow but ensuring that when you click on the logout button you get properly logged out and then redirected to the login with  SSO provider page. This will then force you to have to click on the button again in order to properly log out. 
Manually brought up a SAML setup and logged out and then validated that this was all …
=> fix(SSO): Logout funtionality fixed

web/src/components/llm/LLMSelector.tsx, web/src/sections/sidebar/Settings.tsx
Currently with the updated FE, the User Settings page has a Model Selection dropdown that does not work and does not display anything. 
Our old setup had a different issue in which it would show all of the models that were usable with the provider selected but this causes confusion amongst users and thus we need to limit it to the models that have already been selected to be visible by the admin users. 
Tested this locally and ensured that it was working properly 
Fe-dev:
Localhost:
=> fix(UI): Update User Settings Model Selection
