backend/danswer/auth/users.py
backend/danswer/main.py
backend/danswer/server/manage/users.py
web/src/app/assistants/gallery/page.tsx

Stops unnecessary logging of stack trace when user is not authenticated
New logs look like 
```
INFO:     11/09/2024 01:20:12 PM                    h11_impl.py  499: 127.0.0.1:62124 - "GET /me HTTP/1.1" 403
ERROR:    11/09/2024 01:20:12 PM                        main.py  201: Authentication failed: 403: User Not Authenticated
INFO:     11/09/2024 01:20:12 PM                    h11_impl.py  499: 127.0.0.1:62127 - "GET /me HTTP/1.1" 403
INFO:     11/09/2024 01:20:12 PM                    h11_impl.py  499: 127.0.0.1:62120 - "GET /auth/oauth/authorize HTTP/1.1" 200
INFO:     11/09/2024 01:20:12 PM                    h11_impl.py  499: ::1:0 - "GET /health HTTP/1.1" 200
ERROR:    11/09/2024 01:20:12 PM                        main.py  201: Authentication failed: 403: Access denied. User is not …
```

Silence auth logs

---

web/src/app/chat/ChatPage.tsx
web/src/app/chat/lib.tsx

Improved mobile scroll

---

backend/danswer/configs/model_configs.py
backend/danswer/llm/chat_llm.py

Support LITELLM_EXTRA_BODY env variable

---

examples/widget/src/app/widget/Widget.tsx

Fix widget example

---

backend/danswer/connectors/confluence/utils.py
backend/tests/daily/connectors/confluence/test_confluence_basic.py

Added support for page within a page in Confluence

---

backend/danswer/db/connector_credential_pair.py
backend/danswer/server/documents/cc_pair.py
backend/danswer/server/documents/connector.py
backend/danswer/server/documents/models.py
backend/ee/danswer/db/user_group.py
backend/tests/integration/common_utils/managers/cc_pair.py
backend/tests/integration/common_utils/managers/connector.py
backend/tests/integration/common_utils/test_models.py
backend/tests/integration/connector_job_tests/slack/test_permission_sync.py
backend/tests/integration/connector_job_tests/slack/test_prune.py
backend/tests/integration/multitenant_tests/tenants/test_tenant_creation.py
backend/tests/integration/tests/permissions/test_cc_pair_permissions.py
backend/tests/integration/tests/permissions/test_connector_permissions.py
backend/tests/integration/tests/permissions/test_whole_curator_flow.py
web/src/app/admin/connector/[ccPairId]/page.tsx
web/src/app/admin/connector/[ccPairId]/types.ts
web/src/app/admin/connectors/[connector]/AddConnectorPage.tsx
web/src/app/admin/connectors/[connector]/pages/DynamicConnectorCreationForm.tsx
web/src/app/admin/connectors/[connector]/pages/utils/files.ts
web/src/app/admin/connectors/[connector]/pages/utils/google_site.ts
web/src/app/admin/indexing/status/CCPairIndexingStatusTable.tsx
web/src/components/IsPublicGroupSelector.tsx
web/src/components/admin/connectors/AccessTypeForm.tsx
web/src/components/admin/connectors/AccessTypeGroupSelector.tsx
web/src/components/credentials/actions/CreateCredential.tsx
web/src/lib/connectors/connectors.tsx

Make curators able to create permission synced connectors

---

backend/danswer/connectors/google_drive/connector.py
backend/danswer/connectors/google_utils/google_utils.py
web/src/app/admin/connectors/[connector]/pages/DynamicConnectorCreationForm.tsx
web/src/lib/connectors/connectors.tsx

- Updated copy
- changed it from textfield to textarea
- Fixed issue where incorrect options were being displayed to users using oauth
- updated backend logic to not break if non admin user in org is trying to access shared drives using oauth
here is new copy + textarea:

Updated google copy and added non admin oauth support

---

backend/danswer/background/celery/apps/indexing.py

scale indexing sql pool based on concurrency

---

web/src/app/chat/ChatPage.tsx

minor clarity

---

backend/danswer/db/engine.py

use text()

---

.github/workflows/pr-helm-chart-testing.yml

unnecessary python setup

---

backend/danswer/llm/answering/answer.py
backend/danswer/llm/answering/prompts/build.py
backend/danswer/tools/tool_implementations/search_like_tool_utils.py
examples/assistants-api/topics_analyzer.py

There are some flows where the LLM prompt had repeated text.
Tested Search and Slack Bot
This could use integration tests. But I have no time for it.
N/A

Fix Quotes Prompting

---

backend/danswer/document_index/vespa/app_config/schemas/danswer_chunk.sd

minor configuration updates

---

backend/danswer/tools/tool_implementations/custom/custom_tool.py

Add error message on JSON decode error in CustomTool

---

backend/tests/integration/common_utils/managers/cc_pair.py

Fixed int test

---

backend/danswer/background/indexing/run_indexing.py
backend/danswer/db/document.py
backend/danswer/indexing/indexing_pipeline.py
backend/tests/integration/common_utils/managers/cc_pair.py
backend/tests/integration/tests/connector/test_connector_deletion.py

merge overlapping connector hotfix

---

backend/danswer/auth/invited_users.py
backend/danswer/chat/process_message.py
backend/danswer/db/models.py
backend/danswer/key_value_store/interface.py
backend/danswer/key_value_store/store.py
backend/danswer/llm/chat_llm.py
backend/danswer/llm/factory.py
backend/danswer/main.py
backend/danswer/one_shot_answer/answer_question.py
backend/danswer/server/long_term_logs/long_term_logs_api.py
backend/danswer/tools/tool.py
backend/danswer/tools/tool_implementations/custom/custom_tool.py
backend/danswer/tools/tool_implementations/images/image_generation_tool.py
backend/danswer/tools/tool_implementations/internet_search/internet_search_tool.py
backend/danswer/tools/tool_implementations/search/search_tool.py
backend/danswer/utils/long_term_log.py
backend/danswer/utils/special_types.py
web/src/app/admin/debug/page.tsx

Easier way to debug issues at the LLM-call level.

Long term logs

---

web/src/app/chat/ChatPage.tsx
web/src/app/chat/sessionSidebar/HistorySidebar.tsx
web/src/app/chat/shared_chat_search/FixedLogo.tsx
web/src/app/chat/shared_chat_search/FunctionalWrapper.tsx
web/src/components/Dropdown.tsx
web/src/components/assistants/StarterMessage.tsx
web/src/components/header/LogoType.tsx
web/src/components/search/DateRangeSelector.tsx
web/src/components/search/filtering/FilterDropdown.tsx
web/src/components/search/filtering/Filters.tsx
web/tailwind-themes/tailwind.config.js

1. Sidebar Styling:
- `background-history-sidebar-button-hover`: Hover background for sidebar buttons
- `text-history-sidebar-button`: Text and icon color for sidebar buttons
- `divider-history-sidebar-bar`: Color for divider between buttons and chat history
- `text-mobile-sidebar`: Mobile sidebar text color (affects logotype and icons)
2. Chat Empty State:
- `background-starter-message`: Background for starter message cards
- `background-starter-message-hover`: Hover background for starter message cards
3. Search Tab Styling:
- `background-search-filter`: Background for dropdowns/selects in input field
- `background-search-filter-dropdown`: Background for dropdown menus in input field
4. Application Toggle (Search/Chat):
- `text-application-toggled`: Text color for active state
- …

add additional theming options

---

backend/danswer/background/celery/tasks/indexing/tasks.py
backend/danswer/background/celery/tasks/shared/tasks.py
backend/danswer/background/celery/tasks/vespa/tasks.py
backend/danswer/redis/redis_connector_delete.py
backend/danswer/server/documents/connector.py

Hardening deletion when cc pair relationships are left over

---

backend/danswer/document_index/vespa/indexing_utils.py
backend/danswer/indexing/indexing_pipeline.py

add helpful hint on 507

---

web/src/components/search/filtering/Filters.tsx
web/src/components/ui/calendar.tsx
web/src/lib/dateUtils.ts

https://github.com/user-attachments/assets/bffd2ea9-3ac9-4129-b53b-3312c6fdd381

add new date search filter

---

backend/ee/danswer/server/query_history/api.py
backend/tests/integration/tests/query-history/test_query_history.py
web/src/app/ee/admin/performance/query-history/QueryHistoryTable.tsx
web/src/app/ee/admin/performance/usage/types.ts

Extend query history API

---

web/src/app/admin/configuration/llm/LLMProviderUpdateForm.tsx
web/src/components/AdvancedOptionsToggle.tsx
web/src/components/admin/connectors/Field.tsx

Cannot rely on flex's stretch for buttons.
N/A
N/A

ensure margin properly applied

---

backend/danswer/danswerbot/slack/config.py
backend/danswer/danswerbot/slack/listener.py
web/src/app/admin/bots/SlackTokensForm.tsx

update slack redirect + token missing check

---

web/src/lib/chat/fetchAssistantdata.ts

Adjust logging level for a recurring and noisy issue. Other logs would catch API server being down - this one is to be expected. 
N/A
N/A
Note: You have to check that the action passes, otherwise resolve the conflicts manually …

Silence non error

---

backend/danswer/connectors/confluence/connector.py
backend/danswer/connectors/confluence/onyx_confluence.py
backend/danswer/connectors/confluence/utils.py
backend/ee/danswer/external_permissions/confluence/group_sync.py

decreased confluence retry times and added more logging

---

backend/danswer/connectors/confluence/connector.py
backend/danswer/connectors/confluence/onyx_confluence.py
backend/danswer/connectors/confluence/utils.py
backend/ee/danswer/external_permissions/confluence/group_sync.py

* standardized escaping of CQL strings
* think i found it
* fix
* should be fixed
* added handling for special linking behavior in confluence
* Update onyx_confluence.py
* Update onyx_confluence.py
---------
N/A
N/A
- Author has done a …

added logging and bugfixing to conf (#3167)

---

web/src/app/admin/assistants/[id]/page.tsx
web/src/app/assistants/edit/[id]/page.tsx

Editing pages are reversed for admin prop for assistant editor
N/A
N/A

valid assistant editor props

---

web/src/app/globals.css
web/src/components/search/SearchResultsDisplay.tsx

Formatting Niceties

---

backend/danswer/connectors/danswer_jira/connector.py
backend/danswer/connectors/danswer_jira/utils.py
backend/tests/unit/danswer/connectors/jira/test_large_ticket_handling.py

- Added slim connector to jira for less overhead when pruning.
- Added better pagination (now will retrieve->process->retrieve->process instead of retrieve all->process all)
- refactored for future extensibility
- updated tests

Added Slim connector for Jira

---

web/src/lib/constants.ts

Update default sidebar toggle

---

backend/danswer/background/celery/apps/primary.py
backend/danswer/background/celery/tasks/indexing/tasks.py
backend/danswer/background/celery/tasks/vespa/tasks.py
backend/danswer/db/index_attempt.py

backport double check

---

web/src/app/admin/assistants/AssistantEditor.tsx
web/src/components/context/AssistantsContext.tsx

Refresh all assistants on assistant refresh

---

web/src/app/chat/ChatPage.tsx
web/src/app/chat/documentSidebar/DocumentSidebar.tsx
web/src/app/chat/message/Messages.tsx

revert to previous doc select logic

---

backend/danswer/connectors/confluence/onyx_confluence.py

add minimal retries to confluence probe

---

web/src/app/ee/admin/performance/DateRangeSelector.tsx
web/src/app/ee/admin/performance/lib.ts
web/src/app/ee/admin/performance/query-history/QueryHistoryTable.tsx

https://github.com/user-attachments/assets/5245bd3f-1c3e-47de-8075-10bf11c1ce91

Ensure daterange not consistently re rendered

---

web/src/components/search/filtering/Filters.tsx
web/src/components/ui/calendar.tsx
web/src/lib/dateUtils.ts
web/tailwind-themes/tailwind.config.js

Add tailwind customization + date range string formatting
N/A
N/A

minor calendar cleanup

---

backend/danswer/llm/utils.py

minor enforcement of CSV length for internal processing

---

web/src/app/ee/admin/cloud-settings/BillingInformationPage.tsx

remove unused stripe promise

---

backend/danswer/background/celery/tasks/doc_permission_syncing/tasks.py
backend/danswer/background/celery/tasks/external_group_syncing/tasks.py
backend/danswer/connectors/confluence/connector.py
backend/danswer/connectors/confluence/onyx_confluence.py
backend/danswer/db/connector_credential_pair.py
backend/ee/danswer/access/access.py
backend/ee/danswer/db/user_group.py
backend/ee/danswer/external_permissions/confluence/doc_sync.py
backend/ee/danswer/external_permissions/confluence/group_sync.py
backend/ee/danswer/external_permissions/sync_params.py
backend/tests/integration/connector_job_tests/slack/test_permission_sync.py

- groups are no longer added to acl
- decreased group permission sync frequency
- added better logging

Perm sync behavior change

---

web/src/app/ee/admin/performance/usage/QueryPerformanceChart.tsx
web/src/components/ui/areaChart.tsx

no stack by default

---

backend/danswer/natural_language_processing/utils.py

the word "error" might be throwing off sentry

---

backend/danswer/main.py

This pull request includes changes to the `backend/danswer/main.py` file to add a new API key router and integrate it into the application setup.
API Integration:
* [`backend/danswer/main.py`](diffhunk://#diff-1fc76671aa6a416f48f7a3a3ed3e3c85b5f48c9633b770010f874ba16b21d1c7R93): Imported the `api_key_router` from `danswer.server.api_key.api` to include the new API key router.
* [`backend/danswer/main.py`](diffhunk://#diff-1fc76671aa6a416f48f7a3a3ed3e3c85b5f48c9633b770010f874ba16b21d1c7R284): Added `api_key_router` to the application by including it with the `include_router_with_global_prefix_prepended` function in the `get_application` method.
This is tested by looking into the changes in the ui
N/A
N/A …

fix: Cannot configure API keys #3191

---

backend/ee/danswer/main.py

Remove duplicate API key router

---

backend/alembic/versions/abe7378b8217_add_indexing_trigger_to_cc_pair.py
backend/danswer/background/celery/tasks/indexing/tasks.py
backend/danswer/background/celery/versioned_apps/beat.py
backend/danswer/background/celery/versioned_apps/primary.py
backend/danswer/db/connector.py
backend/danswer/db/enums.py
backend/danswer/db/models.py
backend/danswer/main.py
backend/danswer/server/documents/connector.py

use indexing flag in db for manually triggering indexing

---

backend/ee/danswer/external_permissions/confluence/doc_sync.py

increased the pagination limit for confluence spaces

---

backend/danswer/seeding/load_yamls.py
backend/danswer/setup.py

order seeding properly

---

backend/danswer/file_processing/extract_file_text.py

^. Prevents OOM for large xlsx files

Add read_only=True for xlsx parsing

---

backend/danswer/db/persona.py
web/src/app/admin/assistants/lib.ts

^
Previously, if you edited an assistant, its prompt would get wiped.

Fix assistant prompt zero-ing

---

backend/danswer/db/persona.py
web/src/app/admin/assistants/lib.ts

Fix assistant prompt zero-ing (#3293)

---

web/src/app/admin/assistants/AssistantEditor.tsx
web/src/components/chat_search/AssistantSelector.tsx
web/src/components/chat_search/sources/SourceCard.tsx
web/src/lib/utils.ts

Update display name + model truncation

---

backend/requirements/model_server.txt

https://community.openai.com/t/client-openai-returns-error-client-init-got-an-unexpected-keyword-argument-proxies/1035249/14

Update openai version in model server

---

backend/alembic/env.py
backend/alembic_tenants/env.py
backend/danswer/chat/chat_utils.py
backend/danswer/chat/models.py
backend/danswer/tools/tool_implementations/internet_search/internet_search_tool.py
backend/tests/integration/tests/personas/test_persona_categories.py
backend/tests/unit/danswer/llm/answering/conftest.py
backend/tests/unit/danswer/llm/answering/stream_processing/test_citation_processing.py
backend/tests/unit/danswer/llm/answering/stream_processing/test_quote_processing.py
web/src/app/chat/input/ChatInputBar.tsx
web/src/app/chat/input/FilterDisplay.tsx
web/src/app/chat/input/FilterPills.tsx
web/src/app/chat/shared_chat_search/SearchFilters.tsx

- Fix typing (alembic + misc test)
- Add match highlights to LLM Doc (for new order of operations on frontend)
- Add filters within chat input bar (see video)
- Select all only on if all are selected (in document sidebar)
https://github.com/user-attachments/assets/1aa75c2c-a0f8-4b88-9f9a-a7709d420772
N/A
N/A
- Docker images build and basic …

Unified UI

---

backend/danswer/configs/app_configs.py

Adjust default confluence timezone

---

web/src/app/chat/ChatPage.tsx
web/src/app/chat/lib.tsx
web/src/lib/search/interfaces.ts
web/src/lib/search/streamingQa.ts

Fixes https://linear.app/danswer/issue/DAN-1068/small-search-flow-enhancements
N/A
N/A

Search flow improvements

---

web/playwright.config.ts

try single threaded playwright testing

---

web/src/app/admin/assistants/PersonaTable.tsx
web/src/app/admin/connectors/[connector]/pages/gdrive/GoogleDrivePage.tsx
web/src/app/admin/connectors/[connector]/pages/gmail/GmailPage.tsx
web/src/app/auth/impersonate/page.tsx
web/src/app/chat/ChatPage.tsx
web/src/app/ee/admin/groups/[groupId]/GroupDisplay.tsx
web/src/app/ee/admin/groups/page.tsx
web/src/components/IsPublicGroupSelector.tsx
web/src/components/admin/connectors/AccessTypeForm.tsx
web/src/components/admin/connectors/AccessTypeGroupSelector.tsx
web/src/components/context/AssistantsContext.tsx
web/src/components/credentials/actions/CreateCredential.tsx
web/src/components/user/UserProvider.tsx

Removes vestigial user loading indicator.
Previously, we always fetched user client side; now we perform initial fetch server side, so user is never "loading" on the initial page render (which is what all existing conditionals checked for.
N/A
N/A
- Author has done a final read through of the PR …

Remove now unnecessary user loading indicator

---

backend/scripts/chat_loadtest.py

Add basic loadtest script

---

backend/danswer/auth/users.py
backend/danswer/db/engine.py
backend/danswer/main.py
backend/danswer/server/manage/users.py
backend/danswer/server/utils.py
deployment/cloud_kubernetes/workers/beat.yaml
deployment/cloud_kubernetes/workers/heavy_worker.yaml
deployment/cloud_kubernetes/workers/indexing_worker.yaml
deployment/cloud_kubernetes/workers/light_worker.yaml
deployment/cloud_kubernetes/workers/primary.yaml
web/src/app/admin/embeddings/pages/EmbeddingFormPage.tsx

- Update memoization for reindexing (ensure props updated)
- Silence unnecessary auth error logs (~20k weekly unnecessary error logs)
N/A
N/A
Note: You have to check that the action passes, otherwise resolve the conflicts …

Update memoization + silence unnecessary errors

---

web/src/app/global-error.tsx
web/src/app/not-found.tsx

Redirect to chat

---

web/tests/e2e/admin_assistants.spec.ts
web/tests/e2e/home.spec.ts

fixing chromatic tests

---

backend/danswer/chat/process_message.py
backend/danswer/configs/tool_configs.py
backend/danswer/file_store/utils.py
backend/danswer/llm/utils.py
backend/danswer/tools/tool_implementations/images/image_generation_tool.py
backend/danswer/tools/tool_implementations/images/prompt.py
backend/danswer/utils/b64.py

Add b64 image support for image generation

---

web/src/app/chat/ChatPage.tsx
web/src/app/chat/documentSidebar/DocumentSelector.tsx
web/src/components/chat_search/AssistantSelector.tsx
web/src/components/chat_search/Header.tsx

Fix https://linear.app/danswer/issue/DAN-1079/header-bar-clashes-with-new-assistant-selector-sidebar
Fix https://linear.app/danswer/issue/DAN-1080/selecting-a-document-in-the-new-sidebar-opens-the-link
N/A
N/A
Note: You have to …

Various niceties for new chat flow

---

web/src/app/admin/bots/[bot-id]/channels/SlackChannelConfigCreationForm.tsx
web/src/components/admin/connectors/Field.tsx

- Fix info tooltip submitting form
- Fix ordering of checkbox items and follow up in web ui
- Fix reflexion info
Works locally
N/A
N/A

Fix SlackBot Page Bugs

---

backend/danswer/configs/app_configs.py
backend/danswer/setup.py

This is failing for folks despite no issue with Vespa. Bump it up + make it configurable.

Increase vespa attempts on startup

---

backend/alembic/versions/f7a894b06d02_non_nullbale_slack_bot_id_in_channel_.py
backend/danswer/db/models.py

fix slackbot channel config nullable

---

backend/ee/danswer/configs/app_configs.py
backend/ee/danswer/db/external_perm.py
backend/ee/danswer/external_permissions/confluence/doc_sync.py
backend/ee/danswer/external_permissions/sync_params.py

- Caught edge case where some spaces didnt get correctly premission retrieved
- handled case where users didnt had email and not id 
- Logging!

More logging/fixes

---

web/src/app/admin/connectors/[connector]/AddConnectorPage.tsx
web/src/lib/types.ts

hide oauth sources

---

backend/danswer/connectors/teams/connector.py

Tested by running it and viewing the logs (nothing better than ID for channels unfortunately)
```
DEBUG:    12/07/2024 04:27:31 PM                   connector.py  237: [CC Pair: 8] [Index Attempt: 95] Found available teams: ['Test2']
DEBUG:    12/07/2024 04:27:31 PM                   connector.py  246: [CC Pair: 8] [Index Attempt: 95] Found available channels: ['<office365.teams.channels.channel.Channel object at 0x34a601210>', '<office365.teams.channels.channel.Channel object at 0x347b94510>']
DEBUG:    12/07/2024 04:27:31 PM                   connector.py  255: [CC Pair: 8] [Index Attempt: 95] Fetching threads from channel: 19:69a96a63f09c457d9efd43d9b8772140@thread.tacv2
DEBUG:    12/07/2024 04:27:33 PM                   connector.py  255: [CC Pair: 8] [Index Attempt: 95] Fetching …
```

Add more logging + retries to teams connector

---

backend/danswer/db/persona.py
backend/danswer/seeding/load_yamls.py
backend/ee/danswer/server/seeding.py
backend/tests/integration/common_utils/managers/persona.py

Tries to make it harder (impossible??) to have a persona without a prompt. Should fail loudly at the time of issue.

Persona / prompt hardening

---

web/src/app/admin/indexing/status/CCPairIndexingStatusTable.tsx

Fix https://linear.app/danswer/issue/DAN-1150/expand-all-behavior-wrong
N/A
N/A

unify toggling

---

backend/danswer/connectors/linear/connector.py

Fixes https://github.com/onyx-dot-app/onyx/issues/3370
N/A
N/A

fix linear

---

web/src/app/connector/oauth/callback/[source]/route.tsx

Remove dev-only check

---

web/src/app/admin/documents/feedback/DocumentFeedbackTable.tsx

Score alignment was off. ml-auto apparently causes 'margin-left' to be handled automatically, which was making an internal div right-justified.
Checked in UI with multiple window sizes. It looks correct to me, and even if it's not absolutely perfect its a lot better than it was before
N/A
N/A
- Author has done a final read through of the PR right …

centered score in feedback panel

---

web/src/components/assistants/AssistantCards.tsx

Fixes https://linear.app/danswer/issue/DAN-1148/remove-doc-set-for-assistant-display
N/A
N/A

remove doc sets

---

web/src/components/search/results/Citation.tsx

Fixes https://linear.app/danswer/issue/DAN-1123/citation-ugly
- Center align
- Always a circle
- Text in citation aligned with other text content
- Various numbers
N/A
N/A
Note: You have to check that the action passes, otherwise resolve the conflicts manually and tag the …

cleaner citations

---

web/src/app/chat/ChatPage.tsx

Fixes https://linear.app/danswer/issue/DAN-1111/context-sidebar-closes-on-its-own
N/A
N/A

Fix context sidebar effect

---

ct.yaml
deployment/helm/charts/danswer/Chart.lock
deployment/helm/charts/danswer/Chart.yaml

update helm charts for onyx-dot-app rebrand

---

backend/danswer/db/credentials.py
backend/danswer/server/documents/credential.py

Fixes https://linear.app/danswer/issue/DAN-1107/cant-update-credential
Turns out our ORM can't recognize in place updates to json!
N/A
N/A
Note: You have to check that the action passes, otherwise resolve the conflicts manually …

recognize updates

---

web/src/app/admin/connector/[ccPairId]/ConfigDisplay.tsx

Fixes https://linear.app/danswer/issue/DAN-1152/fix-connector-page-ugly
https://github.com/user-attachments/assets/5a7fb494-0b8c-4e12-b047-f00f5756982f
N/A
N/A
Note: You have to check that the action passes, otherwise resolve …

Connector page lists (pending feedback)

---

web/src/app/admin/connector/[ccPairId]/page.tsx

Fix bug (title overflow)

---

backend/danswer/auth/api_key.py

Fixes https://linear.app/danswer/issue/DAN-1116/api-keys-take-very-long-time-to-hash-for-comparison-to-db-objects
N/A
N/A
Note: You have to check that the action passes, otherwise resolve the conflicts manually and tag the …

Faster api hashing

---

backend/tests/integration/connector_job_tests/slack/test_permission_sync.py

Silence Slack permission failing

---

web/src/components/admin/ClientLayout.tsx
web/src/components/chat_search/Header.tsx
web/src/components/header/LogoType.tsx

Fixes https://linear.app/danswer/issue/DAN-1117/chat-page-header-is-clickable-but-nothing-happens-also-when-clicked
N/A
N/A
Note: You have to check that the action passes, otherwise resolve the conflicts manually and tag the …

clean up cursor pointers

---

web/src/app/admin/api-key/page.tsx

Fixes https://linear.app/danswer/issue/DAN-1095/double-x
N/A
N/A

remove double x

---

web/src/app/admin/connectors/[connector]/pages/gdrive/GoogleDrivePage.tsx

- it would confuse credentials that had that field, regardless of source which meant if someone had a gmail connector already set up, it could break

Made frontend conditional check for source for gdrive

---

backend/danswer/connectors/egnyte/connector.py

^
For debugging a failure in our cloud.

add more egnyte failure logging

---

backend/danswer/db/models.py
backend/danswer/db/slack_bot.py
web/src/app/admin/bots/SlackBotTable.tsx

Added text for empty table and cascade delete for slack bot deletion

---

web/src/app/api/[...path]/route.ts

Allows us to configure our Vercel preview environment for EC2 instance access
N/A
N/A

Enable Vercel Preview

---

backend/danswer/document_index/interfaces.py
backend/danswer/document_index/vespa/index.py
backend/danswer/seeding/load_docs.py
backend/danswer/setup.py

Update initial seeding for latency requirements

---

backend/danswer/background/celery/tasks/indexing/tasks.py

use redis completion signal to double check exit code

---

web/src/app/auth/verify-email/Verify.tsx

Refer to https://github.com/onyx-dot-app/onyx/pull/3305
N/A
N/A

Ensure reload post verification

---

backend/onyx/connectors/google_utils/shared_constants.py
backend/tests/daily/connectors/gmail/conftest.py

test changing back emails

---

backend/tests/daily/connectors/gmail/test_gmail_connector.py
backend/tests/daily/connectors/google_drive/conftest.py
backend/tests/daily/connectors/google_drive/consts_and_utils.py
backend/tests/integration/connector_job_tests/slack/test_permission_sync.py
backend/tests/integration/connector_job_tests/slack/test_prune.py
backend/tests/unit/onyx/connectors/gmail/thread.json

update gmail test configuration

---

backend/onyx/seeding/personas.yaml

Change Default Assistant Description

---

backend/onyx/seeding/load_docs.py

Document seeding Title/Content fields were not combined well messing with the keyword matching
Tested locally
N/A
N/A

Seed Spacing

---

web/src/app/assistants/SidebarWrapper.tsx

Align user dropdown in top right

---

web/src/app/chat/folders/FolderList.tsx
web/src/components/chat_search/Header.tsx

Previously, did not properly refresh folders using our chat provider. This meant we didn't always refresh our chat history.
N/A
N/A
Note: You have to check that the action passes, otherwise resolve the conflicts manually and tag …

Update folder logic

---

.github/workflows/docker-build-push-model-server-container-on-tag.yml
.github/workflows/pr-chromatic-tests.yml

Update model server (for testing to function)

---

web/src/app/assistants/SidebarWrapper.tsx
web/src/app/assistants/gallery/WrappedAssistantsGallery.tsx
web/src/app/assistants/gallery/page.tsx
web/src/app/assistants/mine/WrappedAssistantsMine.tsx
web/src/app/assistants/mine/page.tsx

Update chat provider values

---

backend/onyx/seeding/personas.yaml

Update default assistant to search for new users

---

backend/onyx/background/celery/celery_redis.py
backend/onyx/background/celery/tasks/beat_schedule.py
backend/onyx/background/celery/tasks/indexing/tasks.py
backend/onyx/background/celery/tasks/vespa/tasks.py
backend/onyx/configs/constants.py
backend/onyx/redis/redis_connector_index.py

clear indexing fences with no celery tasks queued

---

backend/onyx/llm/chat_llm.py
backend/onyx/llm/llm_provider_options.py
backend/requirements/default.txt
backend/requirements/model_server.txt
web/src/lib/hooks.ts

Support o1

---

backend/onyx/background/celery/apps/app_base.py
backend/onyx/background/celery/apps/beat.py
backend/onyx/background/celery/apps/heavy.py
backend/onyx/background/celery/apps/indexing.py
backend/onyx/background/celery/apps/light.py
backend/onyx/background/celery/apps/primary.py
backend/onyx/background/celery/tasks/indexing/tasks.py
backend/onyx/document_index/vespa/index.py
backend/onyx/document_index/vespa/shared_utils/utils.py

temporarily disabling validate indexing fences

---

backend/ee/onyx/utils/telemetry.py

Fixes mysterious Posthog issue
- Posthog issues are processed async- we were killing process in background workers before the Posthog task could complete. We now flush immediately and log any errors with submitting the Posthog event
- Test locally with Multi tenant- successfully indexing
- Test in cloud - successfully indexing
N/A
N/A
- Author …

Resolve posthog

---

web/src/lib/chat/fetchChatData.ts
web/src/lib/constants.ts

double check sidebar default toggle

---

README.md

Fix Logo On DarkMode

---

backend/onyx/server/query_and_chat/chat_backend.py

allow limited user to create chat session

---

backend/onyx/llm/chat_llm.py

Fixes bedrock w/ access keys.
Tested both Bedrock + Vertex AI locally.

Fix bedrock w/ access keys

---

backend/onyx/background/celery/tasks/indexing/tasks.py
backend/onyx/background/celery/tasks/vespa/tasks.py

log attempt id, log elapsed since task execution start, remove log spam

---

web/src/app/admin/bots/[bot-id]/SlackChannelConfigsTable.tsx

fixed name
removed weird icon
i looked at it

Slackbot polish

---

backend/onyx/connectors/web/connector.py

Prevent SSRF risk

---

backend/onyx/connectors/zendesk/connector.py
backend/onyx/seeding/load_docs.py
backend/onyx/utils/retry_wrapper.py

More Zendesk retries for specific errors
N/A

Zendesk Retries

---

backend/alembic/env.py
backend/onyx/configs/app_configs.py
backend/onyx/db/engine.py
deployment/docker_compose/docker-compose.dev.yml
deployment/docker_compose/docker-compose.gpu-dev.yml
deployment/docker_compose/docker-compose.prod-no-letsencrypt.yml
deployment/docker_compose/docker-compose.prod.yml

Remove:
- Duplicated AWS env vars
- Typo left in
N/A
N/A

Remove left over yaml errors

---

backend/onyx/db/connector_credential_pair.py
backend/onyx/server/documents/connector.py
deployment/docker_compose/docker-compose.prod.yml

Eagerly load CCpair connectors

---

backend/onyx/connectors/salesforce/connector.py
backend/onyx/connectors/salesforce/doc_conversion.py

out of bounds exception!!!!!!!

Fixed out of bounds

---

backend/onyx/background/celery/apps/indexing.py
backend/onyx/background/celery/configs/indexing.py
backend/onyx/background/celery/tasks/beat_schedule.py
backend/onyx/background/celery/tasks/doc_permission_syncing/tasks.py
backend/onyx/background/celery/tasks/external_group_syncing/tasks.py
backend/onyx/background/celery/tasks/indexing/tasks.py
backend/onyx/background/celery/tasks/pruning/tasks.py
backend/onyx/configs/constants.py

permission sync in cloud and beat expiry adjustment

---

backend/onyx/connectors/web/connector.py
backend/onyx/db/models.py
backend/onyx/document_index/interfaces.py
backend/onyx/document_index/vespa/app_config/schemas/danswer_chunk.sd
backend/onyx/document_index/vespa/index.py
backend/onyx/document_index/vespa/indexing_utils.py
backend/onyx/document_index/vespa/shared_utils/vespa_request_builders.py
backend/onyx/document_index/vespa_constants.py
backend/onyx/indexing/indexing_pipeline.py
backend/onyx/indexing/models.py
backend/onyx/seeding/load_docs.py
backend/scripts/query_time_check/seed_dummy_docs.py
web/src/app/chat/documentSidebar/ChatFilters.tsx

This reverts commit 27832167819f063bc2f4436765ff27f0ccba2b64.

Revert "More efficient Vespa indexing (#3552)"

---

backend/onyx/auth/schemas.py
backend/onyx/auth/users.py

Ensure users cannot modify their roles

---

backend/onyx/connectors/slack/utils.py
backend/onyx/onyxbot/slack/blocks.py
backend/onyx/onyxbot/slack/icons.py
backend/onyx/onyxbot/slack/utils.py

Fixes (1) citations not showing up as links as they should and (2) the source image links being wrong -> "link broken" imgs.
Tested Slack bot locally.

Slack fixes

---

backend/onyx/document_index/vespa/deletion.py

retry the individual delete's

---

backend/.gitignore
backend/onyx/connectors/salesforce/connector.py
backend/onyx/connectors/salesforce/doc_conversion.py
backend/onyx/connectors/salesforce/salesforce_calls.py
backend/onyx/connectors/salesforce/shelve_stuff/shelve_functions.py
backend/onyx/connectors/salesforce/shelve_stuff/shelve_utils.py
backend/onyx/connectors/salesforce/shelve_stuff/test_salesforce_shelves.py
backend/onyx/connectors/salesforce/sqlite_functions.py
backend/onyx/connectors/salesforce/utils.py
backend/tests/unit/onyx/connectors/salesforce/test_salesforce_sqlite.py

- uses bulk api to download csv
- stores information in a sqlite db on disk
- uses the sqlite db to build dictionaries for each object 
- tested with our dummy salesforce
- tested at scale with fake data
- tested using tests in this pr

Reworked salesforce connector to use bulk api

---

backend/ee/onyx/background/celery/tasks/vespa/tasks.py

re-prep user group deletion on the actual deletion

---

web/src/app/admin/connectors/[connector]/auth/callback/route.ts
web/src/app/admin/tools/ToolEditor.tsx
web/src/app/chat/documentSidebar/ChatFilters.tsx
web/src/app/chat/lib.tsx
web/src/app/chat/message/Messages.tsx
web/src/components/embedding/CustomEmbeddingModelForm.tsx
web/src/components/search/DocumentDisplay.tsx
web/src/lib/search/streamingUtils.ts
web/src/lib/userSS.ts

Remove Exclamation marks + comments

---

backend/scripts/orphan_doc_cleanup_script.py

Speedup orphan doc cleanup script

---

backend/onyx/background/celery/tasks/indexing/tasks.py
backend/onyx/background/celery/tasks/vespa/tasks.py
backend/onyx/configs/constants.py
backend/onyx/redis/redis_document_set.py
backend/onyx/redis/redis_pool.py

various lock diagnostics and timing adjustments

---

backend/onyx/background/celery/apps/primary.py
backend/onyx/background/celery/tasks/vespa/tasks.py
backend/onyx/redis/redis_pool.py

add detailed timings to monitor vespa sync

---

backend/tests/daily/connectors/zendesk/test_zendesk_connector.py

Minor opensource cleanup

---

backend/onyx/document_index/vespa/index.py

Tracking update

---

backend/ee/onyx/external_permissions/confluence/group_sync.py
backend/onyx/connectors/confluence/onyx_confluence.py
backend/onyx/connectors/confluence/utils.py

Improved logging for confluence calls

---

web/src/app/ee/admin/whitelabeling/WhitelabelingForm.tsx

Whitelabelling

---

.vscode/env_template.txt
backend/onyx/configs/app_configs.py
backend/onyx/natural_language_processing/search_nlp_models.py

- This cuts the time to hot reload the api server in half

Added env var to skip warm up

---

backend/onyx/connectors/salesforce/shelve_stuff/old_test_salesforce_shelves.py
backend/tests/daily/connectors/google_drive/conftest.py
backend/tests/daily/connectors/google_drive/consts_and_utils.py

Fixing google drive tests

---

backend/onyx/document_index/vespa/index.py

Remove unnecessary logs

---

backend/ee/onyx/external_permissions/confluence/doc_sync.py
backend/onyx/connectors/confluence/connector.py
backend/onyx/connectors/confluence/onyx_confluence.py

Conf doc sync improvements

---

.github/workflows/docker-build-push-model-server-container-on-tag.yml

hope this env var works.

---

backend/onyx/background/celery/celery_utils.py
backend/onyx/server/documents/cc_pair.py
web/src/app/admin/connector/[ccPairId]/DeletionButton.tsx
web/src/app/admin/connector/[ccPairId]/page.tsx

Make connector pause and delete fast

---

backend/onyx/connectors/google_utils/google_kv.py
backend/onyx/server/documents/connector.py
backend/onyx/server/documents/credential.py

possible fix for gdrive oauth in the cloud

---

backend/ee/onyx/db/analytics.py
backend/ee/onyx/db/token_limit.py
backend/onyx/db/connector_credential_pair.py
backend/onyx/db/document_set.py
backend/onyx/db/feedback.py
backend/onyx/db/persona.py

Proper anonymous user restricting

---

web/src/lib/llm/utils.ts

Support new model for image input

---

backend/ee/onyx/db/user_group.py
backend/onyx/db/document_set.py

follow on fix for https://github.com/onyx-dot-app/onyx/pull/3658

fix missed var names

---

backend/alembic/versions/0f7ff6d75b57_add_index_to_index_attempt_time_created.py
backend/onyx/background/celery/tasks/indexing/tasks.py
backend/onyx/db/index_attempt.py
backend/onyx/db/models.py

optimize another index attempt check

---

backend/ee/onyx/db/token_limit.py
backend/ee/onyx/db/user_group.py
backend/ee/onyx/external_permissions/salesforce/utils.py
backend/ee/onyx/server/token_rate_limits/api.py
backend/onyx/background/celery/tasks/connector_deletion/tasks.py
backend/onyx/background/celery/tasks/doc_permission_syncing/tasks.py
backend/onyx/background/celery/tasks/external_group_syncing/tasks.py
backend/onyx/background/celery/tasks/indexing/tasks.py
backend/onyx/background/celery/tasks/pruning/tasks.py
backend/onyx/background/celery/tasks/vespa/tasks.py
backend/onyx/background/indexing/run_indexing.py
backend/onyx/db/connector_credential_pair.py
backend/onyx/db/credentials.py
backend/onyx/db/document.py
backend/onyx/db/document_set.py
backend/onyx/db/feedback.py
backend/onyx/db/persona.py
backend/onyx/onyxbot/slack/handlers/handle_buttons.py
backend/onyx/redis/redis_connector_credential_pair.py
backend/onyx/redis/redis_connector_delete.py
backend/onyx/redis/redis_connector_prune.py
backend/onyx/server/documents/cc_pair.py
backend/onyx/server/documents/connector.py
backend/onyx/server/documents/credential.py
backend/onyx/server/features/persona/api.py
backend/onyx/server/manage/administrative.py
backend/onyx/server/onyx_api/ingestion.py
backend/onyx/server/openai_assistants_api/asssistants_api.py
backend/onyx/server/query_and_chat/chat_backend.py
backend/scripts/force_delete_connector_by_id.py

refactored _add_user_filter usage

---

backend/onyx/background/celery/configs/monitoring.py
backend/onyx/background/celery/tasks/monitoring/tasks.py
backend/onyx/configs/constants.py
deployment/cloud_kubernetes/hpa/workers_hpa.yaml
deployment/cloud_kubernetes/workers/monitoring.yaml

Add monitoring worker

---

backend/tests/daily/connectors/discord/test_discord_connector.py
backend/tests/daily/connectors/discord/test_discord_data.json

- Create daily test for discord
- Create a discord server to test
- Create a JSON file to store test data and compare with connector return.

Add discord daily test

---

backend/tests/daily/connectors/salesforce/test_salesforce_connector.py
backend/tests/daily/connectors/salesforce/test_salesforce_data.json

- Add a basic daily test for salesforce connector to ensure proper data retrieval.

Salesforce daily test

---

backend/tests/daily/connectors/discord/test_discord_connector.py
backend/tests/daily/connectors/fireflies/test_fireflies_connector.py

- fixing env var from discord test

temp test fixes

---

backend/onyx/auth/users.py
backend/onyx/db/connector_credential_pair.py
backend/onyx/db/engine.py
backend/onyx/seeding/load_docs.py

Admin usage for seeding

---

backend/onyx/background/celery/tasks/indexing/tasks.py
backend/onyx/background/indexing/job_client.py
backend/onyx/background/indexing/run_indexing.py
backend/onyx/db/index_attempt.py

better logging and reduce long sessions

---

web/src/app/chat/ChatPage.tsx
web/src/app/chat/RegenerateOption.tsx
web/src/app/chat/interfaces.ts
web/src/app/chat/modal/configuration/LlmTab.tsx
web/src/lib/hooks.ts

Update llm override hook

---

.vscode/env_template.txt
CONTRIBUTING_VSCODE.md
backend/onyx/server/manage/slack_bot.py
backend/onyx/server/manage/validate_tokens.py
backend/requirements/default.txt
web/src/app/admin/bots/SlackTokensForm.tsx

- Updated docs and dependencies to get the system up and running in Ubuntu 22.04.5 LTS
- Added Slack token validation functions to bot creation/ update workflow in the backend.
-  Updated the frontend to make the invalid token error looks nicer.
Smoke tested with real tokens

Validating slackbot tokens

---

web/jest.config.js
web/package-lock.json
web/package.json
web/src/app/chat/message/Messages.tsx
web/src/app/chat/message/__tests__/codeUtils.test.ts
web/src/app/chat/message/codeUtils.ts
web/src/components/CopyButton.tsx

Made copy button and cmd+c work for cmd+v and cmd+shift+v

---

backend/onyx/utils/long_term_log.py

Quick nit for no-longer living files

---

web/src/components/chat_search/TextView.tsx

Markdown rendering

---

backend/onyx/background/celery/tasks/monitoring/tasks.py

1. We were sometimes sending over multiple values, causing the metric to be ignored by the telemetry server.
2. We could miss some connector status metrics if another index attempt has been created before the metric was emitted.
Ran locally, verified that the telemetry server could pick up the metrics.

Small background telemetry fix

---

web/src/lib/hooks.ts

Fixes https://linear.app/danswer/issue/DAN-1303/gmail-connector-broken

Fix gmail connector

---

web/src/app/ee/admin/performance/usage/PersonaMessagesChart.tsx

Change Persona to Assistant for Analytics Page

---

backend/ee/onyx/db/query_history.py
backend/onyx/db/index_attempt.py
backend/onyx/server/documents/cc_pair.py
backend/tests/integration/common_utils/managers/index_attempt.py
backend/tests/integration/common_utils/test_models.py
backend/tests/integration/tests/index_attempt/test_index_attempt_pagination.py
backend/tests/integration/tests/llm_provider/test_llm_provider.py
web/src/app/ee/admin/performance/query-history/QueryHistoryTable.tsx

-  added test for index attempts table

Fix pagination for index attempts table DAN-1284

---

backend/onyx/background/celery/tasks/beat_schedule.py
backend/onyx/background/celery/tasks/monitoring/tasks.py
backend/onyx/configs/constants.py

Fixes DAN-1304.  https://linear.app/danswer/issue/DAN-1304/check-for-migration-issues-in-the-cloud

cloud check for migrations

---

web/src/app/admin/settings/AnonymousUserPath.tsx
web/src/app/admin/settings/interfaces.ts
web/src/app/auth/signup/page.tsx
web/src/app/chat/nrf/NRFPage.tsx
web/src/components/settings/lib.ts
web/src/lib/chat/fetchChatData.ts
web/src/lib/constants.ts
web/src/lib/userSS.ts

Moves web domain to context (no need for setting in docker build) + default sidebar to closed for anonymous users
Fixes https://linear.app/danswer/issue/DAN-1311/not-properly-passing-through-web-domain-in-anonymous-user-page-sidebar
Multi tenant + single tenant anonymous usage locally

Anonymous Polish

---

backend/onyx/background/celery/tasks/indexing/tasks.py

Fixes DAN-1324. https://linear.app/danswer/issue/DAN-1324/remove-tenant-specific-debugging-in-check-for-indexing

remove debugging for specific problem tenants

---

backend/onyx/agents/agent_search/basic/nodes/basic_use_tool_response.py
backend/onyx/agents/agent_search/basic/nodes/tool_call.py
backend/onyx/agents/agent_search/basic/utils.py
backend/onyx/agents/agent_search/run_graph.py
backend/onyx/chat/stream_processing/answer_response_handler.py
backend/onyx/tools/tool_implementations/search/search_tool.py
backend/onyx/tools/tool_implementations/search_like_tool_utils.py
backend/tests/unit/onyx/chat/conftest.py
backend/tests/unit/onyx/chat/test_answer.py

https://linear.app/danswer/issue/DAN-1328/stream-cancellation-basic-citations
ran the product and the two tests that now work, things look good

async task cleanup + basic citations

---

backend/ee/onyx/background/celery/tasks/beat_schedule.py

Fixes DAN-1329. https://linear.app/danswer/issue/DAN-1329/fix-ee-tasks

missed ee_tasks_to_schedule declaration

---

backend/scripts/onyx_redis.py
backend/scripts/onyx_vespa.py

Fixes https://linear.app/danswer/issue/DAN-1330/improved-redis-debugging
Fixes https://linear.app/danswer/issue/DAN-1325/improved-vespa-debugging
Most useful options:
- Delete (ie. logout) / get user token from Redis
- Fetch ACLs from Vespa (huge time saver already!)
- All options, multi tenant + non multi tenant

Vespa scripts + Redis script update

---

web/src/app/chat/ChatPage.tsx
web/src/app/chat/input/ChatInputBar.tsx
web/src/app/chat/interfaces.ts
web/src/app/chat/lib.tsx
web/src/app/chat/message/AgenticMessage.tsx
web/src/app/chat/message/SourcesDisplay.tsx
web/src/app/chat/message/StreamingMessages.ts
web/src/app/chat/message/SubQuestionsDisplay.tsx
web/src/app/chat/refinmentBadge.tsx
web/src/components/WebResultIcon.tsx
web/src/components/chat_search/sources/SourceCard.tsx
web/src/lib/search/interfaces.ts

Fixes https://linear.app/danswer/issue/DAN-1325/improved-vespa-debugging
Fixes https://linear.app/danswer/issue/DAN-1330/improved-redis-debugging

Improved ux

---

backend/alembic/versions/211b14ab5a91_refined_answer_improvement.py
backend/onyx/chat/process_message.py
backend/onyx/db/chat.py
backend/onyx/db/models.py

see title
ran the UI, looked fine. 

Persist refined improvement

---

backend/onyx/agents/agent_search/deep_search_a/main/nodes/generate_initial_answer.py
backend/onyx/agents/agent_search/deep_search_a/main/nodes/generate_refined_answer.py
backend/onyx/agents/agent_search/shared_graph_utils/utils.py
backend/onyx/chat/models.py

send back a StreamStopInfo packet when done yielding the initial and refined answers
UI works fine

stop info answers

---

backend/onyx/agents/agent_search/deep_search_a/expanded_retrieval/nodes/doc_reranking.py

skip reranking for <=1 doc

---

backend/onyx/agents/agent_search/deep_search_a/answer_initial_sub_question/nodes/answer_check.py
backend/onyx/agents/agent_search/deep_search_a/expanded_retrieval/nodes/doc_reranking.py
backend/onyx/agents/agent_search/deep_search_a/expanded_retrieval/nodes/doc_retrieval.py
backend/onyx/agents/agent_search/deep_search_a/main/graph_builder.py
backend/onyx/agents/agent_search/deep_search_a/main/nodes/agent_path_decision.py
backend/onyx/agents/agent_search/deep_search_a/main/nodes/agent_search_start.py
backend/onyx/agents/agent_search/deep_search_a/main/nodes/entity_term_extraction_llm.py
backend/onyx/agents/agent_search/deep_search_a/main/nodes/initial_sub_question_creation.py
backend/onyx/agents/agent_search/deep_search_a/main/nodes/refined_sub_question_creation.py
backend/onyx/agents/agent_search/deep_search_a/main/states.py
backend/onyx/agents/agent_search/models.py
backend/onyx/agents/agent_search/run_graph.py
backend/onyx/agents/agent_search/shared_graph_utils/prompts.py
backend/onyx/agents/agent_search/shared_graph_utils/utils.py
backend/onyx/configs/agent_configs.py

- taking out extraction for now
- sharper prompts
- forcing agent search for tests

Various fixes

---

backend/onyx/db/chat.py
backend/onyx/server/query_and_chat/models.py
web/src/app/chat/ChatPage.tsx
web/src/app/chat/interfaces.ts
web/src/app/chat/lib.tsx
web/src/app/chat/message/AgenticMessage.tsx
web/src/app/chat/message/SubQuestionsDisplay.tsx
web/src/app/chat/refinmentBadge.tsx
web/src/app/chat/sessionSidebar/HistorySidebar.tsx
web/src/components/search/results/Citation.tsx

Agent search streaming + ux improvements

---

backend/Dockerfile

Not tested, should work though

Turn off Unstructured telemetry

---

.github/workflows/pr-linear-check.yml
web/src/app/admin/assistants/AssistantEditor.tsx
web/src/app/admin/embeddings/interfaces.ts
web/src/app/assistants/mine/AssistantModal.tsx
web/src/app/chat/input/ChatInputBar.tsx
web/src/app/chat/message/MemoizedTextComponents.tsx
web/src/app/chat/message/Messages.tsx
web/src/app/chat/sessionSidebar/HistorySidebar.tsx
web/src/app/chat/sessionSidebar/PagesTab.tsx
web/src/app/globals.css
web/src/components/Modal.tsx
web/src/components/admin/connectors/Field.tsx
web/src/components/assistants/AssistantIcon.tsx
web/src/components/ui/dialog.tsx

Fixes https://linear.app/danswer/issue/DAN-1310/linking-scrolling-ux-touch-ups
Fixes https://linear.app/danswer/issue/DAN-1299/checkbox-fixes 
- Ensure basic links always link out
- Ensure textareas can be dragged on edge
- Minor extra padding on bottom of assistant modal
- Standardize checkboxes

Improved linking + scrolling

---

backend/onyx/seeding/initial_docs.json
backend/onyx/seeding/initial_docs_cohere.json
backend/scripts/document_seeding_prep.py

Fix Seeding Link for Support Use Case

---

backend/onyx/background/celery/apps/beat.py
backend/onyx/background/celery/tasks/beat_schedule.py
backend/onyx/background/celery/tasks/indexing/tasks.py
backend/onyx/background/celery/tasks/indexing/utils.py
backend/onyx/background/celery/tasks/shared/tasks.py
backend/onyx/background/celery/tasks/vespa/tasks.py
backend/onyx/configs/app_configs.py
backend/onyx/redis/redis_pool.py

Fixes DAN-1321. https://linear.app/danswer/issue/DAN-1321/allow-usage-of-redis-replica

try using a redis replica in some areas

---

backend/ee/onyx/external_permissions/google_drive/doc_sync.py
backend/onyx/connectors/google_drive/doc_conversion.py
backend/scripts/onyx_vespa.py

Fixes https://linear.app/danswer/issue/DAN-1339/better-vespa-debugging

Better vespa interface

---

web/src/app/admin/embeddings/pages/EmbeddingFormPage.tsx

https://github.com/user-attachments/assets/51c573da-3a0c-493e-8f9d-b542c305a382

Hotfix reranking form

---

web/Dockerfile
web/next.config.js

Fixes https://linear.app/danswer/issue/DAN-1341/web-build-size
- No unnecessary inclusion of sourcemap
- Properly pass node options

Improvements for web build

---

web/src/components/ui/select.tsx

Does not play well with ShadCN component that we use

Remove checkmark

---

backend/onyx/file_processing/extract_file_text.py
backend/onyx/file_processing/unstructured.py
backend/onyx/server/query_and_chat/chat_backend.py

Unstructured fix

---

backend/onyx/db/llm.py
backend/onyx/server/manage/llm/api.py

Fixes https://linear.app/danswer/issue/DAN-1343/cycle-42-goals
Refer to: https://github.com/onyx-dot-app/onyx/pull/3674/files
On main and this branch, create private LLMs and access chat as anonymous user

Double check all chat accessible dependencies

---

web/src/app/chat/ChatPage.tsx

remove debug

---

backend/onyx/db/document.py
backend/onyx/document_index/vespa/index.py
backend/onyx/indexing/indexing_pipeline.py
backend/onyx/indexing/models.py
backend/onyx/seeding/load_docs.py

Log indexing

---

backend/onyx/agents/agent_search/deep_search_a/initial_search_sq_subgraph/nodes/generate_initial_answer.py

Send search responses to the front end for the initial answer, even when empty.
tested in UI

Always send docs

---

web/src/app/chat/tools/constants.ts

Fix search tool name

---

backend/onyx/chat/answer.py
backend/onyx/chat/models.py
backend/onyx/chat/process_message.py
backend/tests/unit/onyx/chat/test_answer.py
backend/tests/unit/onyx/chat/test_skip_gen_ai.py

Refactored Answer to construct AgentSearchConfig internally instead of being passed in.
tested in UI, unit tests

Agent Search config in Answer

---

backend/onyx/connectors/fireflies/connector.py

Fixes https://linear.app/danswer/issue/DAN-1368/fix-fireflies-no-sentences-case

Fireflies update

---

backend/ee/onyx/external_permissions/confluence/group_sync.py

Add more group sync logging

---

backend/requirements/default.txt

Pin shapely

---

backend/alembic/versions/33ea50e88f24_foreign_key_input_prompts.py
web/src/app/chat/sessionSidebar/HistorySidebar.tsx

Foreign key input prompts

---

backend/alembic/versions/33ea50e88f24_foreign_key_input_prompts.py

Update foreign key migration

---

backend/onyx/server/query_and_chat/chat_backend.py

Ensure anonymous users can give feedback

---

backend/alembic/versions/98a5008d8711_agent_tracking.py
backend/onyx/agents/agent_search/deep_search/shared/expanded_retrieval/nodes/retrieve_documents.py
backend/onyx/chat/process_message.py
backend/onyx/context/search/pipeline.py
backend/onyx/tools/tool_implementations/search/search_tool.py

- fix alembic heads
- fix basic search doc persistence
- remove unnecessary state from SearchTool
unit tests, UI

Misc Fixes for Agent Search

---

backend/onyx/connectors/airtable/airtable_connector.py

On failure, actually perform retries.
Unit tests + cloud tests

Improved attachment handling

---

backend/onyx/agents/agent_search/deep_search/initial/generate_individual_sub_answer/nodes/check_sub_answer.py
backend/onyx/agents/agent_search/deep_search/initial/generate_initial_answer/nodes/generate_initial_answer.py
backend/onyx/agents/agent_search/deep_search/initial/generate_sub_answers/nodes/decompose_orig_question.py
backend/onyx/agents/agent_search/deep_search/initial/retrieve_orig_question_docs/nodes/format_orig_question_search_output.py
backend/onyx/agents/agent_search/deep_search/initial/retrieve_orig_question_docs/states.py
backend/onyx/agents/agent_search/deep_search/main/nodes/compare_answers.py
backend/onyx/agents/agent_search/deep_search/main/nodes/create_refined_sub_questions.py
backend/onyx/agents/agent_search/deep_search/main/nodes/extract_entities_terms.py
backend/onyx/agents/agent_search/deep_search/main/nodes/generate_refined_answer.py
backend/onyx/agents/agent_search/deep_search/main/states.py
backend/onyx/agents/agent_search/deep_search/shared/expanded_retrieval/models.py
backend/onyx/agents/agent_search/deep_search/shared/expanded_retrieval/nodes/expand_queries.py
backend/onyx/agents/agent_search/deep_search/shared/expanded_retrieval/nodes/format_results.py
backend/onyx/agents/agent_search/deep_search/shared/expanded_retrieval/nodes/verify_documents.py
backend/onyx/agents/agent_search/deep_search/shared/expanded_retrieval/states.py
backend/onyx/agents/agent_search/shared_graph_utils/agent_prompt_ops.py
backend/onyx/agents/agent_search/shared_graph_utils/prompts.py
backend/onyx/agents/agent_search/shared_graph_utils/utils.py

- more renamings
- fix of prompt construction for refined answer
locally - backend and frontend

renames + fix of refined answer generation prompt

---

backend/onyx/agents/agent_search/shared_graph_utils/utils.py

add title and meta-data to doc 
Locally. I also manually added a fake dict with str and list values.

add title and meta-data to doc

---

backend/tests/integration/tests/dev_apis/test_simple_chat_api.py

https://linear.app/danswer/issue/DAN-1408/temporary-xfail-of-broken-test

xfail test until fixed

---

backend/ee/onyx/server/middleware/tenant_tracking.py
backend/ee/onyx/server/tenants/api.py
backend/onyx/auth/email_utils.py
backend/onyx/auth/users.py
backend/onyx/configs/constants.py
backend/onyx/redis/redis_pool.py
backend/onyx/server/manage/users.py
backend/scripts/sources_selection_analysis.py
backend/tests/integration/common_utils/managers/user.py
web/src/app/auth/forgot-password/utils.ts
web/src/app/auth/reset-password/page.tsx
web/src/lib/constants.ts

FastAPI users doesn't exactly play nice with our version of mult-tenancy, which means we need to occasionally employ some workarounds like here.

Password reset tenant

---

web/src/app/chat/documentSidebar/ChatDocumentDisplay.tsx

(nit) remove unused border

---

backend/onyx/onyxbot/slack/listener.py

Too many Slackbots for internal dev purposes, I can never know what my credentials belong to. Logging the Slackbot to tag when it gets registered as listener.
Locally

Slackbot to know its name

---

backend/ee/onyx/db/persona.py
backend/ee/onyx/server/middleware/tenant_tracking.py
backend/onyx/agents/agent_search/deep_search/initial/generate_sub_answers/nodes/decompose_orig_question.py
backend/onyx/agents/agent_search/deep_search/main/nodes/create_refined_sub_questions.py
backend/onyx/agents/agent_search/deep_search/main/operations.py
backend/onyx/agents/agent_search/shared_graph_utils/utils.py
backend/onyx/db/persona.py
backend/onyx/server/query_and_chat/chat_backend.py
backend/tests/integration/Dockerfile
web/src/app/admin/configuration/llm/interfaces.ts
web/src/app/admin/settings/SettingsForm.tsx
web/src/app/admin/settings/interfaces.ts
web/src/app/chat/ChatPage.tsx
web/src/app/chat/input/ChatInputBar.tsx
web/src/app/chat/input/LLMPopover.tsx
web/src/app/chat/interfaces.ts
web/src/app/chat/message/Messages.tsx
web/src/app/chat/message/SourcesDisplay.tsx
web/src/app/chat/message/StreamingMessages.ts
web/src/app/chat/message/SubQuestionsDisplay.tsx
web/src/components/SearchResultIcon.tsx
web/src/components/UserDropdown.tsx
web/src/components/chat/Notifications.tsx
web/src/components/chat/sources/SourceCard.tsx
web/src/components/search/filtering/FilterPopup.tsx
web/src/components/settings/lib.ts
web/src/components/table/DragHandle.tsx
web/src/components/table/DraggableRow.tsx
web/src/components/table/DraggableTable.tsx

Fixes https://docs.google.com/document/d/1r89Z_YqOegTtp9lpKWZYFPjCyTYl4188AlqZGsXnB2w/edit?tab=t.0

Various improvements

---

web/src/app/assistants/mine/AssistantModal.tsx

https://linear.app/danswer/issue/DAN-1439/fix-interactivity-freezing

Fix odd interaction

---

backend/model_server/constants.py
backend/model_server/encoders.py
backend/model_server/main.py
backend/model_server/management_endpoints.py
backend/model_server/utils.py

Fixes DAN-1428.
https://linear.app/danswer/issue/DAN-1428/improve-model-server-gpu-logging

improve gpu detection functions and logging in model server

---

web/src/components/assistants/StarterMessage.tsx

Improve starter message splitting

---

backend/onyx/document_index/vespa/indexing_utils.py

https://linear.app/danswer/issue/DAN-1441/indexing-failure-due-to-illegal-code-point-in-metadata
👀 

Clean illegal chars in metadata

---

.github/workflows/docker-build-push-model-server-container-on-tag.yml

Should only build if there are changes to the model server code or Dockerfile.
N/A pray this works

Don't build model server every night

---

backend/onyx/connectors/onyx_jira/connector.py

Jira add key to semantic id

---

backend/alembic/versions/f39c5794c10a_add_background_errors_table.py
backend/ee/onyx/external_permissions/confluence/group_sync.py
backend/onyx/background/celery/tasks/external_group_syncing/tasks.py
backend/onyx/background/error_logging.py
backend/onyx/db/background_error.py
backend/onyx/db/models.py

For easier hunting down of errors.
Tested group sync locally.

Add background errors ability

---

backend/tests/daily/connectors/jira/test_jira_basic.py

Fixes DAN-1446.
https://linear.app/danswer/issue/DAN-1446/fix-jira-connector-test

fix title check

---

backend/onyx/auth/email_utils.py
backend/onyx/main.py

Improved email formatting

---

backend/tests/daily/llm/test_bedrock.py

Fixes DAN-1447.
https://linear.app/danswer/issue/DAN-1447/xfail-bedrock-test

xfail this test

---

backend/ee/onyx/configs/app_configs.py
backend/ee/onyx/server/tenants/api.py
backend/ee/onyx/server/tenants/product_gating.py
backend/onyx/background/celery/tasks/beat_schedule.py
backend/onyx/background/celery/tasks/shared/tasks.py

Pause cloud tasks for gated tenants

---

backend/ee/onyx/server/tenants/product_gating.py

Minor read replica fix

---

backend/scripts/debugging/onyx_vespa.py

Fix vespa script

---

web/src/app/chat/message/MemoizedTextComponents.tsx

Remove extra `l`

---

backend/onyx/agents/agent_search/basic/graph_builder.py
backend/onyx/agents/agent_search/basic/states.py
backend/onyx/agents/agent_search/run_graph.py
backend/requirements/default.txt

bump version and fix related issues

---

backend/onyx/connectors/airtable/airtable_connector.py

Fix typing for metadata

---

backend/onyx/db/chat.py
backend/onyx/server/settings/store.py

Minor cleanup

---

backend/onyx/db/chat.py

consistent refined answer improvement

---

backend/Dockerfile
backend/onyx/connectors/dropbox/connector.py
backend/onyx/connectors/github/connector.py
backend/onyx/connectors/interfaces.py
backend/onyx/connectors/notion/connector.py
backend/onyx/connectors/onyx_jira/connector.py
web/src/app/admin/connector/[ccPairId]/ReIndexButton.tsx
web/src/components/HoverPopup.tsx

Basic validation for:
- Github
- Notion
- Jira

Additional connector validation classes

---

web/src/components/credentials/actions/CreateCredential.tsx
web/src/components/credentials/lib.ts

improve validation schema

---

backend/alembic/versions/9c00a2bccb83_chat_message_agentic.py
backend/onyx/chat/process_message.py
backend/onyx/db/chat.py
backend/onyx/db/models.py
backend/onyx/server/query_and_chat/models.py

new is_agentic flag for chatmessages

---

backend/ee/onyx/external_permissions/confluence/group_sync.py
backend/onyx/background/celery/tasks/external_group_syncing/tasks.py
backend/onyx/connectors/confluence/onyx_confluence.py

^
Tested locally with both data center and cloud.

Small confluence group sync tweaks

---

web/src/app/chat/message/AgenticMessage.tsx
web/src/app/chat/message/MemoizedTextComponents.tsx
web/src/app/chat/message/Messages.tsx
web/src/app/chat/message/SubQuestionsDisplay.tsx
web/src/components/search/results/Citation.tsx

fix https://linear.app/danswer/issue/DAN-1461/markdown-links-broken

Quick link fix

---

backend/onyx/llm/chat_llm.py

Don't pass thorugh parallel_tool_calls for o-family models

---

backend/onyx/auth/users.py
backend/onyx/main.py

Update error class

---

web/src/app/admin/settings/SettingsForm.tsx
web/src/app/chat/ChatPage.tsx

Fix streaming

---

backend/onyx/background/celery/apps/app_base.py

Fixes DAN-1466.
https://linear.app/danswer/issue/DAN-1466/on-task-postrun-is-broken

fix usage of tenant_id

---

backend/onyx/auth/email_utils.py
backend/onyx/server/manage/users.py

https://linear.app/danswer/issue/DAN-1467/add-support-for-sending-email-invites-for-self-hosted-deployments
Tested locally in single tenant mode. Need to verify that cloud/multi-tenant works—current plan is to deploy and test invitation.

Add support for sending email invites for single tenant users

---

web/src/app/chat/ChatPage.tsx
web/src/app/chat/RegenerateOption.tsx
web/src/app/chat/input/ChatInputBar.tsx
web/src/app/chat/input/LLMPopover.tsx
web/src/app/chat/lib.tsx
web/src/app/chat/message/AgenticMessage.tsx
web/src/app/chat/message/Messages.tsx
web/src/app/chat/modal/ShareChatSessionModal.tsx
web/src/app/chat/modal/UserSettingsModal.tsx
web/src/lib/hooks.ts
web/src/lib/llm/utils.ts
web/src/lib/users/UserSettings.tsx

https://linear.app/danswer/issue/DAN-1475/fix-llm-selection
Tested the bugged behavior locally + switching between chats and verified that (1) web session overrides, (2) chat session overrides, (3) assistant level overrides, and (4) user level overrides all work as expected.

Fix LLM selection

---

deployment/data/nginx/run-nginx.sh

Fix nginx for prod compose file

---

backend/onyx/background/celery/tasks/connector_deletion/tasks.py
backend/onyx/redis/redis_connector_stop.py

Fixes DAN-1480.
https://linear.app/danswer/issue/DAN-1480/more-aggressive-handling-of-tasks-blocking-deletion

more aggressive handling of tasks blocking deletion

---

web/src/lib/hooks.ts

Prettier formatting for bedrock

---

backend/onyx/onyxbot/slack/listener.py

Handle bad slack configurations– multi tenant

---

backend/alembic/versions/8f43500ee275_add_index.py

Index safety for B trees

---

backend/tests/daily/connectors/confluence/test_confluence_basic.py

Fix confluence test

---

backend/alembic/versions/8f43500ee275_add_index.py

temp remove

---

backend/onyx/auth/email_utils.py

Improve deliverability
Fix https://github.com/onyx-dot-app/onyx/issues/4066
- Send email with code on main
- Send email with code on this branch
- Observe Gmail "Show full info" settings, more robut

Add Date and Message-ID headers to improve email deliverability

---

web/src/app/chat/ChatPage.tsx

Improve lengthy chats

---

web/next.config.js

Fix openapi

---

backend/ee/onyx/server/query_history/api.py
backend/onyx/configs/app_configs.py
backend/onyx/configs/constants.py
backend/onyx/server/settings/models.py
backend/onyx/server/settings/store.py
web/src/app/admin/settings/interfaces.ts
web/src/components/admin/ClientLayout.tsx
web/src/components/settings/lib.ts

Fixes DAN-1487.
https://linear.app/danswer/issue/DAN-1487/add-query-history-privacy-env-vars

first cut at anonymizing query history

---

backend/onyx/auth/users.py

Address Auth Edge Case

---

backend/ee/onyx/server/tenants/provisioning.py
backend/onyx/server/documents/cc_pair.py

- Ensure we seed with display models
- Always delete connectors if attempting to associate and we fail (this flow only occurs during connector creation (i.e. we won't delete connectors unnecessarily)

Minor improvements to provisioning

---

web/src/app/chat/ChatPage.tsx
web/src/app/chat/interfaces.ts
web/src/app/chat/message/AgenticMessage.tsx
web/src/app/chat/message/Resubmit.tsx
web/src/components/ui/alert.tsx
web/src/components/ui/button.tsx

Better looking errors

---

backend/ee/onyx/server/tenants/billing.py
backend/onyx/auth/users.py

Multi tenant user google auth fix

---

backend/ee/onyx/server/query_history/api.py
backend/onyx/db/chat.py
backend/onyx/server/features/folder/api.py
backend/onyx/server/openai_assistants_api/threads_api.py
backend/onyx/server/query_and_chat/chat_backend.py
backend/onyx/server/query_and_chat/models.py
backend/onyx/server/query_and_chat/query_backend.py
web/src/app/chat/folders/FolderList.tsx
web/src/app/chat/interfaces.ts
web/src/app/chat/lib.tsx
web/src/app/chat/shared/[chatId]/SharedChatDisplay.tsx
web/src/lib/chat/fetchChatData.ts

Order chat sessions by time updated, not created

---

backend/Dockerfile

fix apt versioning issues

---

backend/alembic/versions/f11b408e39d3_force_lowercase_all_users.py
backend/alembic_tenants/versions/34e3630c7f32_lowercase_multi_tenant_user_auth.py
backend/onyx/db/models.py
web/src/app/auth/login/EmailPasswordForm.tsx

Lowercase multi tenant email mapping

---

web/src/app/admin/users/page.tsx

Show warning when inviting first user in non multi-tenant mode

---

backend/onyx/server/manage/slack_bot.py
web/src/app/admin/bots/[bot-id]/channels/SlackChannelConfigFormFields.tsx
web/src/app/auth/error/layout.tsx
web/src/app/auth/error/page.tsx

Log server side auth error + slackbot pagination fix

---

web/src/components/context/AppProvider.tsx
web/src/lib/assistants/utils.ts

Filter assistants fix

---

web/src/components/admin/connectors/AccessTypeForm.tsx

Minor persistence fix

---

web/src/app/assistants/mine/AssistantModal.tsx
web/src/app/ee/admin/billing/BillingAlerts.tsx
web/src/app/ee/admin/billing/InfoItem.tsx
web/src/components/admin/ClientLayout.tsx
web/src/components/ui/alert.tsx

Update warning copy

---

web/package-lock.json
web/package.json

Thank you to @emerzon !
NextJS bump 
- Fixes critical bug with "Response.clone: Body has already been consumed" error
- Issue was affecting server-side rendering and prefetching in Next.js
See: https://github.com/vercel/next.js/discussions/69635

Bump NextJS version

---

backend/onyx/connectors/web/connector.py

Current handling of #! sites yields duplicates. Since some sites have duplicate content and some do not following #!, added a caching to check for this.
Tested with local Onyx env

Handling of #! sites

---

web/src/app/admin/connectors/[connector]/pages/ConnectorInput/NumberInput.tsx

Small tweak to NumberInput

---

backend/onyx/connectors/web/connector.py
backend/tests/integration/tests/pruning/test_pruning.py

Fixes DAN-1508.
https://linear.app/danswer/issue/DAN-1508/fix-web-pruning-tests

fix web connector tests to handle new deduping

---

backend/ee/onyx/server/tenants/provisioning.py
backend/onyx/auth/users.py

Nit: logging adjustments

---

web/src/app/chat/shared/[chatId]/SharedChatDisplay.tsx
web/src/components/admin/users/SignedUpUserTable.tsx
web/src/components/health/refreshUtils.ts
web/src/components/llm/LLMSelector.tsx

Add minor fixes

---

deployment/docker_compose/docker-compose.dev.yml
deployment/docker_compose/docker-compose.gpu-dev.yml

Add ONYX_QUERY_HISTORY_TYPE to the dev compose files

---

backend/onyx/configs/app_configs.py
backend/onyx/configs/llm_configs.py
backend/onyx/connectors/vision_enabled_connector.py
backend/onyx/context/search/postprocessing/postprocessing.py
backend/onyx/server/settings/models.py
backend/onyx/server/settings/store.py
web/src/app/admin/settings/SettingsForm.tsx
web/src/app/admin/settings/interfaces.ts

Fixes https://linear.app/danswer/issue/DAN-1524/add-workspace-configs-for-image-indexing-analsysis 

Workspace configs

---

backend/alembic/versions/3bd4c84fe72f_improved_index.py

Fixes https://linear.app/danswer/issue/DAN-1528/fix-tsvector-population

Batch processing

---

.github/workflows/docker-build-push-model-server-container-on-tag.yml

Fix model server build

---

backend/ee/onyx/server/tenants/provisioning.py
backend/onyx/auth/users.py
web/src/app/auth/login/EmailPasswordForm.tsx

Fixes https://linear.app/danswer/issue/DAN-1511/address-gap-between-tenant-created-and-user-created-metric

Fix extra tenant mystery

---

backend/ee/onyx/server/tenants/product_gating.py

Fix gated tenants

---

backend/onyx/connectors/confluence/connector.py
backend/onyx/indexing/indexing_pipeline.py

Fixes https://linear.app/danswer/issue/DAN-1534/confluence-links-broken
Tested locally with "Chris' space"

Confluence fixes

---

backend/alembic/versions/3934b1bc7b62_update_github_connector_repo_name_to_.py
backend/onyx/connectors/github/connector.py
backend/tests/daily/connectors/confluence/test_confluence_basic.py
web/src/components/admin/connectors/ConnectorTitle.tsx
web/src/lib/connectors/connectors.tsx

Allow users to specify a list
Fixes https://linear.app/danswer/issue/DAN-1522/comma-separated-list-for-github-repos

Comma separated list for Github repos

---

.github/workflows/docker-build-push-model-server-container-on-tag.yml

Fixes DAN-1533.
https://linear.app/danswer/issue/DAN-1533/hotfix-model-server-build

revert to always building model server

---

.github/workflows/pr-python-connector-tests.yml
backend/onyx/connectors/confluence/connector.py
backend/tests/daily/connectors/confluence/test_confluence_basic.py
backend/tests/daily/connectors/confluence/test_confluence_permissions_basic.py

Connector tests

---

backend/onyx/connectors/confluence/connector.py

remove confluence image filtering

---

backend/onyx/background/celery/memory_monitoring.py
backend/onyx/background/celery/tasks/indexing/tasks.py

Fix local background jobs

---

backend/onyx/connectors/gitbook/connector.py
backend/tests/daily/connectors/gitbook/test_gitbook_connector.py

Fixes https://linear.app/danswer/issue/DAN-1548/gitbook-missing-pages-during-indexing
Added more tests.

SMall gitbook tweaks

---

backend/onyx/connectors/slack/connector.py

Fix slack channel validation

---

web/src/components/credentials/actions/ModifyCredential.tsx

small modal improvement

---

.github/workflows/pr-python-connector-tests.yml
backend/onyx/connectors/notion/connector.py
backend/tests/daily/connectors/notion/test_notion_connector.py

Ref https://linear.app/danswer/issue/DAN-1546/notion-indexing-issue.
UT

Small notion tweaks

---

backend/requirements/dev.txt
backend/tests/integration/mock_services/mock_connector_server/Dockerfile

Fixes DAN-1571.
https://linear.app/danswer/issue/DAN-1571/corrupt-pip-versions

fix pip versions

---

backend/scripts/debugging/onyx_redis.py

Fixes https://linear.app/danswer/issue/DAN-1575/basic-redis-script

Add basic user invite flow to redis script

---

backend/onyx/connectors/confluence/connector.py
backend/onyx/connectors/confluence/onyx_confluence.py
backend/onyx/connectors/confluence/utils.py
backend/requirements/dev.txt
backend/tests/integration/mock_services/mock_connector_server/Dockerfile

Fixes DAN-1561.
https://linear.app/danswer/issue/DAN-1561/possible-attachment-issues-in-confluence

fix oauth downloading and size limits in confluence

---

backend/onyx/connectors/salesforce/connector.py
web/src/components/credentials/actions/CreateCredential.tsx
web/src/lib/connectors/credentials.ts

Fixes https://linear.app/danswer/issue/DAN-1572/add-support-for-salesforce-sandbox
Tested our salesforce locally.

Add support for sandboxed salesforce

---

backend/onyx/llm/llm_provider_options.py
backend/requirements/default.txt
web/src/app/admin/configuration/llm/LLMProviderUpdateForm.tsx

^
Tested claude 3.7 for bedrock locally

Enable claude 3.7 for bedrock

---

backend/ee/onyx/external_permissions/confluence/doc_sync.py
backend/ee/onyx/external_permissions/gmail/doc_sync.py
backend/ee/onyx/external_permissions/google_drive/doc_sync.py
backend/ee/onyx/external_permissions/slack/doc_sync.py
backend/ee/onyx/external_permissions/sync_params.py
backend/onyx/access/models.py
backend/onyx/background/celery/tasks/doc_permission_syncing/tasks.py
backend/onyx/connectors/slack/connector.py

Fixes https://linear.app/danswer/issue/DAN-1583/fix-perm-sync-memory-usage-issues
Integration tests + local testing for the 4 effected connectors + 👀 

Fix perm sync memory usage

---

backend/onyx/background/celery/tasks/beat_schedule.py
backend/onyx/background/celery/tasks/monitoring/tasks.py
backend/onyx/configs/constants.py

Add process-level memory monitoring

---

backend/onyx/configs/constants.py

FIxes https://linear.app/danswer/issue/DAN-1607/minor-rename-task-for-cloud

Use `ONYX_CLOUD_CELERY_TASK_PREFIX` for pre provisioning task

---

backend/tests/daily/connectors/highspot/test_highspot_connector.py

Fixes DAN-1609.
https://linear.app/danswer/issue/DAN-1609/xfail-highspot-connector-tests

xfail highspot connector tests

---

backend/scripts/docker_memory_tracking.sh

Memory tracking script

---

backend/onyx/connectors/slack/connector.py
backend/onyx/server/manage/slack_bot.py
web/src/app/admin/bots/[bot-id]/channels/SlackChannelConfigFormFields.tsx

Fixes https://linear.app/danswer/issue/DAN-1613/slack-connector-creation-hanging
Tested creating locally.

Fix slack connector creation

---

backend/onyx/agents/agent_search/deep_search/main/nodes/extract_entities_terms.py
backend/onyx/background/indexing/checkpointing_utils.py
backend/onyx/background/indexing/run_indexing.py
backend/onyx/configs/app_configs.py
backend/onyx/connectors/connector_runner.py
backend/onyx/connectors/google_drive/connector.py
backend/onyx/connectors/google_drive/doc_conversion.py
backend/onyx/connectors/google_drive/file_retrieval.py
backend/onyx/connectors/google_drive/models.py
backend/onyx/connectors/google_utils/google_utils.py
backend/onyx/connectors/interfaces.py
backend/onyx/connectors/mock_connector/connector.py
backend/onyx/connectors/models.py
backend/onyx/connectors/slack/connector.py
backend/onyx/tools/message.py
backend/onyx/utils/lazy.py
backend/onyx/utils/threadpool_concurrency.py
backend/tests/daily/connectors/google_drive/consts_and_utils.py
backend/tests/daily/connectors/google_drive/test_admin_oauth.py
backend/tests/daily/connectors/google_drive/test_sections.py
backend/tests/daily/connectors/google_drive/test_service_acct.py
backend/tests/daily/connectors/google_drive/test_slim_docs.py
backend/tests/daily/connectors/google_drive/test_user_1_oauth.py
backend/tests/integration/mock_services/docker-compose.mock-it-services.yml
backend/tests/integration/tests/indexing/test_checkpointing.py
backend/tests/unit/onyx/utils/test_threadpool_concurrency.py

Addresses https://linear.app/danswer/issue/DAN-1505/google-drive-checkpointed-connector
- Refactored CheckpointConnector to have better typing
- Implemented Checkpointing for google drive using OAuth and service account credentials
- Checkpointing is done in stages based on what the user specified they wanted retrieved
- within each stage, retrieval is now ordered by modified time to allow returning to the stage at the stored time
- When retrieval reaches the folder crawling stage, checkpointing is based on a set of previously seen parent folder ids. This means we will re-traverse the folder structure to find new docs to index. potential future work could include making this more efficient, but it likely isn't too many extra calls since we exit early from already-seen folders.
- Slim …

Gdrive checkpointed connector

---

backend/onyx/connectors/connector_runner.py
backend/onyx/connectors/google_drive/connector.py
backend/onyx/connectors/interfaces.py
backend/onyx/connectors/mock_connector/connector.py
backend/onyx/connectors/onyx_jira/connector.py
backend/onyx/connectors/slack/connector.py
backend/tests/daily/connectors/google_drive/consts_and_utils.py
backend/tests/daily/connectors/jira/test_jira_basic.py
backend/tests/daily/connectors/utils.py
backend/tests/unit/onyx/connectors/jira/test_jira_checkpointing.py
backend/tests/unit/onyx/connectors/jira/test_large_ticket_handling.py
backend/tests/unit/onyx/connectors/utils.py

Fixes https://linear.app/danswer/issue/DAN-1594/checkpointed-jira-connector
UT + tested Jira connector locally.

Checkpointed Jira connector

---

backend/onyx/connectors/google_drive/connector.py
backend/onyx/connectors/google_drive/file_retrieval.py
backend/onyx/connectors/google_utils/google_utils.py

Reduce drive retries

---

backend/model_server/main.py

Fixes https://linear.app/danswer/issue/DAN-1627/fix-ramp-startup-issue-with-huggingface-dir
👁️ 

Handle move errors

---

backend/onyx/connectors/slack/connector.py

Fixes https://linear.app/danswer/issue/DAN-1630/assertionerror-found-non-none-doc-with-none-thread-ts
Tested locally before/after

Fix slack connector

---

web/src/app/chat/message/SourcesDisplay.tsx
web/src/components/SearchResultIcon.tsx
web/src/components/WebResultIcon.tsx
web/src/components/chat/sources/SourceCard.tsx

Fixes https://linear.app/danswer/issue/DAN-1603/touchups-on-demo-instance-ui
Fix icon for consistency and dark mode

Minor ux nits

---

backend/alembic.ini
backend/alembic/env.py

Fixes DAN-1629.
https://linear.app/danswer/issue/DAN-1629/fix-alembic-script-logging

alembic script logging fixes

---

backend/onyx/server/manage/slack_bot.py
web/src/app/admin/bots/[bot-id]/channels/SlackChannelConfigFormFields.tsx
web/src/components/Dropdown.tsx

Fixes https://linear.app/danswer/issue/DAN-1596/investigate-slack-channels-not-auto-populating

Update slack bot listing endpoint

---

backend/ee/onyx/server/tenants/provisioning.py
backend/onyx/connectors/file/connector.py
backend/onyx/file_processing/extract_file_text.py

Fixes https://linear.app/danswer/issue/DAN-1585/fix-links-for-files

Fix links from file metadata

---

backend/onyx/connectors/confluence/onyx_confluence.py

Adjust spammy log

---

backend/onyx/connectors/interfaces.py
backend/onyx/connectors/zendesk/connector.py
backend/tests/daily/connectors/zendesk/test_zendesk_connector.py
backend/tests/unit/onyx/connectors/zendesk/test_zendesk_checkpointing.py

Addresses https://linear.app/danswer/issue/DAN-1616/checkpointed-zendesk-connector
Adds checkpointing to the Zendesk connector
Tested in UI and unit tests

zendesk checkpointed connector

---

backend/onyx/configs/app_configs.py
backend/onyx/connectors/confluence/connector.py

Error handling for Daylight Savings and improvements to default timezone guess
Will rely on automated tests for this because it's difficult to test. 

Daylight savings time handling

---

web/src/app/chat/ChatPage.tsx

Fixes https://linear.app/danswer/issue/DAN-1639/invalid-chat-message-specified-in-ui-sticks-around

Fix loading errors persisting

---

web/src/app/admin/assistants/AssistantEditor.tsx

Fixes https://linear.app/danswer/issue/DAN-1632/make-private-vs-public-more-clear

Make public / private for assistants clearer

---

backend/onyx/background/celery/tasks/doc_permission_syncing/tasks.py
backend/onyx/background/indexing/run_indexing.py
backend/onyx/connectors/google_drive/connector.py
backend/onyx/db/index_attempt.py
backend/onyx/utils/telemetry.py
backend/onyx/utils/threadpool_concurrency.py

Fixes https://linear.app/danswer/issue/DAN-1606/thread-util-respecting-for-drive

Respect contextvars when parallelizing for Google Drive

---

backend/onyx/auth/email_utils.py
backend/onyx/db/index_attempt.py

Fixes https://linear.app/danswer/issue/DAN-1650/fix-the-email-formatting-in-various-clients
- Use a proper multipart/related container for the HTML part with embedded images
- Format Content-ID headers with angle brackets (<{inline_png[0]}>) as required by the MIME standard
- Properly nest the HTML and image parts in the correct hierarchy
Tested with various email flows locally

Email formatting devices

---

backend/onyx/auth/email_utils.py
backend/onyx/auth/users.py
web/src/app/auth/login/EmailPasswordForm.tsx
web/src/app/auth/verify-email/Verify.tsx

Fixes https://linear.app/danswer/issue/DAN-1648/ensure-the-organization-onboarding-flow-always-works
Running multi tenant locally

fix invitation on cloud

---

backend/Dockerfile

Fixes https://linear.app/danswer/issue/DAN-1649/minor-fix-email-invite-flow

Minor update for email flow

---

backend/onyx/background/celery/tasks/connector_deletion/tasks.py

Fixes https://linear.app/danswer/issue/DAN-1660/fix-separate-foreign-key-issue-for-emerzon

Add a flush

---

backend/alembic/versions/3bd4c84fe72f_improved_index.py

Fix recurring column existing issues for migratinos that failed partway old version 
Fixes https://linear.app/danswer/issue/DAN-1669/more-permanent-fix-in-main-for-chat-message-tsv
- Extra safeguards

Extra safeguards

---

backend/onyx/background/celery/memory_monitoring.py
deployment/docker_compose/docker-compose.dev.yml
deployment/docker_compose/docker-compose.gpu-dev.yml
deployment/docker_compose/docker-compose.multitenant-dev.yml
deployment/docker_compose/docker-compose.prod-cloud.yml
deployment/docker_compose/docker-compose.prod-no-letsencrypt.yml
deployment/docker_compose/docker-compose.prod.yml
deployment/docker_compose/docker-compose.search-testing.yml

Ref https://linear.app/danswer/issue/DAN-1670/resolve-alation-instance-crashing
Tested compose file locally + verified logs were persisted.

Save all logs + add log persistence to most Onyx-owned containers

---

backend/ee/onyx/server/tenants/billing.py
backend/ee/onyx/server/tenants/user_mapping.py
backend/onyx/server/manage/users.py
backend/tests/integration/common_utils/managers/user.py
backend/tests/integration/multitenant_tests/invitation/invite_various_organizations.py

Fixes https://linear.app/danswer/issue/DAN-1656/robust-multi-tenant-testing-user-org-invite-flow

Add multi-tenant user invitation flow test

---

backend/ee/onyx/configs/app_configs.py
backend/ee/onyx/external_permissions/sync_params.py
backend/onyx/background/celery/apps/beat.py
backend/onyx/background/celery/tasks/beat_schedule.py
backend/onyx/background/celery/tasks/doc_permission_syncing/tasks.py
backend/onyx/background/celery/tasks/indexing/tasks.py
backend/onyx/configs/constants.py
backend/onyx/server/runtime/onyx_runtime.py

Fixes DAN-1668.
https://linear.app/danswer/issue/DAN-1668/allow-adjusting-some-more-vars-in-real-time-for-tuning-load-in-the

adjust some vars in real time

---

web/src/app/chat/ChatPage.tsx

Add some debug logging

---

web/src/app/admin/actions/ActionTable.tsx

Fixes https://linear.app/danswer/issue/DAN-1681/very-minor-link-fix

Fix actions link

---

backend/ee/onyx/chat/process_message.py
backend/ee/onyx/server/query_and_chat/models.py
backend/onyx/agents/agent_search/basic/utils.py
backend/onyx/agents/agent_search/deep_search/initial/generate_initial_answer/nodes/generate_initial_answer.py
backend/onyx/agents/agent_search/deep_search/main/nodes/generate_validate_refined_answer.py
backend/onyx/agents/agent_search/deep_search/shared/expanded_retrieval/nodes/format_results.py
backend/onyx/agents/agent_search/orchestration/nodes/use_tool_response.py
backend/onyx/chat/models.py
backend/onyx/chat/process_message.py
backend/onyx/chat/stream_processing/utils.py
backend/onyx/context/search/pipeline.py
backend/onyx/tools/tool_implementations/search/search_tool.py
backend/onyx/tools/tool_implementations/search/search_utils.py
backend/tests/unit/onyx/chat/conftest.py
backend/tests/unit/onyx/chat/test_answer.py
backend/tests/unit/onyx/chat/test_skip_gen_ai.py

Remove OnyxContext

---

backend/ee/onyx/server/query_and_chat/chat_backend.py
backend/ee/onyx/server/query_and_chat/models.py
backend/onyx/chat/prune_and_merge.py
backend/onyx/context/search/pipeline.py
backend/onyx/tools/tool_implementations/search/search_tool.py
backend/tests/integration/common_utils/managers/chat.py
backend/tests/integration/common_utils/test_models.py
backend/tests/integration/tests/dev_apis/test_simple_chat_api.py
backend/tests/integration/tests/streaming_endpoints/conftest.py
backend/tests/integration/tests/streaming_endpoints/test_chat_stream.py
web/src/components/search/DocumentDisplay.tsx

Fixes https://linear.app/danswer/issue/DAN-1602/deduping-issue-onyxdanswerdev

Fix duplicate docs

---

backend/onyx/main.py
web/src/app/layout.tsx
web/src/components/context/AppProvider.tsx
web/src/components/user/UserProvider.tsx
web/src/hooks/useTokenRefresh.ts

Fixes https://linear.app/danswer/issue/DAN-1680/refresh-failure-with-oidc-enabled

Update refresh conditional

---

backend/ee/onyx/server/middleware/tenant_tracking.py
backend/onyx/auth/users.py
web/src/app/auth/login/LoginPage.tsx
web/src/app/auth/login/page.tsx
web/src/app/chat/nrf/NRFPage.tsx
web/src/app/layout.tsx

Fixes https://linear.app/danswer/issue/DAN-1688/clarify-multi-tenant-anonymous-user-interaction

Improve multi tenant anonymous user interaction

---

backend/ee/onyx/server/tenants/provisioning.py

Fixes https://linear.app/danswer/issue/DAN-1679/ephemeral-provisioning-exceptions

Event loop fix

---

web/src/app/chat/message/Messages.tsx
web/src/app/chat/message/codeUtils.test.ts
web/src/app/chat/message/codeUtils.ts

Fixes https://linear.app/danswer/issue/DAN-1692/fix-mystery-slashes

Fix mystery slashes

---

backend/onyx/auth/users.py
web/package-lock.json

Fixes https://linear.app/danswer/issue/DAN-1714/mysterious-auth-issue

Still delete cookies

---

backend/ee/onyx/external_permissions/salesforce/postprocessing.py

[tiny] Additional logging to salesforce perm sync

---

backend/alembic/versions/f7505c5b0284_updated_constraints_for_ccpairs.py
backend/onyx/db/models.py

Fixes https://linear.app/danswer/issue/DAN-1694/fix-bug-with-emerzon-deletion

Fix cc pair doc deletion

---

backend/alembic/versions/f7505c5b0284_updated_constraints_for_ccpairs.py

Fix migrations

---

backend/onyx/connectors/confluence/utils.py

Add retries for confluence calls

---

backend/onyx/background/celery/apps/app_base.py
backend/onyx/background/celery/apps/client.py
backend/onyx/background/celery/apps/primary.py
backend/onyx/background/celery/configs/client.py
backend/onyx/background/celery/versioned_apps/client.py
backend/onyx/connectors/confluence/utils.py
backend/onyx/server/documents/cc_pair.py
backend/onyx/server/documents/connector.py
backend/onyx/server/features/document_set/api.py
backend/onyx/server/manage/administrative.py
backend/tests/integration/common_utils/managers/document.py
backend/tests/integration/common_utils/managers/index_attempt.py

Fixes DAN-1674.
https://linear.app/danswer/issue/DAN-1674/confluence-url-concatenation-missing-possibly-page-id

harden join function

---

backend/ee/onyx/external_permissions/salesforce/utils.py

Fix Salesforce perm sync

---

backend/onyx/llm/utils.py

Fixes https://linear.app/danswer/issue/DAN-1737/llm-menu-providers-hanging

Use max token fallback

---

backend/ee/onyx/external_permissions/confluence/doc_sync.py
backend/onyx/access/models.py

More logging on confluence space permissions

---

backend/onyx/db/connector_credential_pair.py
backend/onyx/db/document.py
backend/onyx/db/index_attempt.py
backend/onyx/db/swap_index.py
backend/onyx/server/manage/search_settings.py
backend/onyx/setup.py
web/src/app/admin/embeddings/pages/EmbeddingFormPage.tsx

Fixes https://linear.app/danswer/issue/DAN-1746/fix-index-swap-weirdness
Tested many index swaps locally

Fix weird re-index state

---

deployment/aws_ecs_fargate/cloudformation/onyx_config.jsonl

Fix onyx_config.jsonl

---

web/src/lib/sources.ts

Fixes https://linear.app/danswer/issue/DAN-1752/mock-connector-in-cloud-and-possibly-other-places

Don't show mock connector

---

deployment/kubernetes/background-deployment.yaml

Fix naming of volume

---

backend/onyx/background/celery/apps/beat.py

Fixes https://linear.app/danswer/issue/DAN-1794/fix-beat-init

beat crashes in multi tenant mode

---

backend/onyx/agents/agent_search/orchestration/nodes/use_tool_response.py
backend/onyx/auth/users.py
backend/requirements/dev.txt
backend/requirements/model_server.txt
backend/tests/integration/tests/index_attempt/test_index_attempt_pagination.py

Fixes DAN-1795.
https://linear.app/danswer/issue/DAN-1795/update-more-dependencies

updating more packages

---

backend/onyx/db/models.py
backend/onyx/utils/logger.py
backend/shared_configs/configs.py

Fix default log level

---

backend/ee/onyx/db/analytics.py
backend/model_server/custom_models.py
backend/model_server/onyx_torch_model.py
backend/onyx/chat/process_message.py
backend/onyx/db/auth.py
backend/pyproject.toml

Addresses https://linear.app/danswer/issue/DAN-1802/code-cleanup-for-process-message-some-typing-bugs
Some refactoring to address typing issues and too-long functions.
Sanity check in UI

refactor to use stricter typing

---

web/src/app/admin/embeddings/RerankingFormPage.tsx

Fixes https://linear.app/danswer/issue/DAN-1808/cohere-validation-fix

Cohere validation logic update

---

deployment/data/nginx/run-nginx.sh

Small no-letsencrypt improvement

---

backend/ee/onyx/server/saml.py

Fixes https://linear.app/danswer/issue/DAN-1809/saml-validation-upsert

Fix bug with saml validation

---

backend/onyx/llm/llm_provider_options.py
backend/requirements/default.txt
backend/requirements/model_server.txt
web/src/lib/hooks.ts
web/src/lib/llm/utils.ts

fixes https://linear.app/danswer/issue/DAN-1828/litellm-bump-41

Bump LiteLLM + add 4.1

---

backend/onyx/connectors/blob/connector.py

Fixes https://linear.app/danswer/issue/DAN-1821/images-for-s3

Skip image files for S3

---

backend/onyx/connectors/slack/connector.py

Fixes DAN-1840.
https://linear.app/danswer/issue/DAN-1840/small-slack-logging-improvements

slightly better slack logging

---

backend/ee/onyx/external_permissions/sync_params.py
backend/onyx/background/indexing/run_indexing.py
backend/onyx/connectors/web/connector.py
backend/onyx/server/documents/models.py
web/src/app/admin/connector/[ccPairId]/ConfigDisplay.tsx
web/src/app/admin/connector/[ccPairId]/IndexingAttemptsTable.tsx
web/src/app/admin/connector/[ccPairId]/page.tsx
web/src/app/admin/connector/[ccPairId]/types.ts

Fixes https://linear.app/danswer/issue/DAN-1841/improve-connector-display-part-2

Small improvements to connector UI

---

.github/workflows/pr-python-connector-tests.yml
backend/requirements/dev.txt

^
---
Enabled parallel execution of connector tests to speed up test runs.
- **Dependencies**
- Added pytest-xdist to development requirements.

Parallelize connector tests

---

backend/onyx/onyxbot/slack/handlers/handle_regular_answer.py

Fixes https://linear.app/danswer/issue/DAN-1855/fix-slack-bot-feedback
Should have test for this, but waiting for Subash's general slack tests.

Fix slack bot feedback

---

web/src/app/admin/connector/[ccPairId]/page.tsx

Fix missing Connector Configuration

---

backend/alembic/versions/da42808081e3_migrate_jira_connectors_to_new_format.py

Transfer any existing Jira connector configs over in an old migration
n/a; we should definitely create some utils for testing migrations. I'm also in favor of strongly-typed connector-specific configs

transfer old fileds to new config

---

.github/workflows/pr-playwright-tests.yml
backend/tests/integration/tests/playwright/test_playwright.py
web/tests/e2e/assistants/create_and_edit_assistant.spec.ts

Add e2e test for assistant creation/edit

---

backend/onyx/background/indexing/checkpointing_utils.py

Fixes https://linear.app/danswer/issue/DAN-1916/better-checkpoint-handling-on-repeated-failures
👀 

Small improvements to checkpoint pickup logic

---

backend/onyx/connectors/highspot/connector.py

Fixes https://linear.app/danswer/issue/DAN-1931/highspot-cleanup
Ran connector tests.

Highspot cleanup

---

.github/actions/custom-build-and-push/action.yml
.github/workflows/docker-build-push-backend-container-on-tag.yml
.github/workflows/docker-build-push-cloud-web-container-on-tag.yml
.github/workflows/docker-build-push-model-server-container-on-tag.yml
.github/workflows/docker-build-push-web-container-on-tag.yml
.github/workflows/pr-integration-tests.yml
.github/workflows/pr-mit-integration-tests.yml
backend/onyx/db/document.py
backend/onyx/redis/redis_connector_delete.py
backend/tests/integration/Dockerfile

Fixes https://linear.app/danswer/issue/DAN-1934/connector-deletion-oom-for-melio

memory optimize task generation for connector deletion

---

.github/workflows/pr-helm-chart-testing.yml
backend/onyx/db/swap_index.py
deployment/helm/README.md
deployment/helm/charts/onyx/templates/tests/test-connection.yaml
deployment/helm/charts/onyx/values.yaml

Refs https://linear.app/danswer/issue/DAN-1956/update-helm-charts-to-separate-workers

run testing

---

backend/onyx/connectors/github/connector.py

Fixes https://linear.app/danswer/issue/DAN-1968/small-github-validation-improvements
Created github connector locally 🙏 

Small GitHub enhancements

---

backend/ee/onyx/background/celery/apps/heavy.py

Fix heavy import

---

backend/onyx/connectors/slack/connector.py
backend/onyx/connectors/teams/connector.py
backend/tests/daily/connectors/slack/test_slack_connector.py
backend/tests/daily/connectors/teams/test_teams_connector.py
backend/tests/daily/connectors/utils.py

This PR implements checkpointing for the Teams connector.
Addresses: https://linear.app/danswer/issue/DAN-1835/teams-checkpointing-connector.
Wrote some automated tests inside of `backend/tests/daily/connectors/teams`.

perf: Implement checkpointing for Teams Connector.

---

backend/onyx/auth/users.py

Fixes https://linear.app/danswer/issue/DAN-1974/fix-user-create

use existing session user if it matches the email

---

backend/onyx/connectors/highspot/client.py

This pull request introduces pagination to the `get_spots` method in the `HighspotClient` class and centralizes the page size configuration for consistency. 
By running the test class

Implement pagination for retrieving spots in HighspotClient

---

backend/onyx/llm/utils.py
backend/onyx/tools/utils.py

Fix import ordering

---

deployment/kubernetes/slackbot-service-deployment.yaml

Fix slack bot kubernetes template

---

backend/ee/onyx/external_permissions/slack/doc_sync.py
backend/ee/onyx/external_permissions/slack/group_sync.py

Fixes https://linear.app/danswer/issue/DAN-1995/selfdatabase-isnt-a-real-member-var

fix slack rate limit retry handler for groups

---

backend/onyx/connectors/salesforce/connector.py
backend/onyx/connectors/salesforce/salesforce_calls.py
backend/tests/daily/connectors/web/test_web_connector.py

Fixes https://linear.app/danswer/issue/DAN-1998/mitigate-salesforce-csv-memory-usage

mitigate memory usage during csv download

---

backend/onyx/background/celery/apps/app_base.py
backend/onyx/background/celery/apps/heavy.py
backend/onyx/background/celery/apps/indexing.py
backend/onyx/background/celery/apps/light.py
backend/onyx/background/celery/apps/monitoring.py
backend/onyx/background/celery/apps/primary.py
backend/onyx/background/celery/celery_k8s_probe.py

Fixes https://linear.app/danswer/issue/DAN-2001/readiness-and-liveness-probes-for-k8s

add k8s probes

---

backend/onyx/connectors/slack/connector.py

add a comment

---

backend/onyx/connectors/confluence/connector.py
backend/onyx/connectors/cross_connector_utils/miscellaneous_utils.py
backend/onyx/connectors/onyx_jira/connector.py

Handle jira daylight savings in the same way we handle confluence
it hasn't yet

jira daylight savings handling

---

backend/onyx/server/documents/cc_pair.py
web/src/app/admin/connector/[ccPairId]/IndexAttemptErrorsModal.tsx
web/src/app/chat/ChatPage.tsx
web/src/app/chat/input/ChatInputBar.tsx
web/src/components/chat/UnconfiguredLlmProviderText.tsx

Fixes https://linear.app/danswer/issue/DAN-2022/fix-pagination-on-the-index-attempt-errors-table
Tested locally

Fix failed docs table

---

backend/onyx/chat/process_message.py
backend/onyx/chat/user_files/parse_user_files.py
backend/onyx/context/search/pipeline.py
backend/onyx/file_store/utils.py

Adjust user file access

---

backend/onyx/chat/process_message.py
backend/onyx/chat/user_files/parse_user_files.py
backend/onyx/context/search/pipeline.py
backend/onyx/context/search/postprocessing/postprocessing.py
backend/onyx/tools/models.py
backend/onyx/tools/tool_implementations/search/search_tool.py

Remove ordering-only flow

---

backend/alembic/versions/ca04500b9ee8_add_cascade_deletes_to_agent_tables.py
backend/onyx/db/chat.py
backend/onyx/db/models.py
backend/onyx/server/query_and_chat/chat_backend.py
backend/onyx/server/query_and_chat/models.py
backend/tests/integration/common_utils/managers/chat.py
backend/tests/integration/common_utils/managers/user.py
backend/tests/integration/conftest.py
backend/tests/integration/tests/chat/test_chat_deletion.py
backend/tests/integration/tests/index_attempt/test_index_attempt_pagination.py
backend/tests/integration/tests/users/test_user_pagination.py

Fixes https://linear.app/danswer/issue/DAN-2026/fix-hard-delete-of-agentic-chats
New integration tests

Fix hard delete of agentic chats

---

backend/onyx/llm/chat_llm.py
backend/onyx/llm/utils.py
backend/tests/unit/onyx/llm/test_model_is_reasoning.py

Fixes https://linear.app/danswer/issue/DAN-2034/improve-reasoning-detection
UT

Improve reasoning detection

---

backend/onyx/background/indexing/run_indexing.py
backend/onyx/connectors/slack/connector.py

Fixes https://linear.app/danswer/issue/DAN-2031/improve-slack-percentage-progress-reporting

add slack percentage progress

---

backend/ee/onyx/document_index/vespa/app_config/cloud-services.xml.jinja
backend/scripts/debugging/onyx_vespa_schemas.py

Extend the onyx_vespa_schemas.py script

---

backend/scripts/restart_containers.sh

previous change to clarify errors caused script to fail on first startup

Restart script clarity

---

backend/onyx/connectors/blob/connector.py
web/src/components/credentials/actions/CreateCredential.tsx
web/src/components/credentials/actions/CredentialFieldsRenderer.tsx
web/src/components/credentials/actions/EditCredential.tsx
web/src/components/credentials/lib.ts
web/src/lib/connectors/credentials.ts

This pull request introduces support for multiple authentication methods in credential management.
Task link -> https://linear.app/danswer/issue/DAN-2046/iam-support-for-s3-blob-connector
Tested by creating the connector.

IAM support for S3 / blob connector

---

backend/onyx/kg/extractions/extraction_processing.py

fix kg variable

---

backend/onyx/auth/users.py
backend/onyx/configs/app_configs.py

Make password validation configurable
Related Issue: https://github.com/onyx-dot-app/onyx/issues/4775
Locally.

Make password validation configurable

---

deployment/README.md
deployment/helm/charts/onyx/templates/api-deployment.yaml
deployment/helm/charts/onyx/templates/celery-beat.yaml
deployment/helm/charts/onyx/templates/celery-worker-heavy.yaml
deployment/helm/charts/onyx/templates/celery-worker-indexing.yaml
deployment/helm/charts/onyx/templates/celery-worker-light.yaml
deployment/helm/charts/onyx/templates/celery-worker-monitoring.yaml
deployment/helm/charts/onyx/templates/celery-worker-primary.yaml
deployment/helm/charts/onyx/templates/celery-worker-user-files-indexing.yaml
deployment/helm/charts/onyx/templates/indexing-model-deployment.yaml
deployment/helm/charts/onyx/templates/inference-model-deployment.yaml
deployment/helm/charts/onyx/templates/slackbot.yaml
deployment/helm/charts/onyx/templates/webserver-deployment.yaml
deployment/helm/charts/onyx/values.yaml

^
Deployed new helm charts, verified slack bot worked as expected.

ADd slackbot to helm

---

backend/onyx/connectors/blob/connector.py
backend/onyx/connectors/cross_connector_utils/miscellaneous_utils.py
backend/onyx/connectors/file/connector.py
backend/onyx/connectors/models.py
backend/tests/daily/connectors/file/test_file_connector.py

Text files from blob can have metadata just like file connector
Fixes https://linear.app/danswer/issue/DAN-2078/gcs-metadata

GCS metadata processing

---

backend/onyx/agents/agent_search/kb_search/nodes/a3_generate_simple_sql.py
backend/onyx/db/relationships.py
backend/onyx/kg/extractions/extraction_processing.py
backend/onyx/prompts/kg_prompts.py

Here are the highlights:
- no classification if deep extraction is False
- separate names for views in LLM generation
- better prompts
- any relationship type provided to LLM that relates to identified entities
Here is the Linear ticket: https://linear.app/danswer/issue/DAN-2109/small-kg-improvements
Locally, multi-tenant

KG Updates

---

.github/workflows/pr-python-connector-tests.yml
backend/onyx/connectors/hubspot/connector.py
backend/tests/daily/connectors/hubspot/test_hubspot_connector.py
web/package-lock.json
web/package.json
web/src/app/admin/connectors/[connector]/pages/FieldRendering.tsx
web/src/lib/connectors/connectors.tsx

Add support for Companies, Deals, and Contacts
Fixes https://linear.app/danswer/issue/DAN-2111/enhance-hubspot-connector
Tests + manual testing.

Hubspot connector enhancements

---

backend/onyx/tools/tool_implementations/search/search_tool.py

Fix parallel Search tool calls

---

backend/ee/onyx/background/celery/apps/heavy.py

Fix query history

---

backend/alembic/versions/7b9b952abdf6_update_entities.py
backend/onyx/connectors/linear/connector.py
backend/onyx/db/tag.py
backend/onyx/kg/setup/kg_default_entity_definitions.py
backend/onyx/kg/utils/extraction_utils.py
backend/onyx/kg/vespa/vespa_interactions.py

Added creator to linear
Added linear creator relationship stuff to kg
Shuffled things around
Locally

Add creator to linear

---

backend/onyx/federated_connectors/slack/federated_connector.py

Forgot this :(
Pretty important

add missing slack scope

---

backend/onyx/connectors/imap/connector.py
backend/tests/daily/connectors/imap/test_imap_connector.py

Found some bugs while running the IMAP connector at scale (state transitioning errors, etc.).
Addresses: https://linear.app/danswer/issue/DAN-2168/fix-imap-backend-connector-failures.
Tests already written. However, scalable tests do not exist (and will be hard to emulate).

fix: IMAP backend fixes

---

backend/ee/onyx/server/tenants/billing_api.py
backend/ee/onyx/server/tenants/models.py
backend/ee/onyx/server/tenants/product_gating.py

Add full sync endpoint

---

backend/onyx/background/celery/tasks/pruning/tasks.py

More pruning logging

---

backend/ee/onyx/server/query_and_chat/chat_backend.py
backend/ee/onyx/server/query_and_chat/models.py

feat: remove chat session necessity from send message simple api

---

deployment/helm/charts/onyx/Chart.lock
deployment/helm/charts/onyx/Chart.yaml

Update to the Vespa Helm Chart value so also updating the onyx chart values.
Just a version bump 

feat(infra): Bump Vespa Helm Version

---

deployment/helm/charts/onyx/values.yaml

fix: add require_email_verification to values.yaml

---

backend/onyx/file_processing/extract_file_text.py

- deprecated function after @evan-onyx markitdown change

fix: remove dead code

---

web/src/app/chat/message/messageComponents/AIMessage.tsx
web/tests/e2e/utils/chatActions.ts

fix: playwright tests

---

web/src/components/admin/actions/forms.tsx

Remove console-log

---

backend/onyx/connectors/freshdesk/connector.py

- generic backoff not enough as retry set to 30-40s on first 429

fix: honor freshdesk 429

---

backend/onyx/llm/llm_provider_options.py
backend/onyx/tools/tool_implementations/custom/custom_tool.py
backend/onyx/tools/tool_implementations/images/image_generation_tool.py
backend/requirements/default.txt
backend/requirements/model_server.txt

chore: bump litellm to fix self-hosted inference

---

web/src/app/admin/assistants/AssistantEditor.tsx
web/src/app/admin/configuration/llm/LLMProviderUpdateForm.tsx
web/src/app/chat/message/codeUtils.ts
web/src/lib/assistants/updateAssistantPreferences.ts

1. Fix inline math rendering issue (re-enable LaTeX math rendering by replacing `\(...\)` with `$$...$$` but leaving `$...$` inline latex rendering disabled which helps reduce mistakes with `$` in variable names or referencing money 
2. Newly created assistants pinned by default
3. Simplified Azure form
https://linear.app/danswer/issue/DAN-2370/when-creating-a-new-assistant-it-should-be-default-pinned-right-after
tested locally

fix: various bug bash improvements

---

web/src/app/chat/components/input/ChatInputBar.tsx

fix: non-image gen models

---

deployment/helm/charts/onyx/Chart.yaml

Adding Keda as a dependency for our Helm Charts
Locally

fix(infra): Add KEDA Dependency

---

.github/workflows/pr-helm-chart-testing.yml
deployment/helm/charts/onyx/Chart.yaml
deployment/helm/charts/onyx/templates/_helpers.tpl
deployment/helm/charts/onyx/templates/api-scaledobject.yaml
deployment/helm/charts/onyx/templates/celery-worker-docfetching-scaledobject.yaml
deployment/helm/charts/onyx/templates/celery-worker-docprocessing-scaledobject.yaml
deployment/helm/charts/onyx/templates/celery-worker-heavy-scaledobject.yaml
deployment/helm/charts/onyx/templates/celery-worker-light-scaledobject.yaml
deployment/helm/charts/onyx/templates/celery-worker-monitoring-scaledobject.yaml
deployment/helm/charts/onyx/templates/celery-worker-primary-scaledobject.yaml
deployment/helm/charts/onyx/templates/celery-worker-user-file-processing-hpa.yaml
deployment/helm/charts/onyx/templates/celery-worker-user-file-processing-scaledobject.yaml
deployment/helm/charts/onyx/templates/celery-worker-user-file-processing.yaml
deployment/helm/charts/onyx/templates/celery-worker-user-files-indexing-scaledobject.yaml
deployment/helm/charts/onyx/templates/webserver-scaledobject.yaml
deployment/helm/charts/onyx/values.yaml

This PR was merged https://github.com/onyx-dot-app/onyx/pull/5248 but the helm chart version was not incremented. 
This PR just increments the value so that we deploy a new version of the charts
Broken Helm Chart pipeline here: https://github.com/onyx-dot-app/onyx/actions/runs/18046914828/job/51359818428
This is just a chart update

fix(infra): Increment Helm Version for Projects

---

.github/workflows/pr-playwright-tests.yml
web/tests/e2e/utils/chatActions.ts

fix: more test hardening

---

web/src/app/auth/saml/callback/route.ts

We correctly update the endpoints so that we can accept POST and GET requests but our FE now doesn't know what to do with the GET function so this is to transform this information to properly get setup.
Tested locally to make sure that this is correct.

fix(saml): Update the route to take GET's and transform to POST

---

web/tests/e2e/chat/current_assistant.spec.ts

Skip flakey test

---

.github/workflows/pr-integration-tests.yml
.github/workflows/pr-mit-integration-tests.yml

Reverts onyx-dot-app/onyx#5487 temporarily to let my tests pass

Revert "fix(github): Revert cache being turned off"

---

.github/workflows/pr-integration-tests.yml
.github/workflows/pr-mit-integration-tests.yml

Reverts onyx-dot-app/onyx#5575

fix(github): Revert cache being turned off

---

CONTRIBUTING.md
CONTRIBUTING_VSCODE.md

chore: update contributing readmes

---

backend/onyx/context/search/retrieval/search_runner.py
backend/onyx/context/search/utils.py
backend/onyx/file_processing/extract_file_text.py
backend/onyx/file_processing/html_utils.py
backend/onyx/file_processing/unstructured.py
backend/onyx/kg/clustering/normalizations.py
backend/onyx/natural_language_processing/utils.py
backend/scripts/check_lazy_imports.py

more lazy imports get primary worker from 480 -> 316 mb
https://linear.app/danswer/issue/DAN-2761/lazy-load-nltk-and-tokenizer-from-prompt

fix(infra): lazy load nltk and some more

---

backend/requirements/default.txt
backend/requirements/dev.txt
backend/requirements/model_server.txt

chore: bump dependabot backlog
